# FROM yandex/clickhouse-server:22.3
FROM cr.yandex/crpsufj53lhl0via9iam/clickhouse-server:22.3

COPY db-clickhouse/users.xml /etc/clickhouse-server/users.xml

COPY db-clickhouse/docker-entrypoint-initdb.d/ /docker-entrypoint-initdb.d/
