FROM clickhouse/clickhouse-server:26.1

COPY db-clickhouse/users.xml /etc/clickhouse-server/users.xml

COPY db-clickhouse/data /common-data

COPY db-clickhouse/docker-entrypoint-initdb.d/ /docker-entrypoint-initdb.d/
