# FROM yandex/clickhouse-server:21.8.7.22
FROM yandex/clickhouse-server:21.8.7.22

COPY db-clickhouse/users.xml /etc/clickhouse-server/users.xml

COPY db-clickhouse/data /common-data

COPY db-clickhouse/docker-entrypoint-initdb.d/ /docker-entrypoint-initdb.d/
