#!/bin/sh -x

set -Eeu

if [ -e "dist" ]; then
    echo "'dist' exists" >&2
    exit 1
fi

python3 -V
twine --version

python3 ./setup.py sdist bdist_wheel
twine upload --repository yandex dist/*
rm -r dist
