advertising_fields = [
    {
        "description": "Количество посетителей, купивших хотя бы один товар, суммарно по всем визитам.",
        "is_dim": False,
        "name": "ym:ad:productPurchasedUniq",
        "title": "Количество посетителей, купивших товар",
        "type": "integer",
    },
    {
        "description": "Среднее время от предпоследнего визита в днях.",
        "is_dim": False,
        "name": "ym:ad:userRecencyDays",
        "title": "Дней от предыдущего визита",
        "type": "float",
    },
    {
        "description": "Количество новых посетителей.",
        "is_dim": False,
        "name": "ym:ad:newUsers",
        "title": "Новые посетители",
        "type": "float",
    },
    {
        "description": "Доля визитов посетителей, возраст которых менее 18 лет.",
        "is_dim": False,
        "name": "ym:ad:under18AgePercentage",
        "title": "Менее 18 лет",
        "type": "float",
    },
    {
        "description": "Доля визитов и хитов, совершенных с мобильных устройств.",
        "is_dim": False,
        "name": "ym:ad:mobilePercentage",
        "title": "Мобильность",
        "type": "float",
    },
    {
        "description": "Средняя продолжительность визита в минутах и секундах.",
        "is_dim": False,
        "name": "ym:ad:avgVisitDurationSeconds",
        "title": "Время на сайте",
        "type": "float",
    },
    {
        "description": "Сумма значений параметров визитов. Вычисляется, если в качестве значений параметров визитов передаётся число.",
        "is_dim": False,
        "name": "ym:ad:sumParams",
        "title": "Сумма параметров визитов",
        "type": "integer",
    },
    {
        "description": "Доля визитов посетителей, вернувшихся на сайт через более чем 365 дней.",
        "is_dim": False,
        "name": "ym:ad:overYearUserRecencyPercentage",
        "title": "Вернувшиеся: более чем 365 дней",
        "type": "float",
    },
    {
        "description": "Суммарное количество кликов по рекламе.",
        "is_dim": False,
        "name": "ym:ad:clicks",
        "title": "Клики",
        "type": "integer",
    },
    {
        "description": "Доля визитов и хитов с поддержкой Silverlight.",
        "is_dim": False,
        "name": "ym:ad:silverlightEnabledPercentage",
        "title": "Поддержка Silverlight",
        "type": "float",
    },
    {
        "description": "Количество уникальных посетителей.",
        "is_dim": False,
        "name": "ym:ad:users",
        "title": "Посетители",
        "type": "integer",
    },
    {
        "description": "",
        "is_dim": False,
        "name": "ym:ad:ecommercePurchases",
        "title": "Количество покупок",
        "type": "integer",
    },
    {
        "description": "Доля визитов посетителей, возраст которых от 25 до 34 лет.",
        "is_dim": False,
        "name": "ym:ad:upTo34AgePercentage",
        "title": "25‑34 лет",
        "type": "float",
    },
    {
        "description": "Доля визитов и хитов с поддержкой JavaScript.",
        "is_dim": False,
        "name": "ym:ad:jsEnabledPercentage",
        "title": "Поддержка JavaScript",
        "type": "float",
    },
    {
        "description": None,
        "is_dim": False,
        "name": "ym:ad:visitsPerDay",
        "title": "Визитов в день",
        "type": "float",
    },
    {
        "description": "Количество посетителей, добавивших в корзину хотя бы один товар суммарно по всем визитам.",
        "is_dim": False,
        "name": "ym:ad:productBasketsUniq",
        "title": "Количество посетителей, добавивших товар в корзину",
        "type": "integer",
    },
    {
        "description": "Доля визитов посетителей, известных меньше одного дня.",
        "is_dim": False,
        "name": "ym:ad:upToDaySinceFirstVisitPercentage",
        "title": "Новизна менее одного дня",
        "type": "float",
    },
    {
        "description": "Число просмотров страниц на сайте за отчетный период.",
        "is_dim": False,
        "name": "ym:ad:pageviews",
        "title": "Просмотры",
        "type": "integer",
    },
    {
        "description": "Доля визитов и хитов с поддержкой Flash.",
        "is_dim": False,
        "name": "ym:ad:flashEnabledPercentage",
        "title": "Поддержка Flash",
        "type": "float",
    },
    {
        "description": 'Доля визитов с меткой "GCLID".',
        "is_dim": False,
        "name": "ym:ad:GCLIDPercentage",
        "title": "Доля GCLID",
        "type": "float",
    },
    {
        "description": "Доля визитов посетителей, известных более 365 дней.",
        "is_dim": False,
        "name": "ym:ad:overYearSinceFirstVisitPercentage",
        "title": "Новизна более 365 дней",
        "type": "float",
    },
    {
        "description": "Доля посетителей, купивших товар на сайте, по отношению к общему числу посетителей.",
        "is_dim": False,
        "name": "ym:ad:usersPurchasePercentage",
        "title": "Доля посетителей, купивших товар",
        "type": "float",
    },
    {
        "description": "Доля визитов посетителей, возраст которых от 45 до 55 лет.",
        "is_dim": False,
        "name": "ym:ad:upTo54AgePercentage",
        "title": "45‑55 лет",
        "type": "float",
    },
    {
        "description": "Количество купленных единиц товара суммарно по всем визитам.",
        "is_dim": False,
        "name": "ym:ad:productPurchasedQuantity",
        "title": "Товаров куплено",
        "type": "integer",
    },
    {
        "description": "",
        "is_dim": False,
        "name": "ym:ad:womanPercentage",
        "title": "Доля женщин",
        "type": "float",
    },
    {
        "description": "Доля визитов новых посетителей.",
        "is_dim": False,
        "name": "ym:ad:newUserVisitsPercentage",
        "title": "Доля визитов новых посетителей",
        "type": "float",
    },
    {
        "description": "Доля визитов посетителей, вернувшихся на сайт через 2‑7 дней.",
        "is_dim": False,
        "name": "ym:ad:upToWeekUserRecencyPercentage",
        "title": "Вернувшиеся: 2‑7 дней",
        "type": "float",
    },
    {
        "description": "Доля визитов посетителей с частотой визитов один раз в 1 день. Учитываются посетители, совершившие больше двух визитов, которые произошли в разные дни.",
        "is_dim": False,
        "name": "ym:ad:oneDayBetweenVisitsPercentage",
        "title": "Периодичность 1 день",
        "type": "float",
    },
    {
        "description": "Доля визитов посетителей, известных от 91 до 365 дней.",
        "is_dim": False,
        "name": "ym:ad:upToYearSinceFirstVisitPercentage",
        "title": "Новизна 91‑365 дней",
        "type": "float",
    },
    {
        "description": "Доля визитов посетителей с 4‑7 визитами.",
        "is_dim": False,
        "name": "ym:ad:upTo7VisitsPerUserPercentage",
        "title": "4‑7 визитов посетителя",
        "type": "float",
    },
    {
        "description": "Процент уникальных посетителей, посетивших сайт в отчетном периоде, активность которых включала их самый первый за всю историю накопления данных визит на сайт.",
        "is_dim": False,
        "name": "ym:ad:percentNewVisitors",
        "title": "Доля новых посетителей",
        "type": "float",
    },
    {
        "description": "Доля посетителей, предположительно являющихся роботами.",
        "is_dim": False,
        "name": "ym:ad:robotPercentage",
        "title": "Роботность",
        "type": "float",
    },
    {
        "description": "Доля визитов посетителей, вернувшихся на сайт через 32‑90 дней.",
        "is_dim": False,
        "name": "ym:ad:upToQuarterUserRecencyPercentage",
        "title": "Вернувшиеся: 32‑90 дней",
        "type": "float",
    },
    {
        "description": "Среднее время от первого визита в днях.",
        "is_dim": False,
        "name": "ym:ad:avgDaysSinceFirstVisit",
        "title": "Дней от первого визита",
        "type": "float",
    },
    {
        "description": "Среднее значение параметра визита. Вычисляется, если в качестве значения параметра визита передаётся число.",
        "is_dim": False,
        "name": "ym:ad:avgParams",
        "title": "Среднее параметров визитов",
        "type": "float",
    },
    {
        "description": "Доля визитов посетителей, известных от 1 до 7 дней.",
        "is_dim": False,
        "name": "ym:ad:upToWeekSinceFirstVisitPercentage",
        "title": "Новизна 1‑7 дней",
        "type": "float",
    },
    {
        "description": "Доля визитов посетителей, возраст которых от 35 до 45 лет.",
        "is_dim": False,
        "name": "ym:ad:upTo44AgePercentage",
        "title": "35‑45 лет",
        "type": "float",
    },
    {
        "description": "Количество единиц товара, помещённых в корзину, суммарно по всем визитам.",
        "is_dim": False,
        "name": "ym:ad:productBasketsRemoveQuantity",
        "title": "Товаров удалено из корзины",
        "type": "integer",
    },
    {
        "description": "Доля визитов посетителей с одним визитом (первый визит посетителя).",
        "is_dim": False,
        "name": "ym:ad:oneVisitPerUserPercentage",
        "title": "1 визит посетителя",
        "type": "float",
    },
    {
        "description": (
            "Отношение доли посетителей с заданным интересом на этом сайте к "
            "среднестатистической доле посетителей с этим же интересом на "
            "всех сайтах интернета. Разрешена только при использовании "
            'группировки "Категория интересов".'
        ),
        "is_dim": False,
        "name": "ym:ad:affinityIndexInterests",
        "title": "Аффинити‑индекс (старая версия)",
        "type": "float",
    },
    {
        "description": "Доля визитов посетителей с частотой визитов один раз в более чем 31 день. Учитываются посетители, совершившие больше двух визитов, которые произошли в разные дни.",
        "is_dim": False,
        "name": "ym:ad:overMonthBetweenVisitsPercentage",
        "title": "Периодичность более чем 31 день",
        "type": "float",
    },
    {
        "description": "Доля визитов посетителей, вернувшихся на сайт через 8‑31 день.",
        "is_dim": False,
        "name": "ym:ad:upToMonthUserRecencyPercentage",
        "title": "Вернувшиеся: 8‑31 день",
        "type": "float",
    },
    {
        "description": "Доля визитов посетителей, совершивших больше 32 визитов.",
        "is_dim": False,
        "name": "ym:ad:over32VisitsPerUserPercentage",
        "title": "Более чем 32 визита посетителя",
        "type": "float",
    },
    {
        "description": "Доля визитов посетителей, возраст которых более 55 лет.",
        "is_dim": False,
        "name": "ym:ad:over54AgePercentage",
        "title": "Более 55 лет",
        "type": "float",
    },
    {
        "description": None,
        "is_dim": False,
        "name": "ym:ad:visitsPerMinute",
        "title": "Визитов в минуту",
        "type": "float",
    },
    {
        "description": "Суммарное количество визитов.",
        "is_dim": False,
        "name": "ym:ad:visits",
        "title": "Визиты",
        "type": "integer",
    },
    {
        "description": "",
        "is_dim": False,
        "name": "ym:ad:manPercentage",
        "title": "Доля мужчин",
        "type": "float",
    },
    {
        "description": "Количество просмотров страницы с информацией о товарах суммарно по всем визитам.",
        "is_dim": False,
        "name": "ym:ad:productImpressions",
        "title": "Просмотры товаров",
        "type": "integer",
    },
    {
        "description": "Количество единиц товара, добавленных в корзину, суммарно по всем визитам.",
        "is_dim": False,
        "name": "ym:ad:productBasketsQuantity",
        "title": "Товаров добавлено в корзину",
        "type": "integer",
    },
    {
        "description": "Доля визитов посетителей, известных от 8 до 31 день.",
        "is_dim": False,
        "name": "ym:ad:upToMonthSinceFirstVisitPercentage",
        "title": "Новизна 8‑31 день",
        "type": "float",
    },
    {
        "description": "Среднее количество дней между визитами посетителей.",
        "is_dim": False,
        "name": "ym:ad:avgDaysBetweenVisits",
        "title": "Дней между визитами",
        "type": "float",
    },
    {
        "description": "Доля визитов с блокировщиками рекламы.",
        "is_dim": False,
        "name": "ym:ad:blockedPercentage",
        "title": "Блокировка рекламы",
        "type": "float",
    },
    {
        "description": "Количество посетителей, просмотревших информацию хотя бы об одном товаре.",
        "is_dim": False,
        "name": "ym:ad:productImpressionsUniq",
        "title": "Посетители, просмотревшие товар",
        "type": "integer",
    },
    {
        "description": "Количество страниц, просмотренных посетителем во время визита.",
        "is_dim": False,
        "name": "ym:ad:pageDepth",
        "title": "Глубина просмотра",
        "type": "float",
    },
    {
        "description": "Доля визитов посетителей, возраст которых от 18 до 24 лет.",
        "is_dim": False,
        "name": "ym:ad:upTo24AgePercentage",
        "title": "18‑24 лет",
        "type": "float",
    },
    {
        "description": "Доля визитов и хитов с включенными cookies.",
        "is_dim": False,
        "name": "ym:ad:cookieEnabledPercentage",
        "title": "Поддержка сookies",
        "type": "float",
    },
    {
        "description": "Доля визитов и хитов с поддержкой Java.",
        "is_dim": False,
        "name": "ym:ad:javaEnabledPercentage",
        "title": "Поддержка Java",
        "type": "float",
    },
    {
        "description": "Доля визитов посетителей с 8‑31 визитами.",
        "is_dim": False,
        "name": "ym:ad:upTo31VisitsPerUserPercentage",
        "title": "8‑31 визит посетителя",
        "type": "float",
    },
    {
        "description": "Количество раз, когда в визите встретился параметр визита.",
        "is_dim": False,
        "name": "ym:ad:paramsNumber",
        "title": "Количество параметров визитов",
        "type": "integer",
    },
    {
        "description": None,
        "is_dim": False,
        "name": "ym:ad:visitsPerHour",
        "title": "Визитов в час",
        "type": "float",
    },
    {
        "description": "Доля визитов посетителей с частотой визитов один раз в 8‑31 день. Учитываются посетители, совершившие больше двух визитов. При этом число дней визитов больше 1 дня.",
        "is_dim": False,
        "name": "ym:ad:upToMonthBetweenVisitsPercentage",
        "title": "Периодичность 8‑31 день",
        "type": "float",
    },
    {
        "description": "Доля визитов посетителей, вернувшихся на сайт через 1 день.",
        "is_dim": False,
        "name": "ym:ad:upToDayUserRecencyPercentage",
        "title": "Вернувшиеся: 1 день",
        "type": "float",
    },
    {
        "description": "Доля визитов, в рамках которых состоялся лишь один просмотр страницы, продолжавшийся менее 15 секунд.",
        "is_dim": False,
        "name": "ym:ad:bounceRate",
        "title": "Отказы",
        "type": "float",
    },
    {
        "description": "Конверсия по любой цели.",
        "is_dim": False,
        "name": "ym:ad:anyGoalConversionRate",
        "title": "Конверсия по любой цели",
        "type": "float",
    },
    {
        "description": "Количество достижений любой цели.",
        "is_dim": False,
        "name": "ym:ad:sumGoalReachesAny",
        "title": "Достижения любой цели",
        "type": "integer",
    },
    {
        "description": "Доля визитов посетителей, вернувшихся на сайт через 91‑365 дней.",
        "is_dim": False,
        "name": "ym:ad:upToYearUserRecencyPercentage",
        "title": "Вернувшиеся: 91‑365 дней",
        "type": "float",
    },
    {
        "description": "Доля визитов посетителей, известных от 32 до 90 дней.",
        "is_dim": False,
        "name": "ym:ad:upToQuarterSinceFirstVisitPercentage",
        "title": "Новизна 32‑90 дней",
        "type": "float",
    },
    {
        "description": "Доля визитов посетителей с 2‑3 визитами.",
        "is_dim": False,
        "name": "ym:ad:upTo3VisitsPerUserPercentage",
        "title": "2‑3 визита посетителя",
        "type": "float",
    },
    {
        "description": "Доля визитов посетителей с частотой визитов один раз в 2‑7 дней. Учитываются посетители, совершившие больше двух визитов. При этом число дней визитов больше 1 дня.",
        "is_dim": False,
        "name": "ym:ad:upToWeekBetweenVisitsPercentage",
        "title": "Периодичность 2‑7 дней",
        "type": "float",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:ad:counterID",
        "title": "Счетчик (id)",
        "type": "string",
        "src_key": "id",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:ad:counterIDName",
        "title": "Счетчик",
        "type": "string",
    },
    {
        "description": "Поисковая фраза последнего перехода по объявлению Яндекс.Директа.",
        "is_dim": True,
        "name": "ym:ad:lastSignDirectSearchPhrase",
        "title": "Поисковая фраза (Директ) (last sign)",
        "type": "string",
    },
    {
        "description": "Рекламная кампания Яндекс.Директа.",
        "is_dim": True,
        "name": "ym:ad:lastSignDirectOrder",
        "title": "Кампания Яндекс.Директа (last sign)",
        "type": "string",
    },
    {
        "description": "Валюта, установленная в Яндекс.Директе для рекламной кампании.",
        "is_dim": True,
        "name": "ym:ad:firstCurrencyIDName",
        "title": "Валюта (first)",
        "type": "string",
    },
    {
        "description": "Тип условия показа объявления.",
        "is_dim": True,
        "name": "ym:ad:lastDirectConditionType",
        "title": "Тип условия показа объявления (last)",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:ad:lastDirectBanner",
        "title": "Объявление Яндекс.Директа (last)",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:ad:directBanner",
        "title": "Объявление Яндекс.Директа",
        "type": "string",
    },
    {
        "description": "Округа, в которых находятся посетители сайта.",
        "is_dim": True,
        "name": "ym:ad:regionDistrict",
        "title": "Округ",
        "type": "string",
    },
    {
        "description": "Континенты, в которых находятся посетители сайта.",
        "is_dim": True,
        "name": "ym:ad:regionContinent",
        "title": "Континент",
        "type": "string",
    },
    {
        "description": "Категория коммерческих интересов посетителей.",
        "is_dim": True,
        "name": "ym:ad:interest",
        "title": "Категория интересов",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:ad:directBannerText",
        "title": "Текст объявления",
        "type": "string",
    },
    {
        "description": "Условие показа объявления. Условием могут быть либо ключевые слова, либо условие ретаргетинга.",
        "is_dim": True,
        "name": "ym:ad:firstDirectPhraseOrCond",
        "title": "Условие показа объявления (first)",
        "type": "string",
    },
    {
        "description": "Рекламная площадка Яндекс.Директа.",
        "is_dim": True,
        "name": "ym:ad:directPlatform",
        "title": "Площадка",
        "type": "string",
    },
    {
        "description": "Возраст посетителя, интервал",
        "is_dim": True,
        "name": "ym:ad:ageInterval",
        "title": "Возраст",
        "type": "string",
    },
    {
        "description": "Условие показа объявления. Условием могут быть либо ключевые слова, либо условие ретаргетинга.",
        "is_dim": True,
        "name": "ym:ad:lastSignDirectPhraseOrCond",
        "title": "Условие показа объявления (last sign)",
        "type": "string",
    },
    {
        "description": "Рекламная кампания Яндекс.Директа.",
        "is_dim": True,
        "name": "ym:ad:directOrder",
        "title": "Кампания Яндекс.Директа",
        "type": "string",
    },
    {
        "description": "Рекламная кампания Яндекс.Директа.",
        "is_dim": True,
        "name": "ym:ad:lastDirectOrder",
        "title": "Кампания Яндекс.Директа (last)",
        "type": "string",
    },
    {
        "description": "Валюта, установленная в Яндекс.Директе для рекламной кампании.",
        "is_dim": True,
        "name": "ym:ad:lastCurrencyIDName",
        "title": "Валюта (last)",
        "type": "string",
    },
    {
        "description": "Условие показа объявления. Условием могут быть либо ключевые слова, либо условие ретаргетинга.",
        "is_dim": True,
        "name": "ym:ad:directPhraseOrCond",
        "title": "Условие показа объявления",
        "type": "string",
    },
    {
        "description": "Рекламная кампания Яндекс.Директа.",
        "is_dim": True,
        "name": "ym:ad:firstDirectOrder",
        "title": "Кампания Яндекс.Директа (first)",
        "type": "string",
    },
    {
        "description": "Города, в которых находятся посетители сайта.",
        "is_dim": True,
        "name": "ym:ad:regionCity",
        "title": "Город",
        "type": "string",
    },
    {
        "description": "Условие показа объявления. Условием могут быть либо ключевые слова, либо условие ретаргетинга.",
        "is_dim": True,
        "name": "ym:ad:lastDirectPhraseOrCond",
        "title": "Условие показа объявления (last)",
        "type": "string",
    },
    {
        "description": "Валюта, установленная в Яндекс.Директе для рекламной кампании.",
        "is_dim": True,
        "name": "ym:ad:lastSignCurrencyIDName",
        "title": "Валюта (last sign)",
        "type": "string",
    },
    {
        "description": 'Пол посетителя. Возможные значения: "мужской" или "женский".',
        "is_dim": True,
        "name": "ym:ad:gender",
        "title": "Пол",
        "type": "string",
    },
    {
        "description": "Валюта, установленная в Яндекс.Директе для рекламной кампании.",
        "is_dim": True,
        "name": "ym:ad:currency",
        "title": "Валюта",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:ad:firstDirectBanner",
        "title": "Объявление Яндекс.Директа (first)",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:ad:lastSignDirectBanner",
        "title": "Объявление Яндекс.Директа (last sign)",
        "type": "string",
    },
    {
        "description": "Тип условия показа объявления.",
        "is_dim": True,
        "name": "ym:ad:firstDirectConditionType",
        "title": "Тип условия показа объявления (first)",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:ad:displayCampaign",
        "title": "Номер заказа Яндекс.Дисплея",
        "type": "string",
    },
    {
        "description": "Тип условия показа объявления.",
        "is_dim": True,
        "name": "ym:ad:lastSignDirectConditionType",
        "title": "Тип условия показа объявления (last sign)",
        "type": "string",
    },
    {
        "description": "Группа объявлений Яндекс.Директа.",
        "is_dim": True,
        "name": "ym:ad:directBannerGroup",
        "title": "Группа объявлений",
        "type": "string",
    },
    {
        "description": "Поисковая фраза последнего перехода по объявлению Яндекс.Директа.",
        "is_dim": True,
        "name": "ym:ad:lastDirectSearchPhrase",
        "title": "Поисковая фраза (Директ) (last)",
        "type": "string",
    },
    {
        "description": "Поисковая фраза последнего перехода по объявлению Яндекс.Директа.",
        "is_dim": True,
        "name": "ym:ad:firstDirectSearchPhrase",
        "title": "Поисковая фраза (Директ) (first)",
        "type": "string",
    },
    {
        "description": "Размер города по населению.",
        "is_dim": True,
        "name": "ym:ad:regionCitySize",
        "title": "Размер города",
        "type": "string",
    },
    {
        "description": "Поисковая фраза последнего перехода по объявлению Яндекс.Директа.",
        "is_dim": True,
        "name": "ym:ad:directSearchPhrase",
        "title": "Поисковая фраза (Директ)",
        "type": "string",
    },
    {
        "description": "Тип условия показа объявления.",
        "is_dim": True,
        "name": "ym:ad:directConditionType",
        "title": "Тип условия показа объявления",
        "type": "string",
    },
    {
        "description": "Тип рекламной площадки Яндекс.Директа.",
        "is_dim": True,
        "name": "ym:ad:directPlatformType",
        "title": "Тип площадки",
        "type": "string",
    },
    {
        "description": "Области, в которых находятся посетители сайта.",
        "is_dim": True,
        "name": "ym:ad:regionArea",
        "title": "Область",
        "type": "string",
    },
    {
        "description": "Страны, в которых находятся посетители сайта.",
        "is_dim": True,
        "name": "ym:ad:regionCountry",
        "title": "Страна",
        "type": "string",
    },
]
