hits_fields = [
    {
        "description": "Среднее количество хитов в минуту.",
        "is_dim": False,
        "name": "ym:pv:pageviewsPerMinute",
        "title": "Просмотров в минуту",
        "type": "float",
    },
    {
        "description": "Доля визитов и хитов с поддержкой JavaScript.",
        "is_dim": False,
        "name": "ym:pv:jsEnabledPercentage",
        "title": "Поддержка JavaScript",
        "type": "float",  # percents
    },
    {
        "description": "Число просмотров страниц на сайте за отчетный период.",
        "is_dim": False,
        "name": "ym:pv:pageviews",
        "title": "Просмотры",
        "type": "integer",
    },
    {
        "description": "Средняя глубина просмотра в день.",
        "is_dim": False,
        "name": "ym:pv:pageviewsPerDay",
        "title": "Просмотров в день",
        "type": "float",
    },
    {
        "description": "Количество уникальных посетителей.",
        "is_dim": False,
        "name": "ym:pv:users",
        "title": "Посетители",
        "type": "integer",
    },
    {
        "description": "Среднее количество хитов в час.",
        "is_dim": False,
        "name": "ym:pv:pageviewsPerHour",
        "title": "Просмотров в час",
        "type": "float",
    },
    {
        "description": "Доля визитов с блокировщиками рекламы.",
        "is_dim": False,
        "name": "ym:pv:blockedPercentage",
        "title": "Блокировка рекламы",
        "type": "float",  # percents
    },
    {
        "description": "Доля визитов и хитов с включенными cookies.",
        "is_dim": False,
        "name": "ym:pv:cookieEnabledPercentage",
        "title": "Поддержка сookies",
        "type": "float",  # percents
    },
    {
        "description": "Доля визитов и хитов, совершенных с мобильных устройств.",
        "is_dim": False,
        "name": "ym:pv:mobilePercentage",
        "title": "Мобильность",
        "type": "float",  # percents
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:pv:URLDomain",
        "title": "Домен страницы",
        "type": "string",
    },
    {
        "description": (
            'Часть URL страницы, следующая сразу после домена до "?" (секция параметров), '
            '"#" (секция фрагмента) либо до конца строки. Например, для страницы '
            '"http://news.yandex.ru/quotes/1.html" путем является "/quotes/1.html", '
            'для "http://news.yandex.ru/" - "/", а для "http://news.yandex.ru" - пустая строка'
        ),
        "is_dim": True,
        "name": "ym:pv:URLPath",
        "title": "Путь страницы",
        "type": "string",
    },
    {
        "description": 'IPv4/IPv6-адрес посетителя с обнуленными 1/8 последними байтами соответственно. Например, "77.88.21.0"/"2001:db8:85a3::".',
        "is_dim": True,
        "name": "ym:pv:ipAddress",
        "title": "IP-адрес",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:pv:browserHourMinute",
        "title": "Час и минута на компьютере посетителя",
        "type": "string",
    },
    {
        "description": 'Ориентация экрана. Возможные значения: "landscape", "portrait".',
        "is_dim": True,
        "name": "ym:pv:screenOrientationName",
        "title": "Ориентация экрана",
        "type": "string",
    },
    {
        "description": "Дата и время просмотра в формате YYYY-MM-DD HH:mm:ss.",
        "is_dim": True,
        "name": "ym:pv:dateTime",
        "title": "Дата и время просмотра",
        "type": "datetime",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:pv:clientTimeZone",
        "title": "Часовой пояс на компьютере посетителя",
        "type": "string",
    },
    {
        "description": "Дата просмотра в формате YYYY-MM-DD, округленное до начала квартала.",
        "is_dim": True,
        "name": "ym:pv:startOfQuarter",
        "title": "Квартал просмотра",
        "type": "date",
    },
    {
        "description": "Источник перехода",
        "is_dim": True,
        "name": "ym:pv:UTMSource",
        "title": "UTM Source",
        "type": "string",
    },
    {
        "description": "Дата и время на компьютере посетителя в формате YYYY-MM-DD HH:mm:ss, округленное до начала квартала.",
        "is_dim": True,
        "name": "ym:pv:browserStartOfQuarter",
        "title": "Квартал на компьютере посетителя",
        "type": "datetime",
    },
    {
        "description": 'Первый уровень URL страницы. Например, для "http://ya.ru/1/2/3/4.html" первым уровнем URL является "http://ya.ru/".',
        "is_dim": True,
        "name": "ym:pv:URLPathLevel1",
        "title": "Адрес, ур. 1",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:pv:URL",
        "title": "Адрес страницы",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:pv:month",
        "title": "Месяц просмотра",
        "type": "string",
    },
    {
        "description": 'Глубина цвета экрана в битах. Например, "24".',
        "is_dim": True,
        "name": "ym:pv:screenColorsName",
        "title": "Глубина цвета",
        "type": "string",
    },
    {
        "description": 'Пятый уровень URL страницы входа. Например, для "http://ya.ru/1/2/3/4.html" пятым уровнем URL является "http://ya.ru/1/2/3/4.html".',
        "is_dim": True,
        "name": "ym:pv:URLPathLevel5",
        "title": "Адрес, ур. 5",
        "type": "string",
    },
    {
        "description": 'Четвертый уровень URL страницы. Например, для "http://ya.ru/1/2/3/4.html" четвертым уровнем URL является "http://ya.ru/1/2/3/".',
        "is_dim": True,
        "name": "ym:pv:URLPathLevel4",
        "title": "Адрес, ур. 4",
        "type": "string",
    },
    {
        "description": "Дата и время на компьютере посетителя в формате YYYY-MM-DD HH:mm:ss, округленное до начала 10-минутного интервала.",
        "is_dim": True,
        "name": "ym:pv:browserStartOfDekaminute",
        "title": "Начало декаминуты на компьютере посетителя",
        "type": "datetime",
    },
    {
        "description": 'Третий уровень URL страницы. Например, для "http://ya.ru/1/2/3/4.html" третьим уровнем URL является "http://ya.ru/1/2/".',
        "is_dim": True,
        "name": "ym:pv:URLPathLevel3",
        "title": "Адрес, ур. 3",
        "type": "string",
    },
    {
        "description": 'Второй уровень URL страницы. Например, для "http://ya.ru/1/2/3/4.html" вторым уровнем URL является "http://ya.ru/1/".',
        "is_dim": True,
        "name": "ym:pv:URLPathLevel2",
        "title": "Адрес, ур. 2",
        "type": "string",
    },
    {
        "description": 'Тип устройства, с которого было посещение. Возможные значения: "desktop", "mobile", "tablet", "tv".',
        "is_dim": True,
        "name": "ym:pv:deviceCategoryName",
        "title": "Тип устройства",
        "type": "string",
    },
    {
        "description": "Дата на компьютере посетителя в формате YYYY-MM-DD.",
        "is_dim": True,
        "name": "ym:pv:browserDate",
        "title": "Дата на компьютере посетителя",
        "type": "date",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:pv:hourName",
        "title": "Час просмотра в формате HH:00",
        "type": "string",
    },
    {
        "description": 'Разрешение экрана. Например, "1920х1080".',
        "is_dim": True,
        "name": "ym:pv:screenResolution",
        "title": "Разрешение",
        "type": "string",
    },
    {
        "description": "Континенты, в которых находятся посетители сайта.",
        "is_dim": True,
        "name": "ym:pv:regionContinentName",
        "title": "Континент",
        "type": "string",
    },
    # {
    #     'description': 'Дата просмотра в формате YYYY-MM-DD, округленное до начала месяца.',
    #     'is_dim': True,
    #     'name': 'ym:pv:startOfMonth',
    #     'title': 'Месяц просмотра',
    #     'type': 'date',
    # },
    {
        "description": "Объявление",
        "is_dim": True,
        "name": "ym:pv:UTMContent",
        "title": "UTM Content",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:pv:mobilePhoneName",
        "title": "Производитель устройства",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:pv:hasAdBlockerName",
        "title": "Наличие блокировщиков рекламы",
        "type": "string",
    },
    {
        "description": "Возраст посетителя, интервал",
        "is_dim": True,
        "name": "ym:pv:ageIntervalName",
        "title": "Возраст",
        "type": "string",
    },
    {
        "description": 'Движок браузера посетителя. Например, "WebKit".',
        "is_dim": True,
        "name": "ym:pv:browserEngine",
        "title": "Движок браузера",
        "type": "string",
    },
    {
        "description": "Рекламная кампания",
        "is_dim": True,
        "name": "ym:pv:openstatCampaign",
        "title": "Openstat Campaign",
        "type": "string",
    },
    {
        "description": 'Третий уровень URL реферера. Например, для "http://ya.ru/1/2/3/4.html" третьим уровнем URL является "http://ya.ru/1/2/".',
        "is_dim": True,
        "name": "ym:pv:refererPathLevel3",
        "title": "Реферер, ур. 3",
        "type": "string",
    },
    {
        "description": 'Второй уровень URL реферера. Например, для "http://ya.ru/1/2/3/4.html" вторым уровнем URL является "http://ya.ru/1/".',
        "is_dim": True,
        "name": "ym:pv:refererPathLevel2",
        "title": "Реферер, ур. 2",
        "type": "string",
    },
    {
        "description": 'Первый уровень URL реферера. Например, для "http://ya.ru/1/2/3/4.html" первым уровнем URL является "http://ya.ru/".',
        "is_dim": True,
        "name": "ym:pv:refererPathLevel1",
        "title": "Реферер, ур. 1",
        "type": "string",
    },
    {
        "description": "Рекламный сервис",
        "is_dim": True,
        "name": "ym:pv:openstatService",
        "title": "Openstat Service",
        "type": "string",
    },
    {
        "description": "Средство маркетинга",
        "is_dim": True,
        "name": "ym:pv:UTMMedium",
        "title": "UTM Medium",
        "type": "string",
    },
    {
        "description": 'Реальное разрешение экрана исходя из данных "device pixel ratio". Например, "1920х1080".',
        "is_dim": True,
        "name": "ym:pv:physicalScreenResolution",
        "title": "Реальное разрешение",
        "type": "string",
    },
    {
        "description": 'Пятый уровень URL реферера. Например, для "http://ya.ru/1/2/3/4.html" пятым уровнем URL является "http://ya.ru/1/2/3/4.html".',
        "is_dim": True,
        "name": "ym:pv:refererPathLevel5",
        "title": "Реферер, ур. 5",
        "type": "string",
    },
    {
        "description": 'Четвертый уровень URL реферера. Например, для "http://ya.ru/1/2/3/4.html" четвертым уровнем URL является "http://ya.ru/1/2/3/".',
        "is_dim": True,
        "name": "ym:pv:refererPathLevel4",
        "title": "Реферер, ур. 4",
        "type": "string",
    },
    {
        "description": "Название браузера и его версия.",
        "is_dim": True,
        "name": "ym:pv:browserAndVersionMajorName",
        "title": "Версия браузера",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:pv:browserHourName",
        "title": "Час на компьютере посетителя в формате HH:00",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:pv:operatingSystemName",
        "title": "Операционная система (детально)",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:pv:dayOfWeekName",
        "title": "День недели просмотра",
        "type": "string",
    },
    {
        "description": "Размер города по населению.",
        "is_dim": True,
        "name": "ym:pv:regionCitySizeName",
        "title": "Размер города",
        "type": "string",
    },
    {
        "description": "Области, в которых находятся посетители сайта.",
        "is_dim": True,
        "name": "ym:pv:regionAreaName",
        "title": "Область",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:pv:mobilePhoneModel",
        "title": "Модель устройства",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:pv:refererProto",
        "title": "Протокол реферера",
        "type": "string",
    },
    {
        "description": "URL реферера",
        "is_dim": True,
        "name": "ym:pv:referer",
        "title": "Реферер",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:pv:URLParamNameAndValue",
        "title": "Значение параметра URL",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:pv:from",
        "title": "Метка from",
        "type": "string",
    },
    # {
    #     'description': None,
    #     'is_dim': True,
    #     'name': 'ym:pv:browserDatePeriod<group>',
    #     'title': 'Дата на компьютере посетителя',
    #     'type': 'string',
    # },
    {
        "description": "Дата просмотра в формате YYYY-MM-DD.",
        "is_dim": True,
        "name": "ym:pv:date",
        "title": "Дата просмотра",
        "type": "date",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:pv:URLProto",
        "title": "Протокол страницы",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:pv:operatingSystemRootName",
        "title": "Группа операционных систем",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:pv:browserMonth",
        "title": "Месяц на компьютере посетителя",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:pv:counterID",
        "title": "Счетчик (id)",
        "type": "string",
        "src_key": "id",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:pv:counterIDName",
        "title": "Счетчик",
        "type": "string",
    },
    {
        "description": "Города, в которых находятся посетители сайта.",
        "is_dim": True,
        "name": "ym:pv:regionCityName",
        "title": "Город",
        "type": "string",
    },
    {
        "description": 'Наличие метки "GCLID".',
        "is_dim": True,
        "name": "ym:pv:hasGCLIDName",
        "title": "Наличие GCLID",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:pv:cookieEnabledName",
        "title": "Наличие Cookie",
        "type": "string",
    },
    {
        "description": "Часть URL реферера, следующая сразу после домена. В отличие от простого пути также содержит секции параметров и фрагмента.",
        "is_dim": True,
        "name": "ym:pv:refererPathFull",
        "title": "Путь (полный) реферера",
        "type": "string",
    },
    # {
    #     'description': 'Дата просмотра в формате YYYY-MM-DD, округленное до начала года.',
    #     'is_dim': True,
    #     'name': 'ym:pv:startOfYear',
    #     'title': 'Год просмотра',
    #     'type': 'string',
    # },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:pv:dayOfMonth",
        "title": "День месяца просмотра",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:pv:isTurboPageName",
        "title": "Турбо-страница",
        "type": "string",
    },
    {
        "description": "Часть URL страницы, следующая сразу после домена. В отличие от простого пути также содержит секции параметров и фрагмента",
        "is_dim": True,
        "name": "ym:pv:URLPathFull",
        "title": "Путь (полный) страницы",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:pv:title",
        "title": "Заголовок страницы",
        "type": "string",
    },
    # {
    #     'description': 'Дата и время на компьютере посетителя в формате YYYY-MM-DD HH:mm:ss, округленное до начала года.',
    #     'is_dim': True,
    #     'name': 'ym:pv:browserStartOfYear',
    #     'title': 'Год на компьютере посетителя',
    #     'type': 'string',
    # },
    {
        "description": "Ключевые слова",
        "is_dim": True,
        "name": "ym:pv:UTMTerm",
        "title": "UTM Term",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:pv:refererDomain",
        "title": "Домен реферера",
        "type": "string",
    },
    {
        "description": "Дата и время на компьютере посетителя в формате YYYY-MM-DD HH:mm:ss.",
        "is_dim": True,
        "name": "ym:pv:browserDateTime",
        "title": "Дата и время на компьютере посетителя",
        "type": "datetime",
    },
    {
        "description": "Страны, в которых находятся посетители сайта.",
        "is_dim": True,
        "name": "ym:pv:regionCountryName",
        "title": "Страна",
        "type": "string",
    },
    {
        "description": "Рекламное объявление",
        "is_dim": True,
        "name": "ym:pv:openstatAd",
        "title": "Openstat Ad",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:pv:year",
        "title": "Год просмотра",
        "type": "string",
    },
    {
        "description": "Название проводимой рекламной кампании",
        "is_dim": True,
        "name": "ym:pv:UTMCampaign",
        "title": "UTM Campaign",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:pv:URLParamName",
        "title": "Параметр URL",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:pv:browserYear",
        "title": "Год на компьютере посетителя",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:pv:browserDekaminute",
        "title": "Декаминута на компьютере посетителя",
        "type": "string",
    },
    {
        "description": (
            'Часть URL реферера, следующая сразу после домена до "?" (секция параметров), '
            '"#" (секция фрагмента) либо до конца строки. Например, для страницы '
            '"http://news.yandex.ru/quotes/1.html" путем является "/quotes/1.html", '
            'для "http://news.yandex.ru/"&#160;— "/", '
            'а для "http://news.yandex.ru"&#160;— пустая строка.'
        ),
        "is_dim": True,
        "name": "ym:pv:refererPath",
        "title": "Путь реферера",
        "type": "string",
    },
    {
        "description": 'Отношение ширины к высоте экрана. Например, "16:9".',
        "is_dim": True,
        "name": "ym:pv:screenFormat",
        "title": "Соотношение сторон",
        "type": "string",
    },
    {
        "description": "Место размещения",
        "is_dim": True,
        "name": "ym:pv:openstatSource",
        "title": "Openstat Source",
        "type": "string",
    },
    {
        "description": 'Пол посетителя. Возможные значения: "мужской" или "женский".',
        "is_dim": True,
        "name": "ym:pv:genderName",
        "title": "Пол",
        "type": "string",
    },
    {
        "description": "Логическая ширина экрана.",
        "is_dim": True,
        "name": "ym:pv:screenWidth",
        "title": "Логическая ширина",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:pv:browserLanguage",
        "title": "Язык браузера",
        "type": "string",
    },
    {
        "description": 'Физическая высота экрана исходя из данных "device pixel ratio".',
        "is_dim": True,
        "name": "ym:pv:physicalScreenHeight",
        "title": "Физическая высота",
        "type": "string",
    },
    # {
    #     'description': 'Дата и время на компьютере посетителя в формате YYYY-MM-DD HH:mm:ss, округленное до начала месяца.',
    #     'is_dim': True,
    #     'name': 'ym:pv:browserStartOfMonth',
    #     'title': 'Месяц на компьютере посетителя',
    #     'type': 'string',
    # },
    {
        "description": "Дата и время просмотра в формате YYYY-MM-DD HH:mm:ss, округленное до начала 10-минутного интервала.",
        "is_dim": True,
        "name": "ym:pv:startOfDekaminute",
        "title": "Начало декаминуты просмотра",
        "type": "datetime",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:pv:javascriptEnabledName",
        "title": "Наличие Javascript",
        "type": "string",
    },
    {
        "description": "Первое число в версии движка браузера посетителя.",
        "is_dim": True,
        "name": "ym:pv:browserEngineVersion1",
        "title": "Major-версия движка браузера",
        "type": "string",
    },
    {
        "description": "Второе число в версии движка браузера посетителя.",
        "is_dim": True,
        "name": "ym:pv:browserEngineVersion2",
        "title": "Minor-версия движка браузера",
        "type": "string",
    },
    {
        "description": "Ширина клиентской части окна браузера.",
        "is_dim": True,
        "name": "ym:pv:windowClientWidth",
        "title": "Ширина окна",
        "type": "string",
    },
    {
        "description": "Третье число (обычно номер сборки) в версии движка браузера посетителя.",
        "is_dim": True,
        "name": "ym:pv:browserEngineVersion3",
        "title": "Build-версия движка браузера",
        "type": "string",
    },
    {
        "description": "Дата и время на компьютере посетителя в формате YYYY-MM-DD HH:mm:ss, округленное до начала недели.",
        "is_dim": True,
        "name": "ym:pv:browserStartOfWeek",
        "title": "Неделя на компьютере посетителя",
        "type": "string",
    },
    {
        "description": 'Браузер посетителя. Например, "Яндекс.Браузер".',
        "is_dim": True,
        "name": "ym:pv:browserName",
        "title": "Браузер",
        "type": "string",
    },
    {
        "description": "Четвертое число (обычно номер ревизии) в версии движка браузера посетителя.",
        "is_dim": True,
        "name": "ym:pv:browserEngineVersion4",
        "title": "Revision-версия движка браузера",
        "type": "string",
    },
    # # Currently we don't support parametrized dimensions
    # {
    #     'description': 'Интервал дат с параметризацией размера интервала',
    #     'is_dim': True,
    #     'name': 'ym:pv:datePeriod<group>',
    #     'title': 'Дата',
    #     'type': 'date',
    # },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:pv:dekaminute",
        "title": "Декаминута просмотра",
        "type": "string",
    },
    {
        "description": "Логическая высота экрана.",
        "is_dim": True,
        "name": "ym:pv:screenHeight",
        "title": "Логическая высота",
        "type": "string",
    },
    {
        "description": 'Физическая ширина экрана исходя из данных "device pixel ratio".',
        "is_dim": True,
        "name": "ym:pv:physicalScreenWidth",
        "title": "Физическая ширина",
        "type": "string",
    },
    {
        "description": "Дата и время на компьютере посетителя в формате YYYY-MM-DD HH:mm:ss, округленное до начала часа.",
        "is_dim": True,
        "name": "ym:pv:browserStartOfHour",
        "title": "Час на компьютере посетителя",
        "type": "datetime",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:pv:hourMinute",
        "title": "Час и минута просмотра",
        "type": "string",
    },
    # {
    #     'description': 'Дата и время просмотра в формате YYYY-MM-DD HH:mm:ss, округленное до начала минуты.',
    #     'is_dim': True,
    #     'name': 'ym:pv:startOfMinute',
    #     'title': 'Минута просмотра',
    #     'type': 'datetime',
    # },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:pv:browserCountry",
        "title": "Страна браузера",
        "type": "string",
    },
    {
        "description": "Округа, в которых находятся посетители сайта.",
        "is_dim": True,
        "name": "ym:pv:regionDistrictName",
        "title": "Округ",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:pv:turboPageID",
        "title": "Турбо-страница (ID)",
        "type": "string",
    },
    {
        "description": "Браузер и его полная версия.",
        "is_dim": True,
        "name": "ym:pv:browserAndVersionName",
        "title": "Полная версия браузера",
        "type": "string",
    },
    # {
    #     'description': 'Дата и время на компьютере посетителя в формате YYYY-MM-DD HH:mm:ss, округленное до начала минуты.',
    #     'is_dim': True,
    #     'name': 'ym:pv:browserStartOfMinute',
    #     'title': 'Минута на компьютере посетителя',
    #     'type': 'datetime',
    # },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:pv:browserDayOfWeekName",
        "title": "День недели на компьютере посетителя",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:pv:browserMinute",
        "title": "Минута на компьютере посетителя",
        "type": "string",
    },
    {
        "description": "Дата и время просмотра в формате YYYY-MM-DD HH:mm:ss, округленное до начала часа.",
        "is_dim": True,
        "name": "ym:pv:startOfHour",
        "title": "Час просмотра",
        "type": "datetime",
    },
    {
        "description": "Высота клиентской части окна браузера.",
        "is_dim": True,
        "name": "ym:pv:windowClientHeight",
        "title": "Высота окна",
        "type": "string",
    },
    {
        "description": 'Размер клиентской части окна браузера. Например, "1920х1080".',
        "is_dim": True,
        "name": "ym:pv:windowClientArea",
        "title": "Размер окна",
        "type": "string",
    },
    {
        "description": "Дата просмотра в формате YYYY-MM-DD, округленное до начала недели.",
        "is_dim": True,
        "name": "ym:pv:startOfWeek",
        "title": "Неделя просмотра",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:pv:minute",
        "title": "Минута просмотра",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:pv:browserDayOfMonth",
        "title": "День месяца на компьютере посетителя",
        "type": "string",
    },
]
