# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yandex/cloud/priv/iam/v1/backoffice/permission_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.rpc import status_pb2 as google_dot_rpc_dot_status__pb2
from yandex.cloud.priv.access import access_pb2 as yandex_dot_cloud_dot_priv_dot_access_dot_access__pb2
from yandex.cloud.priv.servicecontrol.v1 import access_service_pb2 as yandex_dot_cloud_dot_priv_dot_servicecontrol_dot_v1_dot_access__service__pb2
from yandex.cloud.priv.servicecontrol.v1 import resource_pb2 as yandex_dot_cloud_dot_priv_dot_servicecontrol_dot_v1_dot_resource__pb2
from yandex.cloud.priv import validation_pb2 as yandex_dot_cloud_dot_priv_dot_validation__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n<yandex/cloud/priv/iam/v1/backoffice/permission_service.proto\x12#yandex.cloud.priv.iam.v1.backoffice\x1a\x17google/rpc/status.proto\x1a%yandex/cloud/priv/access/access.proto\x1a\x38yandex/cloud/priv/servicecontrol/v1/access_service.proto\x1a\x32yandex/cloud/priv/servicecontrol/v1/resource.proto\x1a\"yandex/cloud/priv/validation.proto\"\xca\x01\n\x16\x43heckPermissionRequest\x12 \n\npermission\x18\x01 \x01(\tB\x0c\xa8\x89\x31\x01\xca\x89\x31\x04<=50\x12O\n\rresource_path\x18\x02 \x03(\x0b\x32-.yandex.cloud.priv.servicecontrol.v1.ResourceB\t\xc2\x89\x31\x05\x31-100\x12=\n\x07subject\x18\x03 \x01(\x0b\x32,.yandex.cloud.priv.servicecontrol.v1.Subject\"t\n\x17\x43heckPermissionResponse\x12Y\n\x14resource_permissions\x18\x01 \x03(\x0b\x32;.yandex.cloud.priv.iam.v1.backoffice.ResourcePermissionInfo\"\xa9\x02\n\x16ResourcePermissionInfo\x12?\n\x08resource\x18\x01 \x01(\x0b\x32-.yandex.cloud.priv.servicecontrol.v1.Resource\x12@\n\x0f\x61\x63\x63\x65ss_bindings\x18\x02 \x03(\x0b\x32\'.yandex.cloud.priv.access.AccessBinding\x12J\n\x08response\x18\x03 \x01(\x0b\x32\x36.yandex.cloud.priv.servicecontrol.v1.AuthorizeResponseH\x00\x12$\n\x06status\x18\x04 \x01(\x0b\x32\x12.google.rpc.StatusH\x00\x42\x1a\n\x12\x61uthorize_response\x12\x04\x80\x83\x31\x01\x32\x98\x01\n\x11PermissionService\x12\x82\x01\n\x05\x43heck\x12;.yandex.cloud.priv.iam.v1.backoffice.CheckPermissionRequest\x1a<.yandex.cloud.priv.iam.v1.backoffice.CheckPermissionResponseBhB\x05PBOPSZ_a.yandex-team.ru/cloud/bitbucket/private-api/yandex/cloud/priv/iam/v1/backoffice;iam_backofficeb\x06proto3')



_CHECKPERMISSIONREQUEST = DESCRIPTOR.message_types_by_name['CheckPermissionRequest']
_CHECKPERMISSIONRESPONSE = DESCRIPTOR.message_types_by_name['CheckPermissionResponse']
_RESOURCEPERMISSIONINFO = DESCRIPTOR.message_types_by_name['ResourcePermissionInfo']
CheckPermissionRequest = _reflection.GeneratedProtocolMessageType('CheckPermissionRequest', (_message.Message,), {
  'DESCRIPTOR' : _CHECKPERMISSIONREQUEST,
  '__module__' : 'yandex.cloud.priv.iam.v1.backoffice.permission_service_pb2'
  # @@protoc_insertion_point(class_scope:yandex.cloud.priv.iam.v1.backoffice.CheckPermissionRequest)
  })
_sym_db.RegisterMessage(CheckPermissionRequest)

CheckPermissionResponse = _reflection.GeneratedProtocolMessageType('CheckPermissionResponse', (_message.Message,), {
  'DESCRIPTOR' : _CHECKPERMISSIONRESPONSE,
  '__module__' : 'yandex.cloud.priv.iam.v1.backoffice.permission_service_pb2'
  # @@protoc_insertion_point(class_scope:yandex.cloud.priv.iam.v1.backoffice.CheckPermissionResponse)
  })
_sym_db.RegisterMessage(CheckPermissionResponse)

ResourcePermissionInfo = _reflection.GeneratedProtocolMessageType('ResourcePermissionInfo', (_message.Message,), {
  'DESCRIPTOR' : _RESOURCEPERMISSIONINFO,
  '__module__' : 'yandex.cloud.priv.iam.v1.backoffice.permission_service_pb2'
  # @@protoc_insertion_point(class_scope:yandex.cloud.priv.iam.v1.backoffice.ResourcePermissionInfo)
  })
_sym_db.RegisterMessage(ResourcePermissionInfo)

_PERMISSIONSERVICE = DESCRIPTOR.services_by_name['PermissionService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'B\005PBOPSZ_a.yandex-team.ru/cloud/bitbucket/private-api/yandex/cloud/priv/iam/v1/backoffice;iam_backoffice'
  _CHECKPERMISSIONREQUEST.fields_by_name['permission']._options = None
  _CHECKPERMISSIONREQUEST.fields_by_name['permission']._serialized_options = b'\250\2111\001\312\2111\004<=50'
  _CHECKPERMISSIONREQUEST.fields_by_name['resource_path']._options = None
  _CHECKPERMISSIONREQUEST.fields_by_name['resource_path']._serialized_options = b'\302\2111\0051-100'
  _RESOURCEPERMISSIONINFO.oneofs_by_name['authorize_response']._options = None
  _RESOURCEPERMISSIONINFO.oneofs_by_name['authorize_response']._serialized_options = b'\200\2031\001'
  _CHECKPERMISSIONREQUEST._serialized_start=312
  _CHECKPERMISSIONREQUEST._serialized_end=514
  _CHECKPERMISSIONRESPONSE._serialized_start=516
  _CHECKPERMISSIONRESPONSE._serialized_end=632
  _RESOURCEPERMISSIONINFO._serialized_start=635
  _RESOURCEPERMISSIONINFO._serialized_end=932
  _PERMISSIONSERVICE._serialized_start=935
  _PERMISSIONSERVICE._serialized_end=1087
# @@protoc_insertion_point(module_scope)
