client_events_fields = [
    {
        'description': '',
        'is_dim': False,
        'name': 'ym:ce:users',
        'title': 'Количество пользователей',
        'type': 'integer',
    },
    {
        'description': 'Количество клиентских событий',
        'is_dim': False,
        'name': 'ym:ce:clientEvents',
        'title': 'Количество событий',
        'type': 'integer',
    },
    {
        'description': '',
        'is_dim': False,
        'name': 'ym:ce:devices',
        'title': 'Количество устройств',
        'type': 'integer',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:ce:isRooted',
        'title': 'Root-статус',
        'type': 'string',
    },
    {
        'description': 'Идентификатор приложения',
        'is_dim': True,
        'name': 'ym:ce:apiKey',
        'title': 'ID приложения',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:ce:UUID',
        'title': 'UUID приложения',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:ce:clientKitVersion',
        'title': 'Версия SDK клиента',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:ce:operatingSystemVersionInfo',
        'title': 'Версия платформы',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:ce:appVersion',
        'title': 'Версия приложения',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:ce:year',
        'title': 'Год',
        'type': 'integer',
    },
    {
        'description': 'Название города, к которому принадлежат посетители сайта.',
        'is_dim': True,
        'name': 'ym:ce:regionCityName',
        'title': 'Город',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:ce:date',
        'title': 'Дата',
        'type': 'date',
    },
    {
        'description': 'Дата и время в формате YYYY-MM-DD HH:mm:ss, округленное до начала года.',
        'is_dim': True,
        'name': 'ym:ce:startOfYear',
        'title': 'Дата (год)',
        'type': 'date',
    },
    {
        'description': 'Дата и время в формате YYYY-MM-DD HH:mm:ss, округленное до начала 10-минутного интервала.',
        'is_dim': True,
        'name': 'ym:ce:startOfDekaminute',
        'title': 'Дата (декаминута)',
        'type': 'datetime',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:ce:startOfQuarter',
        'title': 'Дата (квартал)',
        'type': 'date',
    },
    {
        'description': 'Дата и время в формате YYYY-MM-DD HH:mm:ss, округленное до начала месяца.',
        'is_dim': True,
        'name': 'ym:ce:startOfMonth',
        'title': 'Дата (месяц)',
        'type': 'date',
    },
    {
        'description': 'Дата и время в формате YYYY-MM-DD HH:mm:ss, округленное до начала минуты.',
        'is_dim': True,
        'name': 'ym:ce:startOfMinute',
        'title': 'Дата (минута)',
        'type': 'datetime',
    },
    {
        'description': 'Дата и время в формате YYYY-MM-DD HH:mm:ss, округленное до начала часа.',
        'is_dim': True,
        'name': 'ym:ce:startOfHour',
        'title': 'Дата (час)',
        'type': 'datetime',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:ce:dekaminute',
        'title': 'Декаминута',
        'type': 'integer',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:ce:dayOfMonth',
        'title': 'День месяца',
        'type': 'integer',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:ce:dayOfWeekName',
        'title': 'День недели',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:ce:appID',
        'title': 'Идентификатор приложения (в магазине приложений)',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:ce:googleAID',
        'title': 'Идентификатор рекламы Google',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:ce:iosIFA',
        'title': 'Идентификатор рекламы на iOS',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:ce:deviceID',
        'title': 'Идентификатор, полученный средствами системного API или выдаваемый Яндексом',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:ce:osMajorVersionInfoName',
        'title': 'Мажорная версия ОС',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:ce:clientKitVersionDetails',
        'title': 'Информация о версии SDK',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:ce:month',
        'title': 'Месяц',
        'type': 'integer',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:ce:minute',
        'title': 'Минута',
        'type': 'integer',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:ce:mobileDeviceModel',
        'title': 'Модель',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:ce:eventLabel',
        'title': 'Название события',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:ce:mpcName',
        'title': 'Название сотового оператора на основе кода сотового оператора (MPC)',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:ce:mccName',
        'title': 'Название страны на основе мобильного кода страны оператора (MCC)',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:ce:buildNumber',
        'title': 'Номер сборки приложения',
        'type': 'string',
    },
    {
        'description': 'Области, к которым принадлежат посетители сайта.',
        'is_dim': True,
        'name': 'ym:ce:regionAreaName',
        'title': 'Область',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:ce:operatingSystemInfoName',
        'title': 'Операционная система',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:ce:paramsValueNormalized',
        'title': 'Параметры событий',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:ce:paramsLevel1',
        'title': 'Параметры событий: уровень 1',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:ce:paramsLevel2',
        'title': 'Параметры событий: уровень 2',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:ce:paramsLevel3',
        'title': 'Параметры событий: уровень 3',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:ce:paramsLevel4',
        'title': 'Параметры событий: уровень 4',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:ce:paramsLevel5',
        'title': 'Параметры событий: уровень 5',
        'type': 'string',
    },
    {
        'description': 'Возможные значения: "yes", "no", "undefined".',
        'is_dim': True,
        'name': 'ym:ce:limitAdTracking',
        'title': 'Признак ограничения рекламного трекинга',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:ce:mobileDeviceBranding',
        'title': 'Производитель',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:ce:profileOrigin',
        'title': 'Профиль',
        'type': 'string',
    },
    {
        'description': 'Подробная информация о разрешении экрана. Например, "2560x1440 px (xxxhdpi)".',
        'is_dim': True,
        'name': 'ym:ce:screenResolutionDetailed',
        'title': 'Разрешение (подробно)',
        'type': 'string',
    },
    {
        'description': 'Название страны, к которой принадлежат посетители сайта.',
        'is_dim': True,
        'name': 'ym:ce:regionCountryName',
        'title': 'Страна',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:ce:connectionType',
        'title': 'Тип подключения: Cellular или Wi-Fi',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:ce:networkType',
        'title': 'Тип сети: 3G, EDGE и т.д.',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:ce:deviceTypeName',
        'title': 'Тип устройства',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:ce:device',
        'title': 'Устройство',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:ce:hour',
        'title': 'Час',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:ce:hourMinute',
        'title': 'Час и минута',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:ce:locale',
        'title': 'Язык интерфейса',
        'type': 'string',
    },
]
