installs_fields = [
    {
        'description': None,
        'is_dim': False,
        'name': 'ym:ts:openDevices',
        'title': 'Deeplinks',
        'type': 'integer',
    },
    {
        'description': 'Новые установки + реатрибутированные установки',
        'is_dim': False,
        'name': 'ym:ts:advInstallDevices',
        'title': 'Все установки',
        'type': 'integer',
    },
    {
        'description': None,
        'is_dim': False,
        'name': 'ym:ts:userClicks',
        'title': 'Клики',
        'type': 'integer',
    },
    {
        'description': None,
        'is_dim': False,
        'name': 'ym:ts:userConversion',
        'title': 'Конверсия из кликов в установки',
        'type': 'float',
    },
    {
        'description': None,
        'is_dim': False,
        'name': 'ym:ts:advNewInstallDevices',
        'title': 'Новые установки',
        'type': 'integer',
    },
    {
        'description': None,
        'is_dim': False,
        'name': 'ym:ts:advReattributedDevices',
        'title': 'Реатрибутированные установки',
        'type': 'integer',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:ts:campaignID',
        'title': 'Tracking ID кампании',
        'type': 'string',
    },
    {
        'description': 'Идентификатор приложения',
        'is_dim': True,
        'name': 'ym:ts:apiKey',
        'title': 'ID приложения',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:ts:UUID',
        'title': 'UUID приложения',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:ts:clientKitVersion',
        'title': 'Версия SDK клиента',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:ts:operatingSystemVersionInfo',
        'title': 'Версия платформы',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:ts:appVersion',
        'title': 'Версия приложения',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:ts:year',
        'title': 'Год',
        'type': 'integer',
    },
    {
        'description': 'Название города, к которому принадлежат посетители сайта.',
        'is_dim': True,
        'name': 'ym:ts:regionCityName',
        'title': 'Город',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:ts:date',
        'title': 'Дата',
        'type': 'date',
    },
    {
        'description': 'Дата и время в формате YYYY-MM-DD HH:mm:ss, округленное до начала года.',
        'is_dim': True,
        'name': 'ym:ts:startOfYear',
        'title': 'Дата (год)',
        'type': 'date',
    },
    {
        'description': 'Дата и время в формате YYYY-MM-DD HH:mm:ss, округленное до начала 10-минутного интервала.',
        'is_dim': True,
        'name': 'ym:ts:startOfDekaminute',
        'title': 'Дата (декаминута)',
        'type': 'datetime',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:ts:startOfQuarter',
        'title': 'Дата (квартал)',
        'type': 'date',
    },
    {
        'description': 'Дата и время в формате YYYY-MM-DD HH:mm:ss, округленное до начала месяца.',
        'is_dim': True,
        'name': 'ym:ts:startOfMonth',
        'title': 'Дата (месяц)',
        'type': 'date',
    },
    {
        'description': 'Дата и время в формате YYYY-MM-DD HH:mm:ss, округленное до начала минуты.',
        'is_dim': True,
        'name': 'ym:ts:startOfMinute',
        'title': 'Дата (минута)',
        'type': 'datetime',
    },
    {
        'description': 'Дата и время в формате YYYY-MM-DD HH:mm:ss, округленное до начала часа.',
        'is_dim': True,
        'name': 'ym:ts:startOfHour',
        'title': 'Дата (час)',
        'type': 'datetime',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:ts:dekaminute',
        'title': 'Декаминута',
        'type': 'integer',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:ts:dayOfMonth',
        'title': 'День месяца',
        'type': 'integer',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:ts:dayOfWeekName',
        'title': 'День недели',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:ts:urlParamValue',
        'title': 'Значения параметров трекинговой ссылки',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:ts:googleAID',
        'title': 'Идентификатор рекламы Google',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:ts:iosIFA',
        'title': 'Идентификатор рекламы на iOS',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:ts:deviceID',
        'title': 'Идентификатор, полученный средствами системного API или выдаваемый Яндексом',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:ts:urlParamKey',
        'title': 'Имена параметров трекинговой ссылки',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:ts:campaignName',
        'title': 'Кампания',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:ts:osMajorVersionInfoName',
        'title': 'Мажорная версия ОС',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:ts:month',
        'title': 'Месяц',
        'type': 'integer',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:ts:minute',
        'title': 'Минута',
        'type': 'integer',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:ts:mpcName',
        'title': 'Название сотового оператора на основе кода сотового оператора (MPC)',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:ts:mccName',
        'title': 'Название страны на основе мобильного кода страны оператора (MCC)',
        'type': 'string',
    },
    {
        'description': 'Области, к которым принадлежат посетители сайта.',
        'is_dim': True,
        'name': 'ym:ts:regionAreaName',
        'title': 'Область',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:ts:operatingSystemInfoName',
        'title': 'Операционная система',
        'type': 'string',
    },
    {
        'description': 'Возможные значения: "yes", "no", "undefined".',
        'is_dim': True,
        'name': 'ym:ts:limitAdTracking',
        'title': 'Признак ограничения рекламного трекинга',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:ts:publisherName',
        'title': 'Рекламная сеть',
        'type': 'string',
    },
    {
        'description': 'Название страны, к которой принадлежат посетители сайта.',
        'is_dim': True,
        'name': 'ym:ts:regionCountryName',
        'title': 'Страна',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:ts:device',
        'title': 'Устройство',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:ts:hour',
        'title': 'Час',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:ts:hourMinute',
        'title': 'Час и минута',
        'type': 'string',
    },
]
