push_events_fields = [
    {
        'description': '',
        'is_dim': False,
        'name': 'ym:pc:devices',
        'title': 'Количество устройств',
        'type': 'integer',
    },
    {
        'description': '',
        'is_dim': False,
        'name': 'ym:pc:receivedDevices',
        'title': 'Количество устройств, которые получили пуш',
        'type': 'integer',
    },
    {
        'description': '',
        'is_dim': False,
        'name': 'ym:pc:sentDevices',
        'title': 'Количество устройств, на которые был отправлен пуш',
        'type': 'integer',
    },
    {
        'description': '',
        'is_dim': False,
        'name': 'ym:pc:openedDevices',
        'title': 'Количество устройств, открывших пуш',
        'type': 'integer',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:pc:isRooted',
        'title': 'Root-статус',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:pc:tag',
        'title': 'Tag push-api кампании',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:pc:transfer',
        'title': 'Transfer_id push-api кампании',
        'type': 'string',
    },
    {
        'description': 'Идентификатор приложения',
        'is_dim': True,
        'name': 'ym:pc:apiKey',
        'title': 'ID приложения',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:pc:UUID',
        'title': 'UUID приложения',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:pc:clientKitVersion',
        'title': 'Версия SDK клиента',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:pc:operatingSystemVersionInfo',
        'title': 'Версия ОС',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:pc:appVersion',
        'title': 'Версия приложения',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:pc:hypothesisName',
        'title': 'Гипотеза push-кампании',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:pc:year',
        'title': 'Год',
        'type': 'integer',
    },
    {
        'description': 'Название города, к которому принадлежат посетители сайта.',
        'is_dim': True,
        'name': 'ym:pc:regionCityName',
        'title': 'Город',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:pc:date',
        'title': 'Дата',
        'type': 'date',
    },
    {
        'description': 'Дата и время в формате YYYY-MM-DD HH:mm:ss, округленное до начала года.',
        'is_dim': True,
        'name': 'ym:pc:startOfYear',
        'title': 'Дата (год)',
        'type': 'date',
    },
    {
        'description': 'Дата и время в формате YYYY-MM-DD HH:mm:ss, округленное до начала 10-минутного интервала.',
        'is_dim': True,
        'name': 'ym:pc:startOfDekaminute',
        'title': 'Дата (декаминута)',
        'type': 'datetime',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:pc:startOfQuarter',
        'title': 'Дата (квартал)',
        'type': 'date',
    },
    {
        'description': 'Дата и время в формате YYYY-MM-DD HH:mm:ss, округленное до начала месяца.',
        'is_dim': True,
        'name': 'ym:pc:startOfMonth',
        'title': 'Дата (месяц)',
        'type': 'date',
    },
    {
        'description': 'Дата и время в формате YYYY-MM-DD HH:mm:ss, округленное до начала минуты.',
        'is_dim': True,
        'name': 'ym:pc:startOfMinute',
        'title': 'Дата (минута)',
        'type': 'datetime',
    },
    {
        'description': 'Дата и время в формате YYYY-MM-DD HH:mm:ss, округленное до начала часа.',
        'is_dim': True,
        'name': 'ym:pc:startOfHour',
        'title': 'Дата (час)',
        'type': 'datetime',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:pc:dekaminute',
        'title': 'Декаминута',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:pc:dayOfMonth',
        'title': 'День месяца',
        'type': 'integer',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:pc:dayOfWeekName',
        'title': 'День недели',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:pc:appID',
        'title': 'Идентификатор приложения (в магазине приложений)',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:pc:googleAID',
        'title': 'Идентификатор рекламы Google',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:pc:iosIFA',
        'title': 'Идентификатор рекламы на iOS',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:pc:deviceID',
        'title': 'Идентификатор, полученный средствами системного API или выдаваемый Яндексом',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:pc:groupName',
        'title': 'Имя группы push-api кампании',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:pc:clientKitVersionDetails',
        'title': 'Информация о версии SDK',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:pc:campaignName',
        'title': 'Кампания',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:pc:osMajorVersionInfoName',
        'title': 'Мажорная версия ОС',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:pc:month',
        'title': 'Месяц',
        'type': 'integer',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:pc:minute',
        'title': 'Минута',
        'type': 'integer',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:pc:mobileDeviceModel',
        'title': 'Модель',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:pc:mpcName',
        'title': 'Название сотового оператора на основе кода сотового оператора (MPC)',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:pc:mccName',
        'title': 'Название страны на основе мобильного кода страны оператора (MCC)',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:pc:buildNumber',
        'title': 'Номер сборки приложения',
        'type': 'string',
    },
    {
        'description': 'Области, к которым принадлежат посетители сайта.',
        'is_dim': True,
        'name': 'ym:pc:regionAreaName',
        'title': 'Область',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:pc:operatingSystemInfoName',
        'title': 'Операционная система',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:pc:isFromCampaign',
        'title': 'Признак для разделения push-api кампаний и интерфейсных кампаний',
        'type': 'string',
    },
    {
        'description': 'Возможные значения: "yes", "no", "undefined".',
        'is_dim': True,
        'name': 'ym:pc:limitAdTracking',
        'title': 'Признак ограничения рекламного трекинга',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:pc:mobileDeviceBranding',
        'title': 'Производитель',
        'type': 'string',
    },
    {
        'description': 'Подробная информация о разрешении экрана. Например, "2560x1440 px (xxxhdpi)".',
        'is_dim': True,
        'name': 'ym:pc:screenResolutionDetailed',
        'title': 'Разрешение (подробно)',
        'type': 'string',
    },
    {
        'description': 'Название страны, к которой принадлежат посетители сайта.',
        'is_dim': True,
        'name': 'ym:pc:regionCountryName',
        'title': 'Страна',
        'type': 'string',
    },
    {
        'description': 'Возможные значения: Отправлено, Получено, Проигнорировано, Открыто, Контрольная выборка',
        'is_dim': True,
        'name': 'ym:pc:actionTypeName',
        'title': 'Тип события Push',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:pc:deviceTypeName',
        'title': 'Тип устройства',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:pc:device',
        'title': 'Устройство',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:pc:hour',
        'title': 'Час',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:pc:hourMinute',
        'title': 'Час и минута',
        'type': 'string',
    },
    {
        'description': None,
        'is_dim': True,
        'name': 'ym:pc:locale',
        'title': 'Язык интерфейса',
        'type': 'string',
    },
]
