#!/usr/bin/env sh

set -x  # debug.
set -eu

HTTP_BIND_PORT="${RQE_EXT_ASYNC_PORT:-9877}"
if [ "${BISYS_USE_IPV6:-1}" = "1" ]; then HTTP_BIND_ADDR="[::]"; else HTTP_BIND_ADDR="0.0.0.0"; fi

exec \
    /code/app/bi_rqe_ext_async \
        --host "${HTTP_BIND_ADDR}" \
        --port "${HTTP_BIND_PORT}"
