from __future__ import annotations

from typing import (
    Iterable,
    Optional,
)

import attr

from dl_connector_bitrix_gds.core.constants import BitrixGDSTableType


CRM_DEAL = [
    {"name": "ID", "type": "integer"},
    {"name": "DATE_CREATE", "type": "datetime"},
    {"name": "DATE_MODIFY", "type": "datetime"},
    {"name": "CREATED_BY_ID", "type": "integer"},
    {"name": "CREATED_BY_NAME", "type": "string"},
    {"name": "CREATED_BY", "type": "string"},
    {"name": "MODIFY_BY_ID", "type": "integer"},
    {"name": "MODIFIED_BY_NAME", "type": "string"},
    {"name": "MODIFIED_BY", "type": "string"},
    {"name": "ASSIGNED_BY_ID", "type": "integer"},
    {"name": "ASSIGNED_BY_NAME", "type": "string"},
    {"name": "ASSIGNED_BY", "type": "string"},
    {"name": "ASSIGNED_BY_DEPARTMENT", "type": "string"},
    {"name": "OPENED", "type": "string"},
    {"name": "LEAD_ID", "type": "integer"},
    {"name": "COMPANY_ID", "type": "integer"},
    {"name": "COMPANY_NAME", "type": "string"},
    {"name": "COMPANY", "type": "string"},
    {"name": "CONTACT_ID", "type": "string"},
    {"name": "CONTACT_NAME", "type": "string"},
    {"name": "CONTACT", "type": "string"},
    {"name": "TITLE", "type": "string"},
    {"name": "CRM_PRODUCT", "type": "string"},
    {"name": "CRM_PRODUCT_COUNT", "type": "string"},
    {"name": "CATEGORY_ID", "type": "string"},
    {"name": "CATEGORY_NAME", "type": "string"},
    {"name": "CATEGORY", "type": "string"},
    {"name": "STAGE_ID", "type": "string"},
    {"name": "STAGE_NAME", "type": "string"},
    {"name": "STAGE", "type": "string"},
    {"name": "STAGE_SEMANTIC_ID", "type": "string"},
    {"name": "STAGE_SEMANTIC", "type": "string"},
    {"name": "IS_NEW", "type": "string"},
    {"name": "IS_RECURRING", "type": "string"},
    {"name": "IS_RETURN_CUSTOMER", "type": "string"},
    {"name": "CLOSED", "type": "string"},
    {"name": "TYPE_ID", "type": "string"},
    {"name": "OPPORTUNITY", "type": "string"},
    {"name": "IS_MANUAL_OPPORTUNITY", "type": "string"},
    {"name": "TAX_VALUE", "type": "string"},
    {"name": "CURRENCY_ID", "type": "string"},
    {"name": "OPPORTUNITY_ACCOUNT", "type": "string"},
    {"name": "TAX_VALUE_ACCOUNT", "type": "string"},
    {"name": "ACCOUNT_CURRENCY_ID", "type": "string"},
    {"name": "PROBABILITY", "type": "string"},
    {"name": "COMMENTS", "type": "string"},
    {"name": "BEGINDATE", "type": "datetime"},
    {"name": "CLOSEDATE", "type": "datetime"},
    {"name": "LOCATION_ID", "type": "string"},
    {"name": "SOURCE_ID", "type": "string"},
    {"name": "SOURCE_NAME", "type": "string"},
    {"name": "SOURCE", "type": "string"},
    {"name": "SOURCE_DESCRIPTION", "type": "string"},
    {"name": "ORIGINATOR_ID", "type": "string"},
    {"name": "ORIGIN_ID", "type": "string"},
    {"name": "ADDITIONAL_INFO", "type": "string"},
    {"name": "UTM_SOURCE", "type": "string"},
    {"name": "UTM_MEDIUM", "type": "string"},
    {"name": "UTM_CAMPAIGN", "type": "string"},
    {"name": "UTM_CONTENT", "type": "string"},
    {"name": "UTM_TERM", "type": "string"},
    {"name": "BANK_DETAIL_ID", "type": "string"},
]


CRM_LEAD = [
    {"name": "ID", "type": "integer"},
    {"name": "DATE_MODIFY", "type": "datetime"},
    {"name": "DATE_CREATE", "type": "datetime"},
    {"name": "CREATED_BY_ID", "type": "integer"},
    {"name": "CREATED_BY", "type": "string"},
    {"name": "MODIFY_BY_ID", "type": "integer"},
    {"name": "MODIFIED_BY_NAME", "type": "string"},
    {"name": "MODIFIED_BY", "type": "string"},
    {"name": "ASSIGNED_BY_ID", "type": "integer"},
    {"name": "ASSIGNED_BY_NAME", "type": "string"},
    {"name": "ASSIGNED_BY", "type": "string"},
    {"name": "ASSIGNED_BY_DEPARTMENT", "type": "string"},
    {"name": "OPENED", "type": "string"},
    {"name": "COMPANY_ID", "type": "integer"},
    {"name": "COMPANY_NAME", "type": "string"},
    {"name": "COMPANY", "type": "string"},
    {"name": "CONTACT_ID", "type": "string"},
    {"name": "CONTACT_NAME", "type": "string"},
    {"name": "CONTACT", "type": "string"},
    {"name": "STATUS_ID", "type": "string"},
    {"name": "STATUS_NAME", "type": "string"},
    {"name": "STATUS", "type": "string"},
    {"name": "STATUS_DESCRIPTION", "type": "string"},
    {"name": "STATUS_SEMANTIC_ID", "type": "string"},
    {"name": "STATUS_SEMANTIC", "type": "string"},
    {"name": "CRM_PRODUCT_ID", "type": "string"},
    {"name": "CRM_PRODUCT_NAME", "type": "string"},
    {"name": "CRM_PRODUCT", "type": "string"},
    {"name": "OPPORTUNITY", "type": "string"},
    {"name": "CURRENCY_ID", "type": "string"},
    {"name": "SOURCE_ID", "type": "string"},
    {"name": "SOURCE_NAME", "type": "string"},
    {"name": "SOURCE", "type": "string"},
    {"name": "SOURCE_DESCRIPTION", "type": "string"},
    {"name": "TITLE", "type": "string"},
    {"name": "FULL_NAME", "type": "string"},
    {"name": "NAME", "type": "string"},
    {"name": "LAST_NAME", "type": "string"},
    {"name": "SECOND_NAME", "type": "string"},
    {"name": "COMPANY_TITLE", "type": "string"},
    {"name": "POST", "type": "string"},
    {"name": "ADDRESS_1", "type": "string"},
    {"name": "ADDRESS_2", "type": "string"},
    {"name": "ADDRESS_CITY", "type": "string"},
    {"name": "ADDRESS_POSTAL_CODE", "type": "string"},
    {"name": "ADDRESS_REGION", "type": "string"},
    {"name": "ADDRESS_PROVINCE", "type": "string"},
    {"name": "ADDRESS_COUNTRY", "type": "string"},
    {"name": "ADDRESS_COUNTRY_CODE", "type": "string"},
    {"name": "COMMENTS", "type": "string"},
    {"name": "ORIGINATOR_ID", "type": "string"},
    {"name": "ORIGIN_ID", "type": "string"},
    {"name": "DATE_CLOSED", "type": "datetime"},
    {"name": "BIRTHDATE", "type": "datetime"},
    {"name": "HONORIFIC", "type": "string"},
    {"name": "UTM_SOURCE", "type": "string"},
    {"name": "UTM_MEDIUM", "type": "string"},
    {"name": "UTM_CAMPAIGN", "type": "string"},
    {"name": "UTM_CONTENT", "type": "string"},
    {"name": "UTM_TERM", "type": "string"},
    {"name": "PHONE", "type": "string"},
    {"name": "WEB", "type": "string"},
    {"name": "EMAIL", "type": "string"},
    {"name": "IM", "type": "string"},
]


CRM_COMPANY = [
    {"name": "ID", "type": "integer"},
    {"name": "DATE_CREATE", "type": "datetime"},
    {"name": "DATE_MODIFY", "type": "datetime"},
    {"name": "CREATED_BY_ID", "type": "integer"},
    {"name": "CREATED_BY_NAME", "type": "string"},
    {"name": "CREATED_BY", "type": "string"},
    {"name": "MODIFY_BY_ID", "type": "integer"},
    {"name": "MODIFIED_BY_NAME", "type": "string"},
    {"name": "MODIFIED_BY", "type": "string"},
    {"name": "ASSIGNED_BY_ID", "type": "integer"},
    {"name": "ASSIGNED_BY_NAME", "type": "string"},
    {"name": "ASSIGNED_BY", "type": "string"},
    {"name": "OPENED", "type": "string"},
    {"name": "TITLE", "type": "string"},
    {"name": "ADDRESS_1", "type": "string"},
    {"name": "ADDRESS_2", "type": "string"},
    {"name": "ADDRESS_CITY", "type": "string"},
    {"name": "ADDRESS_POSTAL_CODE", "type": "string"},
    {"name": "ADDRESS_REGION", "type": "string"},
    {"name": "ADDRESS_PROVINCE", "type": "string"},
    {"name": "ADDRESS_COUNTRY", "type": "string"},
    {"name": "ADDRESS_COUNTRY_CODE", "type": "string"},
    {"name": "BANKING_DETAILS", "type": "string"},
    {"name": "COMMENTS", "type": "string"},
    {"name": "COMPANY_TYPE_ID", "type": "string"},
    {"name": "COMPANY_TYPE_NAME", "type": "string"},
    {"name": "COMPANY_TYPE", "type": "string"},
    {"name": "INDUSTRY_ID", "type": "string"},
    {"name": "INDUSTRY_NAME", "type": "string"},
    {"name": "INDUSTRY", "type": "string"},
    {"name": "REVENUE", "type": "float"},
    {"name": "CURRENCY_ID", "type": "string"},
    {"name": "EMPLOYEES", "type": "string"},
    {"name": "LEAD_ID", "type": "integer"},
    {"name": "ORIGINATOR_ID", "type": "string"},
    {"name": "ORIGIN_ID", "type": "string"},
    {"name": "ORIGIN_VERSION", "type": "string"},
    {"name": "IS_MY_COMPANY", "type": "string"},
    {"name": "UTM_SOURCE", "type": "string"},
    {"name": "UTM_MEDIUM", "type": "string"},
    {"name": "UTM_CAMPAIGN", "type": "string"},
    {"name": "UTM_CONTENT", "type": "string"},
    {"name": "UTM_TERM", "type": "string"},
    {"name": "PHONE", "type": "string"},
    {"name": "WEB", "type": "string"},
    {"name": "EMAIL", "type": "string"},
    {"name": "IM", "type": "string"},
]


CRM_CONTACT = [
    {"name": "ID", "type": "integer"},
    {"name": "DATE_CREATE", "type": "datetime"},
    {"name": "DATE_MODIFY", "type": "datetime"},
    {"name": "CREATED_BY_ID", "type": "integer"},
    {"name": "CREATED_BY_NAME", "type": "string"},
    {"name": "CREATED_BY", "type": "string"},
    {"name": "MODIFY_BY_ID", "type": "integer"},
    {"name": "MODIFIED_BY_NAME", "type": "string"},
    {"name": "MODIFIED_BY", "type": "string"},
    {"name": "ASSIGNED_BY_ID", "type": "integer"},
    {"name": "ASSIGNED_BY_NAME", "type": "string"},
    {"name": "ASSIGNED_BY", "type": "string"},
    {"name": "OPENED", "type": "string"},
    {"name": "COMPANY_ID", "type": "integer"},
    {"name": "SOURCE_ID", "type": "string"},
    {"name": "SOURCE_DESCRIPTION", "type": "string"},
    {"name": "NAME", "type": "string"},
    {"name": "LAST_NAME", "type": "string"},
    {"name": "SECOND_NAME", "type": "string"},
    {"name": "POST", "type": "string"},
    {"name": "ADDRESS_1", "type": "string"},
    {"name": "ADDRESS_2", "type": "string"},
    {"name": "ADDRESS_CITY", "type": "string"},
    {"name": "ADDRESS_POSTAL_CODE", "type": "string"},
    {"name": "ADDRESS_REGION", "type": "string"},
    {"name": "ADDRESS_PROVINCE", "type": "string"},
    {"name": "ADDRESS_COUNTRY", "type": "string"},
    {"name": "ADDRESS_COUNTRY_CODE", "type": "string"},
    {"name": "COMMENTS", "type": "string"},
    {"name": "LEAD_ID", "type": "integer"},
    {"name": "EXPORT", "type": "string"},
    {"name": "TYPE_ID", "type": "string"},
    {"name": "ORIGINATOR_ID", "type": "string"},
    {"name": "ORIGIN_ID", "type": "string"},
    {"name": "ORIGIN_VERSION", "type": "string"},
    {"name": "BIRTHDATE", "type": "date"},
    {"name": "HONORIFIC", "type": "string"},
    {"name": "FACE_ID", "type": "string"},
    {"name": "PHONE", "type": "string"},
    {"name": "WEB", "type": "string"},
    {"name": "EMAIL", "type": "string"},
    {"name": "IM", "type": "string"},
    {"name": "UTM_SOURCE", "type": "string"},
    {"name": "UTM_MEDIUM", "type": "string"},
    {"name": "UTM_CAMPAIGN", "type": "string"},
    {"name": "UTM_CONTENT", "type": "string"},
    {"name": "UTM_TERM", "type": "string"},
]


CRM_DEAL_STAGE_HISTORY = [
    {"name": "ID", "type": "integer"},
    {"name": "TYPE_ID", "type": "integer"},
    {"name": "DEAL_ID", "type": "integer"},
    {"name": "DATE_CREATE", "type": "datetime"},
    {"name": "START_DATE", "type": "string"},
    {"name": "END_DATE", "type": "string"},
    {"name": "ASSIGNED_BY_ID", "type": "integer"},
    {"name": "ASSIGNED_BY_NAME", "type": "string"},
    {"name": "ASSIGNED_BY", "type": "string"},
    {"name": "ASSIGNED_BY_DEPARTMENT", "type": "string"},
    {"name": "STAGE_SEMANTIC_ID", "type": "string"},
    {"name": "STAGE_SEMANTIC", "type": "string"},
    {"name": "STAGE_ID", "type": "string"},
    {"name": "STAGE_NAME", "type": "string"},
    {"name": "STAGE", "type": "string"},
]


CRM_LEAD_STATUS_HISTORY = [
    {"name": "ID", "type": "integer"},
    {"name": "TYPE_ID", "type": "integer"},
    {"name": "LEAD_ID", "type": "integer"},
    {"name": "DATE_CREATE", "type": "datetime"},
    {"name": "ASSIGNED_BY_ID", "type": "integer"},
    {"name": "ASSIGNED_BY_NAME", "type": "string"},
    {"name": "ASSIGNED_BY", "type": "string"},
    {"name": "ASSIGNED_BY_DEPARTMENT", "type": "string"},
    {"name": "STATUS_SEMANTIC_ID", "type": "string"},
    {"name": "STATUS_SEMANTIC", "type": "string"},
    {"name": "STATUS_ID", "type": "string"},
    {"name": "STATUS_NAME", "type": "string"},
    {"name": "STATUS", "type": "string"},
]


SOCIALNETWORK_GROUP = [
    {"name": "ID", "type": "integer"},
    {"name": "SITE_ID", "type": "string"},
    {"name": "NAME", "type": "string"},
    {"name": "DESCRIPTION", "type": "string"},
    {"name": "DATE_CREATE", "type": "datetime"},
    {"name": "DATE_MODIFY", "type": "datetime"},
    {"name": "OPENED", "type": "string"},
    {"name": "SUBJECT", "type": "string"},
    {"name": "OWNER_ID", "type": "integer"},
    {"name": "OWNER_NAME", "type": "string"},
    {"name": "OWNER", "type": "string"},
    {"name": "KEYWORDS", "type": "string"},
    {"name": "NUMBER_OF_MEMBERS", "type": "integer"},
    {"name": "DATE_ACTIVITY", "type": "datetime"},
    {"name": "CLOSED", "type": "string"},
    {"name": "PROJECT", "type": "string"},
]


TELEPHONY_CALL = [
    {"name": "CALL_ID", "type": "string"},
    {"name": "PORTAL_USER_ID", "type": "integer"},
    {"name": "PORTAL_USER", "type": "string"},
    {"name": "PORTAL_USER_DEPARTMENT", "type": "string"},
    {"name": "PORTAL_NUMBER", "type": "string"},
    {"name": "PHONE_NUMBER", "type": "string"},
    {"name": "CALL_TYPE", "type": "integer"},
    {"name": "CALL_DURATION", "type": "integer"},
    {"name": "CALL_START_TIME", "type": "datetime"},
    {"name": "CALL_STATUS_CODE", "type": "string"},
    {"name": "CALL_STATUS_REASON", "type": "string"},
    {"name": "RECORD_FILE_ID", "type": "integer"},
    {"name": "CALL_VOTE", "type": "integer"},
    {"name": "COST", "type": "float"},
    {"name": "COST_CURRENCY", "type": "string"},
    {"name": "CRM_ENTITY_TYPE", "type": "string"},
    {"name": "CRM_ENTITY_ID", "type": "integer"},
    {"name": "CRM_ACTIVITY_ID", "type": "integer"},
    {"name": "REST_APP_ID", "type": "integer"},
    {"name": "REST_APP_NAME", "type": "string"},
    {"name": "TRANSCRIPT_PENDING", "type": "string"},
    {"name": "TRANSCRIPT_ID", "type": "integer"},
    {"name": "REDIAL_ATTEMPT", "type": "integer"},
    {"name": "COMMENT", "type": "string"},
]


CRM_ACTIVITY = [
    {"name": "ID", "type": "integer"},
    {"name": "TYPE_ID", "type": "integer"},
    {"name": "TYPE_NAME", "type": "string"},
    {"name": "OWNER_ID", "type": "integer"},
    {"name": "OWNER_TYPE_ID", "type": "integer"},
    {"name": "OWNER_TYPE_NAME", "type": "string"},
    {"name": "ASSOCIATED_ENTITY_ID", "type": "integer"},
    {"name": "SUBJECT", "type": "string"},
    {"name": "COMPLETED", "type": "string"},
    {"name": "STATUS_ID", "type": "integer"},
    {"name": "STATUS_NAME", "type": "string"},
    {"name": "RESPONSIBLE_ID", "type": "integer"},
    {"name": "RESPONSIBLE_NAME", "type": "string"},
    {"name": "RESPONSIBLE", "type": "string"},
    {"name": "PRIORITY_ID", "type": "integer"},
    {"name": "PRIORITY_NAME", "type": "string"},
    {"name": "DESCRIPTION", "type": "string"},
    {"name": "DESCRIPTION_TYPE_ID", "type": "integer"},
    {"name": "DESCRIPTION_TYPE_NAME", "type": "string"},
    {"name": "DIRECTION_ID", "type": "integer"},
    {"name": "DIRECTION_NAME", "type": "string"},
    {"name": "DATE_CREATE", "type": "datetime"},
    {"name": "DATE_MODIFY", "type": "datetime"},
    {"name": "START_TIME", "type": "datetime"},
    {"name": "END_TIME", "type": "datetime"},
    {"name": "DEADLINE", "type": "datetime"},
    {"name": "ORIGINATOR_ID", "type": "string"},
    {"name": "ORIGIN_ID", "type": "string"},
    {"name": "AUTHOR_ID", "type": "integer"},
    {"name": "AUTHOR_NAME", "type": "string"},
    {"name": "AUTHOR", "type": "string"},
    {"name": "EDITOR_ID", "type": "integer"},
    {"name": "EDITOR_NAME", "type": "string"},
    {"name": "EDITOR", "type": "string"},
]


CRM_LEAD_UF = [
    {"name": "LEAD_ID", "type": "integer"},
    {"name": "DATE_MODIFY", "type": "datetime"},
    {"name": "DATE_CREATE", "type": "datetime"},
    {"name": "DATE_CLOSED", "type": "datetime"},
]


CRM_DEAL_UF = [
    {"name": "DEAL_ID", "type": "integer"},
    {"name": "DATE_CREATE", "type": "datetime"},
    {"name": "CLOSEDATE", "type": "datetime"},
]


CRM_LEAD_PRODUCT_ROW = [
    {"name": "ID", "type": "integer"},
    {"name": "LEAD_ID", "type": "integer"},
    {"name": "LEAD_DATE_MODIFY", "type": "datetime"},
    {"name": "LEAD_DATE_CREATE", "type": "datetime"},
    {"name": "LEAD_DATE_CLOSED", "type": "datetime"},
    {"name": "PRODUCT", "type": "string"},
    {"name": "PRODUCT_ID", "type": "integer"},
    {"name": "PRODUCT_NAME", "type": "string"},
    {"name": "PRICE", "type": "string"},
    {"name": "PRICE_EXCLUSIVE", "type": "string"},
    {"name": "PRICE_NETTO", "type": "string"},
    {"name": "PRICE_BRUTTO", "type": "string"},
    {"name": "QUANTITY", "type": "string"},
    {"name": "DISCOUNT_TYPE", "type": "string"},
    {"name": "DISCOUNT_TYPE_ID", "type": "integer"},
    {"name": "DISCOUNT_TYPE_NAME", "type": "string"},
    {"name": "DISCOUNT_RATE", "type": "string"},
    {"name": "DISCOUNT_SUM", "type": "string"},
    {"name": "TAX_RATE", "type": "string"},
    {"name": "TAX_INCLUDED", "type": "string"},
    {"name": "CUSTOMIZED", "type": "string"},
    {"name": "MEASURE", "type": "string"},
    {"name": "MEASURE_CODE", "type": "integer"},
    {"name": "MEASURE_NAME", "type": "string"},
    {"name": "SORT", "type": "integer"},
]


CRM_DEAL_PRODUCT_ROW = [
    {"name": "ID", "type": "integer"},
    {"name": "DEAL_ID", "type": "integer"},
    {"name": "DEAL_DATE_CREATE", "type": "datetime"},
    {"name": "DEAL_CLOSEDATE", "type": "datetime"},
    {"name": "PRODUCT", "type": "string"},
    {"name": "PRODUCT_ID", "type": "integer"},
    {"name": "PRODUCT_NAME", "type": "string"},
    {"name": "PRICE", "type": "string"},
    {"name": "PRICE_EXCLUSIVE", "type": "string"},
    {"name": "PRICE_NETTO", "type": "string"},
    {"name": "PRICE_BRUTTO", "type": "string"},
    {"name": "QUANTITY", "type": "string"},
    {"name": "DISCOUNT_TYPE", "type": "string"},
    {"name": "DISCOUNT_TYPE_ID", "type": "integer"},
    {"name": "DISCOUNT_TYPE_NAME", "type": "string"},
    {"name": "DISCOUNT_RATE", "type": "string"},
    {"name": "DISCOUNT_SUM", "type": "string"},
    {"name": "TAX_RATE", "type": "string"},
    {"name": "TAX_INCLUDED", "type": "string"},
    {"name": "CUSTOMIZED", "type": "string"},
    {"name": "MEASURE", "type": "string"},
    {"name": "MEASURE_CODE", "type": "integer"},
    {"name": "MEASURE_NAME", "type": "string"},
    {"name": "SORT", "type": "integer"},
]


CRM_DYNAMIC_ITEMS = [
    {"name": "ID", "type": "integer"},
    {"name": "XML_ID", "type": "string"},
    {"name": "TITLE", "type": "string"},
    {"name": "CREATED_BY", "type": "string"},
    {"name": "CREATED_BY_ID", "type": "integer"},
    {"name": "CREATED_BY_NAME", "type": "string"},
    {"name": "UPDATED_BY", "type": "string"},
    {"name": "UPDATED_BY_ID", "type": "integer"},
    {"name": "UPDATED_BY_NAME", "type": "string"},
    {"name": "MOVED_BY", "type": "string"},
    {"name": "MOVED_BY_ID", "type": "integer"},
    {"name": "MOVED_BY_NAME", "type": "string"},
    {"name": "CREATED_TIME", "type": "datetime"},
    {"name": "UPDATED_TIME", "type": "datetime"},
    {"name": "MOVED_TIME", "type": "datetime"},
    {"name": "CATEGORY", "type": "string"},
    {"name": "CATEGORY_ID", "type": "integer"},
    {"name": "CATEGORY_NAME", "type": "string"},
    {"name": "OPENED", "type": "string"},
    {"name": "STAGE", "type": "string"},
    {"name": "STAGE_ID", "type": "string"},
    {"name": "STAGE_NAME", "type": "string"},
    {"name": "PREVIOUS_STAGE_ID", "type": "string"},
    {"name": "BEGINDATE", "type": "datetime"},
    {"name": "CLOSEDATE", "type": "datetime"},
    {"name": "COMPANY", "type": "string"},
    {"name": "COMPANY_ID", "type": "integer"},
    {"name": "COMPANY_NAME", "type": "string"},
    {"name": "CONTACT", "type": "string"},
    {"name": "CONTACT_ID", "type": "integer"},
    {"name": "CONTACT_NAME", "type": "string"},
    {"name": "OPPORTUNITY", "type": "string"},
    {"name": "IS_MANUAL_OPPORTUNITY", "type": "string"},
    {"name": "TAX_VALUE", "type": "string"},
    {"name": "CURRENCY_ID", "type": "string"},
    {"name": "OPPORTUNITY_ACCOUNT", "type": "string"},
    {"name": "TAX_VALUE_ACCOUNT", "type": "string"},
    {"name": "ACCOUNT_CURRENCY_ID", "type": "string"},
    {"name": "MYCOMPANY", "type": "string"},
    {"name": "MYCOMPANY_ID", "type": "integer"},
    {"name": "MYCOMPANY_NAME", "type": "string"},
    {"name": "SOURCE", "type": "string"},
    {"name": "SOURCE_ID", "type": "string"},
    {"name": "SOURCE_NAME", "type": "string"},
    {"name": "SOURCE_DESCRIPTION", "type": "string"},
    {"name": "ASSIGNED_BY", "type": "string"},
    {"name": "ASSIGNED_BY_ID", "type": "integer"},
    {"name": "ASSIGNED_BY_NAME", "type": "string"},
    {"name": "WEBFORM_ID", "type": "integer"},
]

USER = [
    {"name": "ID", "type": "integer"},
    {"name": "ACTIVE", "type": "string"},
    {"name": "NAME", "type": "string"},
    {"name": "DEPARTMENT", "type": "string"},
]

CRM_COMPANY_UF = [
    {"name": "COMPANY_ID", "type": "integer"},
    {"name": "DATE_CREATE", "type": "datetime"},
]

CRM_CONTACT_UF = [
    {"name": "CONTACT_ID", "type": "integer"},
    {"name": "DATE_CREATE", "type": "datetime"},
]


@attr.s
class BitrixGDSColumn:
    name: str = attr.ib()
    type: str = attr.ib()


@attr.s
class BitrixGDSTable:
    type: BitrixGDSTableType = attr.ib()
    schema: Iterable[BitrixGDSColumn] = attr.ib()
    daterange_col_name: Optional[str] = attr.ib(default=None)

    def get_columns(self) -> list[str]:
        return [column.name for column in self.schema]

    def get_columns_type(self) -> dict[str, str]:
        return {column.name: column.type for column in self.schema}


BITRIX_TABLES_MAP = {
    "crm_deal": BitrixGDSTable(
        type=BitrixGDSTableType.crm_deal,
        daterange_col_name="DATE_CREATE",
        schema=[BitrixGDSColumn(**column) for column in CRM_DEAL],
    ),
    "crm_lead": BitrixGDSTable(
        type=BitrixGDSTableType.crm_lead,
        daterange_col_name="DATE_MODIFY",
        schema=[BitrixGDSColumn(**column) for column in CRM_LEAD],
    ),
    "crm_company": BitrixGDSTable(
        type=BitrixGDSTableType.crm_company,
        daterange_col_name="DATE_CREATE",
        schema=[BitrixGDSColumn(**column) for column in CRM_COMPANY],
    ),
    "crm_contact": BitrixGDSTable(
        type=BitrixGDSTableType.crm_contact,
        daterange_col_name="DATE_CREATE",
        schema=[BitrixGDSColumn(**column) for column in CRM_CONTACT],
    ),
    "crm_deal_stage_history": BitrixGDSTable(
        type=BitrixGDSTableType.crm_deal_stage_history,
        daterange_col_name="DATE_CREATE",
        schema=[BitrixGDSColumn(**column) for column in CRM_DEAL_STAGE_HISTORY],
    ),
    "crm_lead_status_history": BitrixGDSTable(
        type=BitrixGDSTableType.crm_lead_status_history,
        daterange_col_name="DATE_CREATE",
        schema=[BitrixGDSColumn(**column) for column in CRM_LEAD_STATUS_HISTORY],
    ),
    "socialnetwork_group": BitrixGDSTable(
        type=BitrixGDSTableType.socialnetwork_group,
        daterange_col_name="DATE_CREATE",
        schema=[BitrixGDSColumn(**column) for column in SOCIALNETWORK_GROUP],
    ),
    "telephony_call": BitrixGDSTable(
        type=BitrixGDSTableType.telephony_call,
        daterange_col_name="CALL_START_TIME",
        schema=[BitrixGDSColumn(**column) for column in TELEPHONY_CALL],
    ),
    "crm_activity": BitrixGDSTable(
        type=BitrixGDSTableType.crm_activity,
        daterange_col_name="DATE_CREATE",
        schema=[BitrixGDSColumn(**column) for column in CRM_ACTIVITY],
    ),
    "crm_lead_uf": BitrixGDSTable(
        type=BitrixGDSTableType.crm_lead_uf,
        daterange_col_name="DATE_CREATE",
        schema=[BitrixGDSColumn(**column) for column in CRM_LEAD_UF],
    ),
    "crm_deal_uf": BitrixGDSTable(
        type=BitrixGDSTableType.crm_deal_uf,
        daterange_col_name="DATE_CREATE",
        schema=[BitrixGDSColumn(**column) for column in CRM_DEAL_UF],
    ),
    "crm_lead_product_row": BitrixGDSTable(
        type=BitrixGDSTableType.crm_lead_product_row,
        daterange_col_name="LEAD_DATE_MODIFY",
        schema=[BitrixGDSColumn(**column) for column in CRM_LEAD_PRODUCT_ROW],
    ),
    "crm_deal_product_row": BitrixGDSTable(
        type=BitrixGDSTableType.crm_deal_product_row,
        daterange_col_name="DEAL_DATE_CREATE",
        schema=[BitrixGDSColumn(**column) for column in CRM_DEAL_PRODUCT_ROW],
    ),
    "user": BitrixGDSTable(
        type=BitrixGDSTableType.user,
        schema=[BitrixGDSColumn(**column) for column in USER],
    ),
    "crm_company_uf": BitrixGDSTable(
        type=BitrixGDSTableType.crm_company_uf,
        daterange_col_name="DATE_CREATE",
        schema=[BitrixGDSColumn(**column) for column in CRM_COMPANY_UF],
    ),
    "crm_contact_uf": BitrixGDSTable(
        type=BitrixGDSTableType.crm_contact_uf,
        daterange_col_name="DATE_CREATE",
        schema=[BitrixGDSColumn(**column) for column in CRM_CONTACT_UF],
    ),
}

CRM_DYNAMIC_ITEMS_TABLE = BitrixGDSTable(
    type=BitrixGDSTableType.crm_dynamic_items,
    daterange_col_name="CREATED_TIME",
    schema=[BitrixGDSColumn(**column) for column in CRM_DYNAMIC_ITEMS],
)

SMART_PROCESS_TABLE_PREFIX = "crm_dynamic_items_"
