FROM cr.yandex/crpsufj53lhl0via9iam/clickhouse-server:22.11

COPY db-clickhouse/users.xml /etc/clickhouse-server/users.xml

COPY db-clickhouse/data /common-data

COPY db-clickhouse/docker-entrypoint-initdb.d/ /docker-entrypoint-initdb.d/
