from bi_connector_bundle_partners.kontur_market.core.constants import SOURCE_TYPE_KONTUR_MARKET_CH_TABLE
from bi_connector_bundle_partners.kontur_market.core.settings import KonturMarketConnectorSettings
from bi_connector_bundle_partners.kontur_market.core.us_connection import KonturMarketCHConnection
from bi_connector_bundle_partners_tests.db.base.core.connection import PartnersConnectionTestClass
import bi_connector_bundle_partners_tests.db.config as test_config
from bi_connector_bundle_partners_tests.db.kontur_market.core.base import BaseKonturMarketTestClass


class TestKonturMarketConnection(BaseKonturMarketTestClass, PartnersConnectionTestClass[KonturMarketCHConnection]):
    source_type = SOURCE_TYPE_KONTUR_MARKET_CH_TABLE
    sr_connection_settings = KonturMarketConnectorSettings(**test_config.SR_CONNECTION_SETTINGS_PARAMS)
