---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: secret-store
spec:
  provider:
    yandexlockbox:
      auth:
        authorizedKeySecretRef:
          name: eso-yc-auth
          key: authorized-key
      apiEndpoint: {{ .Values.cloud_api_endpoint }}
{{ if .Values.use_internal_ca }}
      caProvider:
        certSecretRef:
          name: yc-internal-ca-cert
          key: cert
{{ end }}
