#!/usr/bin/env sh

set -x  # debug.
set -eu

port="${GUNICORN_LISTEN_PORT:-8080}"
max_rq="${GUNICORN_MAX_RQ:-5000}"
max_rq_jitter="${GUNICORN_MAX_RQ_JITTER:-500}"

exec \
    gunicorn \
    app_yc_file_uploader_api.app:create_gunicorn_app \
    --log-config "${BI_API_GUNICORN_LOG_CONFIG:-${GUNICORN_LOG_CONFIG}}" \
    --bind "[::]:${port}" \
    --max-requests "$max_rq" \
    --max-requests-jitter "$max_rq_jitter" \
    --workers="1" \
    --worker-class aiohttp.GunicornWebWorker
