version: '3'

vars:
  USER_REL_PATH:
    sh: python -c "import os,sys;print(os.path.relpath('{{.USER_WORKING_DIR}}'))"

includes:
  env:
    taskfile: tools/common_taskfile_env.yml
    dir: tools
  i18n:
    taskfile: tools/common_taskfile_i18n.yml
    dir: tools
