version: '3'

vars:
  USER_REL_PATH:
    sh: python -c "import os,sys;print(os.path.relpath('{{.USER_WORKING_DIR}}'))"

  ROOT_DIR:
    sh: pwd

includes:
  # Open-source tasks
  cq:
    taskfile: mainrepo/tools/taskfiles/taskfile_code_quality.yml
    dir: mainrepo/tools
  env:
    taskfile: mainrepo/tools/taskfiles/taskfile_env.yml
    dir: mainrepo/tools
  gen:
    taskfile: mainrepo/tools/taskfiles/taskfile_gen.yml
    dir: mainrepo/tools

  # Internal (ya) tasks
  env-ya:
    taskfile: tools/taskfiles/taskfile_env.yml
    dir: tools
  gen-ya:
    taskfile: tools/taskfiles/taskfile_gen.yml
    dir: tools
  rep-ya:
    taskfile: tools/taskfiles/taskfile_rep.yml
    dir: tools
  pub-ya:
    taskfile: tools/taskfiles/taskfile_pub.yml
    dir: tools
