#!/usr/bin/env sh

set -x  # debug.
set -eu

port="${GUNICORN_LISTEN_PORT:-80}"
max_rq="${GUNICORN_MAX_RQ:-5000}"
max_rq_jitter="${GUNICORN_MAX_RQ_JITTER:-500}"
EXT_API_LAUNCH_TARGET="${EXT_API_LAUNCH_TARGET:-http_api}"

if [ "${EXT_API_LAUNCH_TARGET}" = "http_api" ]; then
    exec \
        gunicorn \
        bi_external_api.app:create_gunicorn_app \
        --log-config /code/gunicorn_logging.ini \
        --bind "[::]:${port}" \
        --max-requests "$max_rq" \
        --max-requests-jitter "$max_rq_jitter" \
        --workers="1" \
        --worker-class aiohttp.GunicornWebWorker
elif [ "${EXT_API_LAUNCH_TARGET}" = "grpc_proxy" ]; then
    exec bi-ext-api-grpc-proxy
else
    echo "Unexpected ${EXT_API_LAUNCH_TARGET}: ${EXT_API_LAUNCH_TARGET}" 1>&2
    sleep 15
    exit 255
fi
