from dl_formula_testing.testcases.conditional_blocks import DefaultConditionalBlockFormulaConnectorTestSuite

from dl_connector_oracle_tests.db.formula.base import OracleTestBase


class TestConditionalBlockOracle(OracleTestBase, DefaultConditionalBlockFormulaConnectorTestSuite):
    pass
