#!/usr/bin/env bash

# This is a wrapper script for docker bake
# It launch `docker buildx bake ...` with appropriate CWD and add all required .hcl files to arguments
# All extra arguments will be passed to bake

set -x

ALL_BAKE_FILES=(
    _bake_vars_functions.hcl
    bake.hcl
    bake_ci.hcl
    bake_code_gen.hcl
)

FILE_AGS=()

for BAKE_FILE in "${ALL_BAKE_FILES[@]}"
do
  FILE_AGS+=(--file "${BAKE_FILE}")
done

HERE="$( cd "$( dirname "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )"
PROJECT_ROOT=$(realpath "${HERE}/..")

ARC_ROOT=$(realpath "${PROJECT_ROOT}/../arc/arcadia")

cd "${HERE}"

PROJECT_ROOT="${PROJECT_ROOT}" ARC_ROOT="${ARC_ROOT}" \
    exec docker buildx bake "${FILE_AGS[@]}" "$@"
