name: dls-tasks
service_account_id: aje2uruba661cok977h5
scale_policy:
  fixed_scale:
    size: 2
deploy_policy:
  max_unavailable: 1
  # здесь лучше 0, для того чтобы виртуалки не пересоздавались каждый раз
  max_expansion: 0
allocation_policy:
  zones:
  - zone_id: ru-central1-a
  - zone_id: ru-central1-b
  - zone_id: ru-central1-c
platform_l7_load_balancer_spec:
  preferred_ip_version: IPV6
  target_group_spec:
    # название вашей таргет-группы, это специальная тг для L7, из интерфейса ее создать невозможно
    name: datalens-prod-dls-tasks
instance_template:
  # шаблон для имени вм, мы используем такой app_name-{instance.internal_dc}-{instance.index}
  name: dls-tasks-{instance.internal_dc}-{instance.index}
  fqdn: dls-tasks-{instance.internal_dc}-{instance.index}.{instance.internal_dc}.datalens.cloud.yandex.net
  service_account_id: ajef7uvq8g2d85q099s4
  labels:
    yandex-dns: ig
    conductor-group: datalens-back-prod
    conductor-role: dls-tasks
  platform_id: standard-v2
  resources_spec:
    memory: 4G
    cores: 2
    core_fraction: 100
  boot_disk_spec:
    mode: READ_WRITE
    disk_spec:
      # айдишник образа, созданного packer-ом, подставляется тимсити, здесь не менять
      image_id: __IMAGE_ID__
      type_id: network-ssd
      size: 30g
  # логи пишутся на secondary-disk, чтобы избежать потери при деплое
  secondary_disk_specs:
  - mode: READ_WRITE
    device_name: data
    disk_spec:
      type_id: network-ssd
      size: 31g
  network_interface_specs:
  - network_id: enpkiqn2ppv4mjcrk0bf
    primary_v6_address_spec: {}
    primary_v4_address_spec: {}
    security_group_ids:
    - enpjnqvkeccjm3rhosbg
  metadata:
    k8s-runtime-bootstrap-yaml: ' '
    # настройка записи логов на secondary-disk
    user-data: |
      #cloud-config
      fs_setup:
      - device: /dev/disk/by-id/virtio-data
        filesystem: ext4
        partition: auto
        overwrite: false
      mounts:
      - [/dev/disk/by-id/virtio-data, /data, ext4, 'defaults,errors=remount-ro', '0', '2']
      - [/data/log/fluent, /var/log/fluent, none, 'defaults,bind', '0', '0']
      runcmd:
      - mkdir -p /data/log/fluent
      - chmod 0777 /data
      - chown td-agent:td-agent /data/log/fluent
      - chmod 0755 /data/log/fluent
      - mount --make-rprivate /data
      - mount -o bind /data/log/fluent /var/log/fluent
      - chmod 0755 /data/log/fluent
      - mount --make-rprivate /data
      - mount -o bind /data/log/fluent /var/log/fluent
      - /usr/local/bin/update_env_vars
      - /usr/bin/skm decrypt
      - /usr/local/bin/update_secrets
      env_vars:
        DLS_DAEMON_NAME: tasks
        DLS_ENV: ext_production
        YENV_TYPE: production
        JAEGER_COLLECTOR_NETLOC: "jaeger-collector.private-api.ycp.cloud.yandex.net:443"
        JAEGER_AGENT_PORT: 16831
        RUN_JAEGER_AGENT: 1
    osquery_tag: ycloud-svc-datalens-bi
    shortname: dls-tasks-{instance.internal_dc}-{instance.index}.{instance.internal_dc}
    nsdomain: datalens.cloud.yandex.net
    skm: |
      api_endpoint: api.cloud.yandex.net:443
      skip_tls_verify: false
      kms_private_endpoint: ""
      iam_private_endpoint: ""
      kms_private_skip_tls_verify: false
      kms_key_uri: yc-kms://abjbvt8c9bmbiat3lfha
      encrypted_dek: AAAAAQAAABRhYmplYWRjNHVyNXBqczg4YW9hZgAAABBlUn7I5kjWJqHYjGh8y2fWAAAADIxVgINjRrr6anjUaOGh+pGjzJF+f4MO8qH4A9XyoSgQMoy6HXIZnwuYF0jDrrfjyQDeGU1Oxu+tiO+gfZG8FOa6FGLBxmiMCgThH9LGXFQ3qmMpf32BasiEYuiO
      secrets:
        - path: /etc/secrets/TVM_SECRET
          ciphertext: !!binary dIpq4aCLfBYmADXePrLVz0RhATU+n5xdbC01b6YBIUqw/GyxvOI=
          mode: 0
          uid: 0
          gid: 0
        - path: /etc/secrets/TVM_INFO
          ciphertext: !!binary |
              xWy9cqwuDtyMj4D8va0VDbNRPrHqsJ7ngTunvyi93TvBXyZNBRIO61MueYbIT0AruMBLGL
              +h0EIq6e8Yuw==
          mode: 0
          uid: 0
          gid: 0
        - path: /etc/secrets/DLS_API_KEY
          ciphertext: !!binary |
              XFP9FNB9ka+yCKokSoh7SD2QhHF6/Bo53adWN3K6E5IzWpErTVk1vNpL6G3TcCK5A8YACq
              HAmVARUTYTMReGjP7B7Z1g5dylhCdaxwk+QH0=
          mode: 0
          uid: 0
          gid: 0
        - path: /etc/secrets/DLS_DB_PASSWORD
          ciphertext: !!binary cqWgps1x0y6pMvihsoUS9oX6hxLXXk/sEWmKMX99F3GCB4B3bnzazM3x+T1HEbAV
          mode: 0
          uid: 0
          gid: 0
        - path: /etc/secrets/DLS_SENTRY_DSN
          ciphertext: !!binary |
              lwQuwDK+og95JEmn4oWLL26YUQoDDu9cyNWQcS2Q+BinkBeH0aMwcIeDsUNGg/XegG/5j8
              MyL/DIW6rbqDYsyyQZR432j84+aWOGj7eNdyZyqt6ktvho3PGkD5wJ/8qpg2CmY5gJj19+
              m60/zwPAkp6ICdTU7NIN
          mode: 0
          uid: 0
          gid: 0
        - path: /etc/secrets/LOGCH_PASSWORD
          ciphertext: !!binary KVKsU1/drNF1cepQqJU8/ii49lASvwJkNb3KBKf8hlo9PxlTbeI=
          mode: 0
          uid: 0
          gid: 0
        - path: /etc/metricsagent/SOLOMON_AUTH_SA_KEY_SA_KEY
          ciphertext: !!binary |
              loicx0ozSSSbRzE9HoP7bmCQxbqbTthFoclu0qjqDKT3JXBAvq9K6U/o+FwBsLKoulvzWT
              yTyQ==
          mode: 0
          uid: 0
          gid: 0
        - path: /etc/metricsagent/SOLOMON_AUTH_SA_KEY
          ciphertext: !!binary |
              iYArI52KEvorUXogp/RQmwc19BIq329bHoe0ruyD4WJ3wxi2L+r9BVraRxVFAG2Mc7u1l5
              J3+UiR13ncn83ImAFFeoPlpXF656AdSdm1ER/fkz2L+qYkNLvsyKinP74r6djrjxDSfGLB
              2WLYkyNNnJMePSWaSNoYB+K/aO0sTL91x3kr5Wp9AGltr5d7uyI4VqSMWjNCbacpdl2Vjr
              kGZM8j1FC1rVi8QHBjRPYC2PPc8bCsu+neeTA216vOfIPGpM/SWHOY7Z/YlMUvqjV0tRB6
              v37mpapPVDz0iqnrzQpY9/e95MlvWXWDzLWTE6sj7TTWLu4iOJw4n/G9CsvcmIAgHWwUcq
              HyTmWE4wqk8hELhaSZ79JFZnUVNngiFXQJMuIlNqNHP/xzSsd29fesaysGxHlQd9q706VQ
              9ZvUON1mxoh5bD3ZkdQ92g+eY/ga08lIyQWaDsVlWIGKwIo6Jg+RcGWzdhl4jI0D9ZDR1j
              eDVRYe6foO75iY+Zeg7278Gu/Gq0EUa37oNlcKUqqrrKLzJNPU36u4eGwOzrOrmi5ucn3j
              qZSZ8bVkSBCPlne+M2Hre4tAAjDgj8Zp4462ITNBuSAnsoAv+xKaawmIMkC9yx4G41hY4N
              8i0hIURaU2Rnx/z7Y5k7G04yf/Vfv6xDVymlLxF1vLzTUN3p5kdM1lBMDjClv48T4GFl93
              2Pya35MwSElxeHtAd+iF0I8Gc3Do8J+77oCJUFG/WC01bUyr+NI1uJzO95bZgeb41UrGRS
              tY2B0/B8c1xLSXbBRujkhIpXwU7sgmt3UtU/fcDeECJpwHi72Ilb04SjVeweTdxdnrcfwa
              ijYnoj82vn7w1efk4ifv8pTvFvPe5fFQB3wJR4zbI5VFP86LOWKwjRpuueb9PbTay5pLjZ
              uTlY9rKAjVVmJhaxFr9aOIhwIS3os7REmOqpNPF40h2+pMw7HPFKGSjtwYSuaUTjs8b29S
              /Tfs5b6viClys8taYbPwEzC8h4D0VxFBjmzwCsII/GPqmsmIP6D9pu1Y2Cy23vtD7X8Mi+
              Yzr6C/5Nnm0xYbiWyq1JRkMtCo6j7/L9qGn7JwlYPhHsGAB5g2PhzxAm5O/tXJoY3rpDAt
              HTSxyU+NHIaMhYj2+4U8VPWkBp5FbrW99JbdYWx/O6jv9EBDNlNRZBxqzzul6aTEgR+2kf
              GYgKV/48ZITFMjuyJlkIu8skBExIKaLJ93sY5eAgWTUlu4Q0m0T7+LeyjKon0FtJJUDNPG
              +hHw14oOZklZA0XWACcIwN0RqlEknJJOZrZ1lraPClBryxvTFejJGfI+MPLU6kw5hYUiSJ
              M8m6n3SodTfXHsX53muet/m0YAgI2VpT7pQVfQpnXdy6IJW85vMnFYhK5HtWxBGtoM464q
              4t0+CUQq57OeKeI7y4P8w/6DRR0MwOBBaGyVmrWZUnRTngxvz54KdebRQfyB4+Vt2h847q
              YqNEjcnORM4JifTfPEt+aqtFfsCqQq7j8CRX3L4rtAdcqnp0exc/4gZwBEuIMGBsvU9Mie
              Fj3PWliDkPvFQhcOWgGomLzmOF9fFRsRvrgVZZpfnZGACm4rRL9Dy30YuhDv5L8wVu4l9R
              JA3e1jx84YVkJXYTpYvq3B1YT9q+DoDDfPWDnfI7mdlgZ/p0J68GY1EfqToidGBZahyuSm
              imLLeA/sS6+fkf0YktziSgCRYdXdZWItlYAgcci6EMnTXbf2uox+liAaRvBwiZGcFx4x2z
              SEIyOL6vrr+trIQkwne4OVznH3A1Dd84f22kKLqcyaalehytMDV2NvaEF8BNdFoBhP1q27
              3u3hJ5Qk1ntsP5nODyXO45pvolKNoiQjuM7OIWjYaylqJ8WvWKUvVEADtyffwcO33mg0lm
              OBjPz9t/YRsEiHCiBeUNt4cXu2SE4iggpBHf+DiHbY3zAhIO3MIZ3g3JvofKC4cG5dFcGH
              JNCaLMn1ZDBHvA9YTo9EH2QFYfISQjspV2NZlQQQDODcwlwwVoie0NQR07R+JturHMFDZ/
              qWGfl7I5PMBUIODo5iR00IZtxoP0URMShlH2/XbesRpP5VXduxTRd/8YZ23o6QPvBiNoJW
              IhEL7y4Z2x+/WRbGfYu9m/UARDtCiYrv7g6pYR7rS7wsp7vGAup2hci1JRkc1RjO7uh4tw
              GySLSthZiFnR+6EMtzjsW5wAeOn8xfCD9LwZ1WQMsDTxtUMBX9UmnUcEHu0VYORzWXkZNU
              16sZGcYpUKU8jqcWtVd04Fmp7vhS14A9O7C9Tr/5a1qHs9CvKD7jAzlMh+nTbWsCWNeN70
              FOXuCZhJNrWWuDFrUs6zButmX+NdEAarkEurQ98lWaFEHtQmzeeX7gHhyQQuS1kMVdo2oh
              u4BRCrMLTINfg6WPq9eOA/rww7ZvTSW4eKq6bjghh6lhuvDZhMhYdUYaGpB87MUxR0Clw6
              UvATLo/X1nCfWrlXecOe8mBH8xISDfASqjqXjcp1P7T+lgxVjamBzuPRcMgNBiYnz3nCIV
              mxSAaYUD9G4vPgw6jdpA9oef8nSLMA59/nnqB0/sxlPjK7XY3/+miSR4sU5O6E5YiRgzKO
              b3suXy5ojdJcpBNTDHm1Tw3HSVz4dXlqFWkUPHvplrnvK6N1gqy3dqvm5iVCgI1a/bXZkx
              ANhrOYMezkM5PM753HGW3zmqHvTMUukH8JFllzjDBN/rtxg9lJzVYQQGAqNnEzq7XbMkdT
              ig2TQTmUdwjaOr3JooZnEdStY6nGZOp7QO1J06dTfHQiyZoJOBk/fssCb/kgNGNGY37RaL
              Mc5hxQ6oAMmpJhXSATyqqj+IC3ZxJ/AXxfgJFXZkcRpHOrrIdXWQbVDJdQxdlaCDiHxVci
              sLdxgftl5fHyFhKS2GPH2w1A0RYXXClWD5G6ic93rXnJOTwSDqv8jW62yzWMSWJpdPaonj
              aaiQXj1fsidIHEvICDFSihbmSlNOPmO+epbL+CWHtVF6RKlJKzHjcRLBaYYRVgohtZNf4W
              hb2fevaKL4GRnY2x9PdlWk8w0yQKFfn3MgLquto4KEPi6NjCkFXa4xnE9/Aimid3u2p7JT
              a9Mx7OHlJ8hJoXDekRv7ecMrRxkP1gSTHWFmEJwta79gJy5fbwwPmG3R6AJmmtTaGEVoOE
              EdcSeszpJp19l8H/ScxP0guDzG8RS5Q7QYjCs/Lo732KyscB3U4h1pYi/AC4+anlOoq22n
              +tsB2dtkdZeRwO9Liu0PcWL/UuV4fgffdHJS1S2cynT5DQrYRc6p
          mode: 0
          uid: 0
          gid: 0
      enc_mode: DETERMINISTIC
      force: false
