from dl_api_lib_testing.connector.complex_queries import DefaultBasicComplexQueryTestSuite

from dl_connector_clickhouse_tests.db.api.base import ClickHouseDataApiTestBase


class TestClickHouseBasicComplexQueries(ClickHouseDataApiTestBase, DefaultBasicComplexQueryTestSuite):
    pass
