# the earliest version supported by BI
# FROM postgres:9.3-alpine
FROM postgres:9.3-alpine@sha256:028cb3bc3792c307a490864b5deecfaec9027cef4aad16d33882e32003052756

# https://st.yandex-team.ru/DEVTOOLSSUPPORT-2799
ENV PGCTLTIMEOUT=300

COPY db-common/data /common-data
COPY db-postgres/docker-entrypoint-initdb.d /docker-entrypoint-initdb.d
