[build-system]
build-backend = "poetry.core.masonry.api"
requires = [
  "poetry-core"
]

[datalens.meta.mypy]
targets = ["bi_ci"]

[datalens.pytest.ext_private]
# just a placeholder to run at least one pytest
root_dir = "bi_ci_tests/"
target_path = "dummy_ext"
labels = ["ext_private"]

[datalens.pytest.ext_public]
# just a placeholder to run at least one pytest
root_dir = "bi_ci_tests/"
target_path = "dummy_ext"
labels = ["ext_public"]

[datalens.pytest.fat]
# just a placeholder to run at least one pytest
root_dir = "bi_ci_tests/"
target_path = "dummy_fat"
labels = ["fat"]

[datalens.pytest.unit]
# just a placeholder to run at least one pytest
root_dir = "bi_ci_tests/"
target_path = "unit"

[[tool.mypy.overrides]]
module = "clize.*"
ignore_missing_imports = true

[tool.poetry]
name = "bi-ci"
version = "0.1.0"
description = ""
authors = ["DataLens Team <datalens-opensource@yandex-team.ru>"]
license = "Apache 2.0"
packages = [{include = "bi_ci"}]

[tool.poetry.dependencies]
python = ">=3.10, <3.12"
tomlkit = ">=0.11.8"
clize = ">=5.0.0"
poetry = ">=1.5.0"

[tool.poetry.scripts]
detect-affected-packages = "bi_ci.detect_affected_packages:main"
run-tests = "bi_ci.run_tests:runner_cli"
fix-ports-in-compose = "bi_ci.fix_ports_in_compose:cmd"
do-we-need-compose = "bi_ci.do_we_need_compose:cmd"
get-compose-path = "bi_ci.get_compose_path:cmd"
split-pytest-tasks = "bi_ci.split_pytest_tasks:cmd"
execute-mypy-multi = "bi_ci.execute_mypy_multi:cmd"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra"
testpaths = ["bi_ci_tests"]

[tool.mypy]
warn_unused_configs = true
disallow_untyped_defs = true
check_untyped_defs = true
strict_optional = true
