# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yandex/cloud/iam/v1/saml/certificate.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from yandex.cloud import validation_pb2 as yandex_dot_cloud_dot_validation__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n*yandex/cloud/iam/v1/saml/certificate.proto\x12\x18yandex.cloud.iam.v1.saml\x1a\x1dyandex/cloud/validation.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xec\x01\n\x0b\x43\x65rtificate\x12\x18\n\x02id\x18\x01 \x01(\tB\x0c\xe8\xc7\x31\x01\x8a\xc8\x31\x04<=50\x12#\n\rfederation_id\x18\x02 \x01(\tB\x0c\xe8\xc7\x31\x01\x8a\xc8\x31\x04<=50\x12/\n\x04name\x18\x03 \x01(\tB!\xf2\xc7\x31\x1d|[a-z][-a-z0-9]{1,61}[a-z0-9]\x12\x1e\n\x0b\x64\x65scription\x18\x04 \x01(\tB\t\x8a\xc8\x31\x05<=256\x12.\n\ncreated_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x1d\n\x04\x64\x61ta\x18\x06 \x01(\tB\x0f\xe8\xc7\x31\x01\x8a\xc8\x31\x07<=32000Bi\n\x1cyandex.cloud.api.iam.v1.samlZIa.yandex-team.ru/cloud/bitbucket/public-api/yandex/cloud/iam/v1/saml;samlb\x06proto3')



_CERTIFICATE = DESCRIPTOR.message_types_by_name['Certificate']
Certificate = _reflection.GeneratedProtocolMessageType('Certificate', (_message.Message,), {
  'DESCRIPTOR' : _CERTIFICATE,
  '__module__' : 'yandex.cloud.iam.v1.saml.certificate_pb2'
  # @@protoc_insertion_point(class_scope:yandex.cloud.iam.v1.saml.Certificate)
  })
_sym_db.RegisterMessage(Certificate)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\034yandex.cloud.api.iam.v1.samlZIa.yandex-team.ru/cloud/bitbucket/public-api/yandex/cloud/iam/v1/saml;saml'
  _CERTIFICATE.fields_by_name['id']._options = None
  _CERTIFICATE.fields_by_name['id']._serialized_options = b'\350\3071\001\212\3101\004<=50'
  _CERTIFICATE.fields_by_name['federation_id']._options = None
  _CERTIFICATE.fields_by_name['federation_id']._serialized_options = b'\350\3071\001\212\3101\004<=50'
  _CERTIFICATE.fields_by_name['name']._options = None
  _CERTIFICATE.fields_by_name['name']._serialized_options = b'\362\3071\035|[a-z][-a-z0-9]{1,61}[a-z0-9]'
  _CERTIFICATE.fields_by_name['description']._options = None
  _CERTIFICATE.fields_by_name['description']._serialized_options = b'\212\3101\005<=256'
  _CERTIFICATE.fields_by_name['data']._options = None
  _CERTIFICATE.fields_by_name['data']._serialized_options = b'\350\3071\001\212\3101\007<=32000'
  _CERTIFICATE._serialized_start=137
  _CERTIFICATE._serialized_end=373
# @@protoc_insertion_point(module_scope)
