visits_fields = [
    {
        "description": "Доля визитов посетителей, известных от 8 до 31 день.",
        "is_dim": False,
        "name": "ym:s:upToMonthSinceFirstVisitPercentage",
        "title": "Новизна 8‑31 день",
        "type": "float",
    },
    {
        "description": (
            "Доля визитов посетителей с частотой визитов один раз в 1 день. "
            "Учитываются посетители, совершившие больше двух визитов, "
            "которые произошли в разные дни."
        ),
        "is_dim": False,
        "name": "ym:s:oneDayBetweenVisitsPercentage",
        "title": "Периодичность 1 день",
        "type": "float",
    },
    {
        "description": "",
        "is_dim": False,
        "name": "ym:s:manPercentage",
        "title": "Доля мужчин",
        "type": "float",
    },
    {
        "description": "",
        "is_dim": False,
        "name": "ym:s:womanPercentage",
        "title": "Доля женщин",
        "type": "float",
    },
    {
        "description": "Количество посетителей, добавивших в корзину хотя бы один товар суммарно по всем визитам.",
        "is_dim": False,
        "name": "ym:s:productBasketsUniq",
        "title": "Количество посетителей, добавивших товар в корзину",
        "type": "integer",
    },
    {
        "description": "Доля визитов посетителей, возраст которых от 35 до 45 лет.",
        "is_dim": False,
        "name": "ym:s:upTo44AgePercentage",
        "title": "35‑45 лет",
        "type": "float",
    },
    {
        "description": "Процент уникальных посетителей, посетивших сайт в отчетном периоде, активность которых включала их самый первый за всю историю накопления данных визит на сайт.",
        "is_dim": False,
        "name": "ym:s:percentNewVisitors",
        "title": "Доля новых посетителей",
        "type": "float",
    },
    {
        "description": None,
        "is_dim": False,
        "name": "ym:s:offlineCallsFirstTimeCallerPercentage",
        "title": "Доля первичных звонков",
        "type": "float",
    },
    {
        "description": "Доля визитов, в рамках которых состоялся лишь один просмотр страницы, продолжавшийся менее 15 секунд.",
        "is_dim": False,
        "name": "ym:s:bounceRate",
        "title": "Отказы",
        "type": "float",
    },
    {
        "description": "Доля визитов посетителей, возраст которых более 55 лет.",
        "is_dim": False,
        "name": "ym:s:over54AgePercentage",
        "title": "Более 55 лет",
        "type": "float",
    },
    {
        "description": "Количество уникальных посетителей.",
        "is_dim": False,
        "name": "ym:s:users",
        "title": "Посетители",
        "type": "integer",
    },
    {
        "description": "Среднее время от первого визита в днях.",
        "is_dim": False,
        "name": "ym:s:avgDaysSinceFirstVisit",
        "title": "Дней от первого визита (среднее)",
        "type": "float",
    },
    {
        "description": None,
        "is_dim": False,
        "name": "ym:s:offlineCallsFirstTimeCaller",
        "title": "Количество первичных звонков",
        "type": "integer",
    },
    {
        "description": "Доля визитов посетителей с одним визитом (первый визит посетителя).",
        "is_dim": False,
        "name": "ym:s:oneVisitPerUserPercentage",
        "title": "1 визит посетителя",
        "type": "float",
    },
    {
        "description": "",
        "is_dim": False,
        "name": "ym:s:ecommerceRevenuePerPurchase",
        "title": "Средний доход покупки",
        "type": "float",
    },
    {
        "description": "Количество раз, когда в визите встретился параметр визита.",
        "is_dim": False,
        "name": "ym:s:paramsNumber",
        "title": "Количество параметров визитов",
        "type": "integer",
    },
    {
        "description": "Доля визитов посетителей, известных более 365 дней.",
        "is_dim": False,
        "name": "ym:s:overYearSinceFirstVisitPercentage",
        "title": "Новизна более 365 дней",
        "type": "float",
    },
    {
        "description": "Доля визитов посетителей с 8‑31 визитами.",
        "is_dim": False,
        "name": "ym:s:upTo31VisitsPerUserPercentage",
        "title": "8‑31 визит посетителя",
        "type": "float",
    },
    {
        "description": None,
        "is_dim": False,
        "name": "ym:s:offlineCalls",
        "title": "Количество звонков",
        "type": "integer",
    },
    {
        "description": "Доля посетителей, купивших товар на сайте, по отношению к общему числу посетителей.",
        "is_dim": False,
        "name": "ym:s:usersPurchasePercentage",
        "title": "Доля посетителей, купивших товар",
        "type": "float",
    },
    {
        "description": "Доля визитов посетителей, известных от 32 до 90 дней.",
        "is_dim": False,
        "name": "ym:s:upToQuarterSinceFirstVisitPercentage",
        "title": "Новизна 32‑90 дней",
        "type": "float",
    },
    {
        "description": "Среднее количество дней между визитами посетителей.",
        "is_dim": False,
        "name": "ym:s:avgDaysBetweenVisits",
        "title": "Дней между визитами",
        "type": "float",
    },
    {
        "description": None,
        "is_dim": False,
        "name": "ym:s:offlineCallsMissed",
        "title": "Количество пропущенных звонков",
        "type": "integer",
    },
    {
        "description": None,
        "is_dim": False,
        "name": "ym:s:visitsPerDay",
        "title": "Визитов в день",
        "type": "float",
    },
    {
        "description": "Доля визитов посетителей с 2‑3 визитами.",
        "is_dim": False,
        "name": "ym:s:upTo3VisitsPerUserPercentage",
        "title": "2‑3 визита посетителя",
        "type": "float",
    },
    {
        "description": (
            "Доля визитов посетителей с частотой визитов один раз в 8‑31 день. "
            "Учитываются посетители, совершившие больше двух визитов. "
            "При этом число дней визитов больше 1 дня."
        ),
        "is_dim": False,
        "name": "ym:s:upToMonthBetweenVisitsPercentage",
        "title": "Периодичность 8‑31 день",
        "type": "float",
    },
    {
        "description": None,
        "is_dim": False,
        "name": "ym:s:offlineCallRevenueAvg",
        "title": "Средняя цена звонка",
        "type": "float",
    },
    {
        "description": "Стоимость купленных товаров суммарно по всем визитам.",
        "is_dim": False,
        "name": "ym:s:productPurchasedPrice",
        "title": "Стоимость купленных товаров",
        "type": "float",
    },
    {
        "description": "Доля визитов посетителей, вернувшихся на сайт через 91‑365 дней.",
        "is_dim": False,
        "name": "ym:s:upToYearUserRecencyPercentage",
        "title": "Вернувшиеся: 91‑365 дней",
        "type": "float",
    },
    {
        "description": "Доля визитов посетителей, известных от 1 до 7 дней.",
        "is_dim": False,
        "name": "ym:s:upToWeekSinceFirstVisitPercentage",
        "title": "Новизна 1‑7 дней",
        "type": "float",
    },
    {
        "description": None,
        "is_dim": False,
        "name": "ym:s:offlineCallsMissedPercentage",
        "title": "Доля пропущенных звонков",
        "type": "float",
    },
    {
        "description": None,
        "is_dim": False,
        "name": "ym:s:offlineCallHoldDurationTillAnswerAvg",
        "title": "Среднее время ожидания до ответа",
        "type": "float",
    },
    {
        "description": "Количество посетителей, купивших хотя бы один товар, суммарно по всем визитам.",
        "is_dim": False,
        "name": "ym:s:productPurchasedUniq",
        "title": "Количество посетителей, купивших товар",
        "type": "integer",
    },
    {
        "description": "Количество единиц товара, добавленных в корзину, суммарно по всем визитам.",
        "is_dim": False,
        "name": "ym:s:productBasketsQuantity",
        "title": "Товаров добавлено в корзину",
        "type": "integer",
    },
    {
        "description": None,
        "is_dim": False,
        "name": "ym:s:offlineCallDurationAvg",
        "title": "Среднее время звонка",
        "type": "float",
    },
    {
        "description": "Доля визитов посетителей, вернувшихся на сайт через 8‑31 день.",
        "is_dim": False,
        "name": "ym:s:upToMonthUserRecencyPercentage",
        "title": "Вернувшиеся: 8‑31 день",
        "type": "float",
    },
    {
        "description": None,
        "is_dim": False,
        "name": "ym:s:pvlAll3Window",
        "title": "PVL‑3",
        "type": "float",
    },
    {
        "description": "Доля визитов посетителей, возраст которых от 45 до 55 лет.",
        "is_dim": False,
        "name": "ym:s:upTo54AgePercentage",
        "title": "45‑55 лет",
        "type": "float",
    },
    {
        "description": None,
        "is_dim": False,
        "name": "ym:s:pvlAll1Window",
        "title": "PVL‑1",
        "type": "float",
    },
    {
        "description": "Количество достижений любой цели.",
        "is_dim": False,
        "name": "ym:s:sumGoalReachesAny",
        "title": "Достижения любой цели",
        "type": "integer",
    },
    {
        "description": "Количество посетителей, просмотревших информацию хотя бы об одном товаре.",
        "is_dim": False,
        "name": "ym:s:productImpressionsUniq",
        "title": "Посетители, просмотревшие товар",
        "type": "integer",
    },
    {
        "description": "Доля визитов посетителей, вернувшихся на сайт через 1 день.",
        "is_dim": False,
        "name": "ym:s:upToDayUserRecencyPercentage",
        "title": "Вернувшиеся: 1 день",
        "type": "float",
    },
    {
        "description": "Конверсия по любой цели.",
        "is_dim": False,
        "name": "ym:s:anyGoalConversionRate",
        "title": "Конверсия по любой цели",
        "type": "float",
    },
    {
        "description": "Суммарное количество визитов.",
        "is_dim": False,
        "name": "ym:s:visits",
        "title": "Визиты",
        "type": "integer",
    },
    {
        "description": "Доля визитов посетителей, совершивших больше 32 визитов.",
        "is_dim": False,
        "name": "ym:s:over32VisitsPerUserPercentage",
        "title": "Более чем 32 визита посетителя",
        "type": "float",
    },
    {
        "description": 'Доля визитов с меткой "GCLID".',
        "is_dim": False,
        "name": "ym:s:GCLIDPercentage",
        "title": "Доля GCLID",
        "type": "float",
    },
    {
        "description": (
            "Доля визитов посетителей с частотой визитов один раз в более чем 31 день. "
            "Учитываются посетители, совершившие больше двух визитов, "
            "которые произошли в разные дни."
        ),
        "is_dim": False,
        "name": "ym:s:overMonthBetweenVisitsPercentage",
        "title": "Периодичность более чем 31 день",
        "type": "float",
    },
    {
        "description": "Доля визитов посетителей, возраст которых от 25 до 34 лет.",
        "is_dim": False,
        "name": "ym:s:upTo34AgePercentage",
        "title": "25‑34 лет",
        "type": "float",
    },
    {
        "description": "Доля визитов посетителей, известных от 91 до 365 дней.",
        "is_dim": False,
        "name": "ym:s:upToYearSinceFirstVisitPercentage",
        "title": "Новизна 91‑365 дней",
        "type": "float",
    },
    {
        "description": None,
        "is_dim": False,
        "name": "ym:s:offlineCallRevenue",
        "title": "Суммарная цена звонка",
        "type": "float",
    },
    {
        "description": None,
        "is_dim": False,
        "name": "ym:s:offlineCallHoldDurationTillMissAvg",
        "title": "Среднее время ожидания до отказа",
        "type": "float",
    },
    {
        "description": "",
        "is_dim": False,
        "name": "ym:s:ecommercePurchases",
        "title": "Количество покупок",
        "type": "integer",
    },
    {
        "description": "Количество страниц, просмотренных посетителем во время визита.",
        "is_dim": False,
        "name": "ym:s:pageDepth",
        "title": "Глубина просмотра",
        "type": "float",
    },
    {
        "description": "Доля визитов и хитов с поддержкой JavaScript.",
        "is_dim": False,
        "name": "ym:s:jsEnabledPercentage",
        "title": "Поддержка JavaScript",
        "type": "float",
    },
    {
        "description": "Доля посетителей, предположительно являющихся роботами.",
        "is_dim": False,
        "name": "ym:s:robotPercentage",
        "title": "Роботность (доля)",
        "type": "float",
    },
    {
        "description": "Число просмотров страниц на сайте за отчетный период.",
        "is_dim": False,
        "name": "ym:s:pageviews",
        "title": "Просмотры",
        "type": "integer",
    },
    {
        "description": "Доля визитов новых посетителей.",
        "is_dim": False,
        "name": "ym:s:newUserVisitsPercentage",
        "title": "Доля визитов новых посетителей",
        "type": "float",
    },
    {
        "description": "Количество единиц товара, помещённых в корзину, суммарно по всем визитам.",
        "is_dim": False,
        "name": "ym:s:productBasketsRemoveQuantity",
        "title": "Товаров удалено из корзины",
        "type": "integer",
    },
    {
        "description": "Количество просмотров страницы с информацией о товарах суммарно по всем визитам.",
        "is_dim": False,
        "name": "ym:s:productImpressions",
        "title": "Просмотры товаров",
        "type": "integer",
    },
    {
        "description": "Доля визитов посетителей, возраст которых от 18 до 24 лет.",
        "is_dim": False,
        "name": "ym:s:upTo24AgePercentage",
        "title": "18‑24 лет",
        "type": "float",
    },
    {
        "description": (
            "Доля визитов посетителей с частотой визитов один раз в 2‑7 дней. "
            "Учитываются посетители, совершившие больше двух визитов. "
            "При этом число дней визитов больше 1 дня."
        ),
        "is_dim": False,
        "name": "ym:s:upToWeekBetweenVisitsPercentage",
        "title": "Периодичность 2‑7 дней",
        "type": "float",
    },
    {
        "description": None,
        "is_dim": False,
        "name": "ym:s:offlineCallsUniq",
        "title": "Количество звонков с уникальных номеров",
        "type": "integer",
    },
    {
        "description": "Средняя продолжительность визита в минутах и секундах.",
        "is_dim": False,
        "name": "ym:s:avgVisitDurationSeconds",
        "title": "Время на сайте (в секундах)",
        "type": "float",
    },
    {
        "description": "Доля визитов посетителей, известных меньше одного дня.",
        "is_dim": False,
        "name": "ym:s:upToDaySinceFirstVisitPercentage",
        "title": "Новизна менее одного дня",
        "type": "float",
    },
    {
        "description": None,
        "is_dim": False,
        "name": "ym:s:visitsPerHour",
        "title": "Визитов в час",
        "type": "float",
    },
    {
        "description": (
            "Отношение доли посетителей с заданным интересом на этом сайте к "
            "среднестатистической доле посетителей с этим же интересом "
            "на всех сайтах интернета. "
            'Разрешена только при использовании группировки "Категория интересов".'
        ),
        "is_dim": False,
        "name": "ym:s:affinityIndexInterests2",
        "title": "Аффинити‑индекс",
        "type": "float",
    },
    {
        "description": None,
        "is_dim": False,
        "name": "ym:s:offlineCallTalkDurationAvg",
        "title": "Среднее время разговора",
        "type": "float",
    },
    {
        "description": "Стоимость товаров, добавленных в корзину, суммарно по всем визитам.",
        "is_dim": False,
        "name": "ym:s:productBasketsPrice",
        "title": "Стоимость добавленных в корзину товаров",
        "type": "float",
    },
    {
        "description": "Доля визитов посетителей с 4‑7 визитами.",
        "is_dim": False,
        "name": "ym:s:upTo7VisitsPerUserPercentage",
        "title": "4‑7 визитов посетителя",
        "type": "float",
    },
    {
        "description": (
            "Полученный доход суммарно по всем визитам. "
            "Присылается в поле revenue при покупке товара, "
            "либо вычисляется автоматически как сумма цен всех товаров, "
            "ассоциированных с покупкой."
        ),
        "is_dim": False,
        "name": "ym:s:ecommerceRevenue",
        "title": "Доход",
        "type": "float",
    },
    {
        "description": None,
        "is_dim": False,
        "name": "ym:s:pvlAll7Window",
        "title": "PVL‑7",
        "type": "float",
    },
    {
        "description": "",
        "is_dim": False,
        "name": "ym:s:ecommerceRevenuePerVisit",
        "title": "Средний доход визита",
        "type": "float",
    },
    {
        "description": "Доля визитов с блокировщиками рекламы.",
        "is_dim": False,
        "name": "ym:s:blockedPercentage",
        "title": "Блокировка рекламы",
        "type": "float",
    },
    {
        "description": "Доля визитов и хитов, совершенных с мобильных устройств.",
        "is_dim": False,
        "name": "ym:s:mobilePercentage",
        "title": "Мобильность",
        "type": "float",
    },
    {
        "description": (
            "Среднее значение параметра визита. "
            "Вычисляется, если в качестве значения параметра визита передаётся число."
        ),
        "is_dim": False,
        "name": "ym:s:avgParams",
        "title": "Среднее параметров визитов",
        "type": "float",
    },
    {
        "description": "Количество купленных единиц товара суммарно по всем визитам.",
        "is_dim": False,
        "name": "ym:s:productPurchasedQuantity",
        "title": "Товаров куплено",
        "type": "integer",
    },
    {
        "description": "Доля визитов посетителей, вернувшихся на сайт через более чем 365 дней.",
        "is_dim": False,
        "name": "ym:s:overYearUserRecencyPercentage",
        "title": "Вернувшиеся: более чем 365 дней",
        "type": "float",
    },
    {
        "description": "Доля визитов посетителей, возраст которых менее 18 лет.",
        "is_dim": False,
        "name": "ym:s:under18AgePercentage",
        "title": "Менее 18 лет",
        "type": "float",
    },
    {
        "description": "Доля визитов и хитов с включенными cookies.",
        "is_dim": False,
        "name": "ym:s:cookieEnabledPercentage",
        "title": "Поддержка сookies",
        "type": "float",
    },
    {
        "description": "Доля визитов посетителей, вернувшихся на сайт через 32‑90 дней.",
        "is_dim": False,
        "name": "ym:s:upToQuarterUserRecencyPercentage",
        "title": "Вернувшиеся: 32‑90 дней",
        "type": "float",
    },
    {
        "description": None,
        "is_dim": False,
        "name": "ym:s:visitsPerMinute",
        "title": "Визитов в минуту",
        "type": "float",
    },
    {
        "description": "Среднее время от предпоследнего визита в днях.",
        "is_dim": False,
        "name": "ym:s:userRecencyDays",
        "title": "Дней от предыдущего визита",
        "type": "float",
    },
    {
        "description": "Стоимость товаров, удалённых из корзины, суммарно по всем визитам.",
        "is_dim": False,
        "name": "ym:s:productBasketsRemovePrice",
        "title": "Стоимость удалённых из корзины товаров",
        "type": "float",
    },
    {
        "description": "Доля визитов посетителей, вернувшихся на сайт через 2‑7 дней.",
        "is_dim": False,
        "name": "ym:s:upToWeekUserRecencyPercentage",
        "title": "Вернувшиеся: 2‑7 дней",
        "type": "float",
    },
    {
        "description": "Количество новых посетителей.",
        "is_dim": False,
        "name": "ym:s:newUsers",
        "title": "Новые посетители",
        "type": "integer",
    },
    {
        "description": "Сумма значений параметров визитов. Вычисляется, если в качестве значений параметров визитов передаётся число.",
        "is_dim": False,
        "name": "ym:s:sumParams",
        "title": "Сумма параметров визитов",
        "type": "integer",
    },
    {
        "description": "Среднее число дней между визитами, интервал.",
        "is_dim": True,
        "name": "ym:s:userVisitsPeriodIntervalName",
        "title": "Периодичность",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:productSum",
        "title": "Стоимость товара",
        "type": "string",
    },
    {
        "description": "Рекламный сервис",
        "is_dim": True,
        "name": "ym:s:lastOpenstatService",
        "title": "Last Openstat Service",
        "type": "string",
    },
    {
        "description": "Страница социальной сети, с которой был совершён первый за всю историю переход посетителя.",
        "is_dim": True,
        "name": "ym:s:firstSocialNetworkProfile",
        "title": "Первая страница соц. сети",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:productCoupon",
        "title": "Промокод товара",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:browserHourMinute",
        "title": "Час и минута на компьютере посетителя",
        "type": "string",
    },
    {
        "description": "Количество дней с первого визита посетителя, интервал.",
        "is_dim": True,
        "name": "ym:s:daysSinceFirstVisitIntervalName",
        "title": "Дней от первого визита",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:dekaminute",
        "title": "Декаминута визита",
        "type": "string",
    },
    {
        "description": 'Глубина цвета экрана в битах. Например, "24".',
        "is_dim": True,
        "name": "ym:s:screenColorsName",
        "title": "Глубина цвета",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:advEngineName",
        "title": "Последняя рекламная система",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:productID",
        "title": "ID товара",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:mobilePhoneModel",
        "title": "Модель устройства",
        "type": "string",
    },
    {
        "description": "Количество просмотров во время визита или глубина просмотра. Просмотры исключают обновления страницы в интервале менее 15 секунд.",
        "is_dim": True,
        "name": "ym:s:pageViews",
        "title": "Глубина просмотра (детально)",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:firstVisitDekaminute",
        "title": "Декаминута первого визита",
        "type": "string",
    },
    {
        "description": "Дата и время на компьютере посетителя в формате YYYY-MM-DD HH:mm:ss, округленное до начала квартала.",
        "is_dim": True,
        "name": "ym:s:browserStartOfQuarter",
        "title": "Квартал на компьютере посетителя",
        "type": "date",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:purchaseRevenue",
        "title": "Доход от покупки",
        "type": "string",
    },
    {
        "description": 'Наличие метки "GCLID".',
        "is_dim": True,
        "name": "ym:s:lastSignHasGCLIDName",
        "title": "Наличие GCLID (last sign)",
        "type": "string",
    },
    {
        "description": "Дата и время на компьютере посетителя в формате YYYY-MM-DD HH:mm:ss, округленное до начала часа.",
        "is_dim": True,
        "name": "ym:s:browserStartOfHour",
        "title": "Час на компьютере посетителя",
        "type": "datetime",
    },
    {
        "description": "Дата и время визита в формате YYYY-MM-DD HH:mm:ss, округленное до начала часа.",
        "is_dim": True,
        "name": "ym:s:startOfHour",
        "title": "Час визита (начало часа)",
        "type": "datetime",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:purchaseCoupon",
        "title": "Промокод покупки",
        "type": "string",
    },
    {
        "description": "Объявление",
        "is_dim": True,
        "name": "ym:s:lastUTMContent",
        "title": "Last UTM Content",
        "type": "string",
    },
    {
        "description": "Рекламная кампания",
        "is_dim": True,
        "name": "ym:s:lastOpenstatCampaign",
        "title": "Last Openstat Campaign",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:hasRecommendationsClicksName",
        "title": "Переходы по рекомендациям",
        "type": "string",
    },
    {
        "description": "Место размещения",
        "is_dim": True,
        "name": "ym:s:openstatSource",
        "title": "Openstat Source",
        "type": "string",
    },
    {
        "description": "Дата и время на компьютере посетителя в формате YYYY-MM-DD HH:mm:ss, округленное до начала недели.",
        "is_dim": True,
        "name": "ym:s:browserStartOfWeek",
        "title": "Неделя на компьютере посетителя",
        "type": "date",
    },
    {
        "description": 'Ориентация экрана. Возможные значения: "landscape", "portrait".',
        "is_dim": True,
        "name": "ym:s:screenOrientationName",
        "title": "Ориентация экрана",
        "type": "string",
    },
    {
        "description": "Логическая высота экрана.",
        "is_dim": True,
        "name": "ym:s:screenHeight",
        "title": "Логическая высота",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:javascriptEnabledName",
        "title": "Наличие Javascript",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:endURLDomain",
        "title": "Домен страницы выхода",
        "type": "string",
    },
    {
        "description": "Валюта, установленная в Яндекс.Директе для рекламной кампании.",
        "is_dim": True,
        "name": "ym:s:lastCurrencyIDName",
        "title": "Валюта (last)",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:browserDayOfMonth",
        "title": "День месяца на компьютере посетителя",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:turboPageID",
        "title": "Турбо-страница (ID)",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:productCurrency",
        "title": "Валюта",
        "type": "string",
    },
    {
        "description": "Посетитель предположительно является роботом",
        "is_dim": True,
        "name": "ym:s:isRobotName",
        "title": "Роботность",
        "type": "string",
    },
    {
        "description": "Браузер и его полная версия.",
        "is_dim": True,
        "name": "ym:s:browserAndVersionName",
        "title": "Полная версия браузера",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:offlineCallHoldDuration",
        "title": "Время ожидания",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:browserCountry",
        "title": "Страна браузера",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:offlinePointLocationName",
        "title": "Точка",
        "type": "string",
    },
    {
        "description": "Тип условия показа объявления.",
        "is_dim": True,
        "name": "ym:s:lastDirectConditionTypeName",
        "title": "Тип условия показа объявления (last)",
        "type": "string",
    },
    {
        "description": "Количество визитов посетителя за всю историю, интервал.",
        "is_dim": True,
        "name": "ym:s:userVisitsInterval",
        "title": "Визитов в истории",
        "type": "string",
    },
    {
        "description": "Области, в которых находятся посетители сайта.",
        "is_dim": True,
        "name": "ym:s:regionAreaName",
        "title": "Область",
        "type": "string",
    },
    {
        "description": "Название проводимой рекламной кампании",
        "is_dim": True,
        "name": "ym:s:firstUTMCampaign",
        "title": "First UTM Campaign",
        "type": "string",
    },
    {
        "description": "Социальная сеть, из которой был совершён последний значимый переход посетителя.",
        "is_dim": True,
        "name": "ym:s:lastSignSocialNetworkName",
        "title": "Последняя значимая социальная сеть",
        "type": "string",
    },
    {
        "description": "Дата и время на компьютере посетителя в формате YYYY-MM-DD HH:mm:ss, округленное до начала года.",
        "is_dim": True,
        "name": "ym:s:browserStartOfYear",
        "title": "Год на компьютере посетителя (начало года)",
        "type": "date",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:firstVisitMinute",
        "title": "Минута первого визита",
        "type": "string",
    },
    {
        "description": (
            'Часть URL реферера, следующая сразу после домена до "?" (секция параметров), '
            '"#" (секция фрагмента) либо до конца строки. '
            'Например, для страницы "http://news.yandex.ru/quotes/1.html" путем является "/quotes/1.html", '
            'для "http://news.yandex.ru/"&#160;— "/", а для "http://news.yandex.ru"&#160;— пустая строка.'
        ),
        "is_dim": True,
        "name": "ym:s:refererPath",
        "title": "Путь реферера",
        "type": "string",
    },
    {
        "description": "Количество дней с предпоследнего визита посетителя, интервал.",
        "is_dim": True,
        "name": "ym:s:daysSincePreviousVisitIntervalName",
        "title": "Время возврата",
        "type": "string",
    },
    {
        "description": "Идентификатор посетителя сайта, назначаемый Метрикой",
        "is_dim": True,
        "name": "ym:s:clientID",
        "title": "ClientID",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:operatingSystemRootName",
        "title": "Группа операционных систем",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:from",
        "title": "Метка from",
        "type": "string",
    },
    {
        "description": "Дата и время визита в формате YYYY-MM-DD HH:mm:ss, округленное до начала 10-минутного интервала.",
        "is_dim": True,
        "name": "ym:s:startOfDekaminute",
        "title": "Начало декаминуты визита",
        "type": "datetime",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:productBrandCart",
        "title": "Бренд товара в корзине",
        "type": "string",
    },
    {
        "description": "Дата и время первого визита посетителя в формате YYYY-MM-DD HH:mm:ss, округленное до начала 10-минутного интервала.",
        "is_dim": True,
        "name": "ym:s:firstVisitStartOfDekaminute",
        "title": "Начало декаминуты первого визита",
        "type": "datetime",
    },
    # {
    #     'description': 'Интервал дат с параметризацией размера интервала',
    #    #     'is_dim': True,
    #     'name': 'ym:s:previousVisitDatePeriod<group>',
    #     'title': 'Дата предыдущего визита (интервал)',
    #     'type': 'date',
    # },
    {
        "description": "Идентификатор уточненной поисковой системы.",
        "is_dim": True,
        "name": "ym:s:searchEngineName",
        "title": "Последняя поисковая система (детально)",
        "type": "string",
    },
    {
        "description": "Рекламное объявление",
        "is_dim": True,
        "name": "ym:s:firstOpenstatAd",
        "title": "First Openstat Ad",
        "type": "string",
    },
    # {
    #     'description': None,
    #    #     'is_dim': True,
    #     'name': 'ym:s:browserDatePeriod<group>',
    #     'title': 'Дата на компьютере посетителя',
    #     'type': 'string',
    # },
    {
        "description": "Дата визита в формате YYYY-MM-DD, округленная до начала квартала.",
        "is_dim": True,
        "name": "ym:s:startOfQuarter",
        "title": "Квартал визита",
        "type": "date",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:browserYear",
        "title": "Год на компьютере посетителя",
        "type": "string",
    },
    {
        "description": "Количество дней с предпоследнего визита посетителя.",
        "is_dim": True,
        "name": "ym:s:daysSincePreviousVisit",
        "title": "Время c предыдущего визита",
        "type": "string",
    },
    {
        "description": "Место размещения",
        "is_dim": True,
        "name": "ym:s:lastSignOpenstatSource",
        "title": "Last Sign Openstat Source",
        "type": "string",
    },
    {
        "description": "Источник перехода",
        "is_dim": True,
        "name": "ym:s:UTMSource",
        "title": "UTM Source",
        "type": "string",
    },
    {
        "description": "Дата первого визита посетителя в формате YYYY-MM-DD, округленная до начала месяца.",
        "is_dim": True,
        "name": "ym:s:firstVisitStartOfMonth",
        "title": "Месяц первого визита (начало месяца)",
        "type": "date",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:purchaseExistsVisit",
        "title": "Наличие покупок в визите",
        "type": "string",
    },
    {
        "description": "Дата первого визита посетителя в формате YYYY-MM-DD, округленная до начала недели (понедельник).",
        "is_dim": True,
        "name": "ym:s:firstVisitStartOfWeek",
        "title": "Неделя первого визита",
        "type": "date",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:externalRefererDomain",
        "title": "Домен внешнего реферера",
        "type": "string",
    },
    {
        "description": "Категория коммерческих интересов посетителей.",
        "is_dim": True,
        "name": "ym:s:interestName",
        "title": "Категория интересов",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:purchaseCountVisit",
        "title": "Количество покупок в визите",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:firstAdvEngineName",
        "title": "Первая рекламная система",
        "type": "string",
    },
    {
        "description": "Количество просмотров в визите или глубина просмотра, сгруппированная по интервалам.",
        "is_dim": True,
        "name": "ym:s:pageViewsInterval",
        "title": "Глубина просмотра (по интервалам)",
        "type": "string",
    },
    {
        "description": "Ключевые слова",
        "is_dim": True,
        "name": "ym:s:firstUTMTerm",
        "title": "First UTM Term",
        "type": "string",
    },
    # {
    #     'description': 'Интервал дат с параметризацией размера интервала',
    #    #     'is_dim': True,
    #     'name': 'ym:s:firstVisitDatePeriod<group>',
    #     'title': 'Дата первого визита (интервал)',
    #     'type': 'string',
    # },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:productVariant",
        "title": "Вариант товара",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:startURLProto",
        "title": "Протокол страницы входа",
        "type": "string",
    },
    {
        "description": 'Идентификатор уточненной поисковой системы первого визита посетителя. Например, "Яндекс.Картинки".',
        "is_dim": True,
        "name": "ym:s:firstSearchEngineName",
        "title": "Первая поисковая система (детально)",
        "type": "string",
    },
    {
        "description": 'Размер клиентской части окна браузера. Например, "1920х1080".',
        "is_dim": True,
        "name": "ym:s:windowClientArea",
        "title": "Размер окна",
        "type": "string",
    },
    {
        "description": "Страны, в которых находятся посетители сайта.",
        "is_dim": True,
        "name": "ym:s:regionCountryName",
        "title": "Страна",
        "type": "string",
    },
    {
        "description": "Дата и время предпоследнего визита посетителя в формате YYYY-MM-DD HH:mm:ss, округленное до начала квартала.",
        "is_dim": True,
        "name": "ym:s:previousVisitStartOfQuarter",
        "title": "Квартал предпоследнего визита",
        "type": "date",
    },
    {
        "description": "Валюта, установленная в Яндекс.Директе для рекламной кампании.",
        "is_dim": True,
        "name": "ym:s:firstCurrencyIDName",
        "title": "Валюта (first)",
        "type": "string",
    },
    {
        "description": "Время ― начало часового периода в формате HH:MM.",
        "is_dim": True,
        "name": "ym:s:hourName",
        "title": "Час визита",
        "type": "string",
    },
    {
        "description": "Дата и время на компьютере посетителя в формате YYYY-MM-DD HH:mm:ss, округленное до начала месяца.",
        "is_dim": True,
        "name": "ym:s:browserStartOfMonth",
        "title": "Месяц на компьютере посетителя (начало месяца)",
        "type": "date",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:previousVisitMonth",
        "title": "Месяц предыдущего визита",
        "type": "string",
    },
    {
        "description": "Возраст посетителя, интервал",
        "is_dim": True,
        "name": "ym:s:ageIntervalName",
        "title": "Возраст",
        "type": "string",
    },
    {
        "description": 'Идентификатор уточненной поисковой системы первого визита посетителя. Например, "Яндекс.Картинки".',
        "is_dim": True,
        "name": "ym:s:lastSignSearchEngineName",
        "title": "Последняя значимая поисковая система (детально)",
        "type": "string",
    },
    {
        "description": "Ширина клиентской части окна браузера.",
        "is_dim": True,
        "name": "ym:s:windowClientWidth",
        "title": "Ширина окна",
        "type": "string",
    },
    {
        "description": "Название браузера и его версия.",
        "is_dim": True,
        "name": "ym:s:browserAndVersionMajorName",
        "title": "Версия браузера",
        "type": "string",
    },
    {
        "description": 'Отношение ширины к высоте экрана. Например, "16:9".',
        "is_dim": True,
        "name": "ym:s:screenFormat",
        "title": "Соотношение сторон",
        "type": "string",
    },
    {
        "description": "Часть URL страницы входа, следующая сразу после домена. В отличие от простого пути также содержит секции параметров и фрагмента",
        "is_dim": True,
        "name": "ym:s:startURLPathFull",
        "title": "Путь (полный) страницы входа",
        "type": "string",
    },
    {
        "description": 'Идентификатор верхнего уровня иерархии поисковых систем первого визита посетителя. Например, "Яндекс".',
        "is_dim": True,
        "name": "ym:s:firstSearchEngineRootName",
        "title": "Первая поисковая система",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:browserLanguage",
        "title": "Язык браузера",
        "type": "string",
    },
    {
        "description": "Ключевые слова",
        "is_dim": True,
        "name": "ym:s:UTMTerm",
        "title": "UTM Term",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:dayOfWeekName",
        "title": "День недели визита",
        "type": "string",
    },
    {
        "description": 'Четвертый уровень URL страницы входа. Например, для "http://ya.ru/1/2/3/4.html" четвертым уровнем URL является "http://ya.ru/1/2/3/".',
        "is_dim": True,
        "name": "ym:s:startURLPathLevel4",
        "title": "Страница входа, ур. 4",
        "type": "string",
    },
    {
        "description": 'Третий уровень URL страницы входа. Например, для "http://ya.ru/1/2/3/4.html" третьим уровнем URL является "http://ya.ru/1/2/".',
        "is_dim": True,
        "name": "ym:s:startURLPathLevel3",
        "title": "Страница входа, ур. 3",
        "type": "string",
    },
    {
        "description": "Средство маркетинга",
        "is_dim": True,
        "name": "ym:s:UTMMedium",
        "title": "UTM Medium",
        "type": "string",
    },
    {
        "description": 'Второй уровень URL страницы входа. Например, для "http://ya.ru/1/2/3/4.html" вторым уровнем URL является "http://ya.ru/1/".',
        "is_dim": True,
        "name": "ym:s:startURLPathLevel2",
        "title": "Страница входа, ур. 2",
        "type": "string",
    },
    {
        "description": 'Первый уровень URL страницы входа. Например, для "http://ya.ru/1/2/3/4.html" первым уровнем URL является "http://ya.ru/".',
        "is_dim": True,
        "name": "ym:s:startURLPathLevel1",
        "title": "Страница входа, ур. 1",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:offlineCallTag",
        "title": "Метка",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:refererProto",
        "title": "Протокол реферера",
        "type": "string",
    },
    {
        "description": "Объявление",
        "is_dim": True,
        "name": "ym:s:firstUTMContent",
        "title": "First UTM Content",
        "type": "string",
    },
    {
        "description": "Дата предыдущего визита посетителя в формате YYYY-MM-DD.",
        "is_dim": True,
        "name": "ym:s:previousVisitDate",
        "title": "Дата предыдущего визита",
        "type": "date",
    },
    {
        "description": 'Пятый уровень URL страницы входа. Например, для "http://ya.ru/1/2/3/4.html" пятым уровнем URL является "http://ya.ru/1/2/3/4.html".',
        "is_dim": True,
        "name": "ym:s:startURLPathLevel5",
        "title": "Страница входа, ур. 5",
        "type": "string",
    },
    {
        "description": (
            'Часть URL страницы входа, следующая сразу после домена до "?" (секция параметров), '
            '"#" (секция фрагмента) либо до конца строки. '
            'Например, для страницы "http://news.yandex.ru/quotes/1.html" путем является "/quotes/1.html", '
            'для "http://news.yandex.ru/" - "/", а для "http://news.yandex.ru" - пустая строка'
        ),
        "is_dim": True,
        "name": "ym:s:startURLPath",
        "title": "Путь страницы входа",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:PProductBrand",
        "title": "Бренд товара в заказе",
        "type": "string",
    },
    {
        "description": "Дата и время первого визита посетителя в формате YYYY-MM-DD HH:mm:ss.",
        "is_dim": True,
        "name": "ym:s:firstVisitDateTime",
        "title": "Дата и время первого визита",
        "type": "datetime",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:firstTrafficSourceName",
        "title": "Первый источник трафика",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:trafficSourceName",
        "title": "Последний источник трафика",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:lastSignTrafficSourceName",
        "title": "Последний значимый источник трафика",
        "type": "string",
    },
    {
        "description": "Второй уровень источников трафика",
        "is_dim": True,
        "name": "ym:s:firstSourceEngineName",
        "title": "Первый источник трафика (детально)",
        "type": "string",
    },
    {
        "description": "Второй уровень источников трафика",
        "is_dim": True,
        "name": "ym:s:sourceEngineName",
        "title": "Последний источник трафика (детально)",
        "type": "string",
    },
    {
        "description": "Второй уровень источников трафика",
        "is_dim": True,
        "name": "ym:s:lastSignSourceEngineName",
        "title": "Последний значимый источник трафика (детально)",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:endURL",
        "title": "Страница выхода",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:hourMinute",
        "title": "Час и минута визита",
        "type": "string",
    },
    {
        "description": 'Наличие метки "GCLID".',
        "is_dim": True,
        "name": "ym:s:lastHasGCLIDName",
        "title": "Наличие GCLID (last)",
        "type": "string",
    },
    {
        "description": "Объявление",
        "is_dim": True,
        "name": "ym:s:UTMContent",
        "title": "UTM Content",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:productBrand",
        "title": "Бренд",
        "type": "string",
    },
    {
        "description": "Время на сайте, разбитое по группам.",
        "is_dim": True,
        "name": "ym:s:visitDurationIntervalName",
        "title": "Время на сайте (по группам)",
        "type": "string",
    },
    {
        "description": 'Четвертый уровень URL реферера. Например, для "http://ya.ru/1/2/3/4.html" четвертым уровнем URL является "http://ya.ru/1/2/3/".',
        "is_dim": True,
        "name": "ym:s:refererPathLevel4",
        "title": "Реферер, ур. 4",
        "type": "string",
    },
    {
        "description": 'Третий уровень URL реферера. Например, для "http://ya.ru/1/2/3/4.html" третьим уровнем URL является "http://ya.ru/1/2/".',
        "is_dim": True,
        "name": "ym:s:refererPathLevel3",
        "title": "Реферер, ур. 3",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:cookieEnabledName",
        "title": "Наличие Cookie",
        "type": "string",
    },
    {
        "description": 'Разрешение экрана. Например, "1920х1080".',
        "is_dim": True,
        "name": "ym:s:screenResolution",
        "title": "Разрешение",
        "type": "string",
    },
    {
        "description": "Название проводимой рекламной кампании",
        "is_dim": True,
        "name": "ym:s:lastUTMCampaign",
        "title": "Last UTM Campaign",
        "type": "string",
    },
    {
        "description": "Рекламная кампания",
        "is_dim": True,
        "name": "ym:s:firstOpenstatCampaign",
        "title": "First Openstat Campaign",
        "type": "string",
    },
    {
        "description": 'Пятый уровень URL реферера. Например, для "http://ya.ru/1/2/3/4.html" пятым уровнем URL является "http://ya.ru/1/2/3/4.html".',
        "is_dim": True,
        "name": "ym:s:refererPathLevel5",
        "title": "Реферер, ур. 5",
        "type": "string",
    },
    {
        "description": "С каких сайтов осуществлялись переходы на сайт.",
        "is_dim": True,
        "name": "ym:s:referalSource",
        "title": "Последний переход с сайтов",
        "type": "string",
    },
    {
        "description": 'Третий уровень URL внешнего реферера. Например, для "http://ya.ru/1/2/3/4.html" третьим уровнем URL является "http://ya.ru/1/2/".',
        "is_dim": True,
        "name": "ym:s:externalRefererPathLevel3",
        "title": "Внешний реферер, ур. 3",
        "type": "string",
    },
    {
        "description": 'Второй уровень URL внешнего реферера. Например, для "http://ya.ru/1/2/3/4.html" вторым уровнем URL является "http://ya.ru/1/".',
        "is_dim": True,
        "name": "ym:s:externalRefererPathLevel2",
        "title": "Внешний реферер, ур. 2",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:offlineCallTalkDuration",
        "title": "Время разговора",
        "type": "string",
    },
    {
        "description": 'Второй уровень URL реферера. Например, для "http://ya.ru/1/2/3/4.html" вторым уровнем URL является "http://ya.ru/1/".',
        "is_dim": True,
        "name": "ym:s:refererPathLevel2",
        "title": "Реферер, ур. 2",
        "type": "string",
    },
    {
        "description": 'Пятый уровень URL внешнего реферера. Например, для "http://ya.ru/1/2/3/4.html" пятым уровнем URL является "http://ya.ru/1/2/3/4.html".',
        "is_dim": True,
        "name": "ym:s:externalRefererPathLevel5",
        "title": "Внешний реферер, ур. 5",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:firstVisitDayOfMonth",
        "title": "День месяца первого визита",
        "type": "string",
    },
    {
        "description": 'Первый уровень URL реферера. Например, для "http://ya.ru/1/2/3/4.html" первым уровнем URL является "http://ya.ru/".',
        "is_dim": True,
        "name": "ym:s:refererPathLevel1",
        "title": "Реферер, ур. 1",
        "type": "string",
    },
    {
        "description": 'Четвертый уровень URL внешнего реферера. Например, для "http://ya.ru/1/2/3/4.html" четвертым уровнем URL является "http://ya.ru/1/2/3/".',
        "is_dim": True,
        "name": "ym:s:externalRefererPathLevel4",
        "title": "Внешний реферер, ур. 4",
        "type": "string",
    },
    {
        "description": 'Первый уровень URL внешнего реферера. Например, для "http://ya.ru/1/2/3/4.html" первым уровнем URL является "http://ya.ru/".',
        "is_dim": True,
        "name": "ym:s:externalRefererPathLevel1",
        "title": "Внешний реферер, ур. 1",
        "type": "string",
    },
    {
        "description": "С каких сайтов осуществлялись переходы на сайт.",
        "is_dim": True,
        "name": "ym:s:lastSignReferalSource",
        "title": "Последний значимый переход с сайтов",
        "type": "string",
    },
    {
        "description": "Тип условия показа объявления.",
        "is_dim": True,
        "name": "ym:s:lastSignDirectConditionTypeName",
        "title": "Тип условия показа объявления (last sign)",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:previousVisitDayOfMonth",
        "title": "День месяца предыдущего визита",
        "type": "string",
    },
    {
        "description": "Дата и время первого визита посетителя в формате YYYY-MM-DD HH:mm:ss, округленное до начала часа.",
        "is_dim": True,
        "name": "ym:s:firstVisitStartOfHour",
        "title": "Час первого визита (начало часа)",
        "type": "datetime",
    },
    {
        "description": "Логическая ширина экрана.",
        "is_dim": True,
        "name": "ym:s:screenWidth",
        "title": "Логическая ширина",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:year",
        "title": "Год визита",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:lastSignAdvEngineName",
        "title": "Последняя значимая рекламная система",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:startURLDomain",
        "title": "Домен страницы входа",
        "type": "string",
    },
    {
        "description": "Страница социальной сети.",
        "is_dim": True,
        "name": "ym:s:socialNetworkProfile",
        "title": "Последняя страница соц. сети",
        "type": "string",
    },
    {
        "description": "Рекламное объявление",
        "is_dim": True,
        "name": "ym:s:lastOpenstatAd",
        "title": "Last Openstat Ad",
        "type": "string",
    },
    {
        "description": "Страница социальной сети последнего значимого перехода посетителя за всю историю.",
        "is_dim": True,
        "name": "ym:s:lastSignSocialNetworkProfile",
        "title": "Страница социальной сети, с которой был совершён последний значимый переход.",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:paramsLevel10",
        "title": "Параметр визита, ур. 10",
        "type": "string",
    },
    {
        "description": "Среднее число дней между визитами.",
        "is_dim": True,
        "name": "ym:s:userVisitsPeriod",
        "title": "Периодичность (детально)",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:impressionCountVisit",
        "title": "Количество просмотров товаров в визите",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:paramsLevel3",
        "title": "Параметр визита, ур. 3",
        "type": "string",
    },
    {
        "description": "Часть URL реферера, следующая сразу после домена. В отличие от простого пути также содержит секции параметров и фрагмента.",
        "is_dim": True,
        "name": "ym:s:refererPathFull",
        "title": "Путь (полный) реферера",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:paramsLevel4",
        "title": "Параметр визита, ур. 4",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:paramsLevel1",
        "title": "Параметр визита, ур. 1",
        "type": "string",
    },
    {
        "description": 'Физическая ширина экрана исходя из данных "device pixel ratio".',
        "is_dim": True,
        "name": "ym:s:physicalScreenWidth",
        "title": "Физическая ширина",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:paramsLevel2",
        "title": "Параметр визита, ур. 2",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:paramsLevel7",
        "title": "Параметр визита, ур. 7",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:paramsLevel8",
        "title": "Параметр визита, ур. 8",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:paramsLevel5",
        "title": "Параметр визита, ур. 5",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:paramsLevel6",
        "title": "Параметр визита, ур. 6",
        "type": "string",
    },
    {
        "description": "Средство маркетинга",
        "is_dim": True,
        "name": "ym:s:firstUTMMedium",
        "title": "First UTM Medium",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:PProductName",
        "title": "Название товара в заказе",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:paramsLevel9",
        "title": "Параметр визита, ур. 9",
        "type": "string",
    },
    {
        "description": "Средство маркетинга",
        "is_dim": True,
        "name": "ym:s:lastUTMMedium",
        "title": "Last UTM Medium",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:browserMinute",
        "title": "Минута на компьютере посетителя",
        "type": "string",
    },
    {
        "description": 'Наличие метки "GCLID".',
        "is_dim": True,
        "name": "ym:s:hasGCLIDName",
        "title": "Наличие GCLID",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:month",
        "title": "Месяц визита",
        "type": "string",
    },
    {
        "description": "URL реферера",
        "is_dim": True,
        "name": "ym:s:referer",
        "title": "Реферер",
        "type": "string",
    },
    {
        "description": "Часть URL страницы выхода, следующая сразу после домена. В отличие от простого пути также содержит секции параметров и фрагмента",
        "is_dim": True,
        "name": "ym:s:endURLPathFull",
        "title": "Путь (полный) страницы выхода",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:previousVisitYear",
        "title": "Год предыдущего визита",
        "type": "string",
    },
    {
        "description": 'Физическая высота экрана исходя из данных "device pixel ratio".',
        "is_dim": True,
        "name": "ym:s:physicalScreenHeight",
        "title": "Физическая высота",
        "type": "string",
    },
    {
        "description": "Место размещения",
        "is_dim": True,
        "name": "ym:s:firstOpenstatSource",
        "title": "First Openstat Source",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:hasAdBlockerName",
        "title": "Наличие блокировщиков рекламы",
        "type": "string",
    },
    {
        "description": 'Первый уровень URL страницы выхода. Например, для "http://ya.ru/1/2/3/4.html" первым уровнем URL является "http://ya.ru/".',
        "is_dim": True,
        "name": "ym:s:endURLPathLevel1",
        "title": "Страница выхода, ур. 1",
        "type": "string",
    },
    {
        "description": 'Второй уровень URL страницы выхода. Например, для "http://ya.ru/1/2/3/4.html" вторым уровнем URL является "http://ya.ru/1/".',
        "is_dim": True,
        "name": "ym:s:endURLPathLevel2",
        "title": "Страница выхода, ур. 2",
        "type": "string",
    },
    {
        "description": 'Третий уровень URL страницы выхода. Например, для "http://ya.ru/1/2/3/4.html" третьим уровнем URL является "http://ya.ru/1/2/".',
        "is_dim": True,
        "name": "ym:s:endURLPathLevel3",
        "title": "Страница выхода, ур. 3",
        "type": "string",
    },
    {
        "description": 'Четвертый уровень URL страницы выхода. Например, для "http://ya.ru/1/2/3/4.html" четвертым уровнем URL является "http://ya.ru/1/2/3/".',
        "is_dim": True,
        "name": "ym:s:endURLPathLevel4",
        "title": "Страница выхода, ур. 4",
        "type": "string",
    },
    {
        "description": 'Пятый уровень URL страницы выхода. Например, для "http://ya.ru/1/2/3/4.html" пятым уровнем URL является "http://ya.ru/1/2/3/4.html".',
        "is_dim": True,
        "name": "ym:s:endURLPathLevel5",
        "title": "Страница выхода, ур. 5",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:browserDayOfWeekName",
        "title": "День недели на компьютере посетителя",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:browserHourName",
        "title": "Час на компьютере посетителя в формате HH:00",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:topLevelDomain",
        "title": "Домен верхнего уровня страницы входа",
        "type": "string",
    },
    {
        "description": "Дата первого визита посетителя в формате YYYY-MM-DD, округленная до начала квартала.",
        "is_dim": True,
        "name": "ym:s:firstVisitStartOfQuarter",
        "title": "Квартал первого визита",
        "type": "date",
    },
    {
        "description": "Округа, в которых находятся посетители сайта.",
        "is_dim": True,
        "name": "ym:s:regionDistrictName",
        "title": "Округ",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:purchaseRevenueVisit",
        "title": "Сумма покупок в визите",
        "type": "string",
    },
    {
        "description": "Дата и время первого визита посетителя в формате YYYY-MM-DD HH:mm:ss, округленное до начала минуты.",
        "is_dim": True,
        "name": "ym:s:firstVisitStartOfMinute",
        "title": "Минута первого визита (начало минуты)",
        "type": "datetime",
    },
    {
        "description": "Дата визита в формате YYYY-MM-DD, округленная до начала месяца.",
        "is_dim": True,
        "name": "ym:s:startOfMonth",
        "title": "Месяц визита (начало месяца)",
        "type": "date",
    },
    {
        "description": "Города, в которых находятся посетители сайта.",
        "is_dim": True,
        "name": "ym:s:regionCityName",
        "title": "Город",
        "type": "string",
    },
    {
        "description": "Источник трафика - идентификатор социальной сети.",
        "is_dim": True,
        "name": "ym:s:socialNetworkName",
        "title": "Последняя социальная сеть",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:endURLProto",
        "title": "Протокол страницы выхода",
        "type": "string",
    },
    {
        "description": "Источник перехода",
        "is_dim": True,
        "name": "ym:s:firstUTMSource",
        "title": "First UTM Source",
        "type": "string",
    },
    {
        "description": "Рекламный сервис",
        "is_dim": True,
        "name": "ym:s:openstatService",
        "title": "Openstat Service",
        "type": "string",
    },
    {
        "description": "Третье число (обычно номер сборки) в версии движка браузера посетителя.",
        "is_dim": True,
        "name": "ym:s:browserEngineVersion3",
        "title": "Build-версия движка браузера",
        "type": "string",
    },
    {
        "description": 'URL внешнего реферера для источника "Переходы по ссылкам на сайтах"',
        "is_dim": True,
        "name": "ym:s:externalReferer",
        "title": "Внешний реферер",
        "type": "string",
    },
    {
        "description": "Четвертое число (обычно номер ревизии) в версии движка браузера посетителя.",
        "is_dim": True,
        "name": "ym:s:browserEngineVersion4",
        "title": "Revision-версия движка браузера",
        "type": "string",
    },
    {
        "description": "Дата и время визита в формате YYYY-MM-DD HH:mm:ss.",
        "is_dim": True,
        "name": "ym:s:dateTime",
        "title": "Дата и время визита",
        "type": "datetime",
    },
    {
        "description": (
            "Часть URL-адреса внешнего реферера, следующая сразу после домена. "
            "В отличие от простого пути также содержит секции параметров и фрагмента."
        ),
        "is_dim": True,
        "name": "ym:s:externalRefererPathFull",
        "title": "Путь (полный) внешнего реферера",
        "type": "string",
    },
    {
        "description": "Дата и время визита в формате YYYY-MM-DD HH:mm:ss, округленное до начала минуты.",
        "is_dim": True,
        "name": "ym:s:startOfMinute",
        "title": "Минута визита (начало минуты)",
        "type": "datetime",
    },
    {
        "description": (
            'Часть URL внешнего реферера, следующая сразу после домена до "?" (секция параметров), '
            '"#" (секция фрагмента) либо до конца строки. '
            'Например, для страницы "http://news.yandex.ru/quotes/1.html" '
            'путем является "/quotes/1.html", для "http://news.yandex.ru/"&#160;— "/", '
            'а для "http://news.yandex.ru"&#160;— пустая строка.'
        ),
        "is_dim": True,
        "name": "ym:s:externalRefererPath",
        "title": "Путь внешнего реферера",
        "type": "string",
    },
    {
        "description": "Дата первого визита посетителя в формате YYYY-MM-DD.",
        "is_dim": True,
        "name": "ym:s:firstVisitDate",
        "title": "Дата первого визита",
        "type": "date",
    },
    {
        "description": "Тип условия показа объявления.",
        "is_dim": True,
        "name": "ym:s:firstDirectConditionTypeName",
        "title": "Тип условия показа объявления (first)",
        "type": "string",
    },
    {
        "description": "Дата первого визита посетителя в формате YYYY-MM-DD, округленная до начала года.",
        "is_dim": True,
        "name": "ym:s:firstVisitStartOfYear",
        "title": "Год первого визита (начало года)",
        "type": "date",
    },
    {
        "description": "Первое число в версии движка браузера посетителя.",
        "is_dim": True,
        "name": "ym:s:browserEngineVersion1",
        "title": "Major-версия движка браузера",
        "type": "string",
    },
    {
        "description": "Второе число в версии движка браузера посетителя.",
        "is_dim": True,
        "name": "ym:s:browserEngineVersion2",
        "title": "Minor-версия движка браузера",
        "type": "string",
    },
    {
        "description": "Рекламный сервис",
        "is_dim": True,
        "name": "ym:s:firstOpenstatService",
        "title": "First Openstat Service",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:productName",
        "title": "Название товара",
        "type": "string",
    },
    {
        "description": "Поисковая фраза последнего перехода по объявлению Яндекс.Маркета.",
        "is_dim": True,
        "name": "ym:s:marketSearchPhrase",
        "title": "Фраза (Маркет)",
        "type": "string",
    },
    {
        "description": "Континенты, в которых находятся посетители сайта.",
        "is_dim": True,
        "name": "ym:s:regionContinentName",
        "title": "Континент",
        "type": "string",
    },
    {
        "description": 'Реальное разрешение экрана исходя из данных "device pixel ratio". Например, "1920х1080".',
        "is_dim": True,
        "name": "ym:s:physicalScreenResolution",
        "title": "Реальное разрешение",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:lastFrom",
        "title": "Метка from (last)",
        "type": "string",
    },
    {
        "description": "Категория коммерческих интересов посетителей.",
        "is_dim": True,
        "name": "ym:s:interest2Name1",
        "title": "Категория интересов, ур. 1",
        "type": "string",
    },
    {
        "description": "Категория коммерческих интересов посетителей.",
        "is_dim": True,
        "name": "ym:s:interest2Name2",
        "title": "Категория интересов, ур. 2",
        "type": "string",
    },
    {
        "description": "Категория коммерческих интересов посетителей.",
        "is_dim": True,
        "name": "ym:s:interest2Name3",
        "title": "Категория интересов, ур. 3",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:browserDekaminute",
        "title": "Декаминута на компьютере посетителя",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:productPrice",
        "title": "Стоимость единицы товара",
        "type": "string",
    },
    {
        "description": "Место размещения",
        "is_dim": True,
        "name": "ym:s:lastOpenstatSource",
        "title": "Last Openstat Source",
        "type": "string",
    },
    {
        "description": "Ключевые слова",
        "is_dim": True,
        "name": "ym:s:lastSignUTMTerm",
        "title": "Last Sign UTM Term",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:offlineCallMissedName",
        "title": "Пропущенный / Отвеченный",
        "type": "string",
    },
    {
        "description": "Социальная сеть первого перехода посетителя.",
        "is_dim": True,
        "name": "ym:s:firstSocialNetworkName",
        "title": "Первая социальная сеть",
        "type": "string",
    },
    {
        "description": "Рекламное объявление",
        "is_dim": True,
        "name": "ym:s:lastSignOpenstatAd",
        "title": "Last Sing Openstat Ad",
        "type": "string",
    },
    {
        "description": 'IPv4/IPv6-адрес посетителя с обнуленными 1/8 последними байтами соответственно. Например, "77.88.21.0"/"2001:db8:85a3::".',
        "is_dim": True,
        "name": "ym:s:ipAddress",
        "title": "IP-адрес",
        "type": "string",
    },
    {
        "description": "Дата визита в формате YYYY-MM-DD.",
        "is_dim": True,
        "name": "ym:s:date",
        "title": "Дата визита",
        "type": "date",
    },
    {
        "description": "Рекламная кампания",
        "is_dim": True,
        "name": "ym:s:lastSignOpenstatCampaign",
        "title": "Last Sign Openstat Campaign",
        "type": "string",
    },
    {
        "description": 'Браузер посетителя. Например, "Яндекс.Браузер".',
        "is_dim": True,
        "name": "ym:s:browserName",
        "title": "Браузер",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:minute",
        "title": "Минута визита",
        "type": "string",
    },
    {
        "description": "Дата и время на компьютере посетителя в формате YYYY-MM-DD HH:mm:ss.",
        "is_dim": True,
        "name": "ym:s:browserDateTime",
        "title": "Дата и время на компьютере посетителя",
        "type": "datetime",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:firstVisitMonth",
        "title": "Месяц первого визита",
        "type": "string",
    },
    {
        "description": "Название проводимой рекламной кампании",
        "is_dim": True,
        "name": "ym:s:UTMCampaign",
        "title": "UTM Campaign",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:clientTimeZone",
        "title": "Часовой пояс на компьютере посетителя",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:externalRefererProto",
        "title": "Протокол внешнего реферера",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:productPosition",
        "title": "Позиция товара",
        "type": "string",
    },
    {
        "description": "Дата визита в формате YYYY-MM-DD, округленная до начала года.",
        "is_dim": True,
        "name": "ym:s:startOfYear",
        "title": "Год визита (начало года)",
        "type": "date",
    },
    {
        "description": "Дата и время предпоследнего визита посетителя в формате YYYY-MM-DD HH:mm:ss, округленное до начала года.",
        "is_dim": True,
        "name": "ym:s:previousVisitStartOfYear",
        "title": "Год предпоследнего визита",
        "type": "date",
    },
    {
        "description": 'Движок браузера посетителя. Например, "WebKit".',
        "is_dim": True,
        "name": "ym:s:browserEngine",
        "title": "Движок браузера",
        "type": "string",
    },
    {
        "description": (
            'Часть URL страницы выхода, следующая сразу после домена до "?" (секция параметров), '
            '"#" (секция фрагмента) либо до конца строки. '
            'Например, для страницы "http://news.yandex.ru/quotes/1.html" '
            'путем является "/quotes/1.html", для "http://news.yandex.ru/" - "/", '
            'а для "http://news.yandex.ru" - пустая строка'
        ),
        "is_dim": True,
        "name": "ym:s:endURLPath",
        "title": "Путь страницы выхода",
        "type": "string",
    },
    {
        "description": "Количество визитов посетителя за всю историю.",
        "is_dim": True,
        "name": "ym:s:userVisits",
        "title": "Всего визитов",
        "type": "string",
    },
    {
        "description": "Средство маркетинга",
        "is_dim": True,
        "name": "ym:s:lastSignUTMMedium",
        "title": "Last Sign UTM Medium",
        "type": "string",
    },
    {
        "description": "Время ― начало часового периода в формате HH:MM.",
        "is_dim": True,
        "name": "ym:s:firstVisitHourName",
        "title": "Час первого визита",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:firstVisitHourMinute",
        "title": "Час и минута первого визита",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:offlineCallFirstTimeCallerName",
        "title": "Первичный / Повторный",
        "type": "string",
    },
    {
        "description": "Название проводимой рекламной кампании",
        "is_dim": True,
        "name": "ym:s:lastSignUTMCampaign",
        "title": "Last Sign UTM Campaign",
        "type": "string",
    },
    {
        "description": "Дата и время на компьютере посетителя в формате YYYY-MM-DD HH:mm:ss, округленное до начала минуты.",
        "is_dim": True,
        "name": "ym:s:browserStartOfMinute",
        "title": "Минута на компьютере посетителя (начало минуты)",
        "type": "datetime",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:firstVisitDayOfWeekName",
        "title": "День недели первого визита посетителя",
        "type": "string",
    },
    {
        "description": "Рекламное объявление",
        "is_dim": True,
        "name": "ym:s:openstatAd",
        "title": "Openstat Ad",
        "type": "string",
    },
    {
        "description": 'Тип устройства, с которого было посещение. Возможные значения: "desktop", "mobile", "tablet", "tv".',
        "is_dim": True,
        "name": "ym:s:deviceCategoryName",
        "title": "Тип устройства",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:startURL",
        "title": "Страница входа",
        "type": "string",
    },
    {
        "description": (
            "Был ли данный визит отказом с учетом точного показателя отказов. "
            "Если страница просматривалась больше 15 секунд, "
            'то визит не считается отказом. Возможные значения: "Yes", "No".'
        ),
        "is_dim": True,
        "name": "ym:s:bounceName",
        "title": "Отказность",
        "type": "string",
    },
    {
        "description": "Количество дней с первого визита посетителя.",
        "is_dim": True,
        "name": "ym:s:daysSinceFirstVisit",
        "title": "Дней от первого визита (детально)",
        "type": "string",
    },
    {
        "description": "Ключевые слова",
        "is_dim": True,
        "name": "ym:s:lastUTMTerm",
        "title": "Last UTM Term",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:operatingSystemName",
        "title": "Операционная система (детально)",
        "type": "string",
    },
    {
        "description": "Продолжительность визита в секундах.",
        "is_dim": True,
        "name": "ym:s:visitDuration",
        "title": "Время на сайте (детально)",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:productNameCart",
        "title": "Название товара в корзине",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:isTurboPageName",
        "title": "Турбо-страница",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:dayOfMonth",
        "title": "День месяца визита",
        "type": "string",
    },
    {
        "description": "Валюта, установленная в Яндекс.Директе для рекламной кампании.",
        "is_dim": True,
        "name": "ym:s:lastSignCurrencyIDName",
        "title": "Валюта (last sign)",
        "type": "string",
    },
    {
        "description": 'Наличие метки "GCLID".',
        "is_dim": True,
        "name": "ym:s:firstHasGCLIDName",
        "title": "Наличие GCLID (first)",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:counterID",
        "title": "Счетчик (id)",
        "type": "string",
        "src_key": "id",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:counterIDName",
        "title": "Счетчик",
        "type": "string",
    },
    {
        "description": "Дата и время на компьютере посетителя в формате YYYY-MM-DD HH:mm:ss, округленное до начала 10-минутного интервала.",
        "is_dim": True,
        "name": "ym:s:browserStartOfDekaminute",
        "title": "Начало декаминуты на компьютере посетителя",
        "type": "datetime",
    },
    {
        "description": "Рекламная кампания",
        "is_dim": True,
        "name": "ym:s:openstatCampaign",
        "title": "Openstat Campaign",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:PProductID",
        "title": "ID товара в заказе",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:purchaseID",
        "title": "ID покупки",
        "type": "string",
    },
    {
        "description": "Рекламный сервис",
        "is_dim": True,
        "name": "ym:s:lastSignOpenstatService",
        "title": "Last Sign Openstat Service",
        "type": "string",
    },
    # {
    #     'description': 'Интервал дат с параметризацией размера интервала',
    #    #     'is_dim': True,
    #     'name': 'ym:s:datePeriod<group>',
    #     'title': 'Интервал дат визита',
    #     'type': 'string',
    # },
    {
        "description": "Источник перехода",
        "is_dim": True,
        "name": "ym:s:lastUTMSource",
        "title": "Last UTM Source",
        "type": "string",
    },
    {
        "description": "Дата и время предпоследнего визита посетителя в формате YYYY-MM-DD HH:mm:ss, округленное до начала месяца.",
        "is_dim": True,
        "name": "ym:s:previousVisitStartOfMonth",
        "title": "Месяц предпоследнего визита",
        "type": "date",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:productCategoryLevel4",
        "title": "Категория товара, ур. 4",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:productCategoryLevel5",
        "title": "Категория товара, ур. 5",
        "type": "string",
    },
    {
        "description": "С каких сайтов осуществлялись переходы на сайт.",
        "is_dim": True,
        "name": "ym:s:firstReferalSource",
        "title": "Первый переход с сайтов",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:productCategoryLevel2",
        "title": "Категория товара, ур. 2",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:productCategoryLevel3",
        "title": "Категория товара, ур. 3",
        "type": "string",
    },
    {
        "description": "Идентификатор верхнего уровня иерархии поисковых систем.",
        "is_dim": True,
        "name": "ym:s:searchEngineRootName",
        "title": "Последняя поисковая система",
        "type": "string",
    },
    {
        "description": "Размер города по населению.",
        "is_dim": True,
        "name": "ym:s:regionCitySizeName",
        "title": "Размер города",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:productCategoryLevel1",
        "title": "Категория товара, ур. 1",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:productIDCart",
        "title": "ID товара в корзине",
        "type": "string",
    },
    {
        "description": "Источник перехода",
        "is_dim": True,
        "name": "ym:s:lastSignUTMSource",
        "title": "Last Sign UTM Source",
        "type": "string",
    },
    {
        "description": "Дата визита в формате YYYY-MM-DD, округленная до начала недели (понедельник).",
        "is_dim": True,
        "name": "ym:s:startOfWeek",
        "title": "Неделя визита",
        "type": "date",
    },
    {
        "description": "Дата и время предпоследнего визита посетителя в формате YYYY-MM-DD HH:mm:ss, округленное до начала недели.",
        "is_dim": True,
        "name": "ym:s:previousVisitStartOfWeek",
        "title": "Неделя предпоследнего визита",
        "type": "date",
    },
    {
        "description": "Объявление",
        "is_dim": True,
        "name": "ym:s:lastSignUTMContent",
        "title": "Last Sign UTM Content",
        "type": "string",
    },
    {
        "description": "Группировка по достигнутой цели. Позволяет сгруппировать визиты по идентификаторам целей.",
        "is_dim": True,
        "name": "ym:s:goalName",
        "title": "Достигнутая цель",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:lastSignFrom",
        "title": "Метка from (last sign)",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:browserMonth",
        "title": "Месяц на компьютере посетителя",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:firstFrom",
        "title": "Метка from (first)",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:mobilePhoneName",
        "title": "Производитель устройства",
        "type": "string",
    },
    {
        "description": "Дата на компьютере посетителя в формате YYYY-MM-DD.",
        "is_dim": True,
        "name": "ym:s:browserDate",
        "title": "Дата на компьютере посетителя",
        "type": "date",
    },
    {
        "description": 'Пол посетителя. Возможные значения: "мужской" или "женский".',
        "is_dim": True,
        "name": "ym:s:genderName",
        "title": "Пол",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:previousVisitDayOfWeekName",
        "title": "День недели предыдущего визита",
        "type": "string",
    },
    {
        "description": 'Идентификатор верхнего уровня иерархии поисковых систем первого визита посетителя. Например, "Яндекс".',
        "is_dim": True,
        "name": "ym:s:lastSignSearchEngineRootName",
        "title": "Последняя значимая поисковая система",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:firstVisitYear",
        "title": "Год первого визита",
        "type": "string",
    },
    {
        "description": "Высота клиентской части окна браузера.",
        "is_dim": True,
        "name": "ym:s:windowClientHeight",
        "title": "Высота окна",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:isNewUserName",
        "title": "Является ли визит первым визитом посетителя",
        "type": "string",
    },
    {
        "description": None,
        "is_dim": True,
        "name": "ym:s:refererDomain",
        "title": "Домен реферера",
        "type": "string",
    },
]
