from dl_connector_bundle_chs3.file.formula.utils import clickhouse_funcs_for_file_dialect
from dl_connector_clickhouse.formula.definitions.functions_window import DEFINITIONS_WINDOW as CH_DEFINITIONS_WINDOW


DEFINITIONS_WINDOW = clickhouse_funcs_for_file_dialect(CH_DEFINITIONS_WINDOW)
