from dl_connector_bundle_chs3.file.formula.utils import clickhouse_funcs_for_file_dialect
from dl_connector_clickhouse.formula.definitions.functions_logical import DEFINITIONS_LOGICAL as CH_DEFINITIONS_LOGICAL


DEFINITIONS_LOGICAL = clickhouse_funcs_for_file_dialect(CH_DEFINITIONS_LOGICAL)
