from dl_connector_bundle_chs3.file.formula.utils import clickhouse_funcs_for_file_dialect
from dl_connector_clickhouse.formula.definitions.functions_math import DEFINITIONS_MATH as CH_DEFINITIONS_MATH


DEFINITIONS_MATH = clickhouse_funcs_for_file_dialect(CH_DEFINITIONS_MATH)
