from dl_formula_testing.testcases.functions_aggregation import DefaultMainAggFunctionFormulaConnectorTestSuite

from dl_connector_metrica_tests.ext.formula.base import MetricaTestBase


class TestMainAggFunctionBigQuery(MetricaTestBase, DefaultMainAggFunctionFormulaConnectorTestSuite):
    pass
