from dl_formula_testing.testcases.functions_string import DefaultStringFunctionFormulaConnectorTestSuite

from dl_connector_metrica_tests.ext.formula.base import MetricaTestBase


class TestStringFunctionBigQuery(MetricaTestBase, DefaultStringFunctionFormulaConnectorTestSuite):
    pass
