from dl_formula_testing.testcases.functions_markup import DefaultMarkupFunctionFormulaConnectorTestSuite

from dl_connector_metrica_tests.ext.formula.base import MetricaTestBase


class TestMarkupFunctionBigQuery(MetricaTestBase, DefaultMarkupFunctionFormulaConnectorTestSuite):
    pass
