from dl_formula_testing.testcases.functions_logical import DefaultLogicalFunctionFormulaConnectorTestSuite

from dl_connector_metrica_tests.ext.formula.base import MetricaTestBase


class TestLogicalFunctionBigQuery(MetricaTestBase, DefaultLogicalFunctionFormulaConnectorTestSuite):
    pass
