from dl_formula_testing.testcases.functions_datetime import DefaultDateTimeFunctionFormulaConnectorTestSuite

from dl_connector_metrica_tests.ext.formula.base import MetricaTestBase


class TestDateTimeFunctionBigQuery(MetricaTestBase, DefaultDateTimeFunctionFormulaConnectorTestSuite):
    pass
