#!/usr/bin/env python
"""
Put the checks from `MANIFEST.json` into a `releaser`-specified qloud app-environment.
"""

# from __future__ import division, absolute_import, print_function, unicode_literals

COMPONENT_CHECKS = {
    'backend': (
    ),
    'tasks': (
    ),
}

from sbdutils.applib.qloud_juggler import main

if __name__ == '__main__':
    main()
