# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yandex/cloud/priv/oauth/v1/oauth_request.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from yandex.cloud.priv import validation_pb2 as yandex_dot_cloud_dot_priv_dot_validation__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.yandex/cloud/priv/oauth/v1/oauth_request.proto\x12\x1ayandex.cloud.priv.oauth.v1\x1a\"yandex/cloud/priv/validation.proto\"7\n\x0cOAuthRequest\x12\x17\n\tclient_id\x18\x01 \x01(\tB\x04\xa8\x89\x31\x01\x12\x0e\n\x06scopes\x18\x03 \x03(\tB[B\nOAuthModelZMa.yandex-team.ru/cloud/bitbucket/private-api/yandex/cloud/priv/oauth/v1;oauthb\x06proto3')



_OAUTHREQUEST = DESCRIPTOR.message_types_by_name['OAuthRequest']
OAuthRequest = _reflection.GeneratedProtocolMessageType('OAuthRequest', (_message.Message,), {
  'DESCRIPTOR' : _OAUTHREQUEST,
  '__module__' : 'yandex.cloud.priv.oauth.v1.oauth_request_pb2'
  # @@protoc_insertion_point(class_scope:yandex.cloud.priv.oauth.v1.OAuthRequest)
  })
_sym_db.RegisterMessage(OAuthRequest)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'B\nOAuthModelZMa.yandex-team.ru/cloud/bitbucket/private-api/yandex/cloud/priv/oauth/v1;oauth'
  _OAUTHREQUEST.fields_by_name['client_id']._options = None
  _OAUTHREQUEST.fields_by_name['client_id']._serialized_options = b'\250\2111\001'
  _OAUTHREQUEST._serialized_start=114
  _OAUTHREQUEST._serialized_end=169
# @@protoc_insertion_point(module_scope)
