# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yandex/cloud/priv/iam/v1/console/os_login_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from yandex.cloud.priv import validation_pb2 as yandex_dot_cloud_dot_priv_dot_validation__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n7yandex/cloud/priv/iam/v1/console/os_login_service.proto\x12 yandex.cloud.priv.iam.v1.console\x1a\"yandex/cloud/priv/validation.proto\"/\n\x11GetOsLoginRequest\x12\x1a\n\x08\x63loud_id\x18\x01 \x01(\tB\x08\xca\x89\x31\x04<=50\":\n\x12GetOsLoginResponse\x12\x12\n\nsubject_id\x18\x01 \x01(\t\x12\x10\n\x08os_login\x18\x02 \x01(\t2\x82\x01\n\x0eOsLoginService\x12p\n\x03Get\x12\x33.yandex.cloud.priv.iam.v1.console.GetOsLoginRequest\x1a\x34.yandex.cloud.priv.iam.v1.console.GetOsLoginResponseBbB\x05PCOLSZYa.yandex-team.ru/cloud/bitbucket/private-api/yandex/cloud/priv/iam/v1/console;iam_consoleb\x06proto3')



_GETOSLOGINREQUEST = DESCRIPTOR.message_types_by_name['GetOsLoginRequest']
_GETOSLOGINRESPONSE = DESCRIPTOR.message_types_by_name['GetOsLoginResponse']
GetOsLoginRequest = _reflection.GeneratedProtocolMessageType('GetOsLoginRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETOSLOGINREQUEST,
  '__module__' : 'yandex.cloud.priv.iam.v1.console.os_login_service_pb2'
  # @@protoc_insertion_point(class_scope:yandex.cloud.priv.iam.v1.console.GetOsLoginRequest)
  })
_sym_db.RegisterMessage(GetOsLoginRequest)

GetOsLoginResponse = _reflection.GeneratedProtocolMessageType('GetOsLoginResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETOSLOGINRESPONSE,
  '__module__' : 'yandex.cloud.priv.iam.v1.console.os_login_service_pb2'
  # @@protoc_insertion_point(class_scope:yandex.cloud.priv.iam.v1.console.GetOsLoginResponse)
  })
_sym_db.RegisterMessage(GetOsLoginResponse)

_OSLOGINSERVICE = DESCRIPTOR.services_by_name['OsLoginService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'B\005PCOLSZYa.yandex-team.ru/cloud/bitbucket/private-api/yandex/cloud/priv/iam/v1/console;iam_console'
  _GETOSLOGINREQUEST.fields_by_name['cloud_id']._options = None
  _GETOSLOGINREQUEST.fields_by_name['cloud_id']._serialized_options = b'\312\2111\004<=50'
  _GETOSLOGINREQUEST._serialized_start=129
  _GETOSLOGINREQUEST._serialized_end=176
  _GETOSLOGINRESPONSE._serialized_start=178
  _GETOSLOGINRESPONSE._serialized_end=236
  _OSLOGINSERVICE._serialized_start=239
  _OSLOGINSERVICE._serialized_end=369
# @@protoc_insertion_point(module_scope)
