[tool.poetry]
authors = ["DataLens Team <datalens-opensource@yandex-team.ru>"]
description = ""
license = "Apache 2.0"
name = "{{cookiecutter.package_name}}"
packages = [{include = "{{cookiecutter.package_slug}}"}]
readme = "README.md"
version = "0.0.1"

[tool.poetry.dependencies]
python = ">=3.10, <3.13"

[tool.poetry.group.tests.dependencies]
pytest = "*"

[tool.mypy]
check_untyped_defs = true
disallow_untyped_defs = true
strict_optional = true
warn_redundant_casts = true
warn_unused_configs = true
warn_unused_ignores = true

[tool.pytest.ini_options]
addopts = "-ra"
minversion = "6.0"
testpaths = []

[build-system]
build-backend = "poetry.core.masonry.api"
requires = [
  "poetry-core",
]

[datalens.pytest.unit]
labels = ["no_compose"]
root_dir = "{{cookiecutter.package_slug}}_tests/"
skip_compose = "true"
target_path = "unit"
