FROM trinodb/trino:468@sha256:a2b6d3d46c2776c9c1ec3dcdac170d19f98dc538f2c9f2c454f2a364e7f37b87

COPY trino/no_auth_config/* /etc/trino/
COPY trino/catalog/* /etc/trino/catalog/

HEALTHCHECK --interval=30s --timeout=10s --start-period=10s --retries=5 \
    CMD curl -fsS http://localhost:8080/v1/info/state | grep -q '"ACTIVE"'
