FROM nginx:1.27-alpine@sha256:41523187cf7d7a2f2677a80609d9caa14388bf5c1fbca9c410ba3de602aaaab4

COPY nginx/nginx.conf /etc/nginx/nginx.conf
COPY nginx/fetch-certificates.sh /docker-entrypoint.d/

RUN mkdir -p /etc/nginx/certs && \
    chmod +x /docker-entrypoint.d/fetch-certificates.sh
