#!/bin/bash -x

set -Eeuo pipefail

if [ -z "${DLS_DAEMON_NAME:-}" ]; then
    echo "'DLS_DAEMON_NAME' is required." >&2
    sleep 5
    exit 1
fi


case "$DLS_DAEMON_NAME" in
    uvi_http)
        # Twice as fast, but is plagued with about 1% of timeouts on request body read.
        exec gunicorn \
             --log-config /code/gunicorn_logging.ini \
             --workers=4 \
             --worker-class=uvicorn.workers.UvicornWorker \
             --bind "[::]:${DLS_HTTP_PORT:-80}" \
             yadls.httpjrpc.main:app
        ;;
    http|hc_http)
        # Default tested option.
        exec hypercorn \
            --error-log - \
            --workers 4 \
            --bind ":::${DLS_HTTP_PORT:-80}" \
            yadls.httpjrpc.main:app \
            "$@"
        ;;
    x_http)
        # Non-forking customized hypercorn.
        exec bidls-httpjrpc_hc "$@"
        ;;
    dev_http)
        # Dev. Reload... maybe included?
        exec bidls-httpjrpc "$@"
        ;;
    tasks)
        # cron + worker
        exec bidls-tasks "$@"
        ;;
    *)
        echo "Unknown daemon: '$DLS_DAEMON_NAME'" >&2
        sleep 5
        exit 1
esac
