# Include if exists
-include .env


include ../../tools/common_makefile.mk


.PHONY: devenv
devenv:
	docker-compose up --build


devenv-d:
	docker-compose up --build -d


PACKAGE_NAME = bi_connector_snowflake
