FROM cr.yandex/crpsufj53lhl0via9iam/initdb:latest
# ^ https://bb.yandex-team.ru/projects/STATBOX/repos/docker/browse/bi_initdb/Dockerfile

COPY init-db/s3 /s3
COPY init-db/entrypoint.sh /entrypoint.sh

ENTRYPOINT ["sh", "/entrypoint.sh"]
