from dl_formula_testing.testcases.functions_window import DefaultWindowFunctionFormulaConnectorTestSuite

from dl_connector_mysql_tests.db.formula.base import MySQL8p0p12TestBase


class TestWindowFunctionMySQL8p0p12(MySQL8p0p12TestBase, DefaultWindowFunctionFormulaConnectorTestSuite):
    pass
