from bi_connector_postgresql.core.postgresql_base.storage_schemas.connection import ConnectionPostgreSQLBaseDataStorageSchema
from bi_connector_postgresql.core.greenplum.us_connection import GreenplumConnection


class GreenplumConnectionDataStorageSchema(ConnectionPostgreSQLBaseDataStorageSchema):
    TARGET_CLS = GreenplumConnection.DataModel
