# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from yandex.cloud.priv.iam.v1 import access_binding_service_pb2 as yandex_dot_cloud_dot_priv_dot_iam_dot_v1_dot_access__binding__service__pb2
from yandex.cloud.priv.operation import operation_pb2 as yandex_dot_cloud_dot_priv_dot_operation_dot_operation__pb2


class AccessBindingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListAccessBindings = channel.unary_unary(
                '/yandex.cloud.priv.iam.v1.AccessBindingService/ListAccessBindings',
                request_serializer=yandex_dot_cloud_dot_priv_dot_iam_dot_v1_dot_access__binding__service__pb2.ListAccessBindingsRequest.SerializeToString,
                response_deserializer=yandex_dot_cloud_dot_priv_dot_iam_dot_v1_dot_access__binding__service__pb2.ListAccessBindingsResponse.FromString,
                )
        self.SetAccessBindings = channel.unary_unary(
                '/yandex.cloud.priv.iam.v1.AccessBindingService/SetAccessBindings',
                request_serializer=yandex_dot_cloud_dot_priv_dot_iam_dot_v1_dot_access__binding__service__pb2.SetAccessBindingsRequest.SerializeToString,
                response_deserializer=yandex_dot_cloud_dot_priv_dot_operation_dot_operation__pb2.Operation.FromString,
                )
        self.UpdateAccessBindings = channel.unary_unary(
                '/yandex.cloud.priv.iam.v1.AccessBindingService/UpdateAccessBindings',
                request_serializer=yandex_dot_cloud_dot_priv_dot_iam_dot_v1_dot_access__binding__service__pb2.UpdateAccessBindingsRequest.SerializeToString,
                response_deserializer=yandex_dot_cloud_dot_priv_dot_operation_dot_operation__pb2.Operation.FromString,
                )
        self.CheckLikelyPubliclyAccessible = channel.unary_unary(
                '/yandex.cloud.priv.iam.v1.AccessBindingService/CheckLikelyPubliclyAccessible',
                request_serializer=yandex_dot_cloud_dot_priv_dot_iam_dot_v1_dot_access__binding__service__pb2.CheckLikelyPubliclyAccessibleRequest.SerializeToString,
                response_deserializer=yandex_dot_cloud_dot_priv_dot_iam_dot_v1_dot_access__binding__service__pb2.CheckLikelyPubliclyAccessibleResponse.FromString,
                )
        self.ChangeTopLevelResource = channel.unary_unary(
                '/yandex.cloud.priv.iam.v1.AccessBindingService/ChangeTopLevelResource',
                request_serializer=yandex_dot_cloud_dot_priv_dot_iam_dot_v1_dot_access__binding__service__pb2.ChangeTopLevelResourceRequest.SerializeToString,
                response_deserializer=yandex_dot_cloud_dot_priv_dot_operation_dot_operation__pb2.Operation.FromString,
                )
        self.DeleteByTopLevelResource = channel.unary_unary(
                '/yandex.cloud.priv.iam.v1.AccessBindingService/DeleteByTopLevelResource',
                request_serializer=yandex_dot_cloud_dot_priv_dot_iam_dot_v1_dot_access__binding__service__pb2.DeleteByTopLevelResourceRequest.SerializeToString,
                response_deserializer=yandex_dot_cloud_dot_priv_dot_operation_dot_operation__pb2.Operation.FromString,
                )


class AccessBindingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListAccessBindings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetAccessBindings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateAccessBindings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckLikelyPubliclyAccessible(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ChangeTopLevelResource(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteByTopLevelResource(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AccessBindingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListAccessBindings': grpc.unary_unary_rpc_method_handler(
                    servicer.ListAccessBindings,
                    request_deserializer=yandex_dot_cloud_dot_priv_dot_iam_dot_v1_dot_access__binding__service__pb2.ListAccessBindingsRequest.FromString,
                    response_serializer=yandex_dot_cloud_dot_priv_dot_iam_dot_v1_dot_access__binding__service__pb2.ListAccessBindingsResponse.SerializeToString,
            ),
            'SetAccessBindings': grpc.unary_unary_rpc_method_handler(
                    servicer.SetAccessBindings,
                    request_deserializer=yandex_dot_cloud_dot_priv_dot_iam_dot_v1_dot_access__binding__service__pb2.SetAccessBindingsRequest.FromString,
                    response_serializer=yandex_dot_cloud_dot_priv_dot_operation_dot_operation__pb2.Operation.SerializeToString,
            ),
            'UpdateAccessBindings': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateAccessBindings,
                    request_deserializer=yandex_dot_cloud_dot_priv_dot_iam_dot_v1_dot_access__binding__service__pb2.UpdateAccessBindingsRequest.FromString,
                    response_serializer=yandex_dot_cloud_dot_priv_dot_operation_dot_operation__pb2.Operation.SerializeToString,
            ),
            'CheckLikelyPubliclyAccessible': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckLikelyPubliclyAccessible,
                    request_deserializer=yandex_dot_cloud_dot_priv_dot_iam_dot_v1_dot_access__binding__service__pb2.CheckLikelyPubliclyAccessibleRequest.FromString,
                    response_serializer=yandex_dot_cloud_dot_priv_dot_iam_dot_v1_dot_access__binding__service__pb2.CheckLikelyPubliclyAccessibleResponse.SerializeToString,
            ),
            'ChangeTopLevelResource': grpc.unary_unary_rpc_method_handler(
                    servicer.ChangeTopLevelResource,
                    request_deserializer=yandex_dot_cloud_dot_priv_dot_iam_dot_v1_dot_access__binding__service__pb2.ChangeTopLevelResourceRequest.FromString,
                    response_serializer=yandex_dot_cloud_dot_priv_dot_operation_dot_operation__pb2.Operation.SerializeToString,
            ),
            'DeleteByTopLevelResource': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteByTopLevelResource,
                    request_deserializer=yandex_dot_cloud_dot_priv_dot_iam_dot_v1_dot_access__binding__service__pb2.DeleteByTopLevelResourceRequest.FromString,
                    response_serializer=yandex_dot_cloud_dot_priv_dot_operation_dot_operation__pb2.Operation.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'yandex.cloud.priv.iam.v1.AccessBindingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AccessBindingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListAccessBindings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/yandex.cloud.priv.iam.v1.AccessBindingService/ListAccessBindings',
            yandex_dot_cloud_dot_priv_dot_iam_dot_v1_dot_access__binding__service__pb2.ListAccessBindingsRequest.SerializeToString,
            yandex_dot_cloud_dot_priv_dot_iam_dot_v1_dot_access__binding__service__pb2.ListAccessBindingsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetAccessBindings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/yandex.cloud.priv.iam.v1.AccessBindingService/SetAccessBindings',
            yandex_dot_cloud_dot_priv_dot_iam_dot_v1_dot_access__binding__service__pb2.SetAccessBindingsRequest.SerializeToString,
            yandex_dot_cloud_dot_priv_dot_operation_dot_operation__pb2.Operation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateAccessBindings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/yandex.cloud.priv.iam.v1.AccessBindingService/UpdateAccessBindings',
            yandex_dot_cloud_dot_priv_dot_iam_dot_v1_dot_access__binding__service__pb2.UpdateAccessBindingsRequest.SerializeToString,
            yandex_dot_cloud_dot_priv_dot_operation_dot_operation__pb2.Operation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CheckLikelyPubliclyAccessible(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/yandex.cloud.priv.iam.v1.AccessBindingService/CheckLikelyPubliclyAccessible',
            yandex_dot_cloud_dot_priv_dot_iam_dot_v1_dot_access__binding__service__pb2.CheckLikelyPubliclyAccessibleRequest.SerializeToString,
            yandex_dot_cloud_dot_priv_dot_iam_dot_v1_dot_access__binding__service__pb2.CheckLikelyPubliclyAccessibleResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ChangeTopLevelResource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/yandex.cloud.priv.iam.v1.AccessBindingService/ChangeTopLevelResource',
            yandex_dot_cloud_dot_priv_dot_iam_dot_v1_dot_access__binding__service__pb2.ChangeTopLevelResourceRequest.SerializeToString,
            yandex_dot_cloud_dot_priv_dot_operation_dot_operation__pb2.Operation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteByTopLevelResource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/yandex.cloud.priv.iam.v1.AccessBindingService/DeleteByTopLevelResource',
            yandex_dot_cloud_dot_priv_dot_iam_dot_v1_dot_access__binding__service__pb2.DeleteByTopLevelResourceRequest.SerializeToString,
            yandex_dot_cloud_dot_priv_dot_operation_dot_operation__pb2.Operation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
