# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from yandex.cloud.priv.operation import operation_pb2 as yandex_dot_cloud_dot_priv_dot_operation_dot_operation__pb2
from yandex.cloud.priv.quota import quota_limit_pb2 as yandex_dot_cloud_dot_priv_dot_quota_dot_quota__limit__pb2


class QuotaLimitServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Get = channel.unary_unary(
                '/yandex.cloud.priv.iam.v1.QuotaLimitService/Get',
                request_serializer=yandex_dot_cloud_dot_priv_dot_quota_dot_quota__limit__pb2.GetQuotaLimitRequest.SerializeToString,
                response_deserializer=yandex_dot_cloud_dot_priv_dot_quota_dot_quota__limit__pb2.GetQuotaLimitResponse.FromString,
                )
        self.GetDefault = channel.unary_unary(
                '/yandex.cloud.priv.iam.v1.QuotaLimitService/GetDefault',
                request_serializer=yandex_dot_cloud_dot_priv_dot_quota_dot_quota__limit__pb2.GetDefaultQuotaLimitRequest.SerializeToString,
                response_deserializer=yandex_dot_cloud_dot_priv_dot_quota_dot_quota__limit__pb2.GetDefaultQuotaLimitResponse.FromString,
                )
        self.Update = channel.unary_unary(
                '/yandex.cloud.priv.iam.v1.QuotaLimitService/Update',
                request_serializer=yandex_dot_cloud_dot_priv_dot_quota_dot_quota__limit__pb2.UpdateQuotaLimitRequest.SerializeToString,
                response_deserializer=yandex_dot_cloud_dot_priv_dot_operation_dot_operation__pb2.Operation.FromString,
                )
        self.BatchUpdate = channel.unary_unary(
                '/yandex.cloud.priv.iam.v1.QuotaLimitService/BatchUpdate',
                request_serializer=yandex_dot_cloud_dot_priv_dot_quota_dot_quota__limit__pb2.BatchUpdateQuotaLimitsRequest.SerializeToString,
                response_deserializer=yandex_dot_cloud_dot_priv_dot_operation_dot_operation__pb2.Operation.FromString,
                )


class QuotaLimitServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Get(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDefault(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Update(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QuotaLimitServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Get': grpc.unary_unary_rpc_method_handler(
                    servicer.Get,
                    request_deserializer=yandex_dot_cloud_dot_priv_dot_quota_dot_quota__limit__pb2.GetQuotaLimitRequest.FromString,
                    response_serializer=yandex_dot_cloud_dot_priv_dot_quota_dot_quota__limit__pb2.GetQuotaLimitResponse.SerializeToString,
            ),
            'GetDefault': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDefault,
                    request_deserializer=yandex_dot_cloud_dot_priv_dot_quota_dot_quota__limit__pb2.GetDefaultQuotaLimitRequest.FromString,
                    response_serializer=yandex_dot_cloud_dot_priv_dot_quota_dot_quota__limit__pb2.GetDefaultQuotaLimitResponse.SerializeToString,
            ),
            'Update': grpc.unary_unary_rpc_method_handler(
                    servicer.Update,
                    request_deserializer=yandex_dot_cloud_dot_priv_dot_quota_dot_quota__limit__pb2.UpdateQuotaLimitRequest.FromString,
                    response_serializer=yandex_dot_cloud_dot_priv_dot_operation_dot_operation__pb2.Operation.SerializeToString,
            ),
            'BatchUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchUpdate,
                    request_deserializer=yandex_dot_cloud_dot_priv_dot_quota_dot_quota__limit__pb2.BatchUpdateQuotaLimitsRequest.FromString,
                    response_serializer=yandex_dot_cloud_dot_priv_dot_operation_dot_operation__pb2.Operation.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'yandex.cloud.priv.iam.v1.QuotaLimitService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class QuotaLimitService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Get(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/yandex.cloud.priv.iam.v1.QuotaLimitService/Get',
            yandex_dot_cloud_dot_priv_dot_quota_dot_quota__limit__pb2.GetQuotaLimitRequest.SerializeToString,
            yandex_dot_cloud_dot_priv_dot_quota_dot_quota__limit__pb2.GetQuotaLimitResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDefault(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/yandex.cloud.priv.iam.v1.QuotaLimitService/GetDefault',
            yandex_dot_cloud_dot_priv_dot_quota_dot_quota__limit__pb2.GetDefaultQuotaLimitRequest.SerializeToString,
            yandex_dot_cloud_dot_priv_dot_quota_dot_quota__limit__pb2.GetDefaultQuotaLimitResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Update(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/yandex.cloud.priv.iam.v1.QuotaLimitService/Update',
            yandex_dot_cloud_dot_priv_dot_quota_dot_quota__limit__pb2.UpdateQuotaLimitRequest.SerializeToString,
            yandex_dot_cloud_dot_priv_dot_operation_dot_operation__pb2.Operation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BatchUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/yandex.cloud.priv.iam.v1.QuotaLimitService/BatchUpdate',
            yandex_dot_cloud_dot_priv_dot_quota_dot_quota__limit__pb2.BatchUpdateQuotaLimitsRequest.SerializeToString,
            yandex_dot_cloud_dot_priv_dot_operation_dot_operation__pb2.Operation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
