# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yandex/cloud/priv/iam/v1/refresh_token_issue_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from yandex.cloud.priv import validation_pb2 as yandex_dot_cloud_dot_priv_dot_validation__pb2
from yandex.cloud.priv import sensitive_pb2 as yandex_dot_cloud_dot_priv_dot_sensitive__pb2
from yandex.cloud.priv.iam.v1.ts import iam_token_service_subject_pb2 as yandex_dot_cloud_dot_priv_dot_iam_dot_v1_dot_ts_dot_iam__token__service__subject__pb2
from yandex.cloud.priv.oauth.v1 import oauth_request_pb2 as yandex_dot_cloud_dot_priv_dot_oauth_dot_v1_dot_oauth__request__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n:yandex/cloud/priv/iam/v1/refresh_token_issue_service.proto\x12\x18yandex.cloud.priv.iam.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\"yandex/cloud/priv/validation.proto\x1a!yandex/cloud/priv/sensitive.proto\x1a;yandex/cloud/priv/iam/v1/ts/iam_token_service_subject.proto\x1a.yandex/cloud/priv/oauth/v1/oauth_request.proto\"\xb6\x01\n#CreateRefreshTokenForSubjectRequest\x12 \n\nsubject_id\x18\x01 \x01(\tB\x0c\xa8\x89\x31\x01\xca\x89\x31\x04<=50\x12\x45\n\roauth_request\x18\x02 \x01(\x0b\x32(.yandex.cloud.priv.oauth.v1.OAuthRequestB\x04\xa8\x89\x31\x01\x12&\n\x10refresh_token_id\x18\x03 \x01(\tB\x0c\xa8\x89\x31\x01\xca\x89\x31\x04<=50\"\xd3\x01\n\x1a\x43reateRefreshTokenResponse\x12\x1f\n\rrefresh_token\x18\x01 \x01(\tB\x08\xc8\x8f\x31\x01\xd0\x8f\x31\x06\x12-\n\tissued_at\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nexpires_at\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x35\n\x07subject\x18\x03 \x01(\x0b\x32$.yandex.cloud.priv.iam.v1.ts.Subject2\xa4\x01\n\x18RefreshTokenIssueService\x12\x87\x01\n\x10\x43reateForSubject\x12=.yandex.cloud.priv.iam.v1.CreateRefreshTokenForSubjectRequest\x1a\x34.yandex.cloud.priv.iam.v1.CreateRefreshTokenResponseBSB\x06PIRTISZIa.yandex-team.ru/cloud/bitbucket/private-api/yandex/cloud/priv/iam/v1;iamb\x06proto3')



_CREATEREFRESHTOKENFORSUBJECTREQUEST = DESCRIPTOR.message_types_by_name['CreateRefreshTokenForSubjectRequest']
_CREATEREFRESHTOKENRESPONSE = DESCRIPTOR.message_types_by_name['CreateRefreshTokenResponse']
CreateRefreshTokenForSubjectRequest = _reflection.GeneratedProtocolMessageType('CreateRefreshTokenForSubjectRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATEREFRESHTOKENFORSUBJECTREQUEST,
  '__module__' : 'yandex.cloud.priv.iam.v1.refresh_token_issue_service_pb2'
  # @@protoc_insertion_point(class_scope:yandex.cloud.priv.iam.v1.CreateRefreshTokenForSubjectRequest)
  })
_sym_db.RegisterMessage(CreateRefreshTokenForSubjectRequest)

CreateRefreshTokenResponse = _reflection.GeneratedProtocolMessageType('CreateRefreshTokenResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREATEREFRESHTOKENRESPONSE,
  '__module__' : 'yandex.cloud.priv.iam.v1.refresh_token_issue_service_pb2'
  # @@protoc_insertion_point(class_scope:yandex.cloud.priv.iam.v1.CreateRefreshTokenResponse)
  })
_sym_db.RegisterMessage(CreateRefreshTokenResponse)

_REFRESHTOKENISSUESERVICE = DESCRIPTOR.services_by_name['RefreshTokenIssueService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'B\006PIRTISZIa.yandex-team.ru/cloud/bitbucket/private-api/yandex/cloud/priv/iam/v1;iam'
  _CREATEREFRESHTOKENFORSUBJECTREQUEST.fields_by_name['subject_id']._options = None
  _CREATEREFRESHTOKENFORSUBJECTREQUEST.fields_by_name['subject_id']._serialized_options = b'\250\2111\001\312\2111\004<=50'
  _CREATEREFRESHTOKENFORSUBJECTREQUEST.fields_by_name['oauth_request']._options = None
  _CREATEREFRESHTOKENFORSUBJECTREQUEST.fields_by_name['oauth_request']._serialized_options = b'\250\2111\001'
  _CREATEREFRESHTOKENFORSUBJECTREQUEST.fields_by_name['refresh_token_id']._options = None
  _CREATEREFRESHTOKENFORSUBJECTREQUEST.fields_by_name['refresh_token_id']._serialized_options = b'\250\2111\001\312\2111\004<=50'
  _CREATEREFRESHTOKENRESPONSE.fields_by_name['refresh_token']._options = None
  _CREATEREFRESHTOKENRESPONSE.fields_by_name['refresh_token']._serialized_options = b'\310\2171\001\320\2171\006'
  _CREATEREFRESHTOKENFORSUBJECTREQUEST._serialized_start=302
  _CREATEREFRESHTOKENFORSUBJECTREQUEST._serialized_end=484
  _CREATEREFRESHTOKENRESPONSE._serialized_start=487
  _CREATEREFRESHTOKENRESPONSE._serialized_end=698
  _REFRESHTOKENISSUESERVICE._serialized_start=701
  _REFRESHTOKENISSUESERVICE._serialized_end=865
# @@protoc_insertion_point(module_scope)
