"""Create tables

Revision ID: 8f7d8fff4897
Revises:
Create Date: 2021-01-27 18:01:38.641893

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f7d8fff4897'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bi_alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('description', sa.String(length=2048), nullable=True),
    sa.Column('alert_method', sa.Enum('threshold', name='alertmethodtype'), nullable=False),
    sa.Column('alert_params', sa.JSON(), nullable=False),
    sa.Column('owner', sa.String(length=256), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.Column('creation_time', sa.DateTime(), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bi_alert_owner'), 'bi_alert', ['owner'], unique=False)
    op.create_table('bi_datasync',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chart_id', sa.String(length=64), nullable=False),
    sa.Column('chart_params', sa.JSON(), nullable=False),
    sa.Column('chart_params_hash', sa.String(length=64), nullable=False),
    sa.Column('lines', sa.JSON(), nullable=False),
    sa.Column('external_shard_id', sa.String(length=8), nullable=False),
    sa.Column('creation_time', sa.DateTime(), nullable=True),
    sa.Column('last_check_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bi_datasync_chart_id'), 'bi_datasync', ['chart_id'], unique=False)
    op.create_index(op.f('ix_bi_datasync_external_shard_id'), 'bi_datasync', ['external_shard_id'], unique=False)
    op.create_table('bi_notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient', sa.String(length=256), nullable=False),
    sa.Column('transport', sa.Enum('email', name='notificationtransporttype'), nullable=False),
    sa.Column('external_id', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bi_notification_recipient'), 'bi_notification', ['recipient'], unique=False)
    op.create_table('alert_notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=True),
    sa.Column('notification_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['bi_alert.id'], name='fk_alert_id'),
    sa.ForeignKeyConstraint(['notification_id'], ['bi_notification.id'], name='fk_notification_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_notification_active'), 'alert_notification', ['active'], unique=False)
    op.create_index(op.f('ix_alert_notification_alert_id'), 'alert_notification', ['alert_id'], unique=False)
    op.create_index(op.f('ix_alert_notification_notification_id'), 'alert_notification', ['notification_id'], unique=False)
    op.create_table('datasync_alert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datasync_id', sa.Integer(), nullable=True),
    sa.Column('alert_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['bi_alert.id'], name='fk_alert_id'),
    sa.ForeignKeyConstraint(['datasync_id'], ['bi_datasync.id'], name='fk_datasync_id'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datasync_alert_active'), 'datasync_alert', ['active'], unique=False)
    op.create_index(op.f('ix_datasync_alert_alert_id'), 'datasync_alert', ['alert_id'], unique=False)
    op.create_index(op.f('ix_datasync_alert_datasync_id'), 'datasync_alert', ['datasync_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_datasync_alert_datasync_id'), table_name='datasync_alert')
    op.drop_index(op.f('ix_datasync_alert_alert_id'), table_name='datasync_alert')
    op.drop_index(op.f('ix_datasync_alert_active'), table_name='datasync_alert')
    op.drop_table('datasync_alert')
    op.drop_index(op.f('ix_alert_notification_notification_id'), table_name='alert_notification')
    op.drop_index(op.f('ix_alert_notification_alert_id'), table_name='alert_notification')
    op.drop_index(op.f('ix_alert_notification_active'), table_name='alert_notification')
    op.drop_table('alert_notification')
    op.drop_index(op.f('ix_bi_notification_recipient'), table_name='bi_notification')
    op.drop_table('bi_notification')
    op.drop_index(op.f('ix_bi_datasync_external_shard_id'), table_name='bi_datasync')
    op.drop_index(op.f('ix_bi_datasync_chart_id'), table_name='bi_datasync')
    op.drop_table('bi_datasync')
    op.drop_index(op.f('ix_bi_alert_owner'), table_name='bi_alert')
    op.drop_table('bi_alert')
    # ### end Alembic commands ###
