"""Changing owner_uid type

Revision ID: 6cf5bdfccdef
Revises: 1e76a39bf9ae
Create Date: 2021-02-11 10:47:07.934312

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6cf5bdfccdef'
down_revision = '1e76a39bf9ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bi_alert', 'owner_uid',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=64),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bi_alert', 'owner_uid',
               existing_type=sa.String(length=64),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###
