"""Adding window column for bi_alerts

Revision ID: d7335611407d
Revises: 6cf5bdfccdef
Create Date: 2021-02-20 18:13:24.735411

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7335611407d'
down_revision = '6cf5bdfccdef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bi_alert', sa.Column('window', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bi_alert', 'window')
    # ### end Alembic commands ###
