# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from yandex.cloud.priv.iam.v1.mfa.console import totp_profile_service_pb2 as yandex_dot_cloud_dot_priv_dot_iam_dot_v1_dot_mfa_dot_console_dot_totp__profile__service__pb2


class TotpProfileServiceStub(object):
    """A set of methods for managing hardware and software time-based one time passwords (TOTP).
    The user credentials should be passed in the authorization header.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Verify = channel.unary_unary(
                '/yandex.cloud.priv.iam.v1.mfa.console.TotpProfileService/Verify',
                request_serializer=yandex_dot_cloud_dot_priv_dot_iam_dot_v1_dot_mfa_dot_console_dot_totp__profile__service__pb2.VerifyTotpRequest.SerializeToString,
                response_deserializer=yandex_dot_cloud_dot_priv_dot_iam_dot_v1_dot_mfa_dot_console_dot_totp__profile__service__pb2.VerifyTotpResponse.FromString,
                )
        self.List = channel.unary_unary(
                '/yandex.cloud.priv.iam.v1.mfa.console.TotpProfileService/List',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=yandex_dot_cloud_dot_priv_dot_iam_dot_v1_dot_mfa_dot_console_dot_totp__profile__service__pb2.ListTotpResponse.FromString,
                )


class TotpProfileServiceServicer(object):
    """A set of methods for managing hardware and software time-based one time passwords (TOTP).
    The user credentials should be passed in the authorization header.
    """

    def Verify(self, request, context):
        """Verifies user-supplied TOTP value. See https://tools.ietf.org/html/rfc6238#section-5.2 for the reference.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def List(self, request, context):
        """Retrieves the list of TOTP-profiles and required MFA-policies for authenticated user
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TotpProfileServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Verify': grpc.unary_unary_rpc_method_handler(
                    servicer.Verify,
                    request_deserializer=yandex_dot_cloud_dot_priv_dot_iam_dot_v1_dot_mfa_dot_console_dot_totp__profile__service__pb2.VerifyTotpRequest.FromString,
                    response_serializer=yandex_dot_cloud_dot_priv_dot_iam_dot_v1_dot_mfa_dot_console_dot_totp__profile__service__pb2.VerifyTotpResponse.SerializeToString,
            ),
            'List': grpc.unary_unary_rpc_method_handler(
                    servicer.List,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=yandex_dot_cloud_dot_priv_dot_iam_dot_v1_dot_mfa_dot_console_dot_totp__profile__service__pb2.ListTotpResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'yandex.cloud.priv.iam.v1.mfa.console.TotpProfileService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TotpProfileService(object):
    """A set of methods for managing hardware and software time-based one time passwords (TOTP).
    The user credentials should be passed in the authorization header.
    """

    @staticmethod
    def Verify(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/yandex.cloud.priv.iam.v1.mfa.console.TotpProfileService/Verify',
            yandex_dot_cloud_dot_priv_dot_iam_dot_v1_dot_mfa_dot_console_dot_totp__profile__service__pb2.VerifyTotpRequest.SerializeToString,
            yandex_dot_cloud_dot_priv_dot_iam_dot_v1_dot_mfa_dot_console_dot_totp__profile__service__pb2.VerifyTotpResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def List(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/yandex.cloud.priv.iam.v1.mfa.console.TotpProfileService/List',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            yandex_dot_cloud_dot_priv_dot_iam_dot_v1_dot_mfa_dot_console_dot_totp__profile__service__pb2.ListTotpResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
