#!/usr/bin/env sh

set -x  # debug.
set -eu

HTTP_BIND_PORT="8080"
if [ "${BISYS_USE_IPV6:-1}" = "1" ]; then HTTP_BIND_ADDR="[::]"; else HTTP_BIND_ADDR="0.0.0.0"; fi

BI_API_UWSGI_WORKERS_COUNT="${BI_API_UWSGI_WORKERS_COUNT:-}"
if [ -z "$BI_API_UWSGI_WORKERS_COUNT" ]; then
    if [ x"$YENV_TYPE" = x"testing" ]; then
        # Do not use too much memory in testing.
        BI_API_UWSGI_WORKERS_COUNT=4
    else
        BI_API_UWSGI_WORKERS_COUNT=40
    fi
fi

# It is also set in the ini file, but that might not work in some cases.
UWSGI_STATS=/tmp/uwsgi_stats.sock
HTTP_BIND="${HTTP_BIND_ADDR}:${HTTP_BIND_PORT}"

export BI_API_UWSGI_WORKERS_COUNT UWSGI_STATS HTTP_BIND
exec \
    uwsgi \
        --ini=/src/app/uwsgi/uwsgi-bi-api.ini
