[tool.poetry]
name = "datalens-ci-migration"
version = "0.1.0"
description = ""
authors = ["Valentin Gologuzov <vgol@double.cloud>"]
license = "MIT"
packages = [{include = "bi_ci_dummy"}]

[tool.poetry.dependencies]
python = ">=3.10, <3.12"
antlr4-python3-runtime = "==4.11.1"
aiohttp = "==3.8.5"
aiopg = "==1.4.0"
anyascii = "==0.3.2"
attrs = "==22.2.0"
arq = "==0.25.0"
certifi = "==2022.12.7"
openpyxl = "==3.0.10"
aiobotocore = "==2.4.2"
aiogoogle = "==5.2.0"
marshmallow = "==3.19.0"
sentry-sdk = "==1.15.0"
pyyaml = "==5.3.1"
SQLAlchemy = "==1.4.46, <2.0"
gunicorn = "==20.1.0"
shortuuid = "==1.0.11"
sqlalchemy = "==1.4.46, <2.0"
Flask = "==2.0.3"
Flask-SQLAlchemy = "==2.5.1"
Werkzeug = "==2.0.3"
blinker = "==1.5"
certifi-yandex = "==2021.10.08"
flask-marshmallow = "==0.14.0"
flask-restx = "==1.1.0"
graphviz = "==0.17"
ipdb = "==0.13.13"
ipython = "==8.10.0"
marshmallow-oneofschema = "==3.0.1"
pandas = "==1.5.3"
pyopenssl = "==21.0.0"
python-dateutil = "==2.8.2"
raven = "==6.10.0"
requests = "==2.28.2"
tabulate = "==0.9.0"
async-timeout = "==4.0.2"
psycopg2-binary = "==2.9.6"
pyjwt = "==2.3.0"
pytz = "==2022.7.1"
ujson = "==1.35"
werkzeug = "==2.0.3"
xxhash = "==3.2.0"
asyncpg = "==0.27.0"
flask = "==2.0.3"
snowflake-connector-python = "==2.9.0"
snowflake-sqlalchemy = "==1.4.6"
clickhouse-driver = "==0.2.5"
dill = "==0.3.6"
google-api-core = "==2.11.1"
google-auth = "==2.21.0"
oracledb = "==1.3.1"
yarl = "==1.8.2"
googleapis-common-protos = "==1.59.1"
grpcio = "==1.45.0rc1"
mysqlclient = "==1.4.6"
pyodbc = "==4.0.35"
ciso8601 = "==2.2.0"
aiomysql = "==0.2.0"
redis = "==4.5.1"
ydb = "==3.3.6"
Babel = "==2.12.1"
jinja2 = "==3.1.2"
opentracing = "==2.4.0"
frozendict = "==2.3.8"
typing-extensions = "==4.5.0"
aiodns = "==3.0.0"
jaeger-client = "==4.8.0"
pytest = "==7.2.2"
tornado = "==6.2"
yandex-passport-vault-client = "==1.5.2"
cryptography = "==3.3.2"
typeguard = "==2.13.3"
flask-sqlalchemy = "==2.5.1"
marshmallow-sqlalchemy = "==0.25.0"
more-itertools = "==9.1.0"
simplejson = "==3.18.4"
aiochclient = "==2.2.0"
apispec = "==3.3.2"
cchardet = "==2.1.7"
celery = "==5.2.7"
dnspython = "==2.2.1"
lz4 = "==4.3.2"
tvmauth = "==3.4.9"
blackbox = "==0.72"
tvm2 = "==5.0"



[tool.poetry.group.ci.dependencies]
boto3 = ">=1.24.59"  # TODO FIX: This is used in tests in some packages. Try to fix with dependency in relevant packages
#
# All apps should be listed here. This group is installed for CI & local development
#
yandex-bi-package-boilerplate = {path = "../lib/bi_package_boilerplate"}
yandex-bi-connector-bigquery = {path = "../lib/bi_connector_bigquery"}
yandex-bi-connector-postgresql = {path = "../lib/bi_connector_postgresql"}
yandex-bi-api-client = {path = "../lib/bi_api_client"}
yandex-bi-api-commons = {path = "../lib/bi_api_commons"}
yandex-bi-api-connector = {path = "../lib/bi_api_connector"}
yandex-bi-api-lib = {path = "../lib/bi_api_lib"}
yandex-bi-api-lib-testing = {path = "../lib/bi_api_lib_testing"}
yandex-bi-app-tools = {path = "../lib/bi_app_tools"}
yandex-bi-compeng-pg = {path = "../lib/bi_compeng_pg"}
yandex-bi-configs = {path = "../lib/bi_configs"}
yandex-bi-connector-bundle-chs3 = {path = "../lib/bi_connector_bundle_chs3"}
yandex-bi-connector-chyt = {path = "../lib/bi_connector_chyt"}
yandex-bi-connector-clickhouse = {path = "../lib/bi_connector_clickhouse"}
bi-connector-greenplum = {path = "../lib/bi_connector_greenplum"}
yandex-bi-connector-mssql = {path = "../lib/bi_connector_mssql"}
yandex-bi-connector-oracle = {path = "../lib/bi_connector_oracle"}
yandex-bi-connector-promql = {path = "../lib/bi_connector_promql"}
yandex-bi-connector-snowflake = {path = "../lib/bi_connector_snowflake"}
yandex-bi-constants = {path = "../lib/bi_constants"}
yandex-bi-core = {path = "../lib/bi_core"}
yandex-bi-core-testing = {path = "../lib/bi_core_testing"}
yandex-bi-db-testing = {path = "../lib/bi_db_testing"}
bi-file-secure-reader-lib = {path = "../lib/bi_file_secure_reader_lib"}
yandex-bi-file-uploader-api-lib = {path = "../lib/bi_file_uploader_api_lib"}
yandex-bi-file-uploader-lib = {path = "../lib/bi_file_uploader_lib"}
bi-file-uploader-task-interface = {path = "../lib/bi_file_uploader_task_interface"}
yandex-bi-file-uploader-worker-lib = {path = "../lib/bi_file_uploader_worker_lib"}
yandex-bi-formula = {path = "../lib/bi_formula"}
yandex-bi-formula-ref = {path = "../lib/bi_formula_ref"}
bi-i18n = {path = "../lib/bi_i18n"}
yandex-bi-model-tools = {path = "../lib/bi_model_tools"}
yandex-bi-query-processing = {path = "../lib/bi_query_processing"}
yandex-bi-sqlalchemy-chyt = {path = "../lib/bi_sqlalchemy_chyt"}
yandex-bi-sqlalchemy-clickhouse = {path = "../lib/bi_sqlalchemy_clickhouse"}
yandex-bi-sqlalchemy-common = {path = "../lib/bi_sqlalchemy_common"}
yandex-bi-sqlalchemy-mssql = {path = "../lib/bi_sqlalchemy_mssql"}
yandex-bi-sqlalchemy-oracle = {path = "../lib/bi_sqlalchemy_oracle"}
yandex-bi-sqlalchemy-postgres = {path = "../lib/bi_sqlalchemy_postgres"}
yandex-bi-sqlalchemy-promql = {path = "../lib/bi_sqlalchemy_promql"}
bi-task-processor = {path = "../lib/bi_task_processor"}
yandex-bi-testing = {path = "../lib/bi_testing"}
yandex-bi-us-client = {path = "../lib/bi_us_client"}
yandex-bi-utils = {path = "../lib/bi_utils"}
statinfra-clickhouse-sqlalchemy = {path = "../lib/clickhouse-sqlalchemy"}
dynamic-enum = {path = "../lib/dynamic_enum"}
redis_cache_lock = {path = "../lib/redis-cache-lock"}
statcommons = {path = "../lib/statcommons"}


#
# This section defines dependencies groups per app.
# To export/install specific app without other dependencies - use `--only` flag
# Group naming convention: `app_${APP_FOLDER_NAME}`
#

[tool.poetry.group.dev.dependencies]
black = "==23.3.0"
ruff = "==0.0.267"
ipdb = "==0.13.13"
mysqlclient = "==1.4.6"
psycopg2 = "==2.8.6"
pyodbc = "==4.0.35"
pytest = "==7.2.2"
python-dateutil = "==2.8.2"
pytest-asyncio = "==0.21.0"
uwsgi = "==2.0.21"
shortuuid = "==1.0.11"
sentry-sdk = "==1.15.0"
babel = "==2.12.1"
mock = "==4.0.3"
responses = "==0.23.1"
pytest-lazy-fixture = "==0.6.3"
pytz = "==2022.7.1"
oracledb = "==1.3.1"
psycopg2-binary = "==2.9.6"
tomlkit = "==0.11.8"
pandas = "==1.5.3"
platformdirs = "==3.8.0"
clize = "==5.0.0"
poetry = "==1.5.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 140
select = [
    # Pyflakes
    "F",
    # Pycodestyle
    "E",
    "W",
    # isort
    "I"

]

[tool.ruff.isort]
split-on-trailing-comma = true

[tool.black]
line-length = 140
target-version = ['py310']

[[tool.poetry.source]]
name = "ya"
url = "https://pypi.yandex-team.ru/simple/"
priority = "default"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra"
testpaths = []


[datalens.meta.mypy_stubs_packages_override]
# bunch of overrides for different case
# : src package -> {"name": "non standard name, but same stub should have same version"}
# : src package -> {"name": "non standard name", "version": "hard coded version"}
# : src package -> {"version": "hard coded version"}  # implies standard types-{pkg name} name
# : src package -> {"ignore": true} # stub doesn't exist
aiochclient = {ignore = true}
aiodns = {ignore = true}
aiogoogle =  {ignore = true}
aiohttp_cors =  {ignore = true}
aiomysql =  {ignore = true}
aiopg =  {ignore = true}
alembic =  {ignore = true}
antlr4-python3-runtime =  {ignore = true}
apispec =  {ignore = true}
arq =  {ignore = true}
async-timeout =  {ignore = true}
asyncpg =  {ignore = true}
attrs =  {ignore = true}
babel =  {ignore = true}
black =  {ignore = true}
blackbox =  {ignore = true}
blinker =  {ignore = true}
boto3 =  {ignore = true}
cchardet =  {ignore = true}
celery =  {ignore = true}
certifi =  {ignore = true}
certifi-yandex =  {ignore = true}
ciso8601 =  {ignore = true}
clickhouse-driver =  {ignore = true}
clize =  {ignore = true}
dill =  {ignore = true}
django =  {ignore = true}
dnspython =  {ignore = true}
docker =  {ignore = true}
flask =  {ignore = true}
flask-marshmallow =  {ignore = true}
flask-restx =  {ignore = true}
frozendict =  {ignore = true}
google-api-core =  {ignore = true}
google-auth =  {ignore = true}
googleapis-common-protos =  {ignore = true}
granular-settings =  {ignore = true}
graphviz =  {ignore = true}
grpcio =  {ignore = true}
grpcio-health-checking =  {ignore = true}
grpcio-reflection =  {ignore = true}
gunicorn =  {ignore = true}
hypercorn =  {ignore = true}
ipdb =  {ignore = true}
ipython =  {ignore = true}
jaeger-client =  {ignore = true}
jinja2 =  {ignore = true}
lz4 =  {ignore = true}
marshmallow =  {ignore = true}
marshmallow-enum =  {ignore = true}
marshmallow-oneofschema =  {ignore = true}
marshmallow-sqlalchemy =  {ignore = true}
more-itertools =  {ignore = true}
mypy =  {ignore = true}
mysqlclient =  {ignore = true}
openapi-core =  {ignore = true}
openpyxl =  {ignore = true}
oracledb =  {ignore = true}
pandas = {name = "pandas-stubs", version="1.5.3.230321"}
platformdirs =  {ignore = true}
poetry =  {ignore = true}
psycopg2 =  {ignore = true}
psycopg2-binary =  {name = "types-psycopg2"}
pyjwt =  {ignore = true}
pyodbc =  {ignore = true}
pytest =  {ignore = true}
pytest-asyncio =  {ignore = true}
python =  {ignore = true}
pyyaml =  {ignore = true}
quart =  {ignore = true}
raven =  {ignore = true}
responses =  {ignore = true}
ruff =  {ignore = true}
sentry-sdk =  {ignore = true}
service-identity =  {ignore = true}
shortuuid =  {ignore = true}
simplejson =  {ignore = true}
snowflake-connector-python =  {ignore = true}
snowflake-sqlalchemy =  {ignore = true}
sqlalchemy-stubs =  {ignore = true}
tomlkit =  {ignore = true}
tornado =  {ignore = true}
tvm2 =  {ignore = true}
tvmauth =  {ignore = true}
typeguard =  {ignore = true}
typing-extensions =  {ignore = true}
ujson =  {ignore = true}
uvloop =  {ignore = true}
uwsgi =  {ignore = true}
werkzeug =  {ignore = true}
xxhash =  {ignore = true}
yandex-passport-vault-client =  {ignore = true}
yarl =  {ignore = true}
ydb =  {ignore = true}
aiohttp-cors =  {ignore = true}
aioitertools =  {ignore = true}
aiosignal = {ignore = true}
amqp = {ignore = true}
aniso8601 = {ignore = true}
anyascii = {ignore = true}
argcomplete = {ignore = true}
asn1crypto = {ignore = true}
asttokens = {ignore = true}
backcall = {ignore = true}
bcrypt = {ignore = true}
billiard = {ignore = true}
botocore = {ignore = true}
build = {ignore = true}
"cachecontrol[filecache]" = {ignore = true}
cachetools = {ignore = true}
charset-normalizer = {ignore = true}
cleo = {ignore = true}
click = {ignore = true}
click-didyoumean = {ignore = true}
click-plugins = {ignore = true}
click-repl = {ignore = true}
configparser = {ignore = true}
crashtest = {ignore = true}
distlib = {ignore = true}
docutils = {ignore = true}
dulwich = {ignore = true}
enum-compat = {ignore = true}
et-xmlfile = {ignore = true}
exceptiongroup = {ignore = true}
executing = {ignore = true}
filelock = {ignore = true}
frozenlist = {ignore = true}
"google-api-core[grpc]" = {ignore = true}
google-cloud-bigquery = {ignore = true}
google-cloud-bigquery-storage = {ignore = true}
google-cloud-core = {ignore = true}
google-resumable-media = {ignore = true}
h11 = {ignore = true}
h2 = {ignore = true}
hiredis = {ignore = true}
hpack = {ignore = true}
hyperframe = {ignore = true}
idna = {ignore = true}
importlib-metadata = {ignore = true}
iniconfig = {ignore = true}
installer = {ignore = true}
isodate = {ignore = true}
itsdangerous = {ignore = true}
jaraco-classes = {ignore = true}
jedi = {ignore = true}
jsonschema = {ignore = true}
keyring = {ignore = true}
kombu = {ignore = true}
lazy-object-proxy = {ignore = true}
lockfile = {ignore = true}
mako = {ignore = true}
markupsafe = {ignore = true}
matplotlib-inline = {ignore = true}
msgpack = {ignore = true}
multidict = {ignore = true}
numpy = {ignore = true}
od = {ignore = true}
openapi-schema-validator = {ignore = true}
openapi-spec-validator = {ignore = true}
oscrypto = {ignore = true}
packaging = {ignore = true}
parse = {ignore = true}
parso = {ignore = true}
pathspec = {ignore = true}
pickleshare = {ignore = true}
pkginfo = {ignore = true}
poetry-core = {ignore = true}
poetry-plugin-export = {ignore = true}
priority = {ignore = true}
prompt-toolkit = {ignore = true}
ptyprocess = {ignore = true}
pure-eval = {ignore = true}
pyasn1 = {ignore = true}
pyasn1-modules = {ignore = true}
pycares = {ignore = true}
pycparser = {ignore = true}
pycryptodomex = {ignore = true}
pygments = {name = "types-Pygments", version="2.15.0.2"}
pynacl = {ignore = true}
pyproject-hooks = {ignore = true}
pyrsistent = {ignore = true}
python-dotenv = {ignore = true}
python-editor = {ignore = true}
rapidfuzz = {ignore = true}
"redis[hiredis]" = {ignore = true}
requests-toolbelt = {ignore = true}
retrying = {ignore = true}
rfc3339-validator = {ignore = true}
rsa = {ignore = true}
shellingham = {ignore = true}
sigtools = {ignore = true}
sqlalchemy-bigquery = {ignore = true}
sqlparse = {ignore = true}
stack-data = {ignore = true}
tenacity = {ignore = true}
threadloop = {ignore = true}
thrift = {ignore = true}
tomli = {ignore = true}
tonyg-rfc3339 = {ignore = true}
traitlets = {ignore = true}
trove-classifiers = {ignore = true}
types-pyyaml = {ignore = true}
vine = {ignore = true}
virtualenv = {ignore = true}
wcwidth = {ignore = true}
webencodings = {ignore = true}
websocket-client = {ignore = true}
wrapt = {ignore = true}
wsproto = {ignore = true}
yandex-ydb-core-protos = {ignore = true}
yenv = {ignore = true}
ylog = {ignore = true}
zipp = {ignore = true}
aiohttp = {ignore = true}
greenlet = {ignore = true}
jeepney = {ignore = true}
pywin32-ctypes = {ignore = true}
secretstorage = {ignore = true}
tzdata = {ignore = true}
xattr = {ignore = true}
appnope = {ignore = true}
