#syntax=docker/dockerfile:1.4
FROM bake_ctx_base_img

ENV APP_DIR="ops/bi_integration_tests"
ENV RUN_DEVHOST_TESTS=1

# Libs & metapkg
COPY --from=bake_ctx_src_lib / /src

# Sources copy
COPY /pyproject.toml /src/$APP_DIR/pyproject.toml
COPY /bi_integration_tests /src/$APP_DIR/bi_integration_tests
COPY /bi_integration_tests_tests /src/$APP_DIR/bi_integration_tests_tests

# We run integration tests inside doker with single dl_env=DLEnv.dynamic
# So we replace pytest dl_env parameter values list with [DLEnv.dynamic]
RUN perl -0777pi -e "s/(@pytest\.mark\.parametrize\s*\(\s*['\"]dl_env['\"].*?\[).*?]/\$1DLEnv.dynamic\]/sg" /src/$APP_DIR/bi_integration_tests_tests/test_*.py

WORKDIR /src/ops/ci
RUN poetry export --only bi_integration_tests --without-hashes --format=requirements.txt > requirements.txt
RUN pip install -r requirements.txt

ENTRYPOINT ["sh", "-c", "pytest -ra /src/$APP_DIR/bi_integration_tests_tests"]
