
[tool.poetry]
name = "yandex-bi-integration-tests"
version = "0.0.0"
description = ""
authors = ["Konstantin Chupin <kchupin@yandex-team.ru>"]
packages = [{include = "bi_integration_tests"}]
license = "MIT"


[tool.poetry.dependencies]
attrs = ">=22.2.0"
pandas = ">=1.5.3"
pytest-asyncio = ">=0.20.3"
python = ">=3.10, <3.12"
pyyaml = ">=5.3.1"
shortuuid = ">=1.0.11"
yandex-bi-cloud-integration = {path = "../../lib/bi_cloud_integration"}
yandex-bi-api-commons-ya-cloud = {path = "../../lib/bi_api_commons_ya_cloud"}
yandex-bi-dls-client = {path = "../../lib/bi_dls_client"}
yandex-bi-testing-ya = {path = "../../lib/bi_testing_ya"}
datalens-us-client = {path = "../../mainrepo/lib/dl_us_client"}
datalens-testing = {path = "../../mainrepo/lib/dl_testing"}

[tool.poetry.group.tests.dependencies]
pandas = ">=1.5.3"
pytest-asyncio = ">=0.20.3"
yandex-bi-dls-client = {path = "../../lib/bi_dls_client"}
yandex-bi-testing-ya = {path = "../../lib/bi_testing_ya"}
bi-defaults = {path = "../../lib/bi_defaults"}
datalens-testing = {path = "../../mainrepo/lib/dl_testing"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra"
testpaths = ["bi_integration_tests_tests"]
