# Include if exists
-include .env


include ../../tools/common_makefile.mk


# Create a development environment (start all the services required for testing the project)
devenv:
	docker-compose up --build


devenv-d:
	docker-compose up --build -d
