crash_events_fields = [
    {
        "name": "ym:cr2:crashes",
        "title": "Количество крэшей",
        "type": "integer",
        "description": None,
        "is_dim": False,
    },
    {
        "name": "ym:cr2:crashDevices",
        "title": "Количество устройств, на которых возникли аварийные остановки приложения",
        "type": "integer",
        "description": None,
        "is_dim": False,
    },
    {
        "name": "ym:cr2:crashesFreeDevicesPercentage",
        "title": "Процент устройств без крэшей",
        "type": "float",
        "description": None,
        "is_dim": False,
    },
    {
        "name": "ym:cr2:crashesDevicesPercentage",
        "title": "Процент устройств с крэшами",
        "type": "float",
        "description": None,
        "is_dim": False,
    },
    {
        "name": "ym:cr2:isRooted",
        "title": "Root-статус",
        "type": "string",
        "description": None,
        "is_dim": True,
    },
    {
        "description": "Идентификатор приложения",
        "is_dim": True,
        "name": "ym:cr2:apiKey",
        "title": "ID приложения",
        "type": "string",
    },
    {
        "name": "ym:cr2:UUID",
        "title": "UUID приложения",
        "type": "string",
        "description": None,
        "is_dim": True,
    },
    {
        "name": "ym:cr2:clientKitVersion",
        "title": "Версия SDK клиента",
        "type": "string",
        "description": None,
        "is_dim": True,
    },
    {
        "name": "ym:cr2:appVersion",
        "title": "Версия приложения",
        "type": "string",
        "description": None,
        "is_dim": True,
    },
    {
        "name": "ym:cr2:year",
        "title": "Год",
        "type": "string",
        "description": None,
        "is_dim": True,
    },
    {
        "name": "ym:cr2:regionCityName",
        "title": "Город",
        "type": "string",
        "description": "Название города, к которому принадлежат посетители сайта.",
        "is_dim": True,
    },
    {
        "name": "ym:cr2:date",
        "title": "Дата",
        "type": "date",
        "description": None,
        "is_dim": True,
    },
    {
        "name": "ym:cr2:startOfYear",
        "title": "Дата (год)",
        "type": "date",
        "description": "Дата и время в формате YYYY-MM-DD HH:mm:ss, округленное до начала года.",
        "is_dim": True,
    },
    {
        "name": "ym:cr2:startOfDekaminute",
        "title": "Дата (декаминута)",
        "type": "datetime",
        "description": "Дата и время в формате YYYY-MM-DD HH:mm:ss, округленное до начала 10-минутного интервала.",
        "is_dim": True,
    },
    {
        "name": "ym:cr2:startOfQuarter",
        "title": "Дата (квартал)",
        "type": "date",
        "description": "Дата и время в формате YYYY-MM-DD HH:mm:ss, округленное до начала квартала.",
        "is_dim": True,
    },
    {
        "name": "ym:cr2:startOfMonth",
        "title": "Дата (месяц)",
        "type": "date",
        "description": "Дата и время в формате YYYY-MM-DD HH:mm:ss, округленное до начала месяца.",
        "is_dim": True,
    },
    {
        "name": "ym:cr2:startOfMinute",
        "title": "Дата (минута)",
        "type": "datetime",
        "description": "Дата и время в формате YYYY-MM-DD HH:mm:ss, округленное до начала минуты.",
        "is_dim": True,
    },
    {
        "name": "ym:cr2:startOfHour",
        "title": "Дата (час)",
        "type": "datetime",
        "description": "Дата и время в формате YYYY-MM-DD HH:mm:ss, округленное до начала часа.",
        "is_dim": True,
    },
    {
        "name": "ym:cr2:dekaminute",
        "title": "Декаминута",
        "type": "string",
        "description": None,
        "is_dim": True,
    },
    {
        "name": "ym:cr2:dayOfMonth",
        "title": "День месяца",
        "type": "string",
        "description": None,
        "is_dim": True,
    },
    {
        "name": "ym:cr2:dayOfWeekName",
        "title": "День недели",
        "type": "string",
        "description": None,
        "is_dim": True,
    },
    {
        "name": "ym:cr2:crashGroupName",
        "title": "Идентификатор группы крэшей",
        "type": "string",
        "description": None,
        "is_dim": True,
    },
    {
        "name": "ym:cr2:appID",
        "title": "Идентификатор приложения (в магазине приложений)",
        "type": "string",
        "description": None,
        "is_dim": True,
    },
    {
        "name": "ym:cr2:googleAID",
        "title": "Идентификатор рекламы Google",
        "type": "string",
        "description": None,
        "is_dim": True,
    },
    {
        "name": "ym:cr2:iosIFA",
        "title": "Идентификатор рекламы на iOS",
        "type": "string",
        "description": None,
        "is_dim": True,
    },
    {
        "name": "ym:cr2:deviceID",
        "title": "Идентификатор, полученный средствами системного API или выдаваемый Яндексом",
        "type": "string",
        "description": None,
        "is_dim": True,
    },
    {
        "name": "ym:cr2:crashMethodName",
        "title": "Имя метода исходного кода, в котором произошёл крэш",
        "type": "string",
        "description": None,
        "is_dim": True,
    },
    {
        "name": "ym:cr2:crashBinaryName",
        "title": "Имя образа, в котором произошёл крэш",
        "type": "string",
        "description": None,
        "is_dim": True,
    },
    {
        "name": "ym:cr2:crashFileName",
        "title": "Имя файла исходного кода, в котором произошёл крэш",
        "type": "string",
        "description": None,
        "is_dim": True,
    },
    {
        "name": "ym:cr2:clientKitVersionDetails",
        "title": "Информация о версии SDK",
        "type": "string",
        "description": None,
        "is_dim": True,
    },
    {
        "name": "ym:cr2:osMajorVersionInfoName",
        "title": "Мажорная версия ОС",
        "type": "string",
        "description": None,
        "is_dim": True,
    },
    {
        "name": "ym:cr2:month",
        "title": "Месяц",
        "type": "string",
        "description": None,
        "is_dim": True,
    },
    {
        "name": "ym:cr2:minute",
        "title": "Минута",
        "type": "string",
        "description": None,
        "is_dim": True,
    },
    {
        "name": "ym:cr2:mobileDeviceModel",
        "title": "Модель",
        "type": "string",
        "description": None,
        "is_dim": True,
    },
    {
        "name": "ym:cr2:mpcName",
        "title": "Название сотового оператора на основе кода сотового оператора (MPC)",
        "type": "string",
        "description": None,
        "is_dim": True,
    },
    {
        "name": "ym:cr2:mccName",
        "title": "Название страны на основе мобильного кода страны оператора (MCC)",
        "type": "string",
        "description": None,
        "is_dim": True,
    },
    {
        "name": "ym:cr2:buildNumber",
        "title": "Номер сборки приложения",
        "type": "string",
        "description": None,
        "is_dim": True,
    },
    {
        "name": "ym:cr2:crashSourceLine",
        "title": "Номер строки исходного кода, в котором произошёл крэш",
        "type": "string",
        "description": None,
        "is_dim": True,
    },
    {
        "name": "ym:cr2:regionAreaName",
        "title": "Область",
        "type": "string",
        "description": "Области, в которых находятся посетители сайта.",
        "is_dim": True,
    },
    {
        "name": "ym:cr2:operatingSystemInfoName",
        "title": "Операционная система",
        "type": "string",
        "description": None,
        "is_dim": True,
    },
    {
        "name": "ym:cr2:limitAdTracking",
        "title": "Признак ограничения рекламного трекинга",
        "type": "string",
        "description": 'Возможные значения: "yes", "no", "undefined".',
        "is_dim": True,
    },
    {
        "name": "ym:cr2:mobileDeviceBranding",
        "title": "Производитель",
        "type": "string",
        "description": None,
        "is_dim": True,
    },
    {
        "name": "ym:cr2:profileOrigin",
        "title": "Профиль",
        "type": "string",
        "description": None,
        "is_dim": True,
    },
    {
        "name": "ym:cr2:screenResolutionDetailed",
        "title": "Разрешение (подробно)",
        "type": "string",
        "description": 'Подробная информация о разрешении экрана. Например, "2560x1440 px (xxxhdpi)".',
        "is_dim": True,
    },
    {
        "name": "ym:cr2:regionCountryName",
        "title": "Страна",
        "type": "string",
        "description": "Название страны, к которой принадлежат посетители сайта.",
        "is_dim": True,
    },
    {
        "name": "ym:cr2:connectionType",
        "title": "Тип подключения: Cellular или Wi-Fi",
        "type": "string",
        "description": None,
        "is_dim": True,
    },
    {
        "name": "ym:cr2:networkType",
        "title": "Тип сети: 3G, EDGE и т.д.",
        "type": "string",
        "description": None,
        "is_dim": True,
    },
    {
        "name": "ym:cr2:deviceTypeName",
        "title": "Тип устройства",
        "type": "string",
        "description": None,
        "is_dim": True,
    },
    {
        "name": "ym:cr2:device",
        "title": "Устройство",
        "type": "string",
        "description": None,
        "is_dim": True,
    },
    {
        "name": "ym:cr2:hourMinute",
        "title": "Час и минута",
        "type": "string",
        "description": None,
        "is_dim": True,
    },
    {
        "name": "ym:cr2:locale",
        "title": "Язык интерфейса",
        "type": "string",
        "description": None,
        "is_dim": True,
    },
]
