FROM cr.yandex/crpsufj53lhl0via9iam/united-storage:latest

# ???
ENV DEV_MODE="true"
ENV SQL_DEBUG="true"
ENV MULTITENANT="false"
ENV DEBUG="knex:*"
ENV APP_INSTALLATION="yandex-team"
ENV APP_ENV="preprod"
