#!/usr/bin/env sh

set -eu

HTTP_BIND_PORT="8080"
HTTP_BIND_ADDR="0.0.0.0"

if [ -f "/proc/net/if_inet6" ] || [ "${BISYS_USE_IPV6:-0}" = "1" ]; then
  HTTP_BIND_ADDR="[::]"
fi

BI_API_UWSGI_WORKERS_COUNT="${BI_API_UWSGI_WORKERS_COUNT:-40}"

# It is also set in the ini file, but that might not work in some cases.
UWSGI_STATS=/tmp/uwsgi_stats.sock
HTTP_BIND="${HTTP_BIND_ADDR}:${HTTP_BIND_PORT}"

export BI_API_UWSGI_WORKERS_COUNT UWSGI_STATS HTTP_BIND
exec uwsgi --ini=/code/app/uwsgi/uwsgi-dl-api.ini
