DROP TABLE IF EXISTS sample;
CREATE TABLE sample (
    [Category] VARCHAR(255),
    [City] VARCHAR(255),
    [Country] VARCHAR(255),
    [Customer ID] VARCHAR(255),
    [Customer Name] VARCHAR(255),
    [Discount] FLOAT,
    [Order Date] DATE,
    [Order ID] VARCHAR(255),
    [Postal Code] INTEGER,
    [Product ID] VARCHAR(255),
    [Product Name] VARCHAR(255),
    [Profit] FLOAT,
    [Quantity] INTEGER,
    [Region] VARCHAR(255),
    [Row ID] INTEGER PRIMARY KEY,
    [Sales] FLOAT,
    [Segment] VARCHAR(255),
    [Ship Date] DATE,
    [Ship Mode] VARCHAR(255),
    [State] VARCHAR(255),
    [Sub-Category] VARCHAR(255),
    INDEX order_date_idx ([Order Date])
);
