# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yandex/cloud/iam/v1/role.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1eyandex/cloud/iam/v1/role.proto\x12\x13yandex.cloud.iam.v1\"\'\n\x04Role\x12\n\n\x02id\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\tB^\n\x17yandex.cloud.api.iam.v1ZCa.yandex-team.ru/cloud/bitbucket/public-api/yandex/cloud/iam/v1;iamb\x06proto3')



_ROLE = DESCRIPTOR.message_types_by_name['Role']
Role = _reflection.GeneratedProtocolMessageType('Role', (_message.Message,), {
  'DESCRIPTOR' : _ROLE,
  '__module__' : 'yandex.cloud.iam.v1.role_pb2'
  # @@protoc_insertion_point(class_scope:yandex.cloud.iam.v1.Role)
  })
_sym_db.RegisterMessage(Role)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\027yandex.cloud.api.iam.v1ZCa.yandex-team.ru/cloud/bitbucket/public-api/yandex/cloud/iam/v1;iam'
  _ROLE._serialized_start=55
  _ROLE._serialized_end=94
# @@protoc_insertion_point(module_scope)
