# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yandex/cloud/iam/v1/user_account_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from yandex.cloud.iam.v1 import user_account_pb2 as yandex_dot_cloud_dot_iam_dot_v1_dot_user__account__pb2
from yandex.cloud import validation_pb2 as yandex_dot_cloud_dot_validation__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n.yandex/cloud/iam/v1/user_account_service.proto\x12\x13yandex.cloud.iam.v1\x1a\x1cgoogle/api/annotations.proto\x1a&yandex/cloud/iam/v1/user_account.proto\x1a\x1dyandex/cloud/validation.proto\">\n\x15GetUserAccountRequest\x12%\n\x0fuser_account_id\x18\x01 \x01(\tB\x0c\xe8\xc7\x31\x01\x8a\xc8\x31\x04<=502\x9a\x01\n\x12UserAccountService\x12\x83\x01\n\x03Get\x12*.yandex.cloud.iam.v1.GetUserAccountRequest\x1a .yandex.cloud.iam.v1.UserAccount\".\x82\xd3\xe4\x93\x02(\x12&/iam/v1/userAccounts/{user_account_id}B^\n\x17yandex.cloud.api.iam.v1ZCa.yandex-team.ru/cloud/bitbucket/public-api/yandex/cloud/iam/v1;iamb\x06proto3')



_GETUSERACCOUNTREQUEST = DESCRIPTOR.message_types_by_name['GetUserAccountRequest']
GetUserAccountRequest = _reflection.GeneratedProtocolMessageType('GetUserAccountRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETUSERACCOUNTREQUEST,
  '__module__' : 'yandex.cloud.iam.v1.user_account_service_pb2'
  # @@protoc_insertion_point(class_scope:yandex.cloud.iam.v1.GetUserAccountRequest)
  })
_sym_db.RegisterMessage(GetUserAccountRequest)

_USERACCOUNTSERVICE = DESCRIPTOR.services_by_name['UserAccountService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\027yandex.cloud.api.iam.v1ZCa.yandex-team.ru/cloud/bitbucket/public-api/yandex/cloud/iam/v1;iam'
  _GETUSERACCOUNTREQUEST.fields_by_name['user_account_id']._options = None
  _GETUSERACCOUNTREQUEST.fields_by_name['user_account_id']._serialized_options = b'\350\3071\001\212\3101\004<=50'
  _USERACCOUNTSERVICE.methods_by_name['Get']._options = None
  _USERACCOUNTSERVICE.methods_by_name['Get']._serialized_options = b'\202\323\344\223\002(\022&/iam/v1/userAccounts/{user_account_id}'
  _GETUSERACCOUNTREQUEST._serialized_start=172
  _GETUSERACCOUNTREQUEST._serialized_end=234
  _USERACCOUNTSERVICE._serialized_start=237
  _USERACCOUNTSERVICE._serialized_end=391
# @@protoc_insertion_point(module_scope)
