---
network:
  master-addr:     logbroker.yandex.net
  proto:           pq
  tvm-client-id:   {{ pillar['PUSH_CLIENT_TVM_ID'] if 'PUSH_CLIENT_TVM_ID' in pillar else pillar['TVM_APP_ID'] }}
  tvm-server-id:   2001059
  tvm-secret-file: "/etc/secrets/TVM_SECRET"

logger:
  mode: file
  file: /var/spool/push-client/watcher.log
  level: 6
  telemetry_interval: -1
  remote: 0

watcher:
  state: /var/spool/push-client

files:
  - name: /var/log/fluent/access_log.main-app*.log
    topic: {{ pillar['PUSH_CLIENT_NODEJS_TOPIC'] }}
  - name: /var/log/fluent/error_log.main-app*.log
    topic: {{ pillar['PUSH_CLIENT_ERROR_TOPIC'] }}
