name: 'Commitlint'
description: 'Commitlints input according to config'
inputs:
  input:
    description: 'The input to commitlint'
    required: true
  config_path:
    description: 'The path to the commitlint config'
    required: true
runs:
  using: composite

  steps:
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
          node-version: '14'

    - name: Install Dependencies
      shell: bash
      run: |
          npm install conventional-changelog-conventionalcommits
          npm install commitlint@latest

    - name: Lint Commit
      shell: bash
      run: |
          echo "${{ inputs.input }}" | npx commitlint --config ${{ inputs.config_path }}
