name: "Commitlint"
description: "Commitlints input according to config"
inputs:
  input:
    description: "The input to commitlint"
    required: true
runs:
  using: composite

  steps:
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: "22"

    - name: Install Dependencies
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        npm ci

    - name: Lint Commit
      shell: bash
      working-directory: ${{ github.action_path }}
      run: |
        echo "${{ inputs.input }}" | npx commitlint --config ${{ github.action_path }}/src/commitlint.config.js
