from dl_connector_bundle_chs3.chs3_gsheets.formula.utils import clickhouse_funcs_for_gsheets_v2_dialect
from dl_connector_clickhouse.formula.definitions.functions_aggregation import DEFINITIONS_AGG as CH_DEFINITIONS_AGG


DEFINITIONS_AGG = clickhouse_funcs_for_gsheets_v2_dialect(CH_DEFINITIONS_AGG)
