from dl_connector_bundle_chs3.chs3_gsheets.formula.utils import clickhouse_funcs_for_gsheets_v2_dialect
from dl_connector_clickhouse.formula.definitions.operators_ternary import DEFINITIONS_TERNARY as CH_DEFINITIONS_TERNARY


DEFINITIONS_TERNARY = clickhouse_funcs_for_gsheets_v2_dialect(CH_DEFINITIONS_TERNARY)
