{{- define "depl-bi_api" }}
---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: dataset-api
  labels:
    app: dataset-api

spec:
  replicas: {{ .Values.scaling.dataset_api.desired | default 1 }}
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.scaling.dataset_api.max_surge }}
      maxUnavailable: {{ .Values.scaling.dataset_api.max_unavailable }}
  selector:
    matchLabels:
      app: dataset-api
  template:
    metadata:
      labels:
        app: dataset-api
      annotations:
        injector.tumblr.com/request: {{ ternary (ternary "jaeger,nginx_v2" "jaeger,nginx" (eq .Values.enabled_features.rootless_mode true)) "jaeger-agent" (eq .Values.tls_to_backends true) | quote }}
    spec:
      affinity:
        {{- include "pod_affinity-preferred_rqe" . | indent 8}}
      containers:
        - name: main
          image: "{{ .Values.docker_images_info.control_api.repo }}:{{ .Values.docker_images_info.bi_api.tag }}"
          env:
            {{- include "secrets-common" . | indent 12}}
            {{- include "secrets-bi_api" . | indent 12}}
            {{- include "secrets-bi_api_nonpublic" . | indent 12}}
            {{- include "secrets_us_master_token" . | indent 12}}
            - name: CONNECTOR_AVAILABILITY_VISIBLE
              value: "{{- join "," .Values.visible_connectors }}"
            {{ if .Values.enabled_features.service_connectors }}
              {{- include "secrets-service_connectors" . | indent 12}}
            {{ end }}
            {{ if .Values.enabled_features.frozen_connectors }}
              {{- include "env-vars_frozen-connectors" . | indent 12}}
            {{ end }}
            {{ if .Values.apps_to_run.file_uploader }}
              {{- include "secrets-file_uploader" . | indent 12}}
            {{ end }}
            {{- include "env_vars-nginx" . | indent 12 }}
            {{- include "env_vars-bi_api" . | indent 12 }}
            {{- range $var := .Values.connector_forms_env }}
            - name: {{ $var.name }}
              value: {{ $var.value | quote }}
            {{- end }}
            {{- include "env_vars-mdb_domains" . | indent 12 }}
            {{- include "env_vars-conn_chyt" . | indent 12}}
            {{- include "env_vars-yenv" . | indent 12 }}
            {{- include "env_vars-common" . | indent 12 }}
            {{- include "env_vars-data-apps" . | indent 12 }}
            {{ if .Values.apps_to_run.file_uploader }}
              {{- include "env_vars-file_uploader_client" . | indent 12 }}
              {{- $redis_misc_targs := dict "Values" .Values "env_prefix" "REDIS_ARQ" "redis_settings" .Values.redis_misc }}
              {{- include "env_vars-redis" $redis_misc_targs | indent 12 }}
              {{- include "env_vars-file_uploader_data_access" . | indent 12 }}
            - name: REDIS_ARQ_DB
              value: "7"
            {{ end }}
            {{ if not .Values.apps_to_run.file_uploader }}
            # https://st.yandex-team.ru/BI-4799
            - name: CONNECTORS_GSHEETS_V2_BUCKET
              value: "TBD"
            - name: CONNECTORS_GSHEETS_V2_HOST
              value: "TBD"
            - name: CONNECTORS_GSHEETS_V2_USERNAME
              value: "TBD"
            - name: CONNECTORS_GSHEETS_V2_S3_ENDPOINT
              value: "TBD"
            - name: CONNECTORS_FILE_BUCKET
              value: "TBD"
            - name: CONNECTORS_FILE_HOST
              value: "TBD"
            - name: CONNECTORS_FILE_USERNAME
              value: "TBD"
            - name: CONNECTORS_FILE_S3_ENDPOINT
              value: "TBD"
            {{ end }}
            - name: LAUNCH_TARGET
              value: "sync_api"
            - name: NGINX_SERVER_NAME
              value: "dataset-api"
            - name: YC_SA_CREDS_MODE
              value: "env_key_data"
            - name: USE_RQE_PUBLIC
              value: "1"
            {{- $sentry_targs := dict "sentry_enabled" .Values.sentry_enabled "sentry_dsn" .Values.sentry_dsns.dataset_api }}
            {{- include "env_vars-sentry" $sentry_targs | indent 12 }}
            - name: BI_API_UWSGI_WORKERS_COUNT
              value: {{ .Values.dataset_api_num_of_workers | quote }}
            - name: START_COMPENG # disable internal COMPENG TODO: remove
              value: "0"
            - name: SNOWFLAKE_CABUNDLE_PATH
              value: "/usr/lib/python3/dist-packages/certifi/cacert.pem"
            {{ if .Values.enabled_features.network_policy}}
            {{- include "env_vars-rqe-configuration" . | indent 12 }}
            {{ end }}
            - name: USE_IAM_SUBJECT_RESOLVER  # TODO: delete after control_api is updated
              value: "1"
          resources:
            requests:
              cpu: {{ .Values.app_resources.dataset_api.cpu }}
              memory: {{.Values.app_resources.dataset_api.ram}}
          readinessProbe:
            httpGet:
              port: {{ ternary .Values.app_tls_port (ternary 8080 80 (eq .Values.rootless_mode true)) (eq .Values.tls_to_backends true) }}
              scheme: {{ ternary "HTTPS" "HTTP" (eq .Values.tls_to_backends true) }}
              path: "/ping"
            initialDelaySeconds: 60
            periodSeconds: 10
          securityContext:
            {{- include "security-context-data-api" . | indent 12}}
          volumeMounts:
            {{- include "cert-bundle_vol-mount" . | indent 12 }}
        {{ if .Values.enabled_features.network_policy}}
        - name: rqe-int-sync
          image: "{{ .Values.docker_images_info.rqe_int_sync.repo }}:{{ .Values.docker_images_info.bi_api.tag }}"
          env:
            {{- include "env_vars-yenv" . | indent 12 }}
            {{- include "env_vars-common" . | indent 12 }}
            {{- include "env_vars-rqe" . | indent 12 }}
            {{- include "secrets-rqe" . | indent 12}}
            - name: RQE_INT_SYNC_PORT
              value: "9874"
            - name: BISYS_USE_IPV6
              value: "0"
            - name: RQE_INT_SYNC_WORKERS_COUNT
              value: "4"
            {{- include "env_vars-sentry" $sentry_targs | indent 12 }}
          readinessProbe:
            exec:
              command:
              - curl
              - http://127.0.0.1:9874/ping
            initialDelaySeconds: 60
            periodSeconds: 10
          startupProbe:
            exec:
              command:
              - curl
              - http://127.0.0.1:9874/ping
            failureThreshold: 30
            periodSeconds: 10
          securityContext:
            {{- include "security-context-data-api" . | indent 12 }}
          volumeMounts:
            {{- include "cert-internal_vol-mount" . | indent 12 }}
        {{ end }}
      volumes:
        - name: init-scripts
          configMap:
            name: "{{ .Release.Name }}-init-scripts"
        - name: app-secrets
          emptyDir: {}
        {{- include "cert-internal_vol" . | indent 8 }}
        {{- include "cert-bundle_vol" . | indent 8 }}
      tolerations:
        - key: "{{ .Values.node_selection_options.taint_toleration_key }}"
          operator: "Equal"
          value: "{{ .Values.node_selection_options.dataset_api.taint_toleration }}"
          effect: "NoSchedule"

---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: dataset-data-api
  labels:
    app: dataset-data-api

spec:
  replicas: {{ .Values.scaling.dataset_data_api.desired | default 1 }}
  strategy:
    rollingUpdate:
      maxSurge: {{ .Values.scaling.dataset_data_api.max_surge }}
      maxUnavailable: {{ .Values.scaling.dataset_data_api.max_unavailable }}
  selector:
    matchLabels:
      app: dataset-data-api
  template:
    metadata:
      labels:
        app: dataset-data-api
      annotations:
        injector.tumblr.com/request: {{ ternary (ternary "jaeger,nginx_v2" "jaeger,nginx" (eq .Values.enabled_features.rootless_mode true)) "jaeger-agent" (eq .Values.tls_to_backends true) | quote }}
    spec:
      affinity:
        {{- include "pod_affinity-preferred_rqe" . | indent 8}}
      containers:
        - name: main
          image: "{{ .Values.docker_images_info.data_api.repo }}:{{ .Values.docker_images_info.bi_api.tag }}"
          env:
            {{- include "secrets-common" . | indent 12}}
            {{- include "secrets_us_master_token" . | indent 12}}
            {{- include "secrets-bi_api" . | indent 12}}
            {{- include "secrets-bi_api_nonpublic" . | indent 12}}
            {{ if .Values.enabled_features.service_connectors }}
              {{- include "secrets-service_connectors" . | indent 12}}
            {{ end }}
            {{ if .Values.enabled_features.frozen_connectors }}
              {{- include "env-vars_frozen-connectors" . | indent 12}}
            {{ end }}
            {{ if .Values.apps_to_run.file_uploader }}
              {{- include "secrets-file_uploader" . | indent 12}}
              {{- include "env_vars-file_uploader_data_access" . | indent 12}}
              {{- include "env_vars-file_uploader_client" . | indent 12 }}
            {{ end }}
            {{ if not .Values.apps_to_run.file_uploader }}
            # https://st.yandex-team.ru/BI-4799
            - name: CONNECTORS_GSHEETS_V2_BUCKET
              value: "TBD"
            - name: CONNECTORS_GSHEETS_V2_HOST
              value: "TBD"
            - name: CONNECTORS_GSHEETS_V2_USERNAME
              value: "TBD"
            - name: CONNECTORS_GSHEETS_V2_S3_ENDPOINT
              value: "TBD"
            - name: CONNECTORS_FILE_BUCKET
              value: "TBD"
            - name: CONNECTORS_FILE_HOST
              value: "TBD"
            - name: CONNECTORS_FILE_USERNAME
              value: "TBD"
            - name: CONNECTORS_FILE_S3_ENDPOINT
              value: "TBD"
            {{ end }}
            {{- include "env_vars-nginx" . | indent 12 }}
            {{- include "env_vars-yenv" . | indent 12 }}
            {{- include "env_vars-common" . | indent 12 }}
            {{- include "env_vars-data-apps" . | indent 12 }}
            {{- include "env_vars-bi_api" . | indent 12 }}
            {{- include "env_vars-mdb_domains" . | indent 12 }}
            {{- include "env_vars-conn_chyt" . | indent 12}}
            - name: LAUNCH_TARGET
              value: "async_api"
            - name: START_COMPENG # disable internal COMPENG TODO: remove
              value: "0"
            - name: BI_COMPENG_PG_URL
              value: "postgresql://postgres@localhost:5432/postgres"
            - name: YC_SA_CREDS_MODE
              value: "env_key_data"
            - name: NGINX_SERVER_NAME
              value: "dataset-data-api"
            {{ if .Values.enabled_features.caches }}
              {{- $redis_caches_targs := dict "Values" .Values "env_prefix" "CACHES_REDIS" "redis_settings" .Values.redis_caches }}
              {{- include "env_vars-redis" $redis_caches_targs | indent 12 }}
            - name: CACHES_REDIS_DB
              value: "0"
            {{ end }}
            {{ if .Values.enabled_features.mutation_caches }}
              {{- $redis_caches_targs := dict "Values" .Values "env_prefix" "MUTATIONS_REDIS" "redis_settings" .Values.redis_caches }}
              {{- include "env_vars-redis" $redis_caches_targs | indent 12 }}
            - name: MUTATIONS_REDIS_DB
              value: "1"
            {{ end }}
            {{- $sentry_targs := dict "sentry_enabled" .Values.sentry_enabled "sentry_dsn" .Values.sentry_dsns.dataset_data_api }}
            {{- include "env_vars-sentry" $sentry_targs | indent 12 }}
            {{ if .Values.connector_settings.monitoring }}
            {{- include "env_vars-conn_monitoring" . | indent 12 }}
            {{ end }}
            {{ if .Values.enabled_features.network_policy}}
            {{- include "env_vars-rqe-configuration" . | indent 12 }}
            {{ end }}
          resources:
            requests:
              cpu: {{ .Values.app_resources.dataset_data_api.cpu }}
              memory: {{.Values.app_resources.dataset_data_api.ram}}
          readinessProbe:
            httpGet:
              port: {{ ternary .Values.app_tls_port 80 (eq .Values.tls_to_backends true) }}
              scheme: {{ ternary "HTTPS" "HTTP" (eq .Values.tls_to_backends true) }}
              path: "/ping"
            initialDelaySeconds: 60
            periodSeconds: 10
          startupProbe:
            httpGet:
              port: {{ ternary .Values.app_tls_port 80 (eq .Values.tls_to_backends true) }}
              scheme: {{ ternary "HTTPS" "HTTP" (eq .Values.tls_to_backends true) }}
              path: "/ping_ready"
            failureThreshold: 30
            periodSeconds: 10
          securityContext:
            {{- include "security-context-data-api" . | indent 12}}
          volumeMounts:
            {{- include "cert-bundle_vol-mount" . | indent 12 }}
        - name: postgres
          image: "{{ .Values.docker_images_info.docker_repo }}/postgres:12"
          imagePullPolicy: "IfNotPresent"
          command: ["/etc/compeng_init.sh"]
          ports:
            - containerPort: 5432
          securityContext:
            {{- include "security-context-postgres" . | indent 12}}
          volumeMounts:
            - mountPath: /etc/postgresql/12/main
              name: compeng-config
            - mountPath: /etc/compeng_init.sh
              subPath: compeng_init.sh
              name: compeng-init
        {{ if .Values.enabled_features.network_policy}}
        - name: rqe-int-sync
          image: "{{ .Values.docker_images_info.rqe_int_sync.repo }}:{{ .Values.docker_images_info.bi_api.tag }}"
          env:
            {{- include "env_vars-yenv" . | indent 12 }}
            {{- include "env_vars-common" . | indent 12 }}
            {{- include "env_vars-rqe" . | indent 12 }}
            {{- include "secrets-rqe" . | indent 12}}
            - name: RQE_INT_SYNC_PORT
              value: "9874"
            - name: BISYS_USE_IPV6
              value: "0"
            - name: RQE_INT_SYNC_WORKERS_COUNT
              value: "4"
            {{- include "env_vars-sentry" $sentry_targs | indent 12 }}
          readinessProbe:
            exec:
              command:
              - curl
              - http://127.0.0.1:9874/ping
            initialDelaySeconds: 60
            periodSeconds: 10
          startupProbe:
            exec:
              command:
              - curl
              - http://127.0.0.1:9874/ping
            failureThreshold: 30
            periodSeconds: 10
          securityContext:
            {{- include "security-context-common" . | indent 12}}
          volumeMounts:
            {{- include "cert-internal_vol-mount" . | indent 12 }}
        {{ end }}
      volumes:
        - name: init-scripts
          configMap:
            name: "{{ .Release.Name }}-init-scripts"
        - name: app-secrets
          emptyDir: {}
        - name: compeng-config
          configMap:
            name: compeng-config
        - name: compeng-init
          configMap:
            name: compeng-init
            defaultMode: 0777
        {{- include "cert-internal_vol" . | indent 8 }}
        {{- include "cert-bundle_vol" . | indent 8 }}
      tolerations:
        - key: "{{ .Values.node_selection_options.taint_toleration_key }}"
          operator: "Equal"
          value: "{{ .Values.node_selection_options.dataset_data_api.taint_toleration }}"
          effect: "NoSchedule"
{{ end }}
