{{- define "secrets-bi_api" }}
{{ if .Values.enabled_features.caches }}
- name: CACHES_REDIS_PASSWORD
  valueFrom:
    secretKeyRef:
      name: redis-passwords
      key: REDIS_CACHES_PASSWORD

- name: MUTATIONS_REDIS_PASSWORD
  valueFrom:
    secretKeyRef:
      name: redis-passwords
      key: REDIS_CACHES_PASSWORD
{{ end }}

{{ if .Values.apps_to_run.file_uploader }}
- name: REDIS_ARQ_PASSWORD
  valueFrom:
    secretKeyRef:
      name: redis-passwords
      key: REDIS_MISC_PASSWORD
{{ end }}

- name: YC_SA_CREDS_KEY_DATA
  valueFrom:
    secretKeyRef:
      name: service-account-secrets
      key: bi_api_sa_key_data

{{ if .Values.enabled_features.rqe_caches }}
- name: RQE_CACHES_REDIS_PASSWORD
  valueFrom:
    secretKeyRef:
      name: bi-api-secrets
      key: REDIS_RQE_CACHES_PASSWORD
{{ end }}
{{ end }}
