{{- define "secrets-rqe" }}
- name: RQE_SECRET_KEY
  valueFrom:
    secretKeyRef:
      name: common-secrets
      key: EXT_QUERY_EXECUTER_SECRET_KEY

{{ if .Values.enabled_features.rqe_caches }}
- name: RQE_CACHES_REDIS_PASSWORD
  valueFrom:
    secretKeyRef:
      name: bi-api-secrets
      key: REDIS_RQE_CACHES_PASSWORD
{{ end }}
{{ end }}
