---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: common-secrets
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: secret-store
    kind: SecretStore
  target:
    name: common-secrets
  data:
    - secretKey: DL_CRY_KEY_VAL_ID_{{ .Values.crypto_key_name }}_{{ .Values.crypto_key_version }}
      remoteRef:
        key: {{ .Values.secrets.bi_backend_common_secret_id }}
        property: CRYPTO_KEY_{{ .Values.crypto_key_version }}
    - secretKey: DL_CRY_KEY_VAL_ID_{{ .Values.crypto_key_name }}_{{ .Values.crypto_key_version_old }}
      remoteRef:
        key: {{ .Values.secrets.bi_backend_common_secret_id }}
        property: CRYPTO_KEY_{{ .Values.crypto_key_version_old }}
    - secretKey: US_MASTER_TOKEN
      remoteRef:
        key: {{ .Values.secrets.bi_backend_common_secret_id }}
        property: US_MASTER_TOKEN
    - secretKey: IAM_INTERACTION_SERVICE_ACCOUNT_KEY_DATA
      remoteRef:
        key: {{ .Values.secrets.bi_backend_common_secret_id }}
        property: IAM_INTERACTION_SERVICE_ACCOUNT_KEY_DATA
    - secretKey: LOGS_CH_PASSWORD
      remoteRef:
        key: {{ .Values.secrets.bi_backend_common_secret_id }}
        property: LOGS_CH_PASSWORD
    - secretKey: EXT_QUERY_EXECUTER_SECRET_KEY
      remoteRef:
        key: {{ .Values.secrets.bi_backend_common_secret_id }}
        property: EXT_QUERY_EXECUTER_SECRET_KEY
    - secretKey: TVM_INFO
      remoteRef:
        key: {{ .Values.secrets.bi_backend_common_secret_id }}
        property: TVM_INFO
    - secretKey: TVM_SECRET
      remoteRef:
        key: {{ .Values.secrets.bi_backend_common_secret_id }}
        property: TVM_SECRET

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bi-api-secrets
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: secret-store
    kind: SecretStore
  target:
    name: bi-api-secrets
  data:
    - secretKey: DLS_API_KEY
      remoteRef:
        key: {{ .Values.secrets.bi_backend_bi_api_secret_id }}
        property: DLS_API_KEY
    - secretKey: US_PUBLIC_API_TOKEN
      remoteRef:
        key: {{ .Values.secrets.bi_backend_bi_api_secret_id }}
        property: US_PUBLIC_API_TOKEN
    - secretKey: PUBLIC_API_KEY
      remoteRef:
        key: {{ .Values.secrets.bi_backend_bi_api_secret_id }}
        property: PUBLIC_API_KEY
    - secretKey: REDIS_RQE_CACHES_PASSWORD
      remoteRef:
        key: {{ .Values.secrets.bi_backend_bi_api_secret_id }}
        property: REDIS_RQE_CACHES_PASSWORD

{{ if .Values.enabled_features.service_connectors }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: service-connectors-secrets
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: secret-store
    kind: SecretStore
  target:
    name: service-connectors-secrets
  data:
    - secretKey: YA_MUSIC_PODCAST_STATS_PASSWORD
      remoteRef:
        key: {{ .Values.secrets.bi_backend_service_connectors_secret_id }}
        property: YA_MUSIC_PODCAST_STATS_PASSWORD
    - secretKey: MOYSKLAD_DB_USER_PASSWORD
      remoteRef:
        key: {{ .Values.secrets.bi_backend_service_connectors_secret_id }}
        property: MOYSKLAD_DB_USER_PASSWORD
    - secretKey: MOYSKLAD_PARTNER_KEYS
      remoteRef:
        key: {{ .Values.secrets.bi_backend_service_connectors_secret_id }}
        property: MOYSKLAD_PARTNER_KEYS
    - secretKey: EQUEO_DB_USER_PASSWORD
      remoteRef:
        key: {{ .Values.secrets.bi_backend_service_connectors_secret_id }}
        property: EQUEO_DB_USER_PASSWORD
    - secretKey: EQUEO_PARTNER_KEYS
      remoteRef:
        key: {{ .Values.secrets.bi_backend_service_connectors_secret_id }}
        property: EQUEO_PARTNER_KEYS
    - secretKey: KONTUR_MARKET_DB_USER_PASSWORD
      remoteRef:
        key: {{ .Values.secrets.bi_backend_service_connectors_secret_id }}
        property: KONTUR_MARKET_DB_USER_PASSWORD
    - secretKey: KONTUR_MARKET_PARTNER_KEYS
      remoteRef:
        key: {{ .Values.secrets.bi_backend_service_connectors_secret_id }}
        property: KONTUR_MARKET_PARTNER_KEYS
    - secretKey: BITRIX_DB_USER_PASSWORD
      remoteRef:
        key: {{ .Values.secrets.bi_backend_service_connectors_secret_id }}
        property: BITRIX_DB_USER_PASSWORD
    - secretKey: BITRIX_PARTNER_KEYS
      remoteRef:
        key: {{ .Values.secrets.bi_backend_service_connectors_secret_id }}
        property: BITRIX_PARTNER_KEYS
    - secretKey: CH_SCHOOLBOOK_PASSWORD
      remoteRef:
        key: {{ .Values.secrets.bi_backend_service_connectors_secret_id }}
        property: CH_SCHOOLBOOK_PASSWORD
    - secretKey: YC_BILLING_ANALYTICS_PASSWORD
      remoteRef:
        key: {{ .Values.secrets.bi_backend_service_connectors_secret_id }}
        property: YC_BILLING_ANALYTICS_PASSWORD
    - secretKey: CH_MARKET_COURIERS_PASSWORD
      remoteRef:
        key: {{ .Values.secrets.bi_backend_service_connectors_secret_id }}
        property: CH_MARKET_COURIERS_PASSWORD
    - secretKey: CH_SMB_HEATMAPS_PASSWORD
      remoteRef:
        key: {{ .Values.secrets.bi_backend_service_connectors_secret_id }}
        property: CH_SMB_HEATMAPS_PASSWORD
    - secretKey: USAGE_TRACKING_PASSWORD
      remoteRef:
        key: {{ .Values.secrets.bi_backend_service_connectors_secret_id }}
        property: USAGE_TRACKING_PASSWORD
{{ end }}

{{ if .Values.enabled_features.frozen_connectors }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: frozen-connectors-secrets
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: secret-store
    kind: SecretStore
  target:
    name: frozen-connectors-secrets
  data:
    {{- range $cd := .Values.frozen_connectors_data }}
    - secretKey: {{ $cd.connector_settings_key }}_PASSWORD
      remoteRef:
        key: {{ $.Values.secrets.bi_backend_frozen_connectors_secret_id }}
        property: {{ $cd.connector_settings_key }}_PASSWORD
    {{- end }}
{{ end }}

{{ if .Values.apps_to_run.dls }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: dls-secrets
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: secret-store
    kind: SecretStore
  target:
    name: dls-secrets
  data:
    - secretKey: DLS_DB_PASSWORD
      remoteRef:
        key: {{ .Values.secrets.bi_backend_dls_secret_id }}
        property: DLS_DB_PASSWORD
    - secretKey: DLS_SENTRY_DSN
      remoteRef:
        key: {{ .Values.secrets.bi_backend_dls_secret_id }}
        property: DLS_SENTRY_DSN
    - secretKey: DLS_SOLOMON_OAUTH
      remoteRef:
        key: {{ .Values.secrets.bi_backend_dls_secret_id }}
        property: DLS_SOLOMON_OAUTH
{{ end }}

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: service-account-secrets
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: secret-store
    kind: SecretStore
  target:
    name: service-account-secrets
  data:
    - secretKey: bi_api_sa_key_data
      remoteRef:
        key: {{ .Values.secrets.bi_backend_service_account_secret_id }}
        property: bi_api_sa_key_data

{{ if .Values.apps_to_run.file_uploader }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: file-uploader-secrets
spec:
  refreshInterval: 10m
  secretStoreRef:
    name: secret-store
    kind: SecretStore
  target:
    name: file-uploader-secrets
  data:
    - secretKey: CLOUD_S3_SECRET_ACCESS_KEY
      remoteRef:
        key: {{ .Values.file_connector_config.sa_key_secret_id }}
        property: secret_key
    - secretKey: CLOUD_S3_ACCESS_KEY_ID
      remoteRef:
        key: {{ .Values.file_connector_config.sa_key_secret_id }}
        property: access_key
    - secretKey: CSRF_SECRET
      remoteRef:
        key: {{ .Values.secrets.bi_backend_file_uploader_secret_id }}
        property: CSRF_SECRET
    - secretKey: FILE_UPLOADER_MASTER_TOKEN
      remoteRef:
        key: {{ .Values.secrets.bi_backend_file_uploader_secret_id }}
        property: FILE_UPLOADER_MASTER_TOKEN
    - secretKey: CONN_FILE_CH_PASSWORD
      remoteRef:
        key: {{ .Values.file_connector_config.ch_user_secret_id }}
        property: password
    - secretKey: GSHEETS_APP_API_KEY
      remoteRef:
        key: {{ .Values.secrets.bi_backend_file_uploader_secret_id }}
        property: GSHEETS_APP_API_KEY
    - secretKey: GSHEETS_APP_CLIENT_ID
      remoteRef:
        key: {{ .Values.secrets.bi_backend_file_uploader_secret_id }}
        property: GSHEETS_APP_CLIENT_ID
    - secretKey: GSHEETS_APP_CLIENT_SECRET
      remoteRef:
        key: {{ .Values.secrets.bi_backend_file_uploader_secret_id }}
        property: GSHEETS_APP_CLIENT_SECRET
{{ end }}
