{{ if .Values.enabled_features.network_policy }}
---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "deny-egress-to-internal"
spec:
  endpointSelector:
    matchLabels:
      policy: rqe-dataset-api
  egress:
    {{ if .Values.host_allow }}
    {{- range splitList "," .Values.host_allow }}
    - toFQDNs:
      - matchName: {{ (split ":" .)._0 }}
      toPorts:
        - ports:
            - port: {{ (split ":" .)._1 | quote }}
    {{- end }}
    {{ end }}
    - toCIDRSet:
      - cidr: 0.0.0.0/0
        except: {{ splitList "," .Values.ipv4_deny | toYaml | nindent 8}}
      - cidr: ::/0
        except: {{ splitList "," .Values.ipv6_deny | toYaml | nindent 8}}
    - toEndpoints:
      - matchLabels:
          "k8s:io.kubernetes.pod.namespace": kube-system
          "k8s-app": kube-dns
      toPorts:
        - ports:
            - port: "53"
              protocol: ANY
          rules:
            dns:
              - matchPattern: "*"
    - toEndpoints:
      - {}
    - toEntities:
      - cluster
{{ if .Values.apps_to_run.secure_reader }}
---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: "secure-reader-isolation"
spec:
  endpointSelector:
    matchLabels:
      app: file-secure-reader
  ingress:
    - fromEndpoints:
      - matchLabels:
          app: file-uploader-worker
      toPorts:
        - ports:
          {{ if .Values.tls_to_backends }}
          - port: "8443"
            protocol: TCP
          {{ else }}
          - port: "8080"
            protocol: TCP
          {{ end }}
  egress:
    - {}
{{ end }}
{{ end }}
