#!/usr/bin/env sh

set -x  # debug.
set -eu

socket="${GUNICORN_SOCKET_PATH:-/var/reader.sock}"
workers="${GUNICORN_WORKERS_COUNT:-1}"
max_rq="${GUNICORN_MAX_RQ:-5000}"
max_rq_jitter="${GUNICORN_MAX_RQ_JITTER:-500}"

exec \
    gunicorn \
    bi_file_secure_reader.app:create_gunicorn_app \
    --bind "unix:${socket}" \
    --max-requests "$max_rq" \
    --max-requests-jitter "$max_rq_jitter" \
    --workers="$workers" \
    --worker-class aiohttp.GunicornWebWorker
