apiVersion: v1
kind: Secret
metadata:
  name: fluent-bit-key-json
  namespace: {{ .Release.Namespace | quote }}
  labels:
    k8s-app: fluent-bit
type: Opaque
data:
  "key.json": {{ .Values.auth.json | b64enc }}