from dl_formula_testing.testcases.functions_window import DefaultWindowFunctionFormulaConnectorTestSuite

from dl_connector_bundle_chs3_tests.db.yadocs.formula.base import YaDocsTestBase


class TestWindowFunctionYaDocs(YaDocsTestBase, DefaultWindowFunctionFormulaConnectorTestSuite):
    pass
