from dl_formula_testing.testcases.functions_markup import DefaultMarkupFunctionFormulaConnectorTestSuite

from dl_connector_bundle_chs3_tests.db.yadocs.formula.base import YaDocsTestBase


class TestMarkupFunctionYaDocs(YaDocsTestBase, DefaultMarkupFunctionFormulaConnectorTestSuite):
    pass
