from dl_formula_testing.testcases.conditional_blocks import DefaultConditionalBlockFormulaConnectorTestSuite

from dl_connector_trino_tests.db.formula.base import TrinoFormulaTestBase


class TestConditionalBlockTrino(TrinoFormulaTestBase, DefaultConditionalBlockFormulaConnectorTestSuite):
    pass
