[uwsgi]
master = true

no-orphans = true
http-socket = $(HTTP_BIND)

stats = /tmp/uwsgi_stats.sock
memory-report = true

# env for unistat:
env = UWSGI_STATS=/tmp/uwsgi_stats.sock

# https://beenje.github.io/blog/posts/uwsgi-send_file-and-python35/  http://archive.md/gCQSH
wsgi-disable-file-wrapper = true

buffer-size = 32768
harakiri = 300
harakiri-verbose = true

# override to prevent frequent restarts and memory leaks
max-requests = $(BI_API_UWSGI_MAX_REQUESTS_COUNT)
# jitter so that workers do not restart simultaneously
max-requests-delta = 32

chdir = %d../
module = dl_control_api.app
callable = app
die-on-term = true
drop-after-apps = true
uid = www-data
gid = www-data
req-logger = stdout file:/dev/fd/1
logformat = {"level": "DEBUG", "message": "[%(ltime)] %(addr) %(method) %(uri) %(status) [%(msecs) msecs|%(size) B]"}

lazy = true
lazy-apps = true

workers = $(BI_API_UWSGI_WORKERS_COUNT)

# fixed backlog queue size (independent of workers)
# listen = $(BI_API_UWSGI_LISTEN_COUNT)
# WARN: var [listen] passed via cli because [listen] is parsed before env var substitution in .ini config file

enable-threads = true
# concurrency per worker for I/O-bound waits (http calls, db queries)
threads = 2

# prevent keep-alive connections from direct upstream clients
add-header = Connection: close
