#!/usr/bin/env sh

set -x  # debug.
set -eu

if [ "${LOCAL_RQE_EXT_SYNC:-1}" = "0" ]; then
    sleep 9000
    exit 0
fi

HTTP_BIND_PORT="${RQE_EXT_SYNC_PORT:-9876}"
RQE_UWSGI_WORKERS_COUNT="${RQE_EXT_SYNC_WORKERS_COUNT:-16}"
RQE_UWSGI_THREADS_COUNT="${RQE_EXT_SYNC_THREADS_COUNT:-10}"
RQE_RSS_LIMIT="${RQE_EXT_SYNC_RSS_LIMIT:-1073741824}"  # 1GB
if [ "${BISYS_USE_IPV6:-1}" = "1" ]; then HTTP_BIND_ADDR="[::1]"; else HTTP_BIND_ADDR="127.0.0.1"; fi

if [ ! -f /tmp/.iptables_setup_marker ]; then
    echo 'The marker "/tmp/.iptables_setup_marker" does not exist. It should have been created by "/etc/my_init.d/iptables_setup" executed from "/sbin/my_init".' 1>&2
    sleep 15
    exit 255
fi

HTTP_BIND="${HTTP_BIND_ADDR}:${HTTP_BIND_PORT}"
export HTTP_BIND RQE_UWSGI_WORKERS_COUNT RQE_UWSGI_THREADS_COUNT
exec \
    chpst -u ext_query_user:ext_query_user \
    prlimit --rss=${RQE_RSS_LIMIT} \
    uwsgi \
        --ini=/code/app/uwsgi/uwsgi-query-executer.ini \
        --stats=/tmp/uwsgi_stats_rqe_ext_sync.sock
