#!/bin/sh

set -eu

DOCKER_OPTS="${DOCKER_OPTS:-}"
container_name="$(
    sudo docker ps --format '{{.Names}}' \
    | grep main-app \
    | sed 1q
)"
if [ -z "$container_name" ]; then
    echo "Could not find main-app docker container" >&2
    exit 1
fi
exec sudo docker exec $DOCKER_OPTS "$container_name" "$@"
