#!/usr/bin/env python3

import os
import yaml
import json


APP_CONFIG_PATH = '/etc/kubelet.d/app.yaml'
SECRET_DIR = '/etc/secrets'


def get_conf_by_name(lst, name):
    values = [val for val in lst if val['name'] == name]
    assert len(values) <= 1
    return values[0] if values else None


def main():
    print('Going to update secrets in app config')

    with open(APP_CONFIG_PATH) as f:
        app_config = yaml.safe_load(f)
    main_app_conf = get_conf_by_name(app_config['spec']['containers'], 'main-app')

    secrets = {}
    for secret_name in os.listdir(SECRET_DIR):
        if secret_name.endswith('.enc'):
            continue
        secret_content = open(os.path.join(SECRET_DIR, secret_name)).read()
        secrets[secret_name] = secret_content

    existing_secrets = {item['name']: item['value'] for item in main_app_conf['env']}

    print('Existing secrets:', existing_secrets.keys())
    print('Secrets on FS:', secrets.keys())

    existing_secrets.update(secrets)
    main_app_conf['env'] = [{'name': key, 'value': value} for key, value in existing_secrets.items()]

    with open(APP_CONFIG_PATH, 'w') as f:
        yaml.safe_dump(app_config, f)
    print('Secrets have been successfully updated')


if __name__ == '__main__':
    main()
