"""002_log_node

Revision ID: f060464a7028
Revises: 71d8971e553a
Create Date: 2018-07-19 14:31:50.954970

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f060464a7028'
down_revision = '71d8971e553a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dls_log', sa.Column('node_uuid', postgresql.UUID(), nullable=True))
    op.create_index(op.f('ix_dls_log_node_uuid'), 'dls_log', ['node_uuid'], unique=False)
    op.create_foreign_key('fk_node_uuid', 'dls_log', 'dls_node_config', ['node_uuid'], ['node_uuid'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_node_uuid', 'dls_log', type_='foreignkey')
    op.drop_index(op.f('ix_dls_log_node_uuid'), table_name='dls_log')
    op.drop_column('dls_log', 'node_uuid')
    # ### end Alembic commands ###
