version: '3.7'

services:
  db-postgres:
    # image: "postgres:13-alpine"
    image: "registry.yandex.net/statinfra/postgres@sha256:3335d0494b62ae52f0c18a1e4176a83991c9d3727fe67d8b1907b569de2f6175"
    environment:
      - POSTGRES_DB=common_test
      - POSTGRES_USER=datalens
      - POSTGRES_PASSWORD=qwerty
      - PGCTLTIMEOUT=300  # https://st.yandex-team.ru/DEVTOOLSSUPPORT-2799
    ports:
      - 50813:5432
