include ../../tools/common_makefile.mk

# Create a development environment (start all the services required for bi-alerts)
.PHONY: devenv
devenv:
	docker-compose up --build

.PHONY: devenv-d
devenv-d:
	docker-compose up --build -d
