# FROM scality/s3server
# FROM registry.yandex.net/statinfra/s3server@sha256:35fe6b8587847159303779d53cd917ea260ee4b524772df74132825acb939f20

# FROM zenko/cloudserver
FROM cr.yandex/crpsufj53lhl0via9iam/s3cloudserver

COPY s3-storage /data
CMD /s3-storage/entrypoint.sh
