class OpCode:
    WB_CREATE: str = "wb_create"
    WB_DELETE: str = "wb_delete"
    WB_CHECK_EXISTS: str = "wb_check_exists"
    GET_FOLDER_CONTENT: str = "get_folder_content"
    WB_INFO_GET: str = "workbook_info_get"
    WB_BASIC_INFO_GET: str = "workbook_basic_info_get"
    WB_PRIVATE_INFO_GET: str = "private_workbook_info_get"
    COLLECTION_CONTENT_GET: str = "collection_content_get"
    COLLECTION_CREATE: str = "collection_create"
    COLLECTION_GET: str = "collection_get"
    COLLECTION_UPDATE: str = "collection_update"
    COLLECTION_DELETE: str = "collection_delete"
    COLLECTION_MOVE: str = "collection_move"
