from dl_formula_testing.testcases.functions_aggregation import DefaultMainAggFunctionFormulaConnectorTestSuite

from dl_connector_mssql_tests.db.formula.base import MSSQLTestBase


class TestMainAggFunctionMSSQL(MSSQLTestBase, DefaultMainAggFunctionFormulaConnectorTestSuite):
    pass
