from dl_formula_testing.testcases.functions_markup import DefaultMarkupFunctionFormulaConnectorTestSuite

from dl_connector_starrocks_tests.db.formula.base import StarRocksTestBase


class TestMarkupFunctionStarRocks(StarRocksTestBase, DefaultMarkupFunctionFormulaConnectorTestSuite):
    pass
