from dl_formula_testing.testcases.misc_funcs import DefaultMiscFunctionalityConnectorTestSuite

from dl_connector_starrocks_tests.db.formula.base import StarRocksTestBase


class TestMiscFunctionalityStarRocks(StarRocksTestBase, DefaultMiscFunctionalityConnectorTestSuite):
    pass
