from dl_formula_testing.testcases.functions_string import DefaultStringFunctionFormulaConnectorTestSuite

from dl_connector_starrocks_tests.db.formula.base import StarRocksTestBase


class TestStringFunctionStarRocks(StarRocksTestBase, DefaultStringFunctionFormulaConnectorTestSuite):
    supports_regex_extract_all = False
