import pytest

from dl_formula_testing.testcases.functions_window import DefaultWindowFunctionFormulaConnectorTestSuite

from dl_connector_starrocks_tests.db.formula.base import StarRocksTestBase


class TestWindowFunctionStarRocks(StarRocksTestBase, DefaultWindowFunctionFormulaConnectorTestSuite):
    pass
