# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yandex/cloud/iam/v1/awscompatibility/access_key.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n5yandex/cloud/iam/v1/awscompatibility/access_key.proto\x12$yandex.cloud.iam.v1.awscompatibility\x1a\x1fgoogle/protobuf/timestamp.proto\"\x88\x01\n\tAccessKey\x12\n\n\x02id\x18\x01 \x01(\t\x12\x1a\n\x12service_account_id\x18\x02 \x01(\t\x12.\n\ncreated_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\x0e\n\x06key_id\x18\x05 \x01(\tB\x8d\x01\n(yandex.cloud.api.iam.v1.awscompatibilityZaa.yandex-team.ru/cloud/bitbucket/public-api/yandex/cloud/iam/v1/awscompatibility;awscompatibilityb\x06proto3')



_ACCESSKEY = DESCRIPTOR.message_types_by_name['AccessKey']
AccessKey = _reflection.GeneratedProtocolMessageType('AccessKey', (_message.Message,), {
  'DESCRIPTOR' : _ACCESSKEY,
  '__module__' : 'yandex.cloud.iam.v1.awscompatibility.access_key_pb2'
  # @@protoc_insertion_point(class_scope:yandex.cloud.iam.v1.awscompatibility.AccessKey)
  })
_sym_db.RegisterMessage(AccessKey)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n(yandex.cloud.api.iam.v1.awscompatibilityZaa.yandex-team.ru/cloud/bitbucket/public-api/yandex/cloud/iam/v1/awscompatibility;awscompatibility'
  _ACCESSKEY._serialized_start=129
  _ACCESSKEY._serialized_end=265
# @@protoc_insertion_point(module_scope)
