from dl_formula_testing.testcases.functions_markup import DefaultMarkupFunctionFormulaConnectorTestSuite

from dl_connector_bundle_chs3_tests.db.gsheets_v2.formula.base import GSheetsTestBase


class TestMarkupFunctionGSheets(GSheetsTestBase, DefaultMarkupFunctionFormulaConnectorTestSuite):
    pass
