# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from yandex.cloud.priv.mdb.greenplum.v1 import perf_diag_service_pb2 as yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_perf__diag__service__pb2


class PerformanceDiagnosticsServiceStub(object):
    """A set of methods for getting Greenplum performance diagnostics.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetSessionsStatsV2 = channel.unary_unary(
                '/yandex.cloud.priv.mdb.greenplum.v1.PerformanceDiagnosticsService/GetSessionsStatsV2',
                request_serializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_perf__diag__service__pb2.GetSessionsStatsV2Request.SerializeToString,
                response_deserializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_perf__diag__service__pb2.GetSessionsStatsV2Response.FromString,
                )
        self.GetSessionsAtTimeV2 = channel.unary_unary(
                '/yandex.cloud.priv.mdb.greenplum.v1.PerformanceDiagnosticsService/GetSessionsAtTimeV2',
                request_serializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_perf__diag__service__pb2.GetSessionsAtTimeV2Request.SerializeToString,
                response_deserializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_perf__diag__service__pb2.GetSessionsAtTimeV2Response.FromString,
                )


class PerformanceDiagnosticsServiceServicer(object):
    """A set of methods for getting Greenplum performance diagnostics.
    """

    def GetSessionsStatsV2(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSessionsAtTimeV2(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PerformanceDiagnosticsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetSessionsStatsV2': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSessionsStatsV2,
                    request_deserializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_perf__diag__service__pb2.GetSessionsStatsV2Request.FromString,
                    response_serializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_perf__diag__service__pb2.GetSessionsStatsV2Response.SerializeToString,
            ),
            'GetSessionsAtTimeV2': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSessionsAtTimeV2,
                    request_deserializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_perf__diag__service__pb2.GetSessionsAtTimeV2Request.FromString,
                    response_serializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_perf__diag__service__pb2.GetSessionsAtTimeV2Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'yandex.cloud.priv.mdb.greenplum.v1.PerformanceDiagnosticsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PerformanceDiagnosticsService(object):
    """A set of methods for getting Greenplum performance diagnostics.
    """

    @staticmethod
    def GetSessionsStatsV2(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/yandex.cloud.priv.mdb.greenplum.v1.PerformanceDiagnosticsService/GetSessionsStatsV2',
            yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_perf__diag__service__pb2.GetSessionsStatsV2Request.SerializeToString,
            yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_perf__diag__service__pb2.GetSessionsStatsV2Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSessionsAtTimeV2(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/yandex.cloud.priv.mdb.greenplum.v1.PerformanceDiagnosticsService/GetSessionsAtTimeV2',
            yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_perf__diag__service__pb2.GetSessionsAtTimeV2Request.SerializeToString,
            yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_perf__diag__service__pb2.GetSessionsAtTimeV2Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
