from dl_api_connector.i18n.localizer import CONFIGS as BI_API_CONNECTOR_CONFIGS
from dl_api_lib_testing.connection_form_base import ConnectionFormTestBase

from bi_connector_monitoring.api.connection_form.form_config import MonitoringConnectionFormFactory
from bi_connector_monitoring.api.i18n.localizer import CONFIGS as BI_CONNECTOR_MONITORING_CONFIGS


class TestMonitoringConnectionForm(ConnectionFormTestBase):
    CONN_FORM_FACTORY_CLS = MonitoringConnectionFormFactory
    TRANSLATION_CONFIGS = BI_API_CONNECTOR_CONFIGS + BI_CONNECTOR_MONITORING_CONFIGS
