TVM_APP_ID: 2017225
ENV: {}
PUSH_CLIENT_NODEJS_TOPIC: TODO
PUSH_CLIENT_ERROR_TOPIC: TODO
SOLOMON_URL: https://solomon.cloud-preprod.yandex-team.ru/api/v2/push
SOLOMON_PROJECT: aoee4gvsepbo0ah4i2j6
JAEGER_ENDPOINT: jaeger-collector.private-api.ycp.cloud-preprod.yandex.net:443
