# United Storage with predefined env
FROM ghcr.io/datalens-tech/datalens-us:release

ENV DEV_MODE="true"
ENV SQL_DEBUG="true"
ENV MULTITENANT="false"
ENV DEBUG="knex:*"
ENV APP_INSTALLATION="opensource"
ENV APP_ENV="preprod"
