name: converter-api
service_account_id: bfbdtpfu9qlotm99j4h6
scale_policy:
  fixed_scale:
    size: 1
deploy_policy:
  max_unavailable: 1
  # здесь лучше 0, для того чтобы виртуалки не пересоздавались каждый раз
  max_expansion: 0
health_checks_spec:
  health_check_specs:
  - http_options:
      port: 80
        # для проектов на common, проверка живости приложения
      path: /ping
    interval: 11s
    timeout: 10s
    unhealthy_threshold: 2
    healthy_threshold: 3
allocation_policy:
  zones:
  - zone_id: ru-central1-a
  - zone_id: ru-central1-b
  - zone_id: ru-central1-c
platform_l7_load_balancer_spec:
  preferred_ip_version: IPV6
  target_group_spec:
    # название вашей таргет-группы, это специальная тг для L7, из интерфейса ее создать невозможно
    name: datalens-preprod-converter-api
instance_template:
  # шаблон для имени вм, мы используем такой app_name-{instance.internal_dc}-{instance.index}
  name: converter-api-{instance.internal_dc}-{instance.index}
  fqdn: converter-api-{instance.internal_dc}-{instance.index}.{instance.internal_dc}.datalens.cloud-preprod.yandex.net
  service_account_id: bfbgeplq9m3t5qqvpcgh
  labels:
    yandex-dns: ig
    conductor-group: datalens-back-preprod
    conductor-role: converter-api
  platform_id: standard-v2
  resources_spec:
    memory: 4G
    cores: 2
    core_fraction: 20
  boot_disk_spec:
    mode: READ_WRITE
    disk_spec:
      # айдишник образа, созданного packer-ом, подставляется тимсити, здесь не менять
      image_id: __IMAGE_ID__
      type_id: network-ssd
      size: 10g
  # логи пишутся на secondary-disk, чтобы избежать потери при деплое
  secondary_disk_specs:
  - mode: READ_WRITE
    device_name: data
    disk_spec:
      type_id: network-ssd
      size: 11g
  network_interface_specs:
  - network_id: c64teupls8jrjeiqtbho
    primary_v6_address_spec: {}
    primary_v4_address_spec: {}
    security_group_ids:
    - c64pau6gnaao4tfbr25o
  metadata:
    k8s-runtime-bootstrap-yaml: ' '
    # настройка записи логов на secondary-disk
    user-data: |
      #cloud-config
      fs_setup:
      - device: /dev/disk/by-id/virtio-data
        filesystem: ext4
        partition: auto
        overwrite: false
      mounts:
      - [/dev/disk/by-id/virtio-data, /data, ext4, 'defaults,errors=remount-ro', '0', '2']
      - [/data/log/fluent, /var/log/fluent, none, 'defaults,bind', '0', '0']
      runcmd:
      - mkdir -p /data/log/fluent
      - chmod 0777 /data
      - chown td-agent:td-agent /data/log/fluent
      - chmod 0755 /data/log/fluent
      - mount --make-rprivate /data
      - mount -o bind /data/log/fluent /var/log/fluent
      - /usr/local/bin/update_env_vars
      - /usr/bin/skm decrypt
      - /usr/local/bin/update_secrets
      env_vars:
        AUTH_MODE: gauthling
        NGINX_CERT_LOCATION: /etc/secrets/component_cert.pem
        NGINX_CERT_PRIVATE_KEY_LOCATION: /etc/secrets/component_cert.key
        NGINX_SERVER_NAME: converter-api
        RUN_NGINX: 1
        YENV_NAME: cloud
        YENV_TYPE: testing
    osquery_tag: ycloud-svc-datalens-bi
    shortname: converter-api-{instance.internal_dc}-{instance.index}.{instance.internal_dc}
    nsdomain: datalens.cloud-preprod.yandex.net
    skm: |
      api_endpoint: api.cloud-preprod.yandex.net:443
      skip_tls_verify: false
      kms_private_endpoint: ""
      iam_private_endpoint: ""
      kms_private_skip_tls_verify: false
      kms_key_uri: yc-kms://e10mng38moenmrvomcdo
      encrypted_dek: AAAAAQAAABRlMTA5bGE2aGswNXI5NnNhOWhmZAAAABAodcyE5u1SJnmbmiSWL8CdAAAADCf0vZdc/VMwfxTIjNlpqvnU3GAxvlJl4EL8YS2Q9dFx5gmDKKI3I363vY5Y0d752MFcXtrYYrFSb/I8aAcHbXHILtg+VKlBICq+iFTQPsZ5S52H1XSAKqDQ28Tv
      secrets:
        - path: /etc/secrets/TVM_SECRET
          ciphertext: !!binary 7a+QoSkH5F+fAsfThwxP3m9QAtUdNenVdqeyZVkYMCGSS5joMy0=
          mode: 0
          uid: 0
          gid: 0
        - path: /etc/secrets/TVM_INFO
          ciphertext: !!binary |
              8UgXvyTzy9PqNET66Vs+rq+T+kANe1M4jEWlTLfipnd1BxpbcTknt+2xWQppNPdvJjGEME
              n3w1nqcg==
          mode: 0
          uid: 0
          gid: 0
        - path: /etc/secrets/CSRF_SECRET
          ciphertext: !!binary //ksnWxgVOL4RT3HjnAQjhfqsewNhWDyW6vu+ABdrvaT+ScsMcmPflvQvA==
          mode: 0
          uid: 0
          gid: 0
        - path: /etc/secrets/S3_ACCESS_KEY_ID
          ciphertext: !!binary pMEeytkra8Ft+jCfgYYdtel7gKCq1G6FwR1XbTDGF57PT8r5
          mode: 0
          uid: 0
          gid: 0
        - path: /etc/secrets/S3_SECRET_ACCESS_KEY
          ciphertext: !!binary |
              G3dBqkoiDkAoM9l/+zNOBAvD1/iYwnAc2ZINYo//JMVbETj5F9f/g241Bn/pSl2ADhHjl8
              Qj+iU=
          mode: 0
          uid: 0
          gid: 0
        - path: /etc/secrets/US_MASTER_TOKEN
          ciphertext: !!binary ufOwwQrF9Op9rVRkRrt1/pe4UGb5reCFWmWNKJBVddhTgbLTtjjBT5x0a8fGrl25
          mode: 0
          uid: 0
          gid: 0
        - path: /etc/secrets/LOGCH_PASSWORD
          ciphertext: !!binary ISLs2Jw/bkb8/YE3KDpNXNOEpA0YIQv8AqK4eCQzwLRa1liaUhagaQkd
          mode: 0
          uid: 0
          gid: 0
        - path: /etc/secrets/component_cert.pem
          ciphertext: !!binary |
              /3d5zrgR/+bfUgf6Gx4OUHhYZ3fOeOOJs/d/xmrL/Jv0L6uehtbSJHtWeJ6qIJrjB4C2e3
              wc/8l8ndWgS75BG2gMWplK4mRb2Pn20/YjzV/s2Nc9+1XFPvRbeVBRBLLA7+TUTGFpRYeP
              s4zt8UmBkl/sKSC6/lk1VMN9Rmayt+qbqpP6WOa2BNjrqbmqSaEyhPu1NDmGW6qC+3ok03
              ejP29EfroRDfPWXG5OQJs3aBbh5mpPACXFt3t32qDC61AuCZLULtzizBDHwLDOR3hA+4GB
              dBHMqCFZGWf8eXYWUsEhFn3mcNf63nhxo06JM1afbOtDfPbFOtZq6t+ZN0BvtRCblw1W36
              5iHRo8GQf4+PFfLVPnmaQZso/p/ChbRQ2w7IaM5qGztXu963VslOqvQ25v0wcQ11yAEexH
              5mrfOXLwdxpMC7VJamWzwdRaE0AuE5GDBNbhdGpvsame2Q09/mecJX2q0UJ4XtEbmuXM9T
              q05R/+qbaw65Uj5FED9dKUne3xBctvY9vROWqVBZrvvVxmnN1JWKlLh8wxgINJLdmyPPO7
              rdgPx4A1o9J0/u3aXsFBXbb6qS9IK5Jr3np0qzx+vJeMoRPvT4bdJ7f7eLUCqLxk404Le5
              f/eMrdBivWBUo9BWjnMYH7sxfXXZnno5Ss1rrUKJcApfk954LR7htQZq0JnuaRyikPeLYe
              j8rOt9qt9Qw3HdR1T5iGUplqLVmXgyNdFAnIuaF6k8aOgZuUP+Xoj9ej2k7lcooRwV7l+r
              v+aaaHmz22ezHw9ZXlsRc6KSKfMxnhLBozYGqL22cj8Y/weVMG9UnIzCtUaWmz9oH1RRT9
              47Qc6y8/Lhxz83MMFgTmNGBjp+n8b+hb6pWFKJeNb+4z4I6cWxFiN8+/pIQ0P2GBC2GbCD
              gVP9K8yAhLfJeIXcxuQQXmH0E2eXsgjmECtETAEiB9N2E+OwhcTMgC5NX/Mk5T2MNWtJSK
              u+z5+e/hnxmxJEYuf/XjA8hAw4dGGpgj3vLM9c4PWbCBc7kSwIew7ki2yMwfFDPVhROnYw
              7v2rnEUZi4g1dHa/gx5WAVGpeNbTIXHckIqGBXzi1eY0JaKsmO1ZIey3zAGnfIu8800vWC
              l5rCsLiU8dxcvoEauzQleV58kfvH79gZWUFESsNpN+kmIhJz0f8vcxQqrDj4A86yE2jxvQ
              S51+LtLy26uKdiy2xjCoXv0lzW6zgO3d7kaqZteKj8LED189dd40sBxw79Dp78/3iRFisY
              e2JtrAX0iM0+O4Q7BSyjC7ZHqo5kXdpKg90TXRVV/ZUQZ7Lbjk81rrtMXrjs0BW/hf4n9s
              kgNA+rUuYWnR0CVSiRB/YDSfpXfNQlCikssY+T30+l8QCUkOJkqd772ddqzOkYkifrKfLF
              LbAME6zCtbDjd+QwuhrVBgtR6rONQYLhll5dBoY3ECg6Zs2qw201Kgr449Wl34n5FpM5SJ
              NzrlqVm1QzPDocxTSNR2y3AVdesqItuZOBolUGabQe2CjKlRWki6OAPEbUv2v9e273ufEs
              GhhOGo7Ed48hdn2mSK6e4auLemtoKnrlYiF8X5gOP33hm2hP9coldiTbFDp2LW5k8fM5Lq
              dZWNVDVNDptJ+c0jwntQ9dYb47QXEeo5awa0cIP+C75hL0MNf4lXrW8YjG4C5iM9V0Vij6
              IpCmr8V4ueNk/WEswCcJQr6lK1wlErzpyEw22jfzjLO2y/oVW/MJmz/S6LD6vRnTYZ486I
              IOTXIGAlZvG9eY8hFXXvt5Yv9RVeOnJy+t81PEDqR8KCHGPatugpVnFiaqT3Xu2tuJTXwV
              Kp0KV13vc6hjlDTfGUM0jHePJqQ75wf1ai1TbTp8MCS3PWs/4Y8Y7jOnZjhB/Ab52+STPF
              XDmloQKixudddbQrw8R56+oSBFfP2G9J551QhcLL7vyz0AfnCtcECpqYIlA1cpFpPCYHLy
              V0BNI6mWcjZLzKIMZeLBD86vRk2NQ2/w5LqUzThbQQmbwnqBZriHx1ia6XXDEVEmi6fUF5
              oo2q7U3Xtb0Uz2JUXHeNEgU6NvmYQm7UNja/bCvWJdw7DucPWsuGCgT7mrztDhKCmeZMLH
              A5TYecJYsEstcSfWLVXbCzZlvIqx+WPkWQtkWxKe5VP6uoJGBOYDauU8Tb0os7znpw9Agu
              C/fAC2RwjeeNf89XmdX2CwS2anp/7JkYtRi/ZhD0yAJ88aZkhoXivQ11R9fdQE+HCG1ekf
              BTQNh28xN9+Pt6svtBwnS+JDHcXrV4oD3TxM3GY0LNCTDBO0+m7jxMGXilvzfrYJoVh8Gz
              LZ5pgIh+gJ/pwcUlawC0Nm1aPvb3mBuZIkWpjQn9L+4zYuJkx4XO3JpzJfEHLnSKHEi54v
              PkZ/PIidGfE2LwpM+VFSwD+9ZhmzM3Y8Lum5nFPs0q+/EbxWHdol9Kj9MoF+nnYS81dLfc
              IYQ55oTMxuec/lcjimiwVpoYWqh4NAtsGD9Ozevugtklbeb5WOXoi6S6LQg4kcm3bJgFhv
              UprnWaiqlqstbTF6+g95OLlOUEB8wxS6t2aob/4HVYzJmLokCN3Vtk5g88M4zGYbrfeKXH
              LPuwikzLz/H9G8/Ybspo4FlFjJdeHb0u/q0hYkNPXsVob+z0qAm8Tip51XDSqlJZZjlMdw
              zA1TnAmPa7AQXATVmsEWMt+eYTNNSVDK7bnF5OZkLECO1PwctOVyzDA7LaHFhOX2J3fevQ
              6vutSwfV0R3L+6oAczKrz8W8sJITyxoRaKT8bjopqCWiAaz3oYAzmiS03Wf/NBBx4m7os3
              xrtx+j3ZASW2HY9SNzu126+thM1P7Jm595iJY86bt9IxQxBUva9TkSZiJHN56KI96hhUp/
              bw2pQ8QFBIEj7vkvkeGmLTJkeavPmUOJwU3SxGvMsNhO2ugtL8wgmyDepsBo7Xfg2HGctv
              A2zqSsiREPMYccc0wBYMeU+g/RCE/aOofKmw1ZGC43ATD1h9l0Thx3wrXDwDVUMt/XcBFI
              JmSIRFLzvaKoWhLvNGi9IXtWW5jvjlYsXfFSnVsbA2Ils8+9IQhH6s6rPNZ9sHzto8666P
              PXBWEFeU6NL6qnJfURFMIXxXn/gvvi+YVctCVpNUK5v3M/jiFYsS2X96+0AKu0koCevzz4
              VEooPEZAJm66glKbtYpA7rgII5BNMRivOEdA4dm/2r1VbqKXZBcjW0MDj7AB2kG+QxISv6
              8JqCQcgg4+taDMOMqJK4VZ64puFqtugMvGw+iOqEpvqeme320UhnP/5dUsB7WupSzJm0K0
              OzAjM1iFF3KU2Cwci7VH/5KdRLv3iGqzfp3Ij6hXZh5cZurf+3V6sVB3f8FLsUFkHpet4V
              7hc7xzuAWx26FwrTHwAVTRhwzhcNoXeFuWeBAG8gbc04nX/lu8e83m6RyXyTbAXp/5rdV7
              mws04sd2a5aBrZOpX0bwE+qUI4MmMPcqD6bJjlDS8PIv8uLO+CYG2ZzPre68LVziSy4xry
              9i81oqiQH+t1+Kpf6bZX1e8nlG2p/ofncWovi98VbQzv0z/A2PNr5b6x46YUhLCozgs4N7
              E8CIS6qGj3MMp7M2tZqiLW8BBtopVv5BVxz8wTeDeJbbZQGhd3H1q4te3WMZNnHA7lq1qn
              AvfEID79pNN03IdFOlVaHV2qHGk2EP345NyhcLhBm3sK9DKQqR9ufuUHxBTzGeFXyFqouO
              8sDyRVIf7pU6W/9/JRxAB4uhAW9u6WwWim7Jh2TfewEuSCFdb/yyGFqYN7cGdsc6A+sZR+
              LBmG/a0f/Bn5kPfOIEfP6BvQLAq/TwKb7186G1cjgYXqvss6vWAW/rnap7IV7kUsyxsSnU
              CF42xvxMMrwsT3GrTUji5IByxl1HxxntfwaCb7JLLXkjnYJB8xspXZJVIp8dsU5MhxRyB0
              Qsdi5hgirqvUz3wrsYaaGjaUR0OzQ+ZMNKfJKrVR80hJXpoWiTLiERFe5NdwBHx52MEB8R
              7s2sg1f0ywO314pk/rXls0I9V1lBDaMpWVqsbE2Ol4XoVlsw8xqROLCZAp1mm+mW+N0Zte
              aEOakV//nfkcKTyc+ND0ePTm7nmJK47oSNnkI8+lQZ6Xr4yJ1eAJ0AF8TcCldIQfY+TBBu
              /UP7w9OCHUlnvzbn60tnpGunuUdaZw5NQD0LjbZ+L+8JMkx4Hgn/6MNQ9Bo7hO5op5Mjmk
              l/hMWCg3cdki8yiTT0DgGQw5VlRqdCDFhXuqk3gvDiFoCCNsBLRHjQqkCCKpGaEevt9a/C
              ic5ZZ9Ek9QwRN+K+oMEwDgGQEXKAbzncl6Nhrk4qs6CC2mabOWz+AE5WG/LWavH4WMuGQr
              R8leT7RZCkLzUtMXs6klN02FN9643vZP+6MRsfpYShZqjnxb3AxU0LR907ZdsUhedM2H4s
              dNgFmdAHte2fOIdj867hDVSrghQSx9m5hbmC3iLAePYXFzQDwWHlDdyce6fA35c4I98ve+
              sqFB4EwA/wpp+kttK5lnOuCoE5y838C55+xUAvK4u5fwg3J26BWgN1fUoP+KGMYQaDnRn9
              MT5Da3pht2pePRoNMBm8W/sL6dQ3p2K9Y3wp6K3PCz89bHYl56ABrAnY2ji+bNqWCLVN2U
              pNLvJs+j0ONGblWPSzts72kBH+sYXvyTXRA5qe1cHqykGfcGOI7ynZyKLUMBWmaY/J0Xqg
              x4r5eiD7Uk8ZBJzZYL2WQnSJB7KKwwor6ga4xzqUCfV8mwRFKiMNhiNZjL0zHwu4Ijjyba
              xdedtKead1J4KWprwy4psX3KHlVKw+PNpzwES3pQQMwQJsKTV92i4XLA4ow5deWdzCUUpM
              dcPI+nvESj1cXnCOqfj5Ki14EFJ8KZSYAA+RpQD1cAVOZwXkcI/2LS4uUyPcVzRsRUkg4C
              SGsvst6Pax/lmS8TOxxbc/M3XKeuPo/TaOLZTl4gCUWUbXRG3wGXZ7QgDwHbKGM2KFPC2M
              8uLJhWs1V8RUYiFNSVKT68Vzkfz+a8oCehwO8qSNfOTXbk5gxr/pL5M98+xVNd44YUqCMe
              vVEkJBh9ghNnzO7mshYpiVnuU9gylNcvbrsnTM5fVJReZUll64wA1eLjKC2y5U+SmMrl1W
              pWqvwD4/TW13NkGVa6WPkaeNs6FexL1ijE1BqjvxZbDu+tjCyLMYcMe07jS+o4BoID2Vgy
              wOzqONyAgSRHajfYJGP4a7HN0VQH/k1o0nwedGpP0D9JYXHmRpbMOPtgAZ4v2fTmbPviV4
              D5wO9UWWyzXn1z6l2GwEqEOtpaYzBZkayEDMOd+K7eR/zrEjRrJMTfMtaDXRjCKRwz0wOJ
              Au3ywBTMpZOERglA3eHtosMgLGEC8uD8btsdRgFftSkNlATDwICAlXkHIwHLj1BC/iB6hR
              Z7YUR1eOP2pkS7ENZtmTsTXOTu+kzAkM35v1QBlgR0B6uR208gum1QbEKCshVLE1WRz6Y1
              /C28n0+V8L+yhwF5DxaGGDKZta5VFbjLH3RYUPtJRPHYhsvvE3fbZZn+lyXFIknYvekEil
              FxY78TrCbmGb2+qnRh4DrqsuCqE30Btqao2svp49eBUbvXaTIzwuVef1hdVNWq1AEF84r2
              69AqAxWNUJP9hmOXpjO42uDxqiHWiStOP9LP5mNaHwa9nda8TUT1SPuEz/gTIe1QxelOjR
              NYnMLdctGFIF2CRijuqNYA4TGPsSFISMfm+xijtfmYKjZ8vm8kUXQDA+/d0QT+KjW1TD4/
              TmudbBYfkPxq2cRIZ7tF8AEbwsKT4XMc5K1PKaGSny5J5D7L4JBF8SzxhHd7PzqCFzuua7
              WOT8xMUq/okyYVtFD4PQLnozJiWyA9IvB2DHs+2ABB8+OcYb0aHVLqXwIsHifMNTFmR9qQ
              BF1fIh5G6q7Y17q8v/UEWQwk0maRQLgG/Pzsvls96lZq8kr9KZ071lzgz+Xloh6A5PxB16
              drsa+bRDqmRqF+x2U8x0iiF2uh0ObnTj4oWPoWPi/qTWYyooUhKE4Ri/3PIXkW6N5MOmyR
              DnO96IMVjxzvUlDxUTTXdrQf4vVTqWbRzbfpbJXG/rdNUe5VrVNt8FcPxVJmqIUdoKfpiA
              3dPXzpAWsq2pWVRNhEVOv+allrOjoNllHXA2GluB4PVqB0+rvptwb12MMRK77p7kxgWWD/
              7v495UPDCWJjK+nGyxLajhHkoSXO69h98AStqqwBtIe/nHondARe++LHgKRR25EhmmihJ1
              x+2ntSJPMFltHlEaVuB0zGnsgb+IID2iT73ZcoGMez9GDIoO65ewxOrM/+uAQOwMcm1yUe
              AiBlQ7xhk8sVOrZMEM1Vdqwg3duum5y+EQvtnk+iv2vjzDUNg9M/SPuQSbYj2o+ciVknf+
              VUs/1/r06+4EXzJajVuymVI82cWCiL+fFDN/D6fkF/MZusK3oCse0+nCeFtnPb3hF3+nIH
              5KBLqdtSyr1+MOCs/N3rdUKk54T9BQmFOG+MePBBEQ/0gQcWU+QpF8oITVbhTU2JzeyEnS
              ksoIh8Vf4+FyKgPlf4UGw6iGceL0N9gaNQctqtvZhKw8QzrXH5CrXimkP8ylg6ym4x7tkR
              b1tvPj3SeU6SgUwFGtpgHeVzBsyKgrqUrzOO9x3ZCBPImh1aDdhaZyvahE/rG3GYEmyRsY
              jSXjevkt7ZIQnNhNF13JBy5GEVp+JOtCQU/MptMgnQkmYFM8ONYoVTKrSNUkWhVGlBTH5R
              wBBWPDWZlNOBVZCRaJfkl2rCOTPgHAnEUjQfo5Ubrzgbx8rjfh6opL87JdAV5mEL3RPOHT
              E3JKym3+YfkjWBhwssyMUBWL5xAnxyIci9V7XIhWptE8Em+BdxH4IgwXLdwjeZ2MWtz5ZM
              l8IzLYG1uAUwGrwYo3op8gxvFMN+d7v/y+Fp5qBoYDNbt8fvNSA5TWg+aljZxSar4IMon2
              FnwcRrO86/k7G90PT0zuKsbMM20oJJ3Fj5yVkD6yDUf2HBKe1yaOXFAf/0yz4wlJ2HOniz
              dPEeuG5g0vTNdkIbjn8UINdkM5PQee2XV4D6Q3r1bC/f1o+/SMGUejIDAqqEVfjmKraOeJ
              znNx/9M98e0mRe/N401hTdG/fFIQg7KxA6suMezfxTKRM+4uP8Pz3S8m+3GOiMo+fCFBul
              TvJdLIT/G2pjcEsBuc1EHMIpkvVRWHqthnh2IFD+aA7l+E7SSzEWPOPExxOPPMY4TozEOI
              Kn
          mode: 0
          uid: 0
          gid: 0
        - path: /etc/secrets/component_cert.key
          ciphertext: !!binary |
              BijnWxIyl/NSssZ1ob5nbKHXCRqL5J/WJ4mLgfEhrdXSoVdM/Uztz5ZDvDc8dZ0ohNpf5F
              5rFEnLKSkxPpulZCnBxbsTx5pxJglG/nXyMhk+Qt0PoC+XK1b/vPJBGwDwJF5X+ELM6I2y
              1paZl9S8TIBeoRFLmLxektZa+tYvjLpJ0rIKL3Wj+wTe0lIHCDGE9kfXkUkc5HhcHPdpyA
              lXFGZbsYbYzUvFcf9FMkXsrVd8EBcdqRJrdXFif/nbhOyYvpVCJD0npCcGyr3aO7cXYdym
              iQ6eCguXOJqBEWB/sa+5/p1aiyVedxijgURWuU7sSenraUkcj4mqVdBbpyRKWnh97fDGSD
              LUTux7d5PZwdEMvci0HhHYCJNiFu02rEi07m3hI998CBHsyB0JdEVpO1FIwwkC3vMcDXLu
              w92HG9vPLDGIJHgJl+H5V7LWhLa8wqHgf0103wcn4xxgUu7klQZQR92I2s3VG6ALLg+PSS
              kRhAQvTF9rliSSDEvlb9bQ2mVmGKpvvcFfxPGr54lWxh+sP4j846Gcmj7jpc5buOxf7P59
              ApOdcrbN8qbrrc0LYIc5EhZCpfvdH0sL68DHuTxJaCcW9FxP1LZrSXh/R7vza6gHmW0lsF
              MZZrrcazzv15so1j8RqOdXmzvaxh7fQEuSQoZujMOCD2s6QYzmp1HKUTQ1boEUUBjdXOEn
              q5Z9cLBI7q835o6B6keQMyugbNTRZEv2OP7u8he98wbTS4VpwMnFl4p+6H7qgF1Sn2J4s4
              hPbC7Yl2y9/gfIh036b72Fe3r54FIaIlXETtX8b3jzJx8JvotGn6rk+S1ejmpU1qSlemok
              NKY1OMTt7+s4rxPfuO+4xsMi/4lxYnz5QVPeAm5XFfn4b+D6uzDf9Ju9y8eCY6r+DJYj9p
              sPt3Qgtlrfyi+oAITv5AsEnZCgVNl8mzDv6c1q0H+jePj1SDHPSATXh/OF3gL3yRDAZcDH
              KE0h8hC6SLreDeoPmZUno5ymZeXlm4kbyTm7zbavrvHmvOalTXUeO2w4qwpAqeMFyt2+0w
              Bk8dAwgaWEWa4teuZLht7dovr8BhWWRFV8buxiewpTEn9MXiHyC5lsP64QGwUvIlnBbJk7
              Hu8DjrLcZYMERvBDOHNrcngXSOodIptvIkRnAZjczS4yIUFs+6g2l7MuD+DT956dR+LLRb
              Z32ivn8kQ2VyFKTsHgp7plDP5lSaOG8xLTfxsBKnU2gpp8AA4Cvxu9tpVi8ON4GbS4dTwx
              0j9ESHfyTRcobhep7TkXjCopJBB9FG+MGudeRE64829Pe4KVuj+NulY8/YTtLM3h8MTsAN
              HSfZ0rxdq8OXMWPADH9UAeAbR+WRiM32jkn0jJih0hx6wwom5UK0VawNiB48sWzvDuOBHT
              kQGiMT7HVvQ6LZ9C17XLQa0/DNDqjYzjgK3MqH+FSC3pQUe1Pm9J7r/vQn2QK7SzXAK4S2
              WUNyC6Ou3xq5Ua3oM+MzqK//OjaGSoW0gCR6+JdEQ5dQGjXDQz4wCX/V10hYUIKPPFCpmL
              jZ5X0TFd6sQqJFzREyO/+yKGVssL7oHGBHETWy9++My+7jMKZ+X03eKYgRoq79ZTDzR51k
              6DIcOz0nuO7ZIkQlD+ylAF5+BTZWQwATcSWgnupFH94kLk+Dvi0IRj6PAS6giiBuxG9XoJ
              tYkLBBLkx5skpaeIaGQJ409AoSnzx4mBxBgzUk7rGea6mmQa6PdXe4lwk90XhXrTAWiwqg
              yMfIL5q5ry/+3K8Wv5IjmZ0XiVuoLuM03/lOhF+nXDTiOHA+HyBlGW8mfBgMMSLnxDP0ZM
              kbabTQJ3sZ6j80vXtaFrbptSZnEzoVFUzveQIeih4WjYnMo3qFporciRya4At5E1NcGZcG
              s3JwdV5yA9iEm9OTlFIDGgLCP/wCc3GxD5lFZ8OlbOnY9fasURKVWwOUeqlB4tXdozuJAO
              zviBEfwxar+Tcm6YbGyiIwT5k7uBsOPTtsRggSx3Nxg4AhN3xbVFWCqP8F48gpWHWF3Bf5
              QM6FYFvjFOibl4/nWCGOJiV7AOhFTaBuy+atlt0M2aARzhXCaOykdLNKyxtf2/7T7kTB8M
              F3TDg1DD6NUifoSNzn59voiCWyjBRvY7TKyiBt5SvNJG+qxpLcUndhDimq2xWwXL5OGoNY
              gqa78lcskb3Q7b0RjhMILa7xmrqrGAHVqvLCPbAQbKXt72UoTSGNzuGRyMIYmA60ebGRdZ
              ASVkUuRGfC775hWbZi6o
          mode: 0
          uid: 0
          gid: 0
        - path: /etc/metricsagent/SOLOMON_AUTH
          ciphertext: !!binary |
              J8J6M+U56fK4cVY1k1ykdDeLKCK9tcxFLeuCoTggIy2inuo4zZrr+EY22IwGZxHeKn5zBS
              1w7w==
          mode: 0
          uid: 0
          gid: 0
      enc_mode: DETERMINISTIC
      force: false
