# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yandex/cloud/priv/mdb/mysql/v1/backup.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from yandex.cloud.priv import validation_pb2 as yandex_dot_cloud_dot_priv_dot_validation__pb2
from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+yandex/cloud/priv/mdb/mysql/v1/backup.proto\x12\x1eyandex.cloud.priv.mdb.mysql.v1\x1a\"yandex/cloud/priv/validation.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd6\x02\n\x06\x42\x61\x63kup\x12\x10\n\x02id\x18\x01 \x01(\tB\x04\xa8\x89\x31\x01\x12\x11\n\tfolder_id\x18\x02 \x01(\t\x12.\n\ncreated_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x19\n\x11source_cluster_id\x18\x04 \x01(\t\x12.\n\nstarted_at\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0c\n\x04size\x18\x06 \x01(\x03\x12G\n\x04type\x18\x07 \x01(\x0e\x32\x39.yandex.cloud.priv.mdb.mysql.v1.Backup.BackupCreationType\"U\n\x12\x42\x61\x63kupCreationType\x12$\n BACKUP_CREATION_TYPE_UNSPECIFIED\x10\x00\x12\r\n\tAUTOMATED\x10\x01\x12\n\n\x06MANUAL\x10\x02\x42XB\x03PMBZQa.yandex-team.ru/cloud/bitbucket/private-api/yandex/cloud/priv/mdb/mysql/v1;mysqlb\x06proto3')



_BACKUP = DESCRIPTOR.message_types_by_name['Backup']
_BACKUP_BACKUPCREATIONTYPE = _BACKUP.enum_types_by_name['BackupCreationType']
Backup = _reflection.GeneratedProtocolMessageType('Backup', (_message.Message,), {
  'DESCRIPTOR' : _BACKUP,
  '__module__' : 'yandex.cloud.priv.mdb.mysql.v1.backup_pb2'
  # @@protoc_insertion_point(class_scope:yandex.cloud.priv.mdb.mysql.v1.Backup)
  })
_sym_db.RegisterMessage(Backup)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'B\003PMBZQa.yandex-team.ru/cloud/bitbucket/private-api/yandex/cloud/priv/mdb/mysql/v1;mysql'
  _BACKUP.fields_by_name['id']._options = None
  _BACKUP.fields_by_name['id']._serialized_options = b'\250\2111\001'
  _BACKUP._serialized_start=149
  _BACKUP._serialized_end=491
  _BACKUP_BACKUPCREATIONTYPE._serialized_start=406
  _BACKUP_BACKUPCREATIONTYPE._serialized_end=491
# @@protoc_insertion_point(module_scope)
