FROM cr.yandex/yc/yandex-docker-local-ydb:latest

RUN apt update && apt install -y python3 net-tools

COPY db-ydb/ydb-custom-entrypoint.sh /ydb-custom-entrypoint.sh

ENTRYPOINT ["bash", "ydb-custom-entrypoint.sh"]
