from dl_formula_testing.testcases.misc_funcs import DefaultMiscFunctionalityConnectorTestSuite

from dl_connector_clickhouse_tests.db.formula.base import ClickHouse21p8TestBase


class TestMiscFunctionalityClickHouse21p8(ClickHouse21p8TestBase, DefaultMiscFunctionalityConnectorTestSuite):
    pass
