from dl_formula_testing.testcases.functions_markup import DefaultMarkupFunctionFormulaConnectorTestSuite

from dl_connector_clickhouse_tests.db.formula.base import ClickHouse21p8TestBase


class TestMarkupFunctionClickHouse21p8(ClickHouse21p8TestBase, DefaultMarkupFunctionFormulaConnectorTestSuite):
    pass
