from dl_formula_testing.testcases.functions_window import DefaultWindowFunctionFormulaConnectorTestSuite

from dl_connector_clickhouse_tests.db.formula.base import ClickHouse22p10TestBase


class TestWindowFunctionClickHouse22p10(ClickHouse22p10TestBase, DefaultWindowFunctionFormulaConnectorTestSuite):
    pass
