from dl_formula_testing.testcases.conditional_blocks import DefaultConditionalBlockFormulaConnectorTestSuite

from dl_connector_clickhouse_tests.db.formula.base import ClickHouse21p8TestBase


class TestMainAggFunctionClickHouse21p8(ClickHouse21p8TestBase, DefaultConditionalBlockFormulaConnectorTestSuite):
    pass
