from dl_connector_clickhouse.formula.testing.test_suites import LiteralFunctionClickHouseTestSuite
from dl_connector_clickhouse_tests.db.formula.base import ClickHouse21p8TestBase


class TestLiteralFunctionClickHouse21p8(ClickHouse21p8TestBase, LiteralFunctionClickHouseTestSuite):
    pass
