from dl_connector_clickhouse.formula.testing.test_suites import MathFunctionClickHouseTestSuite
from dl_connector_clickhouse_tests.db.formula.base import ClickHouse21p8TestBase


class TestMathFunctionClickHouse21p8(ClickHouse21p8TestBase, MathFunctionClickHouseTestSuite):
    pass
