from dl_connector_clickhouse_tests.db.formula.base import ClickHouse_22_10TestBase
from dl_formula_testing.testcases.functions_window import DefaultWindowFunctionFormulaConnectorTestSuite


class TestWindowFunctionClickHouse_22_10(ClickHouse_22_10TestBase, DefaultWindowFunctionFormulaConnectorTestSuite):
    pass
