from dl_connector_clickhouse.formula.testing.test_suites import StringFunctionClickHouseTestSuite
from dl_connector_clickhouse_tests.db.formula.base import ClickHouse21p8TestBase


class TestStringFunctionClickHouse21p8(ClickHouse21p8TestBase, StringFunctionClickHouseTestSuite):
    supports_regex_extract_all = True
