from dl_connector_clickhouse.formula.testing.test_suites import MainAggFunctionClickHouseTestSuite
from dl_connector_clickhouse_tests.db.formula.base import ClickHouse21p8TestBase


class TestMainAggFunctionClickHouse21p8(ClickHouse21p8TestBase, MainAggFunctionClickHouseTestSuite):
    pass
