from dl_connector_clickhouse_tests.db.formula.base import ClickHouse_21_8TestBase
from dl_formula_testing.testcases.misc_funcs import DefaultMiscFunctionalityConnectorTestSuite


class TestMiscFunctionalityClickHouse_21_8(ClickHouse_21_8TestBase, DefaultMiscFunctionalityConnectorTestSuite):
    pass
