name: materializer-worker
service_account_id: bfbdtpfu9qlotm99j4h6
scale_policy:
  fixed_scale:
    size: 1
deploy_policy:
  max_unavailable: 1
  # здесь лучше 0, для того чтобы виртуалки не пересоздавались каждый раз
  max_expansion: 0
allocation_policy:
  zones:
  - zone_id: ru-central1-a
variables:
- key: v4_address_vla_1
  value: 178.154.242.184
platform_l7_load_balancer_spec:
  preferred_ip_version: IPV6
  target_group_spec:
    # название вашей таргет-группы, это специальная тг для L7, из интерфейса ее создать невозможно
    name: datalens-preprod-materializer-worker
instance_template:
  # шаблон для имени вм, мы используем такой app_name-{instance.internal_dc}-{instance.index}
  name: materializer-worker-{instance.internal_dc}-{instance.index}
  fqdn: materializer-worker-{instance.internal_dc}-{instance.index}.{instance.internal_dc}.datalens.cloud-preprod.yandex.net
  service_account_id: bfb262anc8g1o3hl75kt
  labels:
    yandex-dns: ig
    conductor-group: datalens-back-preprod
    conductor-role: materializer-worker
  platform_id: standard-v2
  resources_spec:
    memory: 4G
    cores: 2
    core_fraction: 20
  boot_disk_spec:
    mode: READ_WRITE
    disk_spec:
      # айдишник образа, созданного packer-ом, подставляется тимсити, здесь не менять
      image_id: __IMAGE_ID__
      type_id: network-ssd
      size: 10g
  # логи пишутся на secondary-disk, чтобы избежать потери при деплое
  secondary_disk_specs:
  - mode: READ_WRITE
    device_name: data
    disk_spec:
      type_id: network-ssd
      size: 11g
  network_interface_specs:
  - network_id: c64an5jmjnpgiaclqg8k
    primary_v6_address_spec: {}
    primary_v4_address_spec:
      one_to_one_nat_spec:
        address: '{v4_address_{instance.internal_dc}_{instance.index_in_zone}}'
    security_group_ids:
    - c64ud7769sqduk0c71ik
  metadata:
    k8s-runtime-bootstrap-yaml: ' '
    # настройка записи логов на secondary-disk
    user-data: |
      #cloud-config
      fs_setup:
      - device: /dev/disk/by-id/virtio-data
        filesystem: ext4
        partition: auto
        overwrite: false
      mounts:
      - [/dev/disk/by-id/virtio-data, /data, ext4, 'defaults,errors=remount-ro', '0', '2']
      - [/data/log/fluent, /var/log/fluent, none, 'defaults,bind', '0', '0']
      runcmd:
      - mkdir -p /data/log/fluent
      - chmod 0777 /data
      - chown td-agent:td-agent /data/log/fluent
      - chmod 0755 /data/log/fluent
      - mount --make-rprivate /data
      - mount -o bind /data/log/fluent /var/log/fluent
      - /usr/local/bin/update_env_vars
      - /usr/bin/skm decrypt
      - /usr/local/bin/update_secrets
      env_vars:
        AUTH_MODE: gauthling
        BI_WORKER_MAX_AS_MIB: 4000
        CLEANER_DRY_RUN: 0
        DL_CRY_ACTUAL_KEY_ID: cloud_preprod_2
        DL_CRY_FALLBACK_KEY_ID: 0
        FAIL_ON_CREATE_TABLE_DDL_TIMEOUT: 1
        INSERT_QUORUM_FOR_MAT_DB: 2
        INSERT_QUORUM_TIMEOUT_FOR_MAT_DB: 60000
        IS_CELERY_BEAT: 1
        IS_CELERY_WORKER: 1
        RUN_NEW_MAT_TASKS: 1
        SAMPLES_CH_HOST: myt-g2ucdqpavskt6irw.db.yandex.net,sas-1h1276u34g7nt0vx.db.yandex.net,sas-t2pl126yki67ztly.db.yandex.net,vla-1zwdkyy37cy8iz7f.db.yandex.net,c-mdbd60phvp3hvq7d3sq6.rw.db.yandex.net,c-mdbggsqlf0pf2rar6cck.rw.db.yandex.net,c-mdb636es44gm87hucoip.rw.db.yandex.net,sas-gvwzxfe1s83fmwex.db.yandex.net,vla-wwc7qtot5u6hhcqc.db.yandex.net
        YENV_NAME: cloud
        YENV_TYPE: testing
        SLEEP_AFTER_CREATE_TABLE_SEC: 180
    osquery_tag: ycloud-svc-datalens-bi
    shortname: materializer-worker-{instance.internal_dc}-{instance.index}.{instance.internal_dc}
    nsdomain: datalens.cloud-preprod.yandex.net
    skm: |
      api_endpoint: api.cloud-preprod.yandex.net:443
      skip_tls_verify: false
      kms_private_endpoint: ""
      iam_private_endpoint: ""
      kms_private_skip_tls_verify: false
      kms_key_uri: yc-kms://e10mng38moenmrvomcdo
      encrypted_dek: AAAAAQAAABRlMTA5bGE2aGswNXI5NnNhOWhmZAAAABAx3zpV4TflGK+liRAO/0ZjAAAADDPGK7Y50gU4zTmW57Etx/ks4x94zArfioEkoC/36ZtHfYYJ7MTjc7eJMktWi4c+wV0pXPb6RESyZiOzUR7TPBgiPwwusDQbfq2NDmN4zt21oeW2Xv1jXbevKXId
      secrets:
        - path: /etc/secrets/TVM_SECRET
          ciphertext: !!binary VEjh/nYz7X99uCOfK6X/gNo1Z4Q3w6je6MKeX408HtfsUxyodXo=
          mode: 0
          uid: 0
          gid: 0
        - path: /etc/secrets/TVM_INFO
          ciphertext: !!binary |
              XZ+UwKEr9a7w/aP4PLCD3fzmKFXZhTRAV3V1NkIBVDdpliAEmHQR5AlGL7HOxImP3yie4A
              pKzeUCaw==
          mode: 0
          uid: 0
          gid: 0
        - path: /etc/secrets/CACHES_REDIS_PASSWORD
          ciphertext: !!binary 903QxlaqQIKs6zqcH3pJFVaC15/KIyUQORSnuK6bXy3CiQvnkbcL0mRlJ+xWJnIP
          mode: 0
          uid: 0
          gid: 0
        - path: /etc/secrets/REDIS_PASSWORD
          ciphertext: !!binary |
              Jtl67rTu7i/UY7NeZcvl4Zvl2A/F8af9WD9zEPVznY3Cgn9yHyGsk9K+vRVk59k7j3mDNx
              EpXn9nX2g=
          mode: 0
          uid: 0
          gid: 0
        - path: /etc/secrets/PG_PASSWORD
          ciphertext: !!binary |
              +qMaEYoVWonAmwL467LXqvDLMH1AmNP1iL33larB4NLPP4nh5n+6wjmtqiIQK4W1xEzLsZ
              u1E7ph6iE=
          mode: 0
          uid: 0
          gid: 0
        - path: /etc/secrets/BILLING_MASTER_TOKEN
          ciphertext: !!binary |
              oiAkVCG4uPwU6zJX4pqQsi6m7JgE1HZldbL3BgBPICu5dJ0NAfXBOpYNFVNAQzkXey/X4v
              EPTqok9mo=
          mode: 0
          uid: 0
          gid: 0
        - path: /etc/secrets/EXT_QUERY_EXECUTER_SECRET_KEY
          ciphertext: !!binary |
              7q0KDcDGJ/NPSECG7Bc6436doTsYt+YQPk83a9PpqfzQ3/Lyiy3PICxTUOzC+81JKdyPsH
              8EvT7DydQE
          mode: 0
          uid: 0
          gid: 0
        - path: /etc/secrets/BACK_SUPERUSER_IAM_KEY_DATA
          ciphertext: !!binary |
              a1UyS4atm579ApqhXvj/KFQ/7J0Nw2A5GbNhL8yp7i9EEy++I+nwmHaOxLH1tg2U4qRmSp
              HKNVWI9+IU/58Ma8GREkQJlvQ8/lpY1qW5x1aNVxTiPsCMICfjX3miKZ8m7LEQeZWhcHVc
              Cn8PXraF8BlmrG3xr20rw7rJHBFR6aK0KPiW6uCXXRc4lziJpA8yuLW5r9stxjIJSwPsy/
              wbknMRjv0jhvrSoTxH6umiebbrOjDvoUngiQiOZ8g4i8NcWw8h9bp+wKY5W2D9XSzdUvNN
              +EItIhcWYN/heqweQTwrgyKseRDDeeKID599rVJOkrOloYoAKrWPUrhdHiMVijm3HDL6Rh
              2iyVwqE9vxpSRM4L5Aa4SObEbB8BGz2qCs7sm5JL+IFkPCg194c5Lyg3OrJPFNKlAwsRZf
              w/AAAmZiRpdWun4n9N+SlhQBx4WIVlN6BzGmH33hrxwkvZXuBRBHrC9iNrdUW6qb5gsocA
              f0FEuObNaqfiTUSapge/XJy+jqsOaH9MjEfhKeD+9CTGtW7LsFxBu3rrR1IPp7HflqYBOY
              4fF116NNsPTRBut2AlNE9+hArZKBmBduLPrs2YNmEpTRAGHsZcNGyCnLTFHiujugDq0iWy
              PWsMS7izV0MnJoLQZTbvc4+R0d4hYbhANAg/OGeIb+P8QVPentDZAJVSfyH+wzrWyuMwYu
              980AQNh5ErwIDtM5SST8VDoBsZc/Op3wkBUVt4DJPta7gwA790PzKMY2b1+iWulxWFaB5Z
              0XopPwQ3uruONPtg2DSfOGpy+DFd5m/bZKvfbsVLjQ/jwFb0jo60BoClHTZ9Cc/3gxEZoX
              gN9O4rbe9d3jLtLAXo+RLVJlS5Zq/YdbGqNc9ytApQ38znssVVPaNI/sCWgyt2UvtDZegF
              7T2/lO9inLiZeDIe85+ASLR12tEzDXujN0Gn6sCfqc4b8oWP/axVRL2Uhn5lnxbVu3JAjL
              LG58qMeaeXkv30pvZIu3oy5oXIxX7Rb7aKmo8q5RkLrxBl7N6jduVyhqNokdp1GkGnYT3u
              ElTzvfyIAiLi582c2rtMW+5KU0wh/I2fl427LI7LfMwsGqhSNdAd9OUFg8orFXz8LsKT/2
              8UPWhmwSo8mq8/w7s0f0sHlkRCjfeLBSy2+/CR280KWotOP7LaKFDeU0oZ4iSAfFcNyBJB
              hzBy3WqsuSu0dM1nby0gfpoG4evxDaEIfCYXQqRBMy1A2peXDsvhMdQWdFVxMgo533i30w
              nYUFTnaC5IgAQRP5ELrBd6t4BZqwEGm/1K2GO/Fcjn/qFMbb8Rgx+sTUj+GuQH4TA3/TTP
              SkefTKba8EgVC8S3dJ9vl5bcCu8GajA9mWAsiirE/7PT/GaA/KhroD4EBveIS2S6QkRJ/t
              JK/evw5tQowtoNDUh0bih4S60uwxz+sFVppJzJxMJUdVOC++hjolrclwcMxF3T+yKzqI70
              6L2Wlozt7leIdqhurPQ+I6TgX35O2Fn+0UcRx0o8FYhOrOJvtQAa7t/N3shnY0Tn9H3xqX
              Nt9tQ9UgmFPQygLy9atbRAcERfCcq0aRM0YlZYLe8N3Ns//GSU76f43pTII1TKhryghThn
              EtCEyJ8LWlPCousFHFEK1vF3GCVSJbNWqYPzKayhyt35+DcJ5ZRwnX4K8vHABo7VUFJzcu
              78HSQ8JTkkx+wo8N3TFJpuz9I1t4+q3UkYHQAGMXQFKp6tzx7jtuxqW5hd74YQYrC4NCWS
              cIKRG6LYKonfbvKmC6o7fqaCjJYBxV4rwut+vavQPN4JU2RSTWJQXSBUS41saxiKGfqBmI
              8NarfIkuyhIjhpaXzW+3HTQtjcdsD4WkRuINwxebQtLHtJbbODVFHHgT9MHHOx/3IC7NwS
              iAn803Gm6xWz6gzO9w3DB3Jyj4kfeqw7k9eE2D0j+Zr6j8HrL3CNpsn+IaB1c/k1XW7BUg
              ufIwn720TAo1zic7TkDXklHH3kUUkoWLE5DEgedVNEXV60QHy1mb7kYv+LRM+g7pZxA5ld
              tEhcgjuSjrKgASngJR32KPUgZdN233S41W5Q+O/e7FwlfjTz7pk4MIcRBHKOoKGsO1GsrI
              gAvDocFcMQqa2gD0Oe4ngv3CMTcVwN8bWEx0GdqK2F8Xrmhjb7IDGkc5Z1/LjzhsFMIOiu
              qn0X+knxDqSCy9MXWt5c6tWc8ncKPZPbL591zunjoV1r8BgT5pYL7K3unY7+nKMReAnZ4d
              QQzhgTjVR3H78fzu7gZh/AwswioAYFFjwpx84fcd0stRdj/HSFGpe/vmyC/34vCJkw9LBE
              nQdYRZYrsy6ubbQ9eNXvjUbDnUJLPExJ49mL/m98LoUbRfvWSyhR1K9JWuP4BNoLtrr5b/
              g92JZwy5CY7ECeF9XorAWq9i1/LaJTYsxa5Wb9sPsArPuOQQmufMJbg48SV/HXN/HHOwyZ
              VADBOAZnotRvh9G8ZNPGouWL5xS+o0Q3XoOQI6hJ2iSdJwTHgksJ03FX1DFYLw6XUMWVeo
              1tOglMFN85Xa+gReNzPRJWt4Y6RaRWCyfTXF6kKTcHk1ki4iBAaNE9L43mme5V/vQNLvRT
              j+1Jh9H60PX+ulam1nCTsac39bkPL5VgNRFEgUZR852Lq6DDo3WDeGFcHTeyX8phxUiEpo
              ysFfovTm1qzkArBsHg3lGZhh2rZb3gzaprd8I7gW5Iq7Or7LcO5PwK96yifgzrPNh4cyt8
              Litk+QUYV7ZXBfDIFb2RcqQ4FGYFQ1dfVthhEWDk735kSS+PBtyLIDI+C6qXBOOOjRZ+QS
              VjonupgQK7gIInkdPPkmNNbZvAqx8osliLxbgceFg6Hhlzzml0brgM2LzV4joUxcHtBJHr
              LBdtaA+z1Anz/LmCfjlAyiT5zGKlnU8jpyBVBVTJ/TZpcLa4j7dBP6wli9kKTu/Y9c0Am8
              EKgS17sVcE93bReS6cQZPhAF/JW2vcRoz4Orl7hpETqaFIkhsQlLeLQcP432YQWCThToys
              9LntcpvsTv9KNO7gFa66Y5rUseA7PhLXERWlbyr5G0wkA42eVQLqYLQE0MAqgR6XfKAk1z
              76Cvk8LOzyyZHmK/wmVXVO4VA7Rf918Dopj+qfI99AXg+/7euKF6ZwfBT5BPAwpAFdkH/1
              Xd0OzllMAbA0oFc0JG5TN9lgM/yJ4FVmTZrDOBsgjHwZaIfe/I/N0TsPieoTBqsLNEEnoB
              UcV+52JydpMdmyodNFzFuwlRVLPLrBWmV48ZdVZi2d3CGWnV1QOqn3aDMG+1udvzUjH6qO
              MgFRx12enTIlIyn419YXiMyaZTPPSjl92lniecCTWSrblRtIJhPI70lOBZk8Ivbvd9pLYg
              xsX2eGzH8yocT66qYYC0Uv8dTeugr4grDgq5ko9Cc5G6a9oDQ9krLGP1Z6Jv06cYOgcS6a
              h4GFnF4X7RNK+SeP1As9u8CYJTqEmjUbNRQ1+GehK3Rk3BE6huRkU41xwgpqJosbwzpTCZ
              wxiLBObjcIW3Y8gI/8C/OJGOWHl/p36C62MujfNUh2uDOExo9OtDxyFavGhBk9ILTIIluK
              Wdfc2jjcwgczFeZFGwWKRyKFioHlErLWv5sAhJbzOL6mZ5tB8BMpHuAY7RddfHFi+//7rc
              Ryg4JmrcuB2jfPUVxjQSoRcFpxlz8xfzBw/W9P0MZwvZ9Pl8FnuWCp2HqfD0j9HpEV9GC0
              2x3kmzW+TILllFaq61pcYmRV7HrBtVD5AeRK2D0XciyeDGHQ7IXSl2aRCVq1P60jRfxXdl
              qmsTCdGcFSCDTmxCKvszxjmlL8DkJpAS6mk1Qa+j5QvsyQ2vFLzANogvTxhcrWgN6oPVN9
              9mTjgWqrH6H+0aUgGk+9gRreQH9P2NwxabOqEZSi9JVY7eDsNXETyvWkJ1x5FZTlH6iCUy
              AWFAT2KP9agFtLO2iUaZKSZRRKQfsgEika/daHdP0BMEesgJ0+EFyuzYd5etRRxuG0BOTV
              8HTM15mkkrVV+xvL2MgcPUXescuD6TH1C9IZLol4BYuGY6kXNelPRREWR6QUbupZcUbRql
              40UC+3lwKzZ9foJVozOqsRW+TYibBDC6YUh96BuQfWTEJxHNexs1SkveWBtocCe3uF56nt
              CfR7MVz3apjT9joW40gd05FTBEJnQo9kUrFfKTT70xDX4EHMYN+Vb464nmo/GUCE8CxtOx
              RhxmEJUZmdxK9gTBlKVmM5JU2uPoST1oj2tHsiq/GdTAAI0F/bqHZBPnHE9cfEIocZMaCJ
              6Iu7pXeYsoznGDGAnRyQh1nvnY/AWQzMxe/efBhkf2RCApFUcjueOh+aNABQWV8CTQsj93
              H0RZKypRHOmikNwSX2JM8xL8+WFveHD9Gjk5RmCSl03iNYL2i8tUi2xplTKAS5jxEF4i0b
              tYmuDT0vlvmFEdkzwkt1NgQOFHLw7EsVbbZVdPrVaWSwzq/+sJTeYmenlz0VDQZr9LGt4s
              mhQlApUMEIWto3GPo0sNZ2tkiivItYX/mbk3BrUYmuFP3gd2lJ2XhgYUDfzonYdZ4nI3AE
              eE21AAngxsUPyaeDFvvYqHfiaVwz7PNE4=
          mode: 0
          uid: 0
          gid: 0
        - path: /etc/secrets/DL_CRY_KEY_VAL_ID_cloud_preprod_2
          ciphertext: !!binary |
              gQrkY7+evFubkiCJUdiWPP9YXxiWVivG5NvI1bQbzMnMqlJQMTpM60nMr863J2RJa9ZwFI
              3CkXHr8RB3
          mode: 0
          uid: 0
          gid: 0
        - path: /etc/secrets/US_MASTER_TOKEN
          ciphertext: !!binary 8U0HxY7v/kVS8eKo+81LYBn/V7zAPs+adaRo/oOrEZWvJO3bNgEacGaA/4s2/Dza
          mode: 0
          uid: 0
          gid: 0
        - path: /etc/secrets/YANDEX_MAPS_API_KEY
          ciphertext: !!binary |
              QYS67gtWyPLYlEJThS4URrtTXISc/Ya0FmAU7huXNHq4cJp1IKvpKtCflCaHakNpl9RD2Q
              ==
          mode: 0
          uid: 0
          gid: 0
        - path: /etc/secrets/GEO_DICT_DST_CLUSTERS_INFO
          ciphertext: !!binary |
              t++xu9QVFPIRCwCW+eP3BN2shmALCKE+FTmjcPiquIwpc0M9QM5um8TUvWajTgUmuBrfzO
              VP1lsCNQs6QLPX0p0v4R/J5E+mjHhXRy0PFT2gu1ShFmh2iaVYy66OyTNIo+dozr8o22cU
              RPFMMMuQ0jAgNbktA4SZqdopRRjCeVBxOwHmEA/GJMCX8Tm+pFX37GyY0mTyauxGYJ5G1J
              PS80HAlQGQ4xc2+kJPUCrH8wJnEBAYs99IFh/4ybEKzOD1LYxJF21Jdtwq74cjVfNsHw==
          mode: 0
          uid: 0
          gid: 0
        - path: /etc/secrets/UI_CONTROL_MASTER_TOKEN
          ciphertext: !!binary 03ydSWO9JzM42mKlh8tZvEkw35AeuB9BGThUaDz7ogF2NA7UxVCA
          mode: 0
          uid: 0
          gid: 0
        - path: /etc/secrets/MAT_CH_SERVICE_USER_PASSWORD
          ciphertext: !!binary DxdR1hmogD2jWGtO+KXI3KLyJX5nioWLF0UNpw==
          mode: 0
          uid: 0
          gid: 0
        - path: /etc/secrets/LOGCH_PASSWORD
          ciphertext: !!binary oYWflSY1FHGAYPo7EF1PDqEnESQLobJRy169bMtNptumGhVAzJKH1lwo
          mode: 0
          uid: 0
          gid: 0
        - path: /etc/metricsagent/SOLOMON_AUTH
          ciphertext: !!binary |
              kyLgW6yhmndZNeAmXXEmViHtAKVFNjlfogYaK8gUJQIEtPSyI2Pg49hLBZECE/zaHfgMOK
              V03A==
          mode: 0
          uid: 0
          gid: 0
      enc_mode: DETERMINISTIC
      force: false
