#!/usr/bin/env sh

set -x  # debug.
set -eu

HTTP_BIND_PORT="${HTTP_BIND_PORT:-80}"
if [ "${BISYS_USE_IPV6:-1}" = "1" ]; then HTTP_BIND_ADDR="[::]"; else HTTP_BIND_ADDR="0.0.0.0"; fi

BI_API_UWSGI_WORKERS_COUNT="${BI_API_UWSGI_WORKERS_COUNT:-40}"

# It is also set in the ini file, but that might not work in some cases.
UWSGI_STATS=/tmp/uwsgi_stats.sock
HTTP_BIND="${HTTP_BIND_ADDR}:${HTTP_BIND_PORT}"

export BI_API_UWSGI_WORKERS_COUNT UWSGI_STATS HTTP_BIND
exec \
    uwsgi \
        --ini="${UWSGI_INI_FOR_APP}"
