from dl_api_lib_testing.connector.complex_queries import DefaultBasicComplexQueryTestSuite

from dl_connector_starrocks_tests.db.api.base import StarRocksDataApiTestBase


class TestStarRocksBasicComplexQueries(StarRocksDataApiTestBase, DefaultBasicComplexQueryTestSuite):
    pass
