#!/usr/bin/env sh

set -x  # debug.
set -eu

if [ "${LOCAL_RQE_INT_SYNC:-1}" = "0" ]; then
    sleep 9000
    exit 0
fi

HTTP_BIND_PORT="${RQE_INT_SYNC_PORT:-9874}"
RQE_UWSGI_WORKERS_COUNT="${RQE_INT_SYNC_WORKERS_COUNT:-16}"
RQE_UWSGI_THREADS_COUNT="${RQE_INT_SYNC_THREADS_COUNT:-10}"
RQE_RSS_LIMIT="${RQE_INT_SYNC_RSS_LIMIT:-1073741824}"  # 1GB
if [ "${BISYS_USE_IPV6:-1}" = "1" ]; then HTTP_BIND_ADDR="[::1]"; else HTTP_BIND_ADDR="127.0.0.1"; fi

HTTP_BIND="${HTTP_BIND_ADDR}:${HTTP_BIND_PORT}"
export HTTP_BIND RQE_UWSGI_WORKERS_COUNT RQE_UWSGI_THREADS_COUNT
exec \
    chpst -u www-data:www-data \
    prlimit --rss=${RQE_RSS_LIMIT} \
    uwsgi \
        --ini=${UWSGI_INI_FOR_RQE} \
        --stats=/tmp/uwsgi_stats_rqe_int_sync.sock
