# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from yandex.cloud.priv.mdb.greenplum.v1.yagpcc import yagpcc_service_pb2 as yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_yagpcc_dot_yagpcc__service__pb2


class YAGPCCHistoryServiceStub(object):
    """A set of methods for getting history of Greenplum performance diagnostic.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListSessionsAtTime = channel.unary_unary(
                '/yandex.cloud.priv.mdb.greenplum.v1.yagpcc.YAGPCCHistoryService/ListSessionsAtTime',
                request_serializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_yagpcc_dot_yagpcc__service__pb2.ListSessionsAtTimeRequest.SerializeToString,
                response_deserializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_yagpcc_dot_yagpcc__service__pb2.SessionsInfoResponse.FromString,
                )
        self.GetSessionDetails = channel.unary_unary(
                '/yandex.cloud.priv.mdb.greenplum.v1.yagpcc.YAGPCCHistoryService/GetSessionDetails',
                request_serializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_yagpcc_dot_yagpcc__service__pb2.GetSessionDetailsRequest.SerializeToString,
                response_deserializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_yagpcc_dot_yagpcc__service__pb2.GetSessionDetailsResponse.FromString,
                )
        self.GetSessionHistory = channel.unary_unary(
                '/yandex.cloud.priv.mdb.greenplum.v1.yagpcc.YAGPCCHistoryService/GetSessionHistory',
                request_serializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_yagpcc_dot_yagpcc__service__pb2.GetSessionHistoryRequest.SerializeToString,
                response_deserializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_yagpcc_dot_yagpcc__service__pb2.SessionsInfoResponse.FromString,
                )
        self.ListQueriesForPeriod = channel.unary_unary(
                '/yandex.cloud.priv.mdb.greenplum.v1.yagpcc.YAGPCCHistoryService/ListQueriesForPeriod',
                request_serializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_yagpcc_dot_yagpcc__service__pb2.ListQueriesForPeriodRequest.SerializeToString,
                response_deserializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_yagpcc_dot_yagpcc__service__pb2.ListQueriesResponse.FromString,
                )
        self.GetQueryDetails = channel.unary_unary(
                '/yandex.cloud.priv.mdb.greenplum.v1.yagpcc.YAGPCCHistoryService/GetQueryDetails',
                request_serializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_yagpcc_dot_yagpcc__service__pb2.GetQueryDetailsRequest.SerializeToString,
                response_deserializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_yagpcc_dot_yagpcc__service__pb2.GetQueryDetailsResponse.FromString,
                )
        self.GetAggregatedQueryDetails = channel.unary_unary(
                '/yandex.cloud.priv.mdb.greenplum.v1.yagpcc.YAGPCCHistoryService/GetAggregatedQueryDetails',
                request_serializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_yagpcc_dot_yagpcc__service__pb2.GetAggregatedQueryDetailsRequest.SerializeToString,
                response_deserializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_yagpcc_dot_yagpcc__service__pb2.GetQueryDetailsResponse.FromString,
                )
        self.GetStatisticsTotal = channel.unary_unary(
                '/yandex.cloud.priv.mdb.greenplum.v1.yagpcc.YAGPCCHistoryService/GetStatisticsTotal',
                request_serializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_yagpcc_dot_yagpcc__service__pb2.GetStatisticsTotalRequest.SerializeToString,
                response_deserializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_yagpcc_dot_yagpcc__service__pb2.GetStatisticsTotalResponse.FromString,
                )
        self.GetStatisticsWithRollup = channel.unary_unary(
                '/yandex.cloud.priv.mdb.greenplum.v1.yagpcc.YAGPCCHistoryService/GetStatisticsWithRollup',
                request_serializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_yagpcc_dot_yagpcc__service__pb2.GetStatisticsWithRollupRequest.SerializeToString,
                response_deserializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_yagpcc_dot_yagpcc__service__pb2.GetStatisticsWithRollupResponse.FromString,
                )


class YAGPCCHistoryServiceServicer(object):
    """A set of methods for getting history of Greenplum performance diagnostic.
    """

    def ListSessionsAtTime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSessionDetails(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSessionHistory(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListQueriesForPeriod(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetQueryDetails(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetAggregatedQueryDetails(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatisticsTotal(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatisticsWithRollup(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_YAGPCCHistoryServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListSessionsAtTime': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSessionsAtTime,
                    request_deserializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_yagpcc_dot_yagpcc__service__pb2.ListSessionsAtTimeRequest.FromString,
                    response_serializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_yagpcc_dot_yagpcc__service__pb2.SessionsInfoResponse.SerializeToString,
            ),
            'GetSessionDetails': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSessionDetails,
                    request_deserializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_yagpcc_dot_yagpcc__service__pb2.GetSessionDetailsRequest.FromString,
                    response_serializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_yagpcc_dot_yagpcc__service__pb2.GetSessionDetailsResponse.SerializeToString,
            ),
            'GetSessionHistory': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSessionHistory,
                    request_deserializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_yagpcc_dot_yagpcc__service__pb2.GetSessionHistoryRequest.FromString,
                    response_serializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_yagpcc_dot_yagpcc__service__pb2.SessionsInfoResponse.SerializeToString,
            ),
            'ListQueriesForPeriod': grpc.unary_unary_rpc_method_handler(
                    servicer.ListQueriesForPeriod,
                    request_deserializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_yagpcc_dot_yagpcc__service__pb2.ListQueriesForPeriodRequest.FromString,
                    response_serializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_yagpcc_dot_yagpcc__service__pb2.ListQueriesResponse.SerializeToString,
            ),
            'GetQueryDetails': grpc.unary_unary_rpc_method_handler(
                    servicer.GetQueryDetails,
                    request_deserializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_yagpcc_dot_yagpcc__service__pb2.GetQueryDetailsRequest.FromString,
                    response_serializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_yagpcc_dot_yagpcc__service__pb2.GetQueryDetailsResponse.SerializeToString,
            ),
            'GetAggregatedQueryDetails': grpc.unary_unary_rpc_method_handler(
                    servicer.GetAggregatedQueryDetails,
                    request_deserializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_yagpcc_dot_yagpcc__service__pb2.GetAggregatedQueryDetailsRequest.FromString,
                    response_serializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_yagpcc_dot_yagpcc__service__pb2.GetQueryDetailsResponse.SerializeToString,
            ),
            'GetStatisticsTotal': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatisticsTotal,
                    request_deserializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_yagpcc_dot_yagpcc__service__pb2.GetStatisticsTotalRequest.FromString,
                    response_serializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_yagpcc_dot_yagpcc__service__pb2.GetStatisticsTotalResponse.SerializeToString,
            ),
            'GetStatisticsWithRollup': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatisticsWithRollup,
                    request_deserializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_yagpcc_dot_yagpcc__service__pb2.GetStatisticsWithRollupRequest.FromString,
                    response_serializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_yagpcc_dot_yagpcc__service__pb2.GetStatisticsWithRollupResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'yandex.cloud.priv.mdb.greenplum.v1.yagpcc.YAGPCCHistoryService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class YAGPCCHistoryService(object):
    """A set of methods for getting history of Greenplum performance diagnostic.
    """

    @staticmethod
    def ListSessionsAtTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/yandex.cloud.priv.mdb.greenplum.v1.yagpcc.YAGPCCHistoryService/ListSessionsAtTime',
            yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_yagpcc_dot_yagpcc__service__pb2.ListSessionsAtTimeRequest.SerializeToString,
            yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_yagpcc_dot_yagpcc__service__pb2.SessionsInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSessionDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/yandex.cloud.priv.mdb.greenplum.v1.yagpcc.YAGPCCHistoryService/GetSessionDetails',
            yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_yagpcc_dot_yagpcc__service__pb2.GetSessionDetailsRequest.SerializeToString,
            yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_yagpcc_dot_yagpcc__service__pb2.GetSessionDetailsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSessionHistory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/yandex.cloud.priv.mdb.greenplum.v1.yagpcc.YAGPCCHistoryService/GetSessionHistory',
            yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_yagpcc_dot_yagpcc__service__pb2.GetSessionHistoryRequest.SerializeToString,
            yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_yagpcc_dot_yagpcc__service__pb2.SessionsInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListQueriesForPeriod(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/yandex.cloud.priv.mdb.greenplum.v1.yagpcc.YAGPCCHistoryService/ListQueriesForPeriod',
            yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_yagpcc_dot_yagpcc__service__pb2.ListQueriesForPeriodRequest.SerializeToString,
            yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_yagpcc_dot_yagpcc__service__pb2.ListQueriesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetQueryDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/yandex.cloud.priv.mdb.greenplum.v1.yagpcc.YAGPCCHistoryService/GetQueryDetails',
            yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_yagpcc_dot_yagpcc__service__pb2.GetQueryDetailsRequest.SerializeToString,
            yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_yagpcc_dot_yagpcc__service__pb2.GetQueryDetailsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetAggregatedQueryDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/yandex.cloud.priv.mdb.greenplum.v1.yagpcc.YAGPCCHistoryService/GetAggregatedQueryDetails',
            yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_yagpcc_dot_yagpcc__service__pb2.GetAggregatedQueryDetailsRequest.SerializeToString,
            yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_yagpcc_dot_yagpcc__service__pb2.GetQueryDetailsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetStatisticsTotal(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/yandex.cloud.priv.mdb.greenplum.v1.yagpcc.YAGPCCHistoryService/GetStatisticsTotal',
            yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_yagpcc_dot_yagpcc__service__pb2.GetStatisticsTotalRequest.SerializeToString,
            yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_yagpcc_dot_yagpcc__service__pb2.GetStatisticsTotalResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetStatisticsWithRollup(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/yandex.cloud.priv.mdb.greenplum.v1.yagpcc.YAGPCCHistoryService/GetStatisticsWithRollup',
            yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_yagpcc_dot_yagpcc__service__pb2.GetStatisticsWithRollupRequest.SerializeToString,
            yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_yagpcc_dot_yagpcc__service__pb2.GetStatisticsWithRollupResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class YAGPCCActualServiceStub(object):
    """A set of methods for getting actual Greenplum status

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListSessionsAtTime = channel.unary_unary(
                '/yandex.cloud.priv.mdb.greenplum.v1.yagpcc.YAGPCCActualService/ListSessionsAtTime',
                request_serializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_yagpcc_dot_yagpcc__service__pb2.ListSessionsAtTimeRequest.SerializeToString,
                response_deserializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_yagpcc_dot_yagpcc__service__pb2.SessionsInfoResponse.FromString,
                )
        self.GetSessionDetails = channel.unary_unary(
                '/yandex.cloud.priv.mdb.greenplum.v1.yagpcc.YAGPCCActualService/GetSessionDetails',
                request_serializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_yagpcc_dot_yagpcc__service__pb2.GetSessionDetailsRequest.SerializeToString,
                response_deserializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_yagpcc_dot_yagpcc__service__pb2.GetSessionDetailsResponse.FromString,
                )
        self.GetQueryDetails = channel.unary_unary(
                '/yandex.cloud.priv.mdb.greenplum.v1.yagpcc.YAGPCCActualService/GetQueryDetails',
                request_serializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_yagpcc_dot_yagpcc__service__pb2.GetQueryDetailsRequest.SerializeToString,
                response_deserializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_yagpcc_dot_yagpcc__service__pb2.GetQueryDetailsResponse.FromString,
                )


class YAGPCCActualServiceServicer(object):
    """A set of methods for getting actual Greenplum status

    """

    def ListSessionsAtTime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSessionDetails(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetQueryDetails(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_YAGPCCActualServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListSessionsAtTime': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSessionsAtTime,
                    request_deserializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_yagpcc_dot_yagpcc__service__pb2.ListSessionsAtTimeRequest.FromString,
                    response_serializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_yagpcc_dot_yagpcc__service__pb2.SessionsInfoResponse.SerializeToString,
            ),
            'GetSessionDetails': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSessionDetails,
                    request_deserializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_yagpcc_dot_yagpcc__service__pb2.GetSessionDetailsRequest.FromString,
                    response_serializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_yagpcc_dot_yagpcc__service__pb2.GetSessionDetailsResponse.SerializeToString,
            ),
            'GetQueryDetails': grpc.unary_unary_rpc_method_handler(
                    servicer.GetQueryDetails,
                    request_deserializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_yagpcc_dot_yagpcc__service__pb2.GetQueryDetailsRequest.FromString,
                    response_serializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_yagpcc_dot_yagpcc__service__pb2.GetQueryDetailsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'yandex.cloud.priv.mdb.greenplum.v1.yagpcc.YAGPCCActualService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class YAGPCCActualService(object):
    """A set of methods for getting actual Greenplum status

    """

    @staticmethod
    def ListSessionsAtTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/yandex.cloud.priv.mdb.greenplum.v1.yagpcc.YAGPCCActualService/ListSessionsAtTime',
            yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_yagpcc_dot_yagpcc__service__pb2.ListSessionsAtTimeRequest.SerializeToString,
            yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_yagpcc_dot_yagpcc__service__pb2.SessionsInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSessionDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/yandex.cloud.priv.mdb.greenplum.v1.yagpcc.YAGPCCActualService/GetSessionDetails',
            yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_yagpcc_dot_yagpcc__service__pb2.GetSessionDetailsRequest.SerializeToString,
            yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_yagpcc_dot_yagpcc__service__pb2.GetSessionDetailsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetQueryDetails(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/yandex.cloud.priv.mdb.greenplum.v1.yagpcc.YAGPCCActualService/GetQueryDetails',
            yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_yagpcc_dot_yagpcc__service__pb2.GetQueryDetailsRequest.SerializeToString,
            yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_yagpcc_dot_yagpcc__service__pb2.GetQueryDetailsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)


class YAGPCCActionServiceStub(object):
    """A set of methods to perform actions in GP cluster 

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.TerminateQuery = channel.unary_unary(
                '/yandex.cloud.priv.mdb.greenplum.v1.yagpcc.YAGPCCActionService/TerminateQuery',
                request_serializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_yagpcc_dot_yagpcc__service__pb2.TerimanteQueryRequest.SerializeToString,
                response_deserializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_yagpcc_dot_yagpcc__service__pb2.TerimanteResponse.FromString,
                )
        self.TerminateSession = channel.unary_unary(
                '/yandex.cloud.priv.mdb.greenplum.v1.yagpcc.YAGPCCActionService/TerminateSession',
                request_serializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_yagpcc_dot_yagpcc__service__pb2.TerimanteSessionRequest.SerializeToString,
                response_deserializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_yagpcc_dot_yagpcc__service__pb2.TerimanteResponse.FromString,
                )


class YAGPCCActionServiceServicer(object):
    """A set of methods to perform actions in GP cluster 

    """

    def TerminateQuery(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TerminateSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_YAGPCCActionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'TerminateQuery': grpc.unary_unary_rpc_method_handler(
                    servicer.TerminateQuery,
                    request_deserializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_yagpcc_dot_yagpcc__service__pb2.TerimanteQueryRequest.FromString,
                    response_serializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_yagpcc_dot_yagpcc__service__pb2.TerimanteResponse.SerializeToString,
            ),
            'TerminateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.TerminateSession,
                    request_deserializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_yagpcc_dot_yagpcc__service__pb2.TerimanteSessionRequest.FromString,
                    response_serializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_yagpcc_dot_yagpcc__service__pb2.TerimanteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'yandex.cloud.priv.mdb.greenplum.v1.yagpcc.YAGPCCActionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class YAGPCCActionService(object):
    """A set of methods to perform actions in GP cluster 

    """

    @staticmethod
    def TerminateQuery(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/yandex.cloud.priv.mdb.greenplum.v1.yagpcc.YAGPCCActionService/TerminateQuery',
            yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_yagpcc_dot_yagpcc__service__pb2.TerimanteQueryRequest.SerializeToString,
            yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_yagpcc_dot_yagpcc__service__pb2.TerimanteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TerminateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/yandex.cloud.priv.mdb.greenplum.v1.yagpcc.YAGPCCActionService/TerminateSession',
            yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_yagpcc_dot_yagpcc__service__pb2.TerimanteSessionRequest.SerializeToString,
            yandex_dot_cloud_dot_priv_dot_mdb_dot_greenplum_dot_v1_dot_yagpcc_dot_yagpcc__service__pb2.TerimanteResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
