from dl_connector_bigquery_tests.ext.formula.base import BigQueryTestBase
from dl_formula_testing.testcases.conditional_blocks import DefaultConditionalBlockFormulaConnectorTestSuite


class TestConditionalBlockBigQuery(BigQueryTestBase, DefaultConditionalBlockFormulaConnectorTestSuite):
    pass
