apiVersion: v1
kind: Pod
metadata:
  name: application
  namespace: kube-system
  annotations:
    scheduler.alpha.kubernetes.io/critical-pod: ""
spec:
  priority: 2000000001
  priorityClassName: system-cluster-critical
  hostNetwork: true
  containers:
    - name: main-app
      image: {{ pillar['BUILD_IMAGE_URL'] }}
      securityContext:
        capabilities:
          add:
            - NET_ADMIN
      volumeMounts:
        - name: common-secrets
          mountPath: /etc/secrets
          readOnly: true
        - name: ca-certificates
          mountPath: /usr/local/share/ca-certificates
          readOnly: true
      env: {}
  volumes:
    - name: common-secrets
      hostPath:
        path: /etc/secrets
        type: Directory
    - name: ca-certificates
      hostPath:
        path: /usr/local/share/ca-certificates
        type: Directory
    - name: tvm-config
      hostPath:
        path: /etc/tvm
        type: Directory
