from dl_api_lib_testing.connector.complex_queries import DefaultBasicComplexQueryTestSuite
from dl_constants.enums import QueryProcessingMode

from dl_connector_postgresql_tests.db.api.base import PostgreSQLDataApiTestBase


class TestPostgreSQLBasicComplexQueries(PostgreSQLDataApiTestBase, DefaultBasicComplexQueryTestSuite):
    query_processing_mode = QueryProcessingMode.native_wf
