# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yandex/cloud/priv/iam/v1/transitional/health_check_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from yandex.cloud.api.tools import options_pb2 as yandex_dot_cloud_dot_api_dot_tools_dot_options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n@yandex/cloud/priv/iam/v1/transitional/health_check_service.proto\x12%yandex.cloud.priv.iam.v1.transitional\x1a\x1cgoogle/api/annotations.proto\x1a$yandex/cloud/api/tools/options.proto\"\x14\n\x12HealthCheckRequest\"\xad\x01\n\x13HealthCheckResponse\x12W\n\x06health\x18\x01 \x01(\x0e\x32G.yandex.cloud.priv.iam.v1.transitional.HealthCheckResponse.HealthStatus\"=\n\x0cHealthStatus\x12\n\n\x06PASSED\x10\x00\x12\n\n\x06\x46\x41ILED\x10\x01\x12\x0b\n\x07UNKNOWN\x10\x02\x1a\x08\xca\xef \x04\x12\x02\x18\x01\x32\xb1\x01\n\x12HealthCheckService\x12\x9a\x01\n\tGetHealth\x12\x39.yandex.cloud.priv.iam.v1.transitional.HealthCheckRequest\x1a:.yandex.cloud.priv.iam.v1.transitional.HealthCheckResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/iam/v1/healthB_B\x05PTHCSZVa.yandex-team.ru/cloud/bitbucket/private-api/yandex/cloud/priv/iam/v1/transitional;iamb\x06proto3')



_HEALTHCHECKREQUEST = DESCRIPTOR.message_types_by_name['HealthCheckRequest']
_HEALTHCHECKRESPONSE = DESCRIPTOR.message_types_by_name['HealthCheckResponse']
_HEALTHCHECKRESPONSE_HEALTHSTATUS = _HEALTHCHECKRESPONSE.enum_types_by_name['HealthStatus']
HealthCheckRequest = _reflection.GeneratedProtocolMessageType('HealthCheckRequest', (_message.Message,), {
  'DESCRIPTOR' : _HEALTHCHECKREQUEST,
  '__module__' : 'yandex.cloud.priv.iam.v1.transitional.health_check_service_pb2'
  # @@protoc_insertion_point(class_scope:yandex.cloud.priv.iam.v1.transitional.HealthCheckRequest)
  })
_sym_db.RegisterMessage(HealthCheckRequest)

HealthCheckResponse = _reflection.GeneratedProtocolMessageType('HealthCheckResponse', (_message.Message,), {
  'DESCRIPTOR' : _HEALTHCHECKRESPONSE,
  '__module__' : 'yandex.cloud.priv.iam.v1.transitional.health_check_service_pb2'
  # @@protoc_insertion_point(class_scope:yandex.cloud.priv.iam.v1.transitional.HealthCheckResponse)
  })
_sym_db.RegisterMessage(HealthCheckResponse)

_HEALTHCHECKSERVICE = DESCRIPTOR.services_by_name['HealthCheckService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'B\005PTHCSZVa.yandex-team.ru/cloud/bitbucket/private-api/yandex/cloud/priv/iam/v1/transitional;iam'
  _HEALTHCHECKRESPONSE_HEALTHSTATUS._options = None
  _HEALTHCHECKRESPONSE_HEALTHSTATUS._serialized_options = b'\312\357 \004\022\002\030\001'
  _HEALTHCHECKSERVICE.methods_by_name['GetHealth']._options = None
  _HEALTHCHECKSERVICE.methods_by_name['GetHealth']._serialized_options = b'\202\323\344\223\002\020\022\016/iam/v1/health'
  _HEALTHCHECKREQUEST._serialized_start=175
  _HEALTHCHECKREQUEST._serialized_end=195
  _HEALTHCHECKRESPONSE._serialized_start=198
  _HEALTHCHECKRESPONSE._serialized_end=371
  _HEALTHCHECKRESPONSE_HEALTHSTATUS._serialized_start=310
  _HEALTHCHECKRESPONSE_HEALTHSTATUS._serialized_end=371
  _HEALTHCHECKSERVICE._serialized_start=374
  _HEALTHCHECKSERVICE._serialized_end=551
# @@protoc_insertion_point(module_scope)
