# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: yandex/cloud/priv/iam/v1/transitional/passport_federation_service.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from yandex.cloud.api import operation_pb2 as yandex_dot_cloud_dot_api_dot_operation__pb2
from yandex.cloud.priv.iam.v1 import user_account_pb2 as yandex_dot_cloud_dot_priv_dot_iam_dot_v1_dot_user__account__pb2
from yandex.cloud.priv.operation import operation_pb2 as yandex_dot_cloud_dot_priv_dot_operation_dot_operation__pb2
from yandex.cloud.priv import validation_pb2 as yandex_dot_cloud_dot_priv_dot_validation__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\nGyandex/cloud/priv/iam/v1/transitional/passport_federation_service.proto\x12%yandex.cloud.priv.iam.v1.transitional\x1a yandex/cloud/api/operation.proto\x1a+yandex/cloud/priv/iam/v1/user_account.proto\x1a+yandex/cloud/priv/operation/operation.proto\x1a\"yandex/cloud/priv/validation.proto\"\xab\x01\n\x1e\x41\x64\x64PassportUserAccountsRequest\x12?\n\x06logins\x18\x01 \x01(\x0b\x32-.yandex.cloud.priv.iam.v1.transitional.LoginsH\x00\x12;\n\x04uids\x18\x02 \x01(\x0b\x32+.yandex.cloud.priv.iam.v1.transitional.UidsH\x00\x42\x0b\n\x03ids\x12\x04\x80\x83\x31\x01\"(\n\x04Uids\x12 \n\x06values\x18\x01 \x03(\x03\x42\x10\xc2\x89\x31\x06<=1000\xba\x89\x31\x02>0\",\n\x06Logins\x12\"\n\x06values\x18\x01 \x03(\tB\x12\xc2\x89\x31\x06<=1000\xca\x89\x31\x04\x32-63\"\x19\n\x17\x41\x64\x64UserAccountsMetadata\"W\n\x17\x41\x64\x64UserAccountsResponse\x12<\n\ruser_accounts\x18\x01 \x03(\x0b\x32%.yandex.cloud.priv.iam.v1.UserAccount2\xd6\x01\n\x19PassportFederationService\x12\xb8\x01\n\x0f\x41\x64\x64UserAccounts\x12\x45.yandex.cloud.priv.iam.v1.transitional.AddPassportUserAccountsRequest\x1a&.yandex.cloud.priv.operation.Operation\"6\xb2\xd2*2\n\x17\x41\x64\x64UserAccountsMetadata\x12\x17\x41\x64\x64UserAccountsResponseB_B\x05PTPFSZVa.yandex-team.ru/cloud/bitbucket/private-api/yandex/cloud/priv/iam/v1/transitional;iamb\x06proto3')



_ADDPASSPORTUSERACCOUNTSREQUEST = DESCRIPTOR.message_types_by_name['AddPassportUserAccountsRequest']
_UIDS = DESCRIPTOR.message_types_by_name['Uids']
_LOGINS = DESCRIPTOR.message_types_by_name['Logins']
_ADDUSERACCOUNTSMETADATA = DESCRIPTOR.message_types_by_name['AddUserAccountsMetadata']
_ADDUSERACCOUNTSRESPONSE = DESCRIPTOR.message_types_by_name['AddUserAccountsResponse']
AddPassportUserAccountsRequest = _reflection.GeneratedProtocolMessageType('AddPassportUserAccountsRequest', (_message.Message,), {
  'DESCRIPTOR' : _ADDPASSPORTUSERACCOUNTSREQUEST,
  '__module__' : 'yandex.cloud.priv.iam.v1.transitional.passport_federation_service_pb2'
  # @@protoc_insertion_point(class_scope:yandex.cloud.priv.iam.v1.transitional.AddPassportUserAccountsRequest)
  })
_sym_db.RegisterMessage(AddPassportUserAccountsRequest)

Uids = _reflection.GeneratedProtocolMessageType('Uids', (_message.Message,), {
  'DESCRIPTOR' : _UIDS,
  '__module__' : 'yandex.cloud.priv.iam.v1.transitional.passport_federation_service_pb2'
  # @@protoc_insertion_point(class_scope:yandex.cloud.priv.iam.v1.transitional.Uids)
  })
_sym_db.RegisterMessage(Uids)

Logins = _reflection.GeneratedProtocolMessageType('Logins', (_message.Message,), {
  'DESCRIPTOR' : _LOGINS,
  '__module__' : 'yandex.cloud.priv.iam.v1.transitional.passport_federation_service_pb2'
  # @@protoc_insertion_point(class_scope:yandex.cloud.priv.iam.v1.transitional.Logins)
  })
_sym_db.RegisterMessage(Logins)

AddUserAccountsMetadata = _reflection.GeneratedProtocolMessageType('AddUserAccountsMetadata', (_message.Message,), {
  'DESCRIPTOR' : _ADDUSERACCOUNTSMETADATA,
  '__module__' : 'yandex.cloud.priv.iam.v1.transitional.passport_federation_service_pb2'
  # @@protoc_insertion_point(class_scope:yandex.cloud.priv.iam.v1.transitional.AddUserAccountsMetadata)
  })
_sym_db.RegisterMessage(AddUserAccountsMetadata)

AddUserAccountsResponse = _reflection.GeneratedProtocolMessageType('AddUserAccountsResponse', (_message.Message,), {
  'DESCRIPTOR' : _ADDUSERACCOUNTSRESPONSE,
  '__module__' : 'yandex.cloud.priv.iam.v1.transitional.passport_federation_service_pb2'
  # @@protoc_insertion_point(class_scope:yandex.cloud.priv.iam.v1.transitional.AddUserAccountsResponse)
  })
_sym_db.RegisterMessage(AddUserAccountsResponse)

_PASSPORTFEDERATIONSERVICE = DESCRIPTOR.services_by_name['PassportFederationService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'B\005PTPFSZVa.yandex-team.ru/cloud/bitbucket/private-api/yandex/cloud/priv/iam/v1/transitional;iam'
  _ADDPASSPORTUSERACCOUNTSREQUEST.oneofs_by_name['ids']._options = None
  _ADDPASSPORTUSERACCOUNTSREQUEST.oneofs_by_name['ids']._serialized_options = b'\200\2031\001'
  _UIDS.fields_by_name['values']._options = None
  _UIDS.fields_by_name['values']._serialized_options = b'\302\2111\006<=1000\272\2111\002>0'
  _LOGINS.fields_by_name['values']._options = None
  _LOGINS.fields_by_name['values']._serialized_options = b'\302\2111\006<=1000\312\2111\0042-63'
  _PASSPORTFEDERATIONSERVICE.methods_by_name['AddUserAccounts']._options = None
  _PASSPORTFEDERATIONSERVICE.methods_by_name['AddUserAccounts']._serialized_options = b'\262\322*2\n\027AddUserAccountsMetadata\022\027AddUserAccountsResponse'
  _ADDPASSPORTUSERACCOUNTSREQUEST._serialized_start=275
  _ADDPASSPORTUSERACCOUNTSREQUEST._serialized_end=446
  _UIDS._serialized_start=448
  _UIDS._serialized_end=488
  _LOGINS._serialized_start=490
  _LOGINS._serialized_end=534
  _ADDUSERACCOUNTSMETADATA._serialized_start=536
  _ADDUSERACCOUNTSMETADATA._serialized_end=561
  _ADDUSERACCOUNTSRESPONSE._serialized_start=563
  _ADDUSERACCOUNTSRESPONSE._serialized_end=650
  _PASSPORTFEDERATIONSERVICE._serialized_start=653
  _PASSPORTFEDERATIONSERVICE._serialized_end=867
# @@protoc_insertion_point(module_scope)
