# the earliest version supported by BI
# FROM mysql:5.6
FROM mysql:5.6@sha256:897086d07d1efa876224b147397ea8d3147e61dd84dce963aace1d5e9dc2802d

COPY db-common/data /common-data
COPY db-mysql/docker-entrypoint-initdb.d /docker-entrypoint-initdb.d
