#!/usr/bin/env sh

set -x  # debug.
set -eu

HTTP_BIND_PORT="${RQE_EXT_SYNC_PORT:-9876}"
RQE_UWSGI_WORKERS_COUNT="${RQE_EXT_SYNC_WORKERS_COUNT:-16}"
RQE_UWSGI_THREADS_COUNT="${RQE_EXT_SYNC_THREADS_COUNT:-10}"
if [ "${BISYS_USE_IPV6:-1}" = "1" ]; then HTTP_BIND_ADDR="[::]"; else HTTP_BIND_ADDR="0.0.0.0"; fi

HTTP_BIND="${HTTP_BIND_ADDR}:${HTTP_BIND_PORT}"
export HTTP_BIND RQE_UWSGI_WORKERS_COUNT RQE_UWSGI_THREADS_COUNT
exec \
    /code/app/bi_rqe_ext_sync \
        --ini=/code/app/uwsgi/uwsgi-query-executer.ini
