from bi_constants.enums import SourceBackendType, ConnectionType, CreateDSFrom


BACKEND_TYPE_CHYT = SourceBackendType.declare('CHYT')
CONNECTION_TYPE_CHYT = ConnectionType.declare('chyt')

SOURCE_TYPE_CHYT_YTSAURUS_TABLE = CreateDSFrom.declare('CHYT_YTSAURUS_TABLE')
SOURCE_TYPE_CHYT_YTSAURUS_SUBSELECT = CreateDSFrom.declare('CHYT_YTSAURUS_SUBSELECT')
SOURCE_TYPE_CHYT_YTSAURUS_TABLE_LIST = CreateDSFrom.declare('CHYT_YTSAURUS_TABLE_LIST')
SOURCE_TYPE_CHYT_YTSAURUS_TABLE_RANGE = CreateDSFrom.declare('CHYT_YTSAURUS_TABLE_RANGE')
