# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from yandex.cloud.priv.mdb.clickhouse.v1 import cluster_service_pb2 as yandex_dot_cloud_dot_priv_dot_mdb_dot_clickhouse_dot_v1_dot_cluster__service__pb2
from yandex.cloud.priv.mdb.clickhouse.v1.config import clickhouse_pb2 as yandex_dot_cloud_dot_priv_dot_mdb_dot_clickhouse_dot_v1_dot_config_dot_clickhouse__pb2
from yandex.cloud.priv.mdb.clickhouse.v1.console import cluster_pb2 as yandex_dot_cloud_dot_priv_dot_mdb_dot_clickhouse_dot_v1_dot_console_dot_cluster__pb2
from yandex.cloud.priv.mdb.clickhouse.v1.console import cluster_service_pb2 as yandex_dot_cloud_dot_priv_dot_mdb_dot_clickhouse_dot_v1_dot_console_dot_cluster__service__pb2


class ClusterServiceStub(object):
    """A set of methods for managing ClickHouse console support.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetClustersConfig = channel.unary_unary(
                '/yandex.cloud.priv.mdb.clickhouse.v1.console.ClusterService/GetClustersConfig',
                request_serializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_clickhouse_dot_v1_dot_console_dot_cluster__service__pb2.GetClustersConfigRequest.SerializeToString,
                response_deserializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_clickhouse_dot_v1_dot_console_dot_cluster__pb2.ClustersConfig.FromString,
                )
        self.EstimateCreate = channel.unary_unary(
                '/yandex.cloud.priv.mdb.clickhouse.v1.console.ClusterService/EstimateCreate',
                request_serializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_clickhouse_dot_v1_dot_cluster__service__pb2.CreateClusterRequest.SerializeToString,
                response_deserializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_clickhouse_dot_v1_dot_console_dot_cluster__pb2.BillingEstimate.FromString,
                )
        self.Estimate = channel.unary_unary(
                '/yandex.cloud.priv.mdb.clickhouse.v1.console.ClusterService/Estimate',
                request_serializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_clickhouse_dot_v1_dot_console_dot_cluster__service__pb2.EstimateRequest.SerializeToString,
                response_deserializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_clickhouse_dot_v1_dot_console_dot_cluster__pb2.BillingEstimate.FromString,
                )
        self.GetClustersStats = channel.unary_unary(
                '/yandex.cloud.priv.mdb.clickhouse.v1.console.ClusterService/GetClustersStats',
                request_serializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_clickhouse_dot_v1_dot_console_dot_cluster__service__pb2.GetClustersStatsRequest.SerializeToString,
                response_deserializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_clickhouse_dot_v1_dot_console_dot_cluster__pb2.ClustersStats.FromString,
                )
        self.GetClickhouseConfigSchema = channel.unary_unary(
                '/yandex.cloud.priv.mdb.clickhouse.v1.console.ClusterService/GetClickhouseConfigSchema',
                request_serializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_clickhouse_dot_v1_dot_console_dot_cluster__service__pb2.GetClickhouseConfigSchemaRequest.SerializeToString,
                response_deserializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_clickhouse_dot_v1_dot_console_dot_cluster__service__pb2.JSONSchema.FromString,
                )
        self.GetUserSettingsSchema = channel.unary_unary(
                '/yandex.cloud.priv.mdb.clickhouse.v1.console.ClusterService/GetUserSettingsSchema',
                request_serializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_clickhouse_dot_v1_dot_console_dot_cluster__service__pb2.GetUserSettingsSchemaRequest.SerializeToString,
                response_deserializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_clickhouse_dot_v1_dot_console_dot_cluster__service__pb2.JSONSchema.FromString,
                )
        self.GetDefaultClickhouseConfigForCreate = channel.unary_unary(
                '/yandex.cloud.priv.mdb.clickhouse.v1.console.ClusterService/GetDefaultClickhouseConfigForCreate',
                request_serializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_clickhouse_dot_v1_dot_console_dot_cluster__service__pb2.GetDefaultClickhouseConfigForCreateRequest.SerializeToString,
                response_deserializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_clickhouse_dot_v1_dot_config_dot_clickhouse__pb2.ClickhouseConfig.FromString,
                )
        self.GetDefaultClickhouseConfigForUpdate = channel.unary_unary(
                '/yandex.cloud.priv.mdb.clickhouse.v1.console.ClusterService/GetDefaultClickhouseConfigForUpdate',
                request_serializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_clickhouse_dot_v1_dot_console_dot_cluster__service__pb2.GetDefaultClickhouseConfigForUpdateRequest.SerializeToString,
                response_deserializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_clickhouse_dot_v1_dot_config_dot_clickhouse__pb2.ClickhouseConfig.FromString,
                )
        self.GetDefaultShardClickhouseConfig = channel.unary_unary(
                '/yandex.cloud.priv.mdb.clickhouse.v1.console.ClusterService/GetDefaultShardClickhouseConfig',
                request_serializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_clickhouse_dot_v1_dot_console_dot_cluster__service__pb2.GetDefaultShardClickhouseConfigRequest.SerializeToString,
                response_deserializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_clickhouse_dot_v1_dot_config_dot_clickhouse__pb2.ClickhouseConfig.FromString,
                )
        self.GetRestoreHints = channel.unary_unary(
                '/yandex.cloud.priv.mdb.clickhouse.v1.console.ClusterService/GetRestoreHints',
                request_serializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_clickhouse_dot_v1_dot_console_dot_cluster__service__pb2.GetRestoreHintsRequest.SerializeToString,
                response_deserializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_clickhouse_dot_v1_dot_console_dot_cluster__pb2.RestoreHints.FromString,
                )


class ClusterServiceServicer(object):
    """A set of methods for managing ClickHouse console support.
    """

    def GetClustersConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EstimateCreate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Estimate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetClustersStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetClickhouseConfigSchema(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserSettingsSchema(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDefaultClickhouseConfigForCreate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDefaultClickhouseConfigForUpdate(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDefaultShardClickhouseConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRestoreHints(self, request, context):
        """Get cluster restore hints for the specified backup.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClusterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetClustersConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetClustersConfig,
                    request_deserializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_clickhouse_dot_v1_dot_console_dot_cluster__service__pb2.GetClustersConfigRequest.FromString,
                    response_serializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_clickhouse_dot_v1_dot_console_dot_cluster__pb2.ClustersConfig.SerializeToString,
            ),
            'EstimateCreate': grpc.unary_unary_rpc_method_handler(
                    servicer.EstimateCreate,
                    request_deserializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_clickhouse_dot_v1_dot_cluster__service__pb2.CreateClusterRequest.FromString,
                    response_serializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_clickhouse_dot_v1_dot_console_dot_cluster__pb2.BillingEstimate.SerializeToString,
            ),
            'Estimate': grpc.unary_unary_rpc_method_handler(
                    servicer.Estimate,
                    request_deserializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_clickhouse_dot_v1_dot_console_dot_cluster__service__pb2.EstimateRequest.FromString,
                    response_serializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_clickhouse_dot_v1_dot_console_dot_cluster__pb2.BillingEstimate.SerializeToString,
            ),
            'GetClustersStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetClustersStats,
                    request_deserializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_clickhouse_dot_v1_dot_console_dot_cluster__service__pb2.GetClustersStatsRequest.FromString,
                    response_serializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_clickhouse_dot_v1_dot_console_dot_cluster__pb2.ClustersStats.SerializeToString,
            ),
            'GetClickhouseConfigSchema': grpc.unary_unary_rpc_method_handler(
                    servicer.GetClickhouseConfigSchema,
                    request_deserializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_clickhouse_dot_v1_dot_console_dot_cluster__service__pb2.GetClickhouseConfigSchemaRequest.FromString,
                    response_serializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_clickhouse_dot_v1_dot_console_dot_cluster__service__pb2.JSONSchema.SerializeToString,
            ),
            'GetUserSettingsSchema': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserSettingsSchema,
                    request_deserializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_clickhouse_dot_v1_dot_console_dot_cluster__service__pb2.GetUserSettingsSchemaRequest.FromString,
                    response_serializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_clickhouse_dot_v1_dot_console_dot_cluster__service__pb2.JSONSchema.SerializeToString,
            ),
            'GetDefaultClickhouseConfigForCreate': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDefaultClickhouseConfigForCreate,
                    request_deserializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_clickhouse_dot_v1_dot_console_dot_cluster__service__pb2.GetDefaultClickhouseConfigForCreateRequest.FromString,
                    response_serializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_clickhouse_dot_v1_dot_config_dot_clickhouse__pb2.ClickhouseConfig.SerializeToString,
            ),
            'GetDefaultClickhouseConfigForUpdate': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDefaultClickhouseConfigForUpdate,
                    request_deserializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_clickhouse_dot_v1_dot_console_dot_cluster__service__pb2.GetDefaultClickhouseConfigForUpdateRequest.FromString,
                    response_serializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_clickhouse_dot_v1_dot_config_dot_clickhouse__pb2.ClickhouseConfig.SerializeToString,
            ),
            'GetDefaultShardClickhouseConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDefaultShardClickhouseConfig,
                    request_deserializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_clickhouse_dot_v1_dot_console_dot_cluster__service__pb2.GetDefaultShardClickhouseConfigRequest.FromString,
                    response_serializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_clickhouse_dot_v1_dot_config_dot_clickhouse__pb2.ClickhouseConfig.SerializeToString,
            ),
            'GetRestoreHints': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRestoreHints,
                    request_deserializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_clickhouse_dot_v1_dot_console_dot_cluster__service__pb2.GetRestoreHintsRequest.FromString,
                    response_serializer=yandex_dot_cloud_dot_priv_dot_mdb_dot_clickhouse_dot_v1_dot_console_dot_cluster__pb2.RestoreHints.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'yandex.cloud.priv.mdb.clickhouse.v1.console.ClusterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ClusterService(object):
    """A set of methods for managing ClickHouse console support.
    """

    @staticmethod
    def GetClustersConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/yandex.cloud.priv.mdb.clickhouse.v1.console.ClusterService/GetClustersConfig',
            yandex_dot_cloud_dot_priv_dot_mdb_dot_clickhouse_dot_v1_dot_console_dot_cluster__service__pb2.GetClustersConfigRequest.SerializeToString,
            yandex_dot_cloud_dot_priv_dot_mdb_dot_clickhouse_dot_v1_dot_console_dot_cluster__pb2.ClustersConfig.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EstimateCreate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/yandex.cloud.priv.mdb.clickhouse.v1.console.ClusterService/EstimateCreate',
            yandex_dot_cloud_dot_priv_dot_mdb_dot_clickhouse_dot_v1_dot_cluster__service__pb2.CreateClusterRequest.SerializeToString,
            yandex_dot_cloud_dot_priv_dot_mdb_dot_clickhouse_dot_v1_dot_console_dot_cluster__pb2.BillingEstimate.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Estimate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/yandex.cloud.priv.mdb.clickhouse.v1.console.ClusterService/Estimate',
            yandex_dot_cloud_dot_priv_dot_mdb_dot_clickhouse_dot_v1_dot_console_dot_cluster__service__pb2.EstimateRequest.SerializeToString,
            yandex_dot_cloud_dot_priv_dot_mdb_dot_clickhouse_dot_v1_dot_console_dot_cluster__pb2.BillingEstimate.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetClustersStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/yandex.cloud.priv.mdb.clickhouse.v1.console.ClusterService/GetClustersStats',
            yandex_dot_cloud_dot_priv_dot_mdb_dot_clickhouse_dot_v1_dot_console_dot_cluster__service__pb2.GetClustersStatsRequest.SerializeToString,
            yandex_dot_cloud_dot_priv_dot_mdb_dot_clickhouse_dot_v1_dot_console_dot_cluster__pb2.ClustersStats.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetClickhouseConfigSchema(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/yandex.cloud.priv.mdb.clickhouse.v1.console.ClusterService/GetClickhouseConfigSchema',
            yandex_dot_cloud_dot_priv_dot_mdb_dot_clickhouse_dot_v1_dot_console_dot_cluster__service__pb2.GetClickhouseConfigSchemaRequest.SerializeToString,
            yandex_dot_cloud_dot_priv_dot_mdb_dot_clickhouse_dot_v1_dot_console_dot_cluster__service__pb2.JSONSchema.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetUserSettingsSchema(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/yandex.cloud.priv.mdb.clickhouse.v1.console.ClusterService/GetUserSettingsSchema',
            yandex_dot_cloud_dot_priv_dot_mdb_dot_clickhouse_dot_v1_dot_console_dot_cluster__service__pb2.GetUserSettingsSchemaRequest.SerializeToString,
            yandex_dot_cloud_dot_priv_dot_mdb_dot_clickhouse_dot_v1_dot_console_dot_cluster__service__pb2.JSONSchema.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDefaultClickhouseConfigForCreate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/yandex.cloud.priv.mdb.clickhouse.v1.console.ClusterService/GetDefaultClickhouseConfigForCreate',
            yandex_dot_cloud_dot_priv_dot_mdb_dot_clickhouse_dot_v1_dot_console_dot_cluster__service__pb2.GetDefaultClickhouseConfigForCreateRequest.SerializeToString,
            yandex_dot_cloud_dot_priv_dot_mdb_dot_clickhouse_dot_v1_dot_config_dot_clickhouse__pb2.ClickhouseConfig.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDefaultClickhouseConfigForUpdate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/yandex.cloud.priv.mdb.clickhouse.v1.console.ClusterService/GetDefaultClickhouseConfigForUpdate',
            yandex_dot_cloud_dot_priv_dot_mdb_dot_clickhouse_dot_v1_dot_console_dot_cluster__service__pb2.GetDefaultClickhouseConfigForUpdateRequest.SerializeToString,
            yandex_dot_cloud_dot_priv_dot_mdb_dot_clickhouse_dot_v1_dot_config_dot_clickhouse__pb2.ClickhouseConfig.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDefaultShardClickhouseConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/yandex.cloud.priv.mdb.clickhouse.v1.console.ClusterService/GetDefaultShardClickhouseConfig',
            yandex_dot_cloud_dot_priv_dot_mdb_dot_clickhouse_dot_v1_dot_console_dot_cluster__service__pb2.GetDefaultShardClickhouseConfigRequest.SerializeToString,
            yandex_dot_cloud_dot_priv_dot_mdb_dot_clickhouse_dot_v1_dot_config_dot_clickhouse__pb2.ClickhouseConfig.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRestoreHints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/yandex.cloud.priv.mdb.clickhouse.v1.console.ClusterService/GetRestoreHints',
            yandex_dot_cloud_dot_priv_dot_mdb_dot_clickhouse_dot_v1_dot_console_dot_cluster__service__pb2.GetRestoreHintsRequest.SerializeToString,
            yandex_dot_cloud_dot_priv_dot_mdb_dot_clickhouse_dot_v1_dot_console_dot_cluster__pb2.RestoreHints.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
