name: build_images

on:
  workflow_dispatch:
  schedule:
    - cron: "04 05 * * 6"

jobs:
  # TODO FIX: Legacy, check if not used & remove
  bake_os:
    runs-on: [ self-hosted, linux ]
    permissions:
      packages: write
      contents: read
    container:
      image: "ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}/debian_docker:latest"
      options: -v /var/run/docker.sock:/var/run/docker.sock
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    env:
      CR_TAG_BASE_OS: "ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}/dl_base_os:latest"
      BAKE_TARGET: "dl_base_linux_w_db_bin_dependencies"
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: "ghcr.io"
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Cleanup build folder'
        run: |
          rm -rf ./* || true
          rm -rf ./.??* || true
      - name: Checkout code
        uses: actions/checkout@v4
      - run: git config --global --add safe.directory /__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}
      - run: |
          cd docker_build
          ./run-project-bake "${BAKE_TARGET}" --push --set "${BAKE_TARGET}.tags=${CR_TAG_BASE_OS}"
