name: billing-api
service_account_id: bfbdtpfu9qlotm99j4h6
scale_policy:
  fixed_scale:
    size: 1
deploy_policy:
  max_unavailable: 1
  # здесь лучше 0, для того чтобы виртуалки не пересоздавались каждый раз
  max_expansion: 0
health_checks_spec:
  health_check_specs:
  - http_options:
      port: 80
        # для проектов на common, проверка живости приложения
      path: /api/v1/ping
    interval: 6s
    timeout: 5s
    unhealthy_threshold: 2
    healthy_threshold: 3
allocation_policy:
  zones:
  - zone_id: ru-central1-a
  - zone_id: ru-central1-b
  - zone_id: ru-central1-c
platform_l7_load_balancer_spec:
  preferred_ip_version: IPV6
  target_group_spec:
    # название вашей таргет-группы, это специальная тг для L7, из интерфейса ее создать невозможно
    name: datalens-preprod-billing-api
instance_template:
  # шаблон для имени вм, мы используем такой app_name-{instance.internal_dc}-{instance.index}
  name: billing-api-{instance.internal_dc}-{instance.index}
  fqdn: billing-api-{instance.internal_dc}-{instance.index}.{instance.internal_dc}.datalens.cloud-preprod.yandex.net
  service_account_id: bfbk1j9tmltib6dttc71
  labels:
    yandex-dns: ig
    conductor-group: datalens-back-preprod
    conductor-role: billing-api
  platform_id: standard-v2
  resources_spec:
    memory: 2G
    cores: 2
    core_fraction: 20
  boot_disk_spec:
    mode: READ_WRITE
    disk_spec:
      # айдишник образа, созданного packer-ом, подставляется тимсити, здесь не менять
      image_id: __IMAGE_ID__
      type_id: network-ssd
      size: 10g
  # логи пишутся на secondary-disk, чтобы избежать потери при деплое
  secondary_disk_specs:
  - mode: READ_WRITE
    device_name: data
    disk_spec:
      type_id: network-ssd
      size: 11g
  network_interface_specs:
  - network_id: c64an5jmjnpgiaclqg8k
    primary_v6_address_spec: {}
    primary_v4_address_spec: {}
    security_group_ids:
    - c64ud7769sqduk0c71ik
  metadata:
    k8s-runtime-bootstrap-yaml: ' '
    # настройка записи логов на secondary-disk
    user-data: |
      #cloud-config
      fs_setup:
      - device: /dev/disk/by-id/virtio-data
        filesystem: ext4
        partition: auto
        overwrite: false
      mounts:
      - [/dev/disk/by-id/virtio-data, /data, ext4, 'defaults,errors=remount-ro', '0', '2']
      - [/data/log/fluent, /var/log/fluent, none, 'defaults,bind', '0', '0']
      runcmd:
      - mkdir -p /data/log/fluent
      - chmod 0777 /data
      - chown td-agent:td-agent /data/log/fluent
      - chmod 0755 /data/log/fluent
      - mount --make-rprivate /data
      - mount -o bind /data/log/fluent /var/log/fluent
      - /usr/local/bin/update_env_vars
      - /usr/bin/skm decrypt
      - /usr/local/bin/update_secrets
      env_vars:
        APP_HOST: '::'
        APP_PORT: 80
        DL_CRY_ACTUAL_KEY_ID: cloud_preprod_2
        DL_CRY_FALLBACK_KEY_ID: 0
        NGINX_CERT_LOCATION: /etc/secrets/component_cert.pem
        NGINX_CERT_PRIVATE_KEY_LOCATION: /etc/secrets/component_cert.key
        NGINX_SERVER_NAME: billing-api
        RUN_API: 1
        RUN_NGINX: 1
        YENV_NAME: other
        YENV_TYPE: testing
        RUN_PURCHASES_AVAILABLE_CHECK: 1
    osquery_tag: ycloud-svc-datalens-bi
    shortname: billing-api-{instance.internal_dc}-{instance.index}.{instance.internal_dc}
    nsdomain: datalens.cloud-preprod.yandex.net
    skm: |
      api_endpoint: api.cloud-preprod.yandex.net:443
      skip_tls_verify: false
      kms_private_endpoint: ""
      iam_private_endpoint: ""
      kms_private_skip_tls_verify: false
      kms_key_uri: yc-kms://e10mng38moenmrvomcdo
      encrypted_dek: AAAAAQAAABRlMTA5bGE2aGswNXI5NnNhOWhmZAAAABB7orjf1yXiyFvMLQ9fwMyhAAAADBDevaC5jyI95bSaCUDwsHcxRAqkoRfE3qszSL69+dnHhUmjlbkfvEQt/VnTZw8i73Z5NB03fQGiQSIJpSjn4wUGtsSBdOvRMMCsbYd10IN/W8HjE8QRnut5B9jr
      secrets:
        - path: /etc/secrets/TVM_SECRET
          ciphertext: !!binary cCW+6nQUTokdAo3nTmGeeUh81gcz/RcSXkp4JyE4NIIY6LlZB6Q=
          mode: 0
          uid: 0
          gid: 0
        - path: /etc/secrets/TVM_INFO
          ciphertext: !!binary |
              C9kPuMGSNlKJRdcYtzRStasi4SukCykKbg5W4jLMTdo2Dt2PpbSu81c/mTNQ6nXaiIM9yj
              qQpOkGmQ==
          mode: 0
          uid: 0
          gid: 0
        - path: /etc/secrets/REDIS_PASSWORD
          ciphertext: !!binary |
              0JKY8TtkHJv/13EeqWIPCoAOWZbyEpn7Cb0fZRVPMgz9jdIkvQ2E3bk8rop4DgTtvgenUf
              nvhA76Nfo=
          mode: 0
          uid: 0
          gid: 0
        - path: /etc/secrets/APP_MASTER_TOKEN
          ciphertext: !!binary |
              HiplI5DQ394KEUq/6ryQAA8NWknBxp8+aS05pjCFDeOTtTS1JxZf8k4XAnp2g5k9qLXRH2
              6vipuZr78=
          mode: 0
          uid: 0
          gid: 0
        - path: /etc/secrets/PG_PASSWORD
          ciphertext: !!binary |
              HBduqngBTsrQvAtr5zS6HS5/YWltozgOO/AIhUfwbBSbPRAVkjrUIOGdnqBOcOFFJnaoyM
              phjjfciw==
          mode: 0
          uid: 0
          gid: 0
        - path: /etc/secrets/DL_CRY_KEY_VAL_ID_cloud_preprod_2
          ciphertext: !!binary |
              O+6kaMhpkeTRQ+OHFbREjJZuemFSMW8Hl2/9A9+BY1w4MCXcpItN0SzYyZ0MuYWucHZmKN
              x//BSgjzte
          mode: 0
          uid: 0
          gid: 0
        - path: /etc/secrets/SETUP_FOLDER_MASTER_TOKEN
          ciphertext: !!binary |
              LnDEbA06Cwineop4qIjhfN3PvZpbvLi6l3GHSYc5kppviBji8PTpsVyereFD5/zzb4rjAy
              C3oh9X0TQ=
          mode: 0
          uid: 0
          gid: 0
        - path: /etc/secrets/SF_PG_PASSWORD
          ciphertext: !!binary |
              mwiP/sQh0k4evILBrqHAxC2ooeFT3BPM8V/KheW30BlaWQZSdrabWD8+ASUkbgdtLB3Fst
              XVLRx8ff8=
          mode: 0
          uid: 0
          gid: 0
        - path: /etc/secrets/US_MASTER_TOKEN
          ciphertext: !!binary 6ACevV8Dsh3/+/BE+01LeJ31EFtVdHhOisBcdoraJmhfzgL4rlzmFlpzBP2Ycjdk
          mode: 0
          uid: 0
          gid: 0
        - path: /etc/secrets/ANALYTICS_CH_PASSWORD
          ciphertext: !!binary |
              jor6aLFIqHYXu6e60elUGGqmcYJOEss49PgNi//Auj3ddOnhGVbjRc8w2Z6fqri4W1RFMp
              aBZYg6KNc=
          mode: 0
          uid: 0
          gid: 0
        - path: /etc/secrets/TVM_CLIENT_SECRET
          ciphertext: !!binary a3ev3TbMEkSbvTz21JTaniITEFggGT74WnaqiquZPskVFmN/gII=
          mode: 0
          uid: 0
          gid: 0
        - path: /etc/secrets/YAV_TOKEN
          ciphertext: !!binary |
              VBsuVvd7r4eikrp/HiL64rwuZGhAgkxIHOt/iJn57sYAmfC2nHzjeFuC00CE19ClHwGu1S
              e1yQ==
          mode: 0
          uid: 0
          gid: 0
        - path: /etc/secrets/LOGCH_PASSWORD
          ciphertext: !!binary agxQuGkY3EDk3wAzLaWTQMLqsONVu7+nwaATC7wl0Sm66zN66xOQ2Oyd
          mode: 0
          uid: 0
          gid: 0
        - path: /etc/secrets/component_cert.pem
          ciphertext: !!binary |
              WkbguFaigR3Oe0SB1DB0hLX4tqqYQ6CKOlNk1GzY/tMuFHRc7aR7WxkSxSOWHF48djwOKr
              4M0CMyxzJP9mNxZt6koKJDzXYDSQ+Wt8hECXJdUdm7kou78r06/kLUr11QPLJa1nWgQN6w
              E0Ix0kH/zuruoHvFY0Cch3t1VcOR1PxRl5KDbC3m0FFazYVeRexGXDe6rk/ytfUbXSaOra
              NNt7khsQfXEaMljmDKwtHlr5W9x/mikiU/ZGm+EymB/QXjTUdBVeV8qlKlkJvb3n5+lxIw
              axbfO/3K5O3QdSbcT34v1r0eqcsmW4UDOrx53xtDQq/kyNic75kqOSoUT4VS5YJ4RjHGUz
              VFyJSS+KnC7lz/WkM6qyaVZaoLDTt0oaA0p+toU6AyIEim2RlVJbvyNdasJJRXzzeIdRB9
              AL7qer8KMsb0zQPihdiCznyIOo39pzarXXwDbmUQxz+onV6i2XhN4bDQ5leCnoweAAU5ee
              rHAkwx6Tz55HryyCFgtzOpDEtb7MKriZ0CAysS73+u/mTZxIZvH2ZFTCBqC5bdXiaCPFrh
              /8spZzXNDG6+DZszNKqfhek7vjxIAm6/lLxQe/r8Thyh6rc2QTH4SFx68Rk65Rz6eFZK8C
              Zo8BEwGinAmzytQ9Xp3uBtWoqQgg+xRRMA0jkmzAiqaqM8IhFBhPt7LKGWsfWFGnk0IRcG
              pnXx+qTYjT5xG8ssjrrbKj3PPNGGnuz1aSGLik5q+BgUt79UyAheJ8xdIjgbvh1Oc2GIBb
              PwiV0UWaDUGSoZqrelphyMdAt3zL7QRqSfWgzXwJ54zjtqQKmhyFN6zSLk7/rw+LljTHQw
              7fpA+rT7FDHdmfiwmMVVSNznMxpU8WIemSj/Wq6vJLSINA7L2ofLur+FdDlOOVT/xHHpzP
              /PG85lVN9ccSDWOlR4Ol5ihPSubWmOXePaTSjCe/96nR9nDKUtP8PavRUtZ7Kv8V0RjblX
              ZphKTjlCMuieXHCCBeES8EZ5f5CLzB+bvsnIopKNcDkHBGncRx4u5kjJ+gpkejbaSYe1Mq
              7Kiwo3vREQUMFXz/KJMUICo25PfR7GPOosUoiy68GSyu50MrbkfZWH4tPtQc5+/c7wjvcl
              hiRc9+jkR+7XNe0zs8B/PxETGQBDVvCsdzKSM7NLq5QRVHC67ycvMr5ceBEYphJfDj320J
              /G7MDw9QGIEFa/cQOxS5dcr/uUt+0e9FG4MS2ujk9YpQ4udancwMcULi9tDNmyGCROzfR9
              yFDdUWgvf7R1mrWalU9eTjV4OD+wrPGiTCtf1FJMEIKbPgicnLp+yTpB4nGDxhcDsRNYve
              IeCmLnZ30ZE31g43lD1haJnmBJs8ujLjv/K3CqXIS4OINyU2YwHZ02vIEPsWaQxgFY0wml
              5t0vrfa+TTyFBVphMtysPhjUqNvuERKak4av5Pqu7lursund3gfENALFxabYMbN9ofs/uq
              fQQO0OZQCaO15VfXNsqzoHQPLDkv0uE/tOn5hndNelIfy5ieu8uG4Eb6XmfRoiqvReFyfN
              FIMLXr+DgaNRQmX3DMd4sH8zvVzn1pWjds3DyCrmkLfyfBYNYdRCEE058GUAul5Juj+s3G
              RRLs/mSgaynfHahBgnzDUjLMyI8GqnbB1hSg/YfhdzCE43g3WbESXEONIO5/coI8Q8Ukyn
              5RVsUzpddROpCYO/Azb8YKl7JtITeHRyN4ATSm9DuesZF6HDFerat9B5ioODmBjsEPT+ND
              wZ4BfFYIBDO7ZdXaMtQ4h30nFTfoUJNCLs5ZBwvvKRXjGl4Yeb20O4VJqDxmW4oK4xqR3C
              Aoo8WpIrTOvjNfm/g3qh4of4Gaj76KuAk1FhCnmpiW1UABAczuG2GqUwMuCPxYyKE0p3pT
              9JjVTkYXGkPzVmrisTzvZkEKfk8GHrhX7IU6Odhq1PsF9GXqTxSiTsKIoog3ljAhjKjmg1
              xYlXzdJGBA0WlsE4s2UZwQt5aBDkguTVmhnRA997dCVjTwfvxdQVDo7PB4/S7A60XB270i
              bnDuOTQgxW5t+mvnEVsmDMrCF+k0+D5bgePNlNjmPXbs+O6feBrvY6dkjJDrEbptO9U9xC
              Xi7+jsuZsvDbbJRBOPG/PKHDbMKmtP6w+Q4AG8fulQUGIstv7ASnVkg+9IVYIAvd7aZuPa
              KNkhiY4Mv80KStE+AsUJzefI6Gl48K9JRAAS6zkRDC/RPn236D/e0eZvI4L7/k0mTRzp1r
              +Ta8vnvnSue+DvPfouwekoOBDTj0gTbTimSdEjlDQZ1XrUELEF2Js82yxLloxaGNWFS2ri
              5uvrcD3R5Zh5AKkIyL8TtTAXP/HOUG7yAN/m+ip8B8pxpi6/VMQoSBMr/FVpwEyKy6j0fY
              1bzOye8EH51DGScTqX3dV/rW6bDPGQqPvgzQrrO2R2HMYltd5hF53zGY8q6st/ElkUgUZK
              OvMqVr5gZ33f4tqqHSZNIOzp/3bMm/GFhwkJySuNhWonL2bBhSJod1nkBp4ecN5yKK2pbJ
              wf1Cohqxt+AahvFQZPdsomX35e2/Al9Oj/+Dc6Idm8AyMvfiD6i+DDmsii2pGrlVDS3p2m
              eXE7SALuLjcRYZW1yFyHDkBROA1PwmRD7jki1PxEadXK0OvKeLSfeiS+AjKgKKbrdJa2sC
              7KorDbuh5Gn+qkTK46EBfLWZFTQiLy46QSz62+FZKskz+SgfGGxfQx9HEWYgk1RtFO8254
              V0ltijn5kTAPiKC1Jrr5Txs0VfJaTrJ2AGsMPF8t1diIUUyVYZSH67YiuQp0UkueFkS7wO
              mU8zsf6IpUFdcv5w1AduXO6dUgIOJfHc5Jl3OGfPO6Jmvidqrugwiw68gOO+lk9n1/zi0x
              5uKzdCphKFsMbZjtGDkd0ilrsJFzWryTueYgdX7iqgE8Fyz00YE+2op5VDhfHrPrwmrFzh
              og17tpDxuI7+dLlOxb4M9KTQou/dJFtEkAQ49SzMchUViq0JNN2uWcGZ+8xvJagOcGUHOr
              WYopzsN+qs+4BvEqQGrTvcJv7eHbCc34C0DEGTHBpg43AGoCAMcJQo0cMkAu+VNRV9oR4s
              TeBDlkUKzviCaxKfVH9f2OIEUDmk1y6kEK5q813FPwaiYiEFeHumCn2FSwS4SZUxQjQCC7
              KqICODVxqgofOegaffbY4DsqqL4EVM5B4hvRxRMNtB87bN7lEN4DYHMIns/L0QrOE0v2++
              4bVhbTPYS8jix45o5/cFt2cc0USonp/8jzglO8FGXKnHcM+BCvbxCUPtxuMNfANQC6ZNWP
              M4oydFnBuuBhqBvzQ4VMOcl2W+T8jiGKiJK+z97qwWhNOvKhee7Mp2m4F/dRN2i4BvpZHN
              ZbMyoszLqNo4xRhtxFNe5I4IQyAWrE+HvBpr5cSEb/nPec//1WKYa8+2+5MNhW7+QtYCjS
              H9S59FZ3+gl/zYRfQFDoe7TKsRkZgouShYM2rDJ1zeH29ZwiimaUWsuvk3bw6MZOj/chKx
              6xBzsTz0p3svPu68ed2drGxP6DEzfLktXmGCGKfQiNUy8RrlXGEiji5UWdv7duxClOIcN+
              JLplUiez6uQifJsKnoW7xUXm4BeermJIHG2buoMc2dp59moG1u1o1CIyERhCRSgcWjGmPW
              MgRinhgbvdQXtRmSwllAY2aAGkZzrjspJjOmWxpjwGOXD08HZUJ81vsWYGT5L0wvVdT9ID
              /cmC/pXwcsXvpo/iUJvpaVzKt7SZZGI6lfDZt/w156up6xFDBgQUjMqnHan4MCzv0a6ste
              /sdSlYbcXu9SSTlUqvzmh8IoLaQmbAhkPmWL3DN9YpNBkbX4zKmGqjNTW77d2ZsparIqnn
              CQMCN/diKafi8PH8SgrvZVe8I2EfQT6K2PGTctI8kMCGmxvna2jeBfG6P1GJLLm1uuhivn
              E9HbJFN0z8febZmz1RlZTaNRHEuR819amKWwq+vRqkKwuADA72POzjVHKV9qHGvbHnZqKb
              9qy8l/nEgj8O4RhFGrWzd5d5i5rB8AvSqPyrESoNjcEOnc3N8xg7Y638MikrZIyxvZPYke
              3OasYQNjPlFNkj9N83ECvc8O+c/gZF2uLt7MbgNyf9w/x2w6RweJRw8Uha5yjhmapzWjR/
              IlH0O/otIqmcJqVsKFNcM7gNtoWaKcwoQMSZ1oNdn0Iq+QuTCVJv9RcfRQ3zrl6hs90bdM
              zVcdxZD4UNSlxLfLBKxCMcA8sB4m3b1xNCltsaUoGIqppAj58+bRh8Dbt4bHqLK2E2dPAF
              jeaa1kUoWdkKY20c2SrPpxkZsCPRzS0aX8A9xx0vQVtPi5MGbeWQpTcQJFwXI8ZZXrY0vH
              yipk+B6Ol7aM3EPLha7Ohlp9kthmtkiO26xIHMtK5aGPyPL3LAFns6i+37Tt6DcnYDCbod
              v9UmC6Pu+GNA+LowN7kOFmV3KNvOCcWSWdXHVIQloy+rxaMS6RGPqPLoKjxYPcY7FFbFV/
              qU8EKgGc8bhrgZLhSxH3O8OymSdqaJBXkpW5U/TVrxOsivoKAyfvU6HfrmpVp4+5o1BecA
              Q4LYRWnFjkw75Qx4Ig/G0S6z9T+UPT0WLcdnyCIEoAKvg1AzwW/okTcm1Jvi+nsf0sfgS7
              vIPSE2UGSQ546n2sJa1AxyODPmkevV9tM48cwvO/ZDpEMIXSUJm/DJuK+g6eLbsbnNTwTu
              lpike+4VPUJF0T+nT03G6BJ5MVQKCv8PJM+2Kf20Q02+wNH3jrSDmtfhkaukoZN8Ct1yk8
              EdDM80fPvhMSwrH1zrJGnEhAcSHtFNhdmZfY93X6XXV0Lpf/Wvb2x5y3d/JxpeUlZ+wiKZ
              HrrW7rCezAEG5OnjW5yLOJi60K3xMK7bvwa9QDFOakm7Lz3bk6E2X9L86lidJVi/6H7Cgw
              olH2zTD8GZ8nqH1p9H+wWq8APtiQRZH/3nfkuVdGCpBwS7mhZZzRmykOGQJjUeXMzJqOok
              TVUsCyye492HFv4lCga5XVPT8VhPQQyiPvSEwm7103geAkz4MY49ZGzXeCxsmQGtw9RjLC
              jFXVofWTVbjVAgm+BAZd3kexlm/eQFj/oVxXLJ05VjUYjIGotf1Cw3AtcV1HE1W3SY+um/
              fo6nHFZgK33viwlG7ae76dTYZ5MgTMVn6pQBr3MhHEznsy5BTJbJFQKpydIFxustLggpvR
              0/oPKNTc9eYQSADdCTuKFgJ/vBNFEisgKwMHHVqWMZ7on27HY7onOPyDcMBF+Q9VaRk/CY
              kZhvLV2bvcxm5G6nDDYMLHRTGevavhk53aA07X58wZBW1PBRqLZaIZPdr0uT/Cw1T1XuNo
              U7RmE4ZT0ApAtyhgIrAWuqLDKx3QFaWlJ82wZFtF5yoTyZCUHQWUmI5xd/noZkugLzDBqO
              aJCshRf54dpUYpyCCfGkCDI2VOla3shDJAqtkSxlqezZxCcpiGsLAQAFlDRrI9Q4ftvFGX
              4ZcMkadmv+n7Nv1lvV0bej+gR7cCpJjNZoSJ+A4CQ4/T6nrbohSM1WfP4EmxTqjlx2AYSK
              A6wLS2d3uIkHoZ99Qxc77m9JvVXweq/Kj8NizeSHv0rLAe+/YZOtgRgWq8NOrcybKeSWMp
              H/ybGvDJ6rsg2PDLu4SD4zPsTguMY12ci3Qi2tUPiqhMPMjey/l1vVLW+rfiPp06VYm5Mg
              OzJ0X94h72nOoiz0mlwWMO6CQFLKx2uph43GUXJk3NHDogsphDphMKnFssMx3adDhsy58s
              pGB1l81wAA7sObNVsHPvhog9MUqPOxyyjjYSr33MAotY7MzgFZherrIugwTHehU2tE9Qls
              jlI6l0WrEKHXfTM7TXWZkSVpLbM3lchCEjni2Y4TNRpaZociPYML1rtOCDWn46aX6UimTP
              5nzHAe3ym4N1j8mSbjmffz/UNGx3eOQMjHdWFe5+TIW/W0MV4KxA5q1+Hv6i8uGJrHHRM8
              EI4O45we1tvMaNlg49YvataKxsKAcVgaDOY9GY08Kn6ylHCZk6CQUWBBJMnPenyMfQA26I
              5sL/C0sRJxtUW13Co9NY5ZpBA6lzXTJ30OfldQ6NE8tnozUuryY28RF2LNYPRmhOV+b8ug
              76oM9s919NpXzburOYZphDfGR1C68LNqBwfbKV7BriyRA1kDIdlZRdbwAliAv+igae4BlF
              uSDpwlOfucENJx+pszhwXGCeGSnGnYxdyXJRln5LgdkQlmcIGz9fxQ1mEkSYDdq5X64Axu
              7J5r+kZ69Kvhskhf3RzN8Ira59iUIKts6q5FFO3dQqeM2UE7R71ym1jkjlEYOfw8gG+AxT
              2ekJDqHX0SFvyAeBWSlW5J79aK3KmnMnxaZBxNnzSX1sOzrS8xiZFCGcr9rb1IaH0/O3rO
              /IOCALumQB3x6Lte7pkKmOieUqT1zlTyTliOB8FcAAZnFABjN7X/b774B5UNzN2AMMqWze
              FzcJZ7NwFMe/h0xCIcYxP5RwOIoC6w8uh2bS0Na4BLfxUENKTYh1nEDe6WnK8NOuzyCp7q
              aeGh7PrQYWKvlWIRPNgEYDWXT/kpcNBdQDv6J8nAVWdh4CnxCw2RWTDW2K0776YoS4odZG
              nfCR/3RGBtFrvwlKfjI0N3rP+sAprjV7cZgilmIF5/2fH2rRWhf95PkolhHU6OwP1qslTr
              z+UIdtRNah746mHOuuWNUFf8bE4SZsUIuJP0+0ZSMX4CEF5GyO4aw945F+pZzrCFuhdui/
              kMLVBjaLLQ9oC1Uw3V/iWoaQG3GJSgbch3z+VIMb5CfXJX45Yy+Q7wPESMAgDGCSlLjItV
              VYhiTR4TMDtTgwa52TkvEsg/awQTgKv7eGxIazsTDjl0kEI+zNYiQEoPSrY/wplOy7yH4T
              7jE4zO1SNbxYwTi/r60d0XmbQZde0AGK8OeTq7eYWGBRnAkKrpmzvrL/9sRB77lHdBANOS
              o3q4CotW7NQiE/m34RZ2FuaRjJbOdFscNVu+I8FbDUXljP/edoePW1KS5JcdGnNrf9Ek30
              xj8FR5yKYMTGNpv7dkOgMdIY0K0Mw3fXlDFHt7tN6FF0hiK79b01QlwUtLBfHwrs/6byFn
              Fjuzp+Kpc5bY5RMWYJHVi3Y//I1e0rhC0WLbjCgMM69JsrcveOaFpw5Bp78f7Y+nlgsZL6
              hBNvhQA2Wb/gDIrGPEQZcRMdE/g4veTrSyTxaPJhCDdlMYoJkJcQ96Mxxl7/7f2l56KKWx
              qm
          mode: 0
          uid: 0
          gid: 0
        - path: /etc/secrets/component_cert.key
          ciphertext: !!binary |
              fFhCaq0BRlIVlAd6E4yFYbpKjY0RHBshFSVn1Pq0BpWEDMeVMRukNiaone9d8o9qtxoUsg
              lN4JpA38I14c986lJ+i9okoksEmt5keru+SuVBcczQ2ZnZh70eSscwcEw+Z593RYB17d7o
              Vs/hEHYD3G/0sj0kYhthhEx5Pl1Zk5Uoj7wuT1gccoqearW+Q4ujPF2jiQ0AX5AssLJvSi
              mF+NEn1QS9KkdfYUy9+qFr3BCP2L/5tzdw9IGZvidecndo6e9e/iRRBn1BkmvQawZT6tJR
              HYNvlZsD1T4l+pVqbojmIXCl2a8BSrXXqMjdjrv3NH2iJP7y/+H8QNR9gXtwyTz5WLB5np
              1zwB51QGK5ujZtuHiXskUx8sjQd16J1d61EKOvRPjewFSGfLZC6hpEzqG593pSB+tmDd+T
              b6U5XsrE76z5W0EFIdEe3akos7TL/2PhOKSS2XUnvcUQvp6s9VZkb6EUBQ94T4aLnkGXq0
              WuEgjEY02PdCG43omAUidWL0JWpDxAesoQ7IkqbgMX9DeT5xNtawHevHVkXBhAWBe5famS
              kFWDR6GsbcLdTUCbWyvGm2haSalCO1yLD+pfUkAXvmvnNAotxNoXukYMNM46XdWOr+4ajI
              bMnLQC7HrxR/6b2JFRiE5x0UsUIY7kz37Gpqi5utQ7+tgOUGJoWkHlk4/N+QgBNLncWrAZ
              hpdJtV8v9+Kt/4CCXHo5LXHoBdNbazNdCgMy7PGJ1ylA+pRljnhTNKHfSExqPJ8+ePKo6+
              L0Ve4eOwVUotD/ZOXU8XAKzA8yWWTzpYVUtD4P8Tm1rEuC2fOi+raeAX2whsjqNTC+wGDf
              TXExctTb/IORcuZKVNDoSoxHDjpYo0BV15fZcOUytFDfaWudRr+HQkO9JK3KoR+J8wlR4R
              PkMUfcOId34jtleKz2xCsTzdhm9AtVnNIiVtDtPHvrBFs2QtPLu5HxtJlIdyImfYuOCnYG
              7q0T64bxsKWnHoBVGpgD3ixI73bH+qddm3z2QDkhamQ7p/V3ya7W27Ze1PBXN/ts8+mJld
              04KM4q3AeHcBHEbfcixqTnspZHtUMqCaaWjWcjUjS+CJV+gwEobrWYWhcYuf1mdFaUAG89
              CtfFd9NHpx6fDuhSacqga4aQCC7KLlXg8IDyWGqjbxnWMbRLzAOx+oZ+Rh85Jsc7HeIp/5
              AGZ8mAoMAPTvPOaO7ZARRbZ6Fptu3vLgNAl+X5IPiU5TNyWlSirbjDC0vCLxBxGl+EAaoC
              5Z3E8aFZuTURvTxN2B9GAp+QAbK3btSIg6OYuZ3VMwHGDxKJJZL79NzXTu8GN2CVXDtRJk
              jBEdu1cyN+9oZXZi6DZiWKXL7SOdMfrvtHgUpSafmszGeJli4SBertqs4CiFd8zptI8uXG
              0suboqdiqWxZPHxFGJPaHeny3dnqFPYZufQuGzgcoSoBHygCE89dUN1qu6EHoNkYBygIrU
              gfjy5UA2+PRsvGj7nOUezVP2t3DrrwyRgEvrOnxTrYlcTK5I3MgMuDXZuRFfYrJzdNRYUc
              0eTpYffzgFBab9nG9eg/06IvK+fxIEvyp2nNx0AuBqiQtxF4fcac4k6XWI4AMU2uwaxQGR
              1RE50umVgtmQEHn6uTZ+ndcFW0Jfw7TX5/HGv26kMyxfqAEC2clFhgnAkY479V9XdKnh4c
              04z46+kTbxB9mZbOqfYui/xvHuj2zpeFYDg28EUkQt3k6TbuvFzkTAdT3dYDFHSsqbQEiU
              TxLieDeH9yn0Iyk12r4/DA8xSu2ErZi1xeCgpaxiiCor7WK4+kHLY69ES9fxsECySpqfCb
              6dIYOlCg+y/3FnO3DRhMmtdaxZZ1US785XG/3LkzeM1+Bgh5wP3g9Nq9UO0WCXT3lJYMNJ
              4W1aEoQwsF1YKwxlRdEVqvnKJUjzoLIZ+2PaLZJOYfOPQer0wRIIK8pxvDQaI1GBDjq+Me
              U+BQNCppflew9KIA91UNIDYK3F1WYbwN165u6cmXlIY0/345z/luCOsCSZC28u/mPFuG/i
              vZPSDFPaADWrtR7npNVBHB3m83ouceg03PqGnMlC+nt2+cbf+RVM9zENjm3dZdIEhGoBCB
              BGx0BsG5vb/ieUNDH+rxNqCtX094WtO+q2W2XnudJtxclDtHPQQNwVEAlBFinRALdT3c4U
              RqAq/wb45AOOANFIn7/E1MZqmkoQLE2jOONpxx79WCgN9H4FO4h9Nuu1rIdu+7Do7BZYDJ
              i5wpwfCVMvFd58LoV8j9
          mode: 0
          uid: 0
          gid: 0
        - path: /etc/metricsagent/SOLOMON_AUTH
          ciphertext: !!binary |
              41Ystql4YR1MrRxzTHEoufpgxdEu7Coyek7Vo5YKXKfKZ81oQHPDGuD17OVfNzjS3m0a5K
              PPiA==
          mode: 0
          uid: 0
          gid: 0
      enc_mode: DETERMINISTIC
      force: false
