version: '3.7'

x-constants:
  US_MASTER_TOKEN: &c-us-master-token "AC1ofiek8coB"

services:
  db-postgres:
    # image: "postgres:13-alpine"
    image: "registry.yandex.net/statinfra/postgres@sha256:3335d0494b62ae52f0c18a1e4176a83991c9d3727fe67d8b1907b569de2f6175"
    environment:
      POSTGRES_DB: datalens
      POSTGRES_USER: datalens
      POSTGRES_PASSWORD: qwerty
    ports:
      - 51013:5432

  pg-us:
    build:
      context: ../../lib/testenv-common/images
      dockerfile: Dockerfile.pg-us
    environment:
      POSTGRES_DB: us-db-ci_purgeable
      POSTGRES_USER: us
      POSTGRES_PASSWORD: us
    ports:
      - 51009:5432

  pg-us-dc:
    build:
      context: ../../lib/testenv-common/images
      dockerfile: Dockerfile.pg-us
    environment:
      POSTGRES_DB: us-db-ci_purgeable
      POSTGRES_USER: us
      POSTGRES_PASSWORD: us
    ports:
      - 51010:5432

  us:
    build:
      context: ../../lib/testenv-common/images
      dockerfile: Dockerfile.us-single-tenant
    ports:
      - 51000:80
    depends_on:
      - pg-us
    environment:
      POSTGRES_DSN_LIST: "postgres://us:us@pg-us:5432/us-db-ci_purgeable"
      AUTH_POLICY: "disabled"
      DLS_ENABLED: "false"
      DISABLE_DLS: "true"
      MULTITENANT: "false"
      MASTER_TOKEN: *c-us-master-token

  us-dc:
    build:
      context: ../../lib/testenv-common/images
      dockerfile: Dockerfile.us-single-tenant
    ports:
      - 51001:80
    depends_on:
      - pg-us-dc
    environment:
      POSTGRES_DSN_LIST: "postgres://us:us@pg-us-dc:5432/us-db-ci_purgeable"
      APP_INSTALLATION: "doublecloud"
      APP_ENV: "preprod"

      DISABLE_ACCESS_SERVICE: "true"
      DISABLE_ACCESS_BINDINGS_SERVICE: "true"

      AUTH_POLICY: "disabled"
      DLS_ENABLED: "false"
      DISABLE_DLS: "true"
      MULTITENANT: "false"
      MASTER_TOKEN: *c-us-master-token


#  charts:
#    image: "registry.yandex.net/data-ui/datalens"
#    network_mode: host
#    environment:
#      APP_INSTALLATION: internal
#      APP_ENV: development
#      APP_MODE: charts
#      AUTH_POLICY: disabled
#
#      BI_DATA_ENDPOINT: "http://localhost:???"
#      BI_API_ENDPOINT: "http://localhost:???"
#      US_ENDPOINT: "http://localhost:51000"
