#!/usr/bin/env sh

set -x  # debug.
set -eu

if [ x"${RUN_HEALTH_CHECK_API:-0}" != x"1" ]; then
    sleep 9000
    exit 0
fi

port="${GUNICORN_LISTEN_PORT:-80}"
max_rq="${GUNICORN_MAX_RQ:-5000}"
max_rq_jitter="${GUNICORN_MAX_RQ_JITTER:-500}"

exec \
    gunicorn \
    bi_file_uploader_worker.app_health_check:create_gunicorn_app \
    --log-config /code/gunicorn_logging.ini \
    --bind "[::]:${port}" \
    --max-requests "$max_rq" \
    --max-requests-jitter "$max_rq_jitter" \
    --workers="1" \
    --worker-class aiohttp.GunicornWebWorker
