from dl_formula_testing.testcases.conditional_blocks import DefaultConditionalBlockFormulaConnectorTestSuite

from dl_connector_greenplum_tests.db.formula.base import GreenplumTestBase


class TestConditionalBlockGreenplum(GreenplumTestBase, DefaultConditionalBlockFormulaConnectorTestSuite):
    pass
