#!/usr/bin/env sh

set -x  # debug.
set -eu

port="${GUNICORN_LISTEN_PORT:-80}"
max_rq="${GUNICORN_MAX_RQ:-5000}"
max_rq_jitter="${GUNICORN_MAX_RQ_JITTER:-500}"

exec \
    gunicorn \
    bi_testing_db_provision.app:create_gunicorn_app \
    --log-config /code/gunicorn_logging.ini \
    --bind "[::]:${port}" \
    --max-requests "$max_rq" \
    --max-requests-jitter "$max_rq_jitter" \
    --workers="1" \
    --worker-class aiohttp.GunicornWebWorker
