from dl_connector_bundle_chs3_tests.db.file.formula.base import FileTestBase
from dl_formula_testing.testcases.functions_markup import DefaultMarkupFunctionFormulaConnectorTestSuite


class TestMarkupFunctionFile(FileTestBase, DefaultMarkupFunctionFormulaConnectorTestSuite):
    pass
