# United Storage with predefined env
FROM ghcr.io/datalens-tech/datalens-us:0.393.0

ENV DEV_MODE="true"
ENV SQL_DEBUG="true"
ENV MULTITENANT="false"
ENV DEBUG="knex:*"
ENV APP_INSTALLATION="opensource"
ENV APP_ENV="preprod"
ENV APP_PORT=8080

EXPOSE 8080
