# United Storage with predefined env
# TODO(BI-7425): Unpin version
FROM ghcr.io/datalens-tech/datalens-us:1.137.0

ENV DEV_MODE="true"
ENV SQL_DEBUG="true"
ENV MULTITENANT="false"
ENV DEBUG="knex:*"
ENV APP_INSTALLATION="opensource"
ENV APP_ENV="development"
ENV APP_PORT=8080

EXPOSE 8080
