[tool.poetry]
name = "datalens-terrarium-metapackage"
version = "0.1.0"
description = ""
authors = ["DataLens Team <datalens-opensource@yandex-team.ru>"]
license = "Apache 2.0"
packages = [{include = "dl_terrarium_metpkg"}]

[tool.poetry.dependencies]
python = ">=3.10, <3.12"

[tool.poetry.group.ci.dependencies]
bi-ci = {path = "../bi_ci"}
datalens-cli-tools = {path = "../dl_cli_tools"}
datalens-gitmanager = {path = "../dl_gitmanager"}
datalens-repmanager = {path = "../dl_repmanager"}

[datalens_ci]
skip_test = true
