name: release_post_process

on:
  pull_request:
    types: [ closed ]

jobs:
  build:
    runs-on: [ self-hosted, linux ]
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.title, 'releasing version ')
    container:
      image: "ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}/dl_releaser:latest"
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
      pull-requests: write
      packages: read
    steps:
      - name: "Cleanup build folder"
        run: |
          rm -rf ./* || true
          rm -rf ./.??* || true
      - name: "Checkout code"
        uses: actions/checkout@v4
      - name: "Git security workaround (ownership)"
        run: git config --global --add safe.directory /__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}
      - name: "Set committer info"
        env:
          CI_COMMIT_AUTHOR: Continuous Integration
        run: |
          git config --global user.name "${CI_COMMIT_AUTHOR}"
          git config --global user.email "username@users.noreply.github.com"
      - name: "Hello, it's me"
        run: echo "Hello, it's me" >> "${GITHUB_STEP_SUMMARY}"
