name: "🚀🟢 Release"

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: "Version to release, in format 'vX.Y.Z'"
      make_latest:
        type: boolean
        description: "Make latest"
        default: true
      draft:
        type: boolean
        description: "Is draft"
        default: false

jobs:
  push_images:
    name: "Pull candidate images and push to release"
    runs-on: ubuntu-latest
    permissions:
      packages: write
    outputs:
      image-version: ${{ steps.push_image.outputs.image-version }}
    strategy:
      matrix:
        image_name:
        - "datalens-control-api"
        - "datalens-data-api"
    env:
      cr_url: "ghcr.io/${{ github.repository_owner }}"

    steps:
    - name: Log in to the Container registry
      uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2
      with:
        registry: ${{ env.cr_url }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3

    - name: Push release tag
      id: push_image
      run: |
        image_version="${version#"v"}"

        image_url_rc="${{ env.cr_url }}/${{ matrix.image_name }}:${image_version}-rc.1"
        echo "Pulling release candidate image: ${image_url_rc}"

        image_url_release="${{ env.cr_url }}/${{ matrix.image_name }}:${image_version}"
        echo "Pushing release image: ${image_url_release}"
        docker buildx imagetools create --tag "${image_url_release}" "${image_url_rc}"

        echo "image-version=${image_version}" >> $GITHUB_OUTPUT
      env:
        version: ${{ github.event.inputs.version }}

  release:
    name: "Create release"
    needs: [ push_images ]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      branch: "release/${{ github.event.inputs.version }}"

    steps:
    - name: Checkout code
      id: checkout
      uses: actions/checkout@ee0669bd1cc54295c223e0bb666b733df41de1c5 # v2
      with:
        ref: "${{ env.branch }}"
        fetch-depth: 0

    - name: Create release
      id: create_release
      working-directory: .github/.scripts
      run: |
        gh release create \
          --repo $REPOSITORY_NAME \
          $VERSION \
          --target ${{ env.branch }} \
          ${{ github.event.inputs.make_latest == 'true' && '--latest' || '' }} \
          ${{ github.event.inputs.draft == 'true' && '--draft' || '' }} \
          --generate-notes
      env:
        VERSION: ${{ github.event.inputs.version }}
        REPOSITORY_NAME: ${{ github.repository_owner }}/${{ github.event.repository.name }}
        GH_TOKEN: ${{ github.token }}
