name: release_bump_version

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [ self-hosted, linux ]
    container:
      image: "ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}/dl_releaser:latest"
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
      pull-requests: write
      packages: read
    steps:
      - name: "Cleanup build folder"
        run: |
          rm -rf ./* || true
          rm -rf ./.??* || true
      - name: "Checkout code"
        uses: actions/checkout@v4
      - name: "Git security workaround (ownership)"
        run: git config --global --add safe.directory /__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}
      # TODO FIX: Move to script
      - name: "Set committer info"
        env:
          CI_COMMIT_AUTHOR: Continuous Integration
        run: |
          git config --global user.name "${CI_COMMIT_AUTHOR}"
          git config --global user.email "username@users.noreply.github.com"
      - name: "Bump version & create PR"
        env:
          GIT_CURRENT_BRANCH: "${{ github.ref_name }}"
          PR_URL_FILE_LOCATION: "./bump_version_pr_url.txt"
          GH_TOKEN: ${{ github.token }}
        run: bash .github/release_scripts/01_bump_version_create_pr.bash
      - name: "Approve PR"
        env:
          GH_TOKEN: "${{ secrets.APPROVE_PR_TOKEN }}"
        run: gh pr review -a "$(cat ./bump_version_pr_url.txt)"
      - name: "Merge PR"
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh pr merge -s "$(cat ./bump_version_pr_url.txt)"
