name: release_bump_version

on:
  workflow_dispatch:
    inputs:
      auto_build_targets:
        type: string
        description: "Space separated. This targets will be added to build_advise.json to launch build."
        default: "app_bi_api app_yc_control_api app_yc_data_api app_yc_data_api_sec_embeds app_yc_public_dataset_api app_bi_rqe_ext_async app_bi_rqe_ext_sync app_bi_rqe_int_sync app_bi_file_uploader app_yc_file_uploader_api app_bi_file_uploader_worker app_yc_file_uploader_worker"

jobs:
  build:
    runs-on: [ self-hosted, linux ]
    container:
      image: "ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}/dl_releaser:latest"
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
      pull-requests: write
      packages: read
    steps:
      - name: "Cleanup build folder"
        run: |
          rm -rf ./* || true
          rm -rf ./.??* || true
      - name: "Checkout code"
        uses: actions/checkout@v4
      - name: "Git security workaround (ownership)"
        run: git config --global --add safe.directory /__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}
      # TODO FIX: Move to script
      - name: "Set committer info"
        env:
          CI_COMMIT_AUTHOR: Continuous Integration
        run: |
          git config --global user.name "${CI_COMMIT_AUTHOR}"
          git config --global user.email "username@users.noreply.github.com"
      - name: "Bump version"
        env:
          GIT_CURRENT_BRANCH: "${{ github.ref_name }}"
          AUTO_BAKE_TARGETS_SPACE_SEPARATED: ${{ github.event.inputs.auto_build_targets }}
          GH_TOKEN_MAIN: "${{ github.token }}"
          GH_TOKEN_FOR_PR_APPROVE: "${{ secrets.APPROVE_PR_TOKEN }}"
        run: bash .github/release_scripts/01_bump_version_create_pr.bash
