name: "Run E2E tests on ref"

on:
  workflow_dispatch:
    inputs:
      # We are using PR number here instead of SHA or branch name to make it possible to run this on PRs from forks
      pr:
        type: string
        required: true
        description: "Pull request number/url"
      sha:
        type: string
        required: true
        description: "Latest PR commit hash"
        # ^ To validate that PR has not changed before the checkout

jobs:
  build_backend:
    name: "Build images"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      image-version: ${{ steps.build_image.outputs.image-version }}
    strategy:
      matrix:
        include:
          - image_name: "datalens-control-api"
            bake_target: "dl_control_api"
          - image_name: "datalens-data-api"
            bake_target: "dl_data_api"
    container:
      image: "ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}/debian_docker:latest"
      options: -v /var/run/docker.sock:/var/run/docker.sock
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    env:
      cr_url: "ghcr.io/${{ github.repository_owner }}"
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Switch to PR head
      run: gh pr checkout ${{ github.event.inputs.pr }}
      env:
        GH_TOKEN: ${{ github.token }}
    - name: Validate SHA
      run: |
        export HEAD_SHA=$(git rev-parse HEAD)
        export INPUT_SHA="${{ github.event.inputs.sha }}"
        echo "Calculated latest commit in PR: $HEAD_SHA"
        if [ x"$HEAD_SHA" != x"$INPUT_SHA" ]; then
          echo "The branch was updated since the workflow was triggered, exiting"
          exit 1
        fi
    - name: Log in to the Container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.cr_url }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build image
      id: build_image
      working-directory: docker_build
      run: |
        bake_target=${{ matrix.bake_target }}
        image_version="${{ github.event.inputs.sha }}"
        image_url="${{ env.cr_url }}/${{ matrix.image_name }}:${image_version}"
        ./run-project-bake "${bake_target}" --push --set "${bake_target}.tags=${image_url}"
        echo "image-version=${image_version}" >> $GITHUB_OUTPUT

  run_e2e_tests:
    name: "Run E2E tests"
    needs: [ build_backend ]
    uses: datalens-tech/datalens-backend/.github/workflows/run_e2e.yml@main
    with:
      image_version: ${{ needs.build_backend.outputs.image-version }}
    secrets: inherit
