# Здесь описываются настройки работы приложения, а также env-переменные, 
# которые будут переданы внутрь docker-контейнера с приложением
ENV:
  - name: VARNAME1
    value: varvalue1
  - name: VARNAME2
    value: varvalue2
PUSH_CLIENT_NODEJS_TOPIC: # topic в logbroker куда будут отправляться stdout из контейнера
PUSH_CLIENT_ERROR_TOPIC: # topic в logbroker куда будут отправляться stderr из контейнера
SOLOMON_PROJECT: # название проекта в соломоне для отливки метрик
TVM_APP_ID: # идентификатор приложения для авторизации в TVM-демоне, который крутится в отдельном контейнере